CONTRIBUTING.md
this doesn't feel "complete" but will have to do now. A separate commit with
expectations. Latest ansible, latest vagrant, latest virtualbox etc., is needed.
=> advice on how to contribute was missing

roles/pulibrary.plum/defaults/main.yml, roles/pulibrary.plum/tasks/main.yml
=> Add mount for lib-gissystem

roles/pulibrary.plum/tasks/main.yml
=> Add nfs-common package

hosts
this adds the DNS names for mariadb cluster hosts
=> add the mariadb hosts

CONTRIBUTING.md
Vagrant and Virtualbox occasionally fail spectacularly and many hours
can be lost debugging
=> a reminder to contributors to run the newest

roles/pulibrary.postgresql/templates/postgresql.conf.j2
this enables autovaccum in our config files.
=> add autovaccuuming

roles/pulibrary.pulmap/templates/pulmap-sneakers.service
Working directory is wrong in pulmap sneakers service configuration. This corrects it.
=> Update working directory in pulmap sneakers service

group_vars/postgresql.yml, roles/pulibrary.postgresql/defaults/main.yml, roles/pulibrary.postgresql/templates/postgresql.conf.j2
tuning postgres to make accomodations of more memory and faster WAL writes.
=> Postgresconf

hosts
=> Add maps2 server to pulmap hosts

roles/pulibrary.sidekiq_worker/defaults/main.yml
See https://github.com/pulibrary/figgy/issues/541
=> Adding low priority sidekiq queue

group_vars/archivesspace.yml
=> upstream version bump

roles/pulibrary.rails-app/tasks/main.yml, roles/pulibrary.rails-app/templates/logrotate.d.rails.j2
=> Ensures that the logs for Rails Apps are rotated daily only if they exceed 500M in size

roles/pulibrary.passenger/templates/passenger.j2
not sure it belongs here because if you uncomment it will break the
ability to use on vagrant set up
=> this allows remote IPs to show up in logs

group_vars/all/vars.yml
=> Add web dev keys.

hosts
=> Add production and staging servers to bibdata hosts

roles/pulibrary.bibdata/README.md
=> Update bibdata README for staging deployment

bibdata.yml, group_vars/bibdata_production.yml, group_vars/bibdata_staging.yml
=> Add sidekiq role to bibdata

roles/pulibrary.downgrade_bundler/tasks/main.yml
This works in my local testing. If accepted, #143 can be closed.
=> Ensure bundler is reinstalled for all users; fixes #142

roles/pulibrary.solr/defaults/main.yml
be good network citizens and use the princeton mirror
=> use the princeton mirror instead of apache

roles/pulibrary.sidekiq_worker/defaults/main.yml
=> Add super_low queue for sidekiq workers; to be used for fixity checks

Vagrant/figgyStagingVagrantfile, group_vars/figgy.yml, group_vars/figgy_production.yml
Resolves #173 and fully resolves https://github.com/pulibrary/figgy/issues/741
=> Ensures that Figgy has the appropriate `INGEST_FOLDER_PATH` env. variable set for the Rails app.

roles/pulibrary.solr/defaults/main.yml
=> Use the princeton solr mirror over http

group_vars/figgy.yml, group_vars/figgy_production.yml, roles/pulibrary.figgy/tasks/main.yml
=> Add gdal and simple-tiles dependencies to figgy

group_vars/figgy.yml, group_vars/figgy_production.yml
=> Set LD_LIBRARY_PATH on Figgy needs for simple tiles

figgy.yml
=> Add rabbitmq role to figgy staging

group_vars/pulmap.yml
=> Fix geoserver url for pulmap production

group_vars/figgy.yml, group_vars/figgy_production.yml
=> Add GEOSERVER_URL variable to figgy app config

group_vars/figgy.yml, group_vars/figgy_production.yml, roles/pulibrary.figgy/files/tika_config.xml, roles/pulibrary.figgy/tasks/main.yml
=> Add Tika configuration to Figgy

bibdata.yml
Forgot to submit a PR for this...
=> add sidekiq to bibdata web app

group_vars/figgy.yml, group_vars/figgy_production.yml
=> Adds MediaInfo as a system package dependency for Figgy

roles/pulibrary.cantaloupe/defaults/main.yml
Resolves https://github.com/pulibrary/figgy/issues/1325
=> Increasing the max. number of pixels by 100M and one order of magnitude for Cantaloupe

pulmap.yml, pulmap_staging.yml, roles/pulibrary.pulmap/tasks/main.yml
=> Add cron jobs to pulmap

group_vars/orangelight.yml, group_vars/orangelight_staging.yml
Removes google analytics from orangelight production and staging.
=> Removes google analytics from orangelight production and staging

group_vars/pulmap.yml, pulmap.yml
=> Add DataDog integration to pulmap

roles/pulibrary.solr/defaults/main.yml
I think we are also using solr 7.1.0 yes?
=> use our our archive mirror

group_vars/dpul_production.yml, group_vars/figgy_production.yml, group_vars/orangelight.yml, group_vars/pulmap.yml
Could be DRY cleaner using variables when passing them into the analysed
scans
=> Adds tracesearch to these endpoints

roles/pulibrary.pulmap/tasks/main.yml
Closes https://github.com/pulibrary/pulmap/issues/566
=> Add thumbnail caching cron job to pulmap

roles/pulibrary.figgy/files/tika_config.xml
Closes #301 
Closes https://github.com/pulibrary/figgy/issues/1639
Tested in staging and it works.
=> Configure Tika to exlclude the zip container detector

group_vars/dpul_staging.yml, group_vars/dss_staging.yml, group_vars/lae_staging.yml
=> Update solr url for dpul-staging, lae-staging, and dss-blacklight-staging

group_vars/pulmap_staging.yml
=> Update pulmap-staging url

group_vars/dpul_staging.yml, group_vars/dss_staging.yml, group_vars/lae_staging.yml
=> Update staging solr core names to match SolrCloud naming scheme

roles/pulibrary.solrcloud/defaults/main.yml, roles/pulibrary.solrcloud/tasks/config.yml, roles/pulibrary.solrcloud/tasks/install.yml, roles/pulibrary.solrcloud/templates/log4j.properties.j2, roles/pulibrary.solrcloud/templates/solr.in.sh.j2, roles/pulibrary.solrcloud/vars/main.yml
Solr cloud is installed on all 3 servers! 
There's an issue with the deploy-user role on lib-solr2 and lib-solr3
Closes #316
=> updates solrcloud config settings, download orangelight jar files

roles/pulibrary.figgy/tasks/main.yml
=> Upgrade GDAL

group_vars/figgy.yml, group_vars/figgy_production.yml, roles/pulibrary.figgy/tasks/main.yml
=> Compile simple tiles after updating gdal

group_vars/solrcloud.yml, solrcloud.yml
Adds some JMX metrics necessary for building a Solr health dashboard.
=> Solr Cloud Datadog

group_vars/all/vars.yml
adding @pmgreen and @cwulfman to the deploy user role.
=> add cliff and peter to deploy user

group_vars/solrcloud.yml
dogstatsd couldn't start because netdata was running on the port it was
trying to launch on.
=> Fix Solr JMX

roles/pulibrary.bibdata/tasks/main.yml
see https://github.com/pulibrary/marc_liberation/pull/504
refs https://github.com/pulibrary/marc_liberation/issues/469
=> Remove bibdata ark seed cron; it's managed by whenever now

group_vars/bibdata.yml, group_vars/bibdata_staging.yml, group_vars/bibdata_workers.yml, roles/pulibrary.bibdata/tasks/samba_client.yml, roles/pulibrary.bibdata/tasks/samba_server.yml
Closes pulibrary/marc_liberation#478
=> makes scsb subdirectory samba share

bibdata.yml, group_vars/bibdata.yml
Adds datadog role and variables to bibdata.
refs: https://github.com/pulibrary/marc_liberation/issues/495
Closes #363
=> Add bibdata to datadog

group_vars/all/vars.yml, group_vars/figgy_production.yml
the location of the keys directory is now relative.
=> location of the keys is now relative

group_vars/bibdata.yml, group_vars/bibdata_workers.yml, playbooks/bibdata.yml
Updates to get Datadog running on bibdata prod and workers.
=> Updates to the bibdata datadog configuration

playbooks/group_vars, playbooks/host_vars
allows all playbooks and roles to access the vars
fixes #380
=> Add symlinks to group_vars and host_vars from new playbook directory

playbooks/figgy.yml, roles/pulibrary.freetds/tasks/main.yml
=> Add a role installing freetds for figgy workers

playbooks/figgy.yml
fixes a bug introduced in #385
=> Add freetds to figgy webserver boxes

Vagrant/figgyStagingVagrantfile, roles/pulibrary.solr/tasks/main.yml
=> Update postgres_host in figgy vagrantfile

hosts
simple update of postgres hosts.
=> modify new postgres hosts

playbooks/figgy_production.yml
resolves #411
I didn't add it to the `figgy` play because that one is deleted in #413
=> Add slack post_task to figgy_production_webserver play

Vagrant/figgyStagingVagrantfile, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/pulibrary.subversion/tasks/main.yml, roles/pulibrary.subversion/templates/servers
=> Add subversion client to figgy role

README.md
As covered by skill share session
=> Add documentation for provisioning one machine at a time

group_vars/orangelight.yml, group_vars/orangelight_staging.yml, playbooks/orangelight.yml, playbooks/orangelight_staging.yml
=>  Add sneakers to orangelight

playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/pulibrary.common/tasks/main.yml, roles/pulibrary.common/templates/tmux.conf.j2
=> Add tmux conf to common role, add common role to figgy

group_vars/solrcloud.yml
=> Don't track catalog-staging

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
capistrano expects it to be there
refs #pulibrary/figgy#2830
=> Pre-set the figgy read only env var

group_vars/figgy_production.yml, group_vars/figgy_staging.yml, playbooks/figgy_toggle_readonly.yml
=> Add a playbook to toggle figgy's readonly mode

group_vars/solrcloud.yml, group_vars/solrcloud_staging.yml, host_vars/lib-solr1.princeton.edu.yml, roles/pulibrary.solrcloud/defaults/main.yml, roles/pulibrary.solrcloud/tasks/config.yml, roles/pulibrary.solrcloud/templates/solr.conf.j2
=> adds ulimit template, updates solr_heap var name

group_vars/figgy_production.yml, group_vars/figgy_staging.yml, roles/pulibrary.common/meta/main.yml, roles/pulibrary.composer/meta/main.yml, roles/pulibrary.deploy-user/tasks/main.yml, roles/pulibrary.drupal/meta/main.yml, roles/pulibrary.drush/meta/main.yml, roles/pulibrary.elastic/meta/main.yml, roles/pulibrary.mariadb/meta/main.yml, roles/pulibrary.mariadb/tasks/main.yml, roles/pulibrary.mariadbserver/meta/main.yml, roles/pulibrary.mariadbserver/tasks/main.yml, roles/pulibrary.matomo/meta/main.yml, roles/pulibrary.nodejs/meta/main.yml, roles/pulibrary.openjdk8/meta/main.yml, roles/pulibrary.php/meta/main.yml, roles/pulibrary.postgresql/defaults/main.yml, roles/pulibrary.redis/meta/main.yml, roles/pulibrary.ruby/meta/main.yml
Running `molecule test` these were all the lint errors we encountered with master.
=> Fixing linting on all roles for molecule

molecule/default/playbooks.yml, molecule/default/tests/test_rails-app.py, roles/pulibrary.matomo/tasks/install.yml, roles/pulibrary.passenger/defaults/main.yml, roles/pulibrary.passenger/tasks/main.yml, roles/pulibrary.passenger/templates/passenger.j2, roles/pulibrary.rails-app/defaults/main.yml, roles/pulibrary.rails-app/meta/main.yml, roles/pulibrary.rails-app/molecule/default/Dockerfile.j2, roles/pulibrary.rails-app/molecule/default/INSTALL.rst, roles/pulibrary.rails-app/molecule/default/molecule.yml, roles/pulibrary.rails-app/molecule/default/playbook.yml, roles/pulibrary.rails-app/molecule/default/tests/test_rails-app.py, roles/pulibrary.rails-app/tasks/main.yml
Added molecule to the rails-app role by moving the role, running molecule init, and then grabbing the needed files.
Added tests for the items the rails role is running.
There are a couple linting items also.
=> Adding test to the rails app

molecule/default/playbooks.yml, roles/pulibrary.mariadb/README.md, roles/pulibrary.mariadb/molecule/default/molecule_vars.yml, roles/pulibrary.mariadb/molecule/default/tests/test_mariadb.py, roles/pulibrary.mariadb/tasks/manage_contents.yml
This creates a database and then creates users for the specified database.
Adds test for database existing with user permissions
=> Adding user creation in mariadb

roles/pulibrary.mariadb/tasks/manage_contents.yml
The two tasks were running locally, but not on the remote server.  Added login_password and login_host to fix the issue
=> Adding in remote host information

group_vars/dpul_production.yml, group_vars/figgy_production.yml, group_vars/orangelight.yml, group_vars/pulmap.yml
These were spamming our logs, and haven't resulted in useful actions.
=> Remove solr pings

roles/pulibrary.figgy/tasks/main.yml
=> add bionic box conditional

group_vars/pulmap.yml, group_vars/pulmap_staging.yml
- Point pulmap_staging to lib-solr-staging
- Move passenger variables to group_vars files
=> Fix pulmap and pulmap-staging playbooks

group_vars/pas-production.yml, hosts, molecule/default/playbooks.yml, playbooks/pas-production-code.yml, playbooks/pas-production.yml, roles/pulibrary.pas_code/README.md, roles/pulibrary.pas_code/defaults/main.yml, roles/pulibrary.pas_code/files/env.j2, roles/pulibrary.pas_code/molecule/default/playbook.yml, roles/pulibrary.pas_code/tasks/main.yml
Fixed up a hard coded staging
Made the permission change change all the files, not just the few craft3 said were needed as they cased the system to fail.
Also added option to force database update.
=> adding playbook and vars for new slavery production

roles/pulibrary.nginxplus/ADDHOSTS.md, roles/pulibrary.nginxplus/README.md
these are the steps needed to add a new virtual server to NGINX Plus.
=> steps to add new hosts

playbooks/figgy_staging.yml, roles/pulibrary.openjdk8/tasks/main.yml
Switch figgy staging to openjdk
=> Ensure box uses openjdk after installing

.circleci/config.yml, Pipfile, Pipfile.lock, roles/pulibrary.apache2/tasks/main.yml, roles/pulibrary.common/molecule/default/playbook.yml, roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.rails-app/molecule/default/yaml-lint.yml, roles/pulibrary.samba/tasks/main.yml
Resolves #455 and builds upon the work introduced by @kayiwa and @carolyncole on https://github.com/pulibrary/princeton_ansible/tree/ansible_circle_ci
=> Introduces CircleCI tests

Pipfile, Pipfile.lock, README.md, tasks.py
Please see https://www.pyinvoke.org/ for reference.  Should this approach be acceptable, please note that the `invoke` tasks can be extended for additional tasks.
=> Introduces invoke as a task tool for adding molecule tests to existing Roles

.circleci/config.yml, roles/pulibrary.pas/molecule/default/playbook.yml
=> Restores the build for pulibrary.pas

.circleci/config.yml, roles/pulibrary.apache2/defaults/main.yml, roles/pulibrary.apache2/molecule/default/playbook.yml, roles/pulibrary.apache2/molecule/default/tests/test_apache2.py, roles/pulibrary.apache2/tasks/main.yml
adding circleci to apache role
=> 584 apache role

.circleci/config.yml, roles/pulibrary.bind9/.yamllint, roles/pulibrary.bind9/README.md, roles/pulibrary.bind9/defaults/main.yml, roles/pulibrary.bind9/meta/main.yml, roles/pulibrary.bind9/molecule/default/Dockerfile.j2, roles/pulibrary.bind9/molecule/default/INSTALL.rst, roles/pulibrary.bind9/molecule/default/molecule.yml, roles/pulibrary.bind9/molecule/default/molecule.yml-e, roles/pulibrary.bind9/molecule/default/playbook.yml, roles/pulibrary.bind9/molecule/default/tests/test_bind9.py, roles/pulibrary.bind9/molecule/default/tests/test_default.py, roles/pulibrary.bind9/molecule/default/yaml-lint.yml, roles/pulibrary.bind9/tasks/main.yml, roles/pulibrary.bind9/vars/main.yml
closes issue [589 ](https://github.com/pulibrary/princeton_ansible/issues/589)
=> 589 bind9 role

roles/pulibrary.bind9/molecule/default/tests/test_bind9.py, roles/pulibrary.bind9/tasks/main.yml, roles/pulibrary.rails-app/meta/main.yml, roles/pulibrary.rails-app/molecule/default/tests/test_rails-app.py, roles/pulibrary.rails-app/tasks/main.yml
while trying to moleculize the capistrano role I noticed that the rails app had identical tasks to the bind role.
=> Rails app bind9

.circleci/config.yml, roles/pulibrary.bind9/molecule/default/tests/test_bind9.py, roles/pulibrary.bind9/tasks/main.yml, roles/pulibrary.capistrano/.yamllint, roles/pulibrary.capistrano/README.md, roles/pulibrary.capistrano/handlers/main.yml, roles/pulibrary.capistrano/meta/main.yml, roles/pulibrary.capistrano/molecule/default/Dockerfile.j2, roles/pulibrary.capistrano/molecule/default/INSTALL.rst, roles/pulibrary.capistrano/molecule/default/molecule.yml, roles/pulibrary.capistrano/molecule/default/molecule.yml-e, roles/pulibrary.capistrano/molecule/default/playbook.yml, roles/pulibrary.capistrano/molecule/default/tests/test_capistrano.py, roles/pulibrary.capistrano/molecule/default/tests/test_default.py, roles/pulibrary.capistrano/molecule/default/yaml-lint.yml, roles/pulibrary.capistrano/tasks/main.yml, roles/pulibrary.rails-app/meta/main.yml, roles/pulibrary.rails-app/molecule/default/tests/test_rails-app.py, roles/pulibrary.rails-app/tasks/main.yml
but for the nodejs unpredictable fail this fixed [issue 592](https://github.com/pulibrary/princeton_ansible/issues/592)
=> 592 capistrano role

roles/pulibrary.passenger/.ansible-lint, roles/pulibrary.passenger/README.md, roles/pulibrary.passenger/defaults/main.yml, roles/pulibrary.passenger/meta/main.yml
this adds rvm as a dependency instead of the OS's ruby.
=> Passenger rvm

roles/pulibrary.rvm/tasks/main.yml, roles/pulibrary.rvm/tasks/remove_ruby.yml
=> In rvm role, remove old brightbox ruby before proceeding

roles/pulibrary.rvm/defaults/main.yml, roles/pulibrary.rvm/tasks/rubies.yml
=> this adds ruby-2.4.6-dev

group_vars/figgy_staging.yml, playbooks/figgy_staging.yml, roles/pulibrary.cantaloupe/defaults/main.yml, roles/pulibrary.cantaloupe/tasks/install.yml, roles/pulibrary.mediainfo/defaults/main.yml, roles/pulibrary.mediainfo/tasks/main.yml, roles/pulibrary.postgres/tasks/readonly_user.yml, roles/pulibrary.postgresql/tasks/create_db.yml, roles/pulibrary.postgresql/tasks/create_users.yml, roles/pulibrary.rabbitmq/tasks/main.yml
Not sure how postgres change will interact with other playbooks. @kayiwa @carolyncole what do you think?
=> Unblock figgy-staging vagrant deploy

group_vars/cicognara.yml
It was moved to lib-solr-staging
=> Update cicognara staging solr url

hosts, playbooks/cicognara_staging.yml
needed an easier to identify name for the stage environment
=> the cicognara name for the playbook

.circleci/config.yml, group_vars/libwww/libwww.yml, roles/pulibrary.common/tasks/main.yml, roles/pulibrary.composer/README.md, roles/pulibrary.composer/defaults/main.yml, roles/pulibrary.composer/tasks/main.yml, roles/pulibrary.drupal/tasks/main.yml, roles/pulibrary.libwww/defaults/main.yml, roles/pulibrary.libwww/molecule/default/playbook.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.php/tasks/main.yml
the code is no longer deployed by ansible
Also fixes #576 by adding circle ci
=> change the libwww role so that capistrano can be used to deploy

group_vars/cantaloupe_staging.yml, hosts, playbooks/cantaloupe_staging.yml, roles/pulibrary.cantaloupe/tasks/install.yml, roles/pulibrary.cantaloupe/templates/staging_nginx_config.j2, roles/pulibrary.deploy-user/tasks/main.yml, roles/pulibrary.samba/tasks/main.yml
refs #659 
There will be a follow-on PR to connect figgy_staging to this new box.
=> Provision cantaloupe-staging

group_vars/libwww/libwww-prod.yml, hosts, playbooks/libwww-prod.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.libwww/templates/aliases_drushrc_php.j2
Allowing deploy to change the ownership
Allowing deploy to restart apache2
Allowing deploy to run commands as www-data
Updating the database to run using mysql commands instead of drush
Removing update.sql since we are doing that in capistrano
=> Adding in production

README.md, roles/example/main.yml, roles/example/molecule.yml, roles/example/yaml-lint.yml
@kayiwa I know this was assigned to you, but @pmgreen and @mzelesky and I went through adding a new one today so I decided to document what we had done.
fixes #575
=> Updating commands in README to match with circle ci

group_vars/nginxplus/main.yml
we do not need http template file examples any more
=> unbreak default.conf

group_vars/libwww/libwww-prod.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml
Additionally adding tests for crontab
Removed duplicate variable entries in production playbook
=> Changing crontab entry to run as www-data

roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml
Also changing pdo to common since that is what is installed
Added tests for the packages
=> Adding the mbstring php package

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
A couple of adjustments upon further review. These should be deployed prior to the domain name transfer if possible.
=> Proxy pass for locator and e-resource resolve app.

group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww.yml
Adding the comment out force setting so folks know that it is possible
=> Add force settings as a possible option

.circleci/config.yml, roles/pulibrary.openjdk/.yamllint, roles/pulibrary.openjdk/README.md, roles/pulibrary.openjdk/defaults/main.yml, roles/pulibrary.openjdk/handlers/main.yml, roles/pulibrary.openjdk/meta/main.yml, roles/pulibrary.openjdk/molecule/default/Dockerfile.j2, roles/pulibrary.openjdk/molecule/default/INSTALL.rst, roles/pulibrary.openjdk/molecule/default/molecule.yml, roles/pulibrary.openjdk/molecule/default/playbook.yml, roles/pulibrary.openjdk/molecule/default/tests/test_openjdk.py, roles/pulibrary.openjdk/molecule/default/tests/test_openjdk8.py, roles/pulibrary.openjdk/molecule/default/yaml-lint.yml, roles/pulibrary.openjdk/tasks/main.yml, roles/pulibrary.openjdk/vars/main.yml
this PR allows us to parametrize the versions of OpenJDK
=> install the headless version of the software

roles/pulibrary.nginxplus/tasks/main.yml, roles/pulibrary.nginxplus/tasks/validate.yml
make sure our configs are valid or fail
Co-authored-by: Carolyn Cole <cam156@psu.edu>
=> add a validation sanity check

roles/pulibrary.libwww/files/get_staff_updates.sh, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml
Setting time to run once at 5 am, instead of every minute in the 5am hour
Adding the path to drush to allow for cron to run it
Adding an output file
=> Changing staff cron job

group_vars/recap/recap-prod.yml, playbooks/recap-production.yml, roles/pulibrary.recap-www/tasks/main.yml, roles/pulibrary.recap-www/templates/drushrc.php.j2
Adding the configuration files for recap production
Adding datadog to recap
=> Recap prod

group_vars/dpul_staging.yml
refs pulibrary/pomegranate#593
=> Use lib-solr-staging for dpul staging

roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.libwww/templates/env.local.j2
Also fix syntax error in template
=> Allow .env file to be updated with force_settings

README.md
Put vault documentation next to each other
mention existence of `.gitattributes` file
=> Update vault documentation

roles/pulibrary.apache2/meta/main.yml, roles/pulibrary.apache2/molecule/default/molecule.yml, roles/pulibrary.apache2/molecule/default/yaml-lint.yml
the `../example/molecule.yml` file under the roles library is the
recommended way to do this
=> point to pulibrary docker

roles/pulibrary.nginxplus/files/conf/http/templates/dss-proxy-pass.conf
Adding additional directories that are needed for the pages to look correct
=> Adding the 2 to the proxy pass

README.md, roles/pulibrary.pas_code/tasks/main.yml
Adds documentation for lpass documentation, and how to set the session to last for more than 1 hour.
=> Adding additional information for last pass

.ansible-lint, roles/pulibrary.php/tasks/main.yml
- Restores installation of latest PHP while skipping linting errors.
Closes #843
=> Restore PHP latest

.github/workflows/molecule_tests.yml, requirements.txt, roles/pulibrary.bibdata/meta/main.yml, roles/pulibrary.extra_path/meta/main.yml, roles/pulibrary.rabbitmq/meta/main.yml, roles/pulibrary.tomcat8/meta/main.yml, run_molecule.py
- Adds a test runner that runs molecule tests for role under the following conditions:
1. The role was edited in the current branch.
1. The role depends on a role that was edited in the current branch.
1. The current branch is master (all molecule tests are run).
- In this PR, the `extra_path` role is modified and I confirmed that the extra_path tests are run.
- The `tomcat8` role is also modified in this PR, and the dependent Geoserver tests are run.
- I added a broken test to `ansible-datadog` and the tests fail as they should.
- https://github.com/pulibrary/princeton_ansible/commit/1b3e728160ec8d3fc6687a0316019a1ee32254fa/checks
- All other tests are skipped which significantly cuts down on the total test time.
=> Molecule improvements

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
Closes #886
Closes https://github.com/pulibrary/figgy/issues/2979
=> Increase ImageMagick resource limits

roles/pulibrary.nginxplus/tasks/keys/sig-science-key.yml, roles/pulibrary.nginxplus/tasks/main.yml, roles/pulibrary.nginxplus/tasks/modules/signal-science.yml
this install signal sciences to our nginx plus
=> install signal sciences module and agent

group_vars/recap/recap-staging.yml, roles/pulibrary.perconaxdb/README.md, roles/pulibrary.recap-www/.ansible-lint, roles/pulibrary.recap-www/defaults/main.yml, roles/pulibrary.recap-www/molecule/default/playbook.yml, roles/pulibrary.recap-www/vars/main.yml
Additionaly moving maria connection information into vars for the role
=> Changing staging to reference the percona server

roles/pulibrary.drupal/tasks/main.yml
It seems to be causing issues with the github actions
=> Removing npm patch for circle ci

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Having the proxy pass rules at special-collections was causing issues within the drupal sites.
=> Updating  proxy pass rules so they live at the base url

group_vars/figgy_production.yml, roles/pulibrary.postgres/tasks/readonly_user.yml, roles/pulibrary.postgresql/tasks/create_db.yml, roles/pulibrary.postgresql/tasks/create_users.yml
@hackmastera Can you look at this? You added the `become` bits, but the role wouldn't run with them
=> Necessary changes to get Figgy Playbook to run.

group_vars/libwww/libwww-staging.yml, roles/pulibrary.libwww/.flake8, roles/pulibrary.libwww/defaults/main.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.libwww/templates/aliases_drushrc_php.j2, roles/pulibrary.libwww/templates/special_collections_settings.php.j2, roles/pulibrary.libwww/vars/main.yml
The rbsc site will eventually be part of the main library site.  For now we are just moving the entire site to sit on the main library site machines.
Related to https://github.com/pulibrary/rbsc_drupal/issues/564
=> Moving RBSC onto the libwww machine

playbooks/patroni-staging.yml, roles/pulibrary.patroni/defaults/main.yml, roles/pulibrary.patroni/molecule/default/molecule_vars.yml, roles/pulibrary.patroni/molecule/default/playbook.yml, roles/pulibrary.patroni/tasks/configure.yml, roles/pulibrary.patroni/tasks/main.yml, roles/pulibrary.patroni/tasks/manage_users.yml
lack of systemd on our docker container makes this role impossible to test.
=> 892 patroni client role

group_vars/locator/locator-staging.yml, roles/pulibrary.locator/defaults/main.yml, roles/pulibrary.locator/meta/main.yml, roles/pulibrary.locator/tasks/main.yml
Additionally converted staging to use perconadb.
=> Adding samba share for images

hosts, playbooks/libruby-dev.yml, playbooks/libruby-prod.yml
Allows us to keep the deploy keys up to date.
=> Adding playbooks for Libruby

playbooks/pas-production-code.yml, playbooks/pas-production.yml, playbooks/pas-staging-code.yml, roles/pulibrary.pas_code/tasks/main.yml
Additionally updating all variable files to point at the new separate vaults
@axamei this is the work we did to get the role to run yesterday morning.
=> Updating the roles to run with master

group_vars/libwww/libwww-prod.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml
Adding special collections directories into prod vars
=> Updates to memory

group_vars/pas/pas-staging.yml, roles/pulibrary.pas/.ansible-lint, roles/pulibrary.pas/defaults/main.yml, roles/pulibrary.pas/molecule/default/playbook.yml, roles/pulibrary.pas_code/.ansible-lint, roles/pulibrary.pas_code/molecule/default/playbook.yml, roles/pulibrary.pas_code/tasks/main.yml
dunno how tight the coupling between `pas` and `pas_code` are so I will make these separate PRs.
=> 880 pas staging percona

group_vars/plantain/plantain_staging.yml, roles/pulibrary.plantain/meta/main.yml
refs pulibrary/plantain#54
this is currently deployed to plantain staging.
=> Add redis and sidekiq to plantain staging

roles/pulibrary.geoserver/tasks/main.yml, roles/pulibrary.geoserver/vars/main.yml
=> upgrade to postgresql-10 postgis-2.4

roles/pulibrary.plantain/templates/solrconfig.xml
Commits were timing out.
This is currently deployed to plantain-staging.
=> Add autocommit configuration for plantain solr

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Hopefully fixes missing styles and images
With the proxypass the page was miss styled.  I am hoping that a redirect works better.
=> Changing to redirect

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
=> Adding pinyin instructions to proxy pass

roles/pulibrary.openjdk8/tasks/main.yml, roles/pulibrary.tomcat8/meta/main.yml
=> remove openjdk8 role

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Adds proxy for firestone/renovations & republic to point at the new static staging server
=> Adding proxy for lib-static-staging

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Decided we do not want to show all the new domains, we want to keep the illusion this is all under the library.princeton.edu
=> Changing rewrite to proxy pass

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
=> Adding missing slash in proxy pass

roles/pulibrary.solrcloud/defaults/main.yml
=> upgrades solr production version to 7.7.2

playbooks/libwww-prod.yml
=> Fixing up formatting so post task runs

group_vars/recap/recap-staging.yml, roles/pulibrary.recap-www/defaults/main.yml, roles/pulibrary.recap-www/templates/settings.php.j2
Co-author-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
=> Moving recap to 3305

roles/pulibrary.libwww/templates/special_collections_settings.php.j2
Co-author-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
=> changing special collections to use 3305

hosts, playbooks/figgy_production.yml, playbooks/figgy_staging.yml
Variables weren't being pulled in.
=> Revert to underscores for Figgy group names.

group_vars/solrcloud.yml
=> Set solr heap to 20G

roles/pulibrary.solrcloud/templates/solr.conf.j2
soft is listed two times.
this closes issue #1076
=> add the hard limits

roles/pulibrary.figgy/defaults/main.yml
=> Remove a bunch of default figgy variables

roles/pulibrary.figgy/tasks/main.yml
in addition remove deprecated apt `squash_actions`
closes issue #1080
=> remove ppa repository for xenial

group_vars/lib-jobs/staging.yml, hosts, playbooks/lib-jobs-prod.yml, roles/pulibrary.lib-jobs/defaults/main.yml, roles/pulibrary.lib-jobs/molecule/default/tests/test_default.py, roles/pulibrary.lib-jobs/tasks/main.yml, roles/pulibrary.lib-jobs/templates/ruby_app_config, roles/pulibrary.lib-jobs/templates/sfx_env.yml.j2, roles/pulibrary.lib-jobs/vars/main.yml
Changing from yml to emvironment variables
Co-authored-by: pmgreen <pmgreen@princeton.edu>
Co-authored-by: Mark Zelesky <mzelesky@princeton.edu>
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
=> Adding production playbook for lib-jobs

group_vars/library-solr/library-solr-staging.yml, playbooks/library-solr-staging.yml, roles/pulibrary.solr/defaults/main.yml, roles/pulibrary.solr/molecule/default/tests/test_default.py, roles/pulibrary.solr/tasks/configure.yml, roles/pulibrary.solr/tasks/links.yml, roles/pulibrary.solr/tasks/main.yml, roles/pulibrary.solr/templates/core.properties.j2, roles/pulibrary.solr/templates/solr.in.sh.j2, roles/pulibrary.solr/templates/solr.xml.j2
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
=> Fixed role to deploy library-solr-staging

roles/pulibrary.mariadb/README.md, roles/pulibrary.mariadb/tasks/manage_contents.yml
Rather than one giant commit this will be one of many to make master green.
=> fix linting errors on this role

roles/pulibrary.composer/defaults/main.yml, roles/pulibrary.composer/molecule/default/playbook.yml, roles/pulibrary.composer/tasks/main.yml, roles/pulibrary.mariadb/tasks/manage_contents.yml, roles/pulibrary.perconaxdb/defaults/main.yml, roles/pulibrary.perconaxdb/tasks/bootstrap.yml
remove trailing space and add space after a variable
=> fix pythonic linting errors

group_vars/library-solr/library-solr-prod.yml, hosts, playbooks/library-solr-prod.yml, roles/pulibrary.solr/tasks/main.yml
Also allowinf deploy to restart solr
=> Adding library-solr-prod playbook

roles/pulibrary.cantaloupe/molecule/default/tests/test_cantaloupe.py
the download is owned by the deploy user
=> the symbolic link is owned by root

group_vars/perconaxdb/perconaxdb-staging.yml, hosts, playbooks/perconadb-staging.yml, roles/pulibrary.perconaxdb/defaults/main.yml, roles/pulibrary.perconaxdb/tasks/secure_install.yml, roles/pulibrary.perconaxdb/tasks/setup_install.yml
Also cleanined up staging files to match prod
=> Adding a root.% user with GRANT privs

hosts
=> Remove lib-proc4 and lib-proc5 from hosts

group_vars/orangelight_staging.yml, group_vars/solrcloud_staging.yml, hosts, playbooks/orangelight_staging.yml, playbooks/solrcloud_staging.yml
=> Add catalog-staging and lib-solr-staging to datadog

roles/pulibrary.locator/tasks/main.yml, roles/pulibrary.locator/templates/my.cnf.j2, roles/pulibrary.mariadb/defaults/main.yml, roles/pulibrary.mariadb/molecule/default/tests/test_mariadb.py, roles/pulibrary.mariadb/tasks/set_permission.yml, roles/pulibrary.mariadb/templates/db-user-my-cnf.j2
=> Adding my.cnf file for deploy user

group_vars/solrcloud_staging.yml
for catalog-staging and dpul-staging
=> Add http checks for solr staging

group_vars/lib-svn/production.yml, hosts, playbooks/lib-svn-prod.yml
we add a playbook and group_vars for lib-svn.
also remove mariadb2 and mariadb3
=> add the lib-svn to the hosts

.github/workflows/molecule_tests.yml, group_vars/dpul_production.yml, group_vars/dpul_staging.yml, group_vars/figgy_production.yml, group_vars/figgy_staging.yml, group_vars/lae_production.yml, group_vars/lae_staging.yml, group_vars/plantain/plantain_staging.yml, playbooks/dpul_production.yml, playbooks/dpul_staging.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, playbooks/lae.yml, playbooks/lae_staging.yml, roles/pulibrary.imagemagick/.yamllint, roles/pulibrary.imagemagick/README.md, roles/pulibrary.imagemagick/defaults/main.yml, roles/pulibrary.imagemagick/handlers/main.yml, roles/pulibrary.imagemagick/meta/main.yml, roles/pulibrary.imagemagick/molecule/default/Dockerfile.j2, roles/pulibrary.imagemagick/molecule/default/INSTALL.rst, roles/pulibrary.imagemagick/molecule/default/molecule.yml, roles/pulibrary.imagemagick/molecule/default/playbook.yml, roles/pulibrary.imagemagick/molecule/default/tests/test_default.py, roles/pulibrary.imagemagick/molecule/default/yaml-lint.yml, roles/pulibrary.imagemagick/tasks/main.yml, roles/pulibrary.imagemagick/templates/policy.xml.j2, roles/pulibrary.imagemagick/vars/main.yml, roles/pulibrary.plantain/meta/main.yml, run_molecule.py
=> Adds configurable ImageMagick Role and makes it configurable

roles/pulibrary.php/molecule/default/tests/test_php.py, roles/pulibrary.php/tasks/main.yml
add it to tests.
this closes #1189
=> add php7.2-zip as part of php install

architecture-decisions/0001-document-architecture-decisions.md
=> Add ADR to use ADRs

roles/pulibrary.apache2/handlers/main.yml, roles/pulibrary.lib-svn/meta/main.yml, roles/pulibrary.lib-svn/molecule/default/tests/test_default.py, roles/pulibrary.lib-svn/tasks/main.yml, roles/pulibrary.lib-svn/templates/svn_host.conf.j2
this also adds configuration for dav and dav_svn
the apache role now has an apache reload handler
the www-data user should be able to read and write the subversion
directories
=> add apache role as a dependency

roles/pulibrary.php/tasks/main.yml
Co-authored-by: Francis Kayiwa <kayiwa@princeton.edu>
=> Adding restart of apache when PHP is updated

group_vars/bibdata/bibdata.yml
add a tls expiration check for bibdata.princeton.edu
=> add tls check

group_vars/figgy_production.yml, group_vars/figgy_production_webserver.yml, group_vars/figgy_production_workers.yml, group_vars/orangelight.yml, group_vars/pulmap.yml
this adds the datadog integration for TLS checks for
figgy.princeton.edu and catalog.princeton.edu
=> add a tls cert check

group_vars/cicognara_production.yml, group_vars/dpul_production.yml
checks for dpul.princeton.edu and cicognara.org
=> add tls checks

group_vars/libwww/libwww-prod.yml, group_vars/pas/pas-production.yml, group_vars/recap/recap-prod.yml
this adds a tls cert check for
recap and library.princeton.edu
=> add a tls cert check intergration

group_vars/pas/pas-production.yml
[pas] fixes issue #1225 on pas
=> fix name of TLS check on PAS

group_vars/dpul_staging.yml
fixes pulibrary/pomegranate#703
=> Add honeybadger key to dpul staging

group_vars/lib-svn/production.yml, group_vars/lib-svn/staging.yml, roles/pulibrary.lib-svn/defaults/main.yml, roles/pulibrary.lib-svn/tasks/main.yml, roles/pulibrary.lib-svn/templates/svn_host.conf.j2
we create a new htpassword file which will use the same credentials for authentication
this requires an update of the apache config and generation of new users
we will also install the python-passlib framework
=> add htpasswd utility generated file

roles/pulibrary.ruby/molecule/default/tests/test_ruby.py, roles/pulibrary.ruby/tasks/main.yml
tests
this will impact any ruby application and closes issue #1233
=> update ruby to 2.6.5 and corresponding

group_vars/all/vars.yml
this variable overrides anything we would try to do
=> remove ruby 2.3.1

group_vars/libwww/libwww-prod.yml, group_vars/pas/pas-production.yml, group_vars/recap/recap-prod.yml
naming the module tls will work.
=> there is no module with the named libwww

roles/pulibrary.clamav/tasks/main.yml
=> clamav does multiple downloads

group_vars/all/vars.yml
also added postgresql 10 version
cleaned up the variables so python syntax enabled editor wouldn't complain
=> remove ruby 2.3.1 reference

roles/pulibrary.perconaxdb/README.md
=> describe how to backup and restore databases

roles/pulibrary.lib-svn/tasks/main.yml, roles/pulibrary.lib-svn/templates/ead_pre_commit.sh.j2
we also install xmllint which is needed by the hook
this closes issue #1254
=> add an ead pre commit hook

playbooks/figgy_production.yml, roles/pulibrary.mediainfo/defaults/main.yml, roles/pulibrary.mediainfo/tasks/main.yml
The old one had expired certs.
=> [Figgy] Update MediaServer repository

group_vars/figgy_production.yml
It needs to ingest some really, really big files.
=> [Figgy] Adjust Figgy ImageMagick configuration

group_vars/solr8cloud/staging.yml
=> Use new solr8 cjk jar

roles/pulibrary.rvm/defaults/main.yml
support for ruby 2.4 ends in March. Upgrading to 2.6.5
=> this role default to ruby 2.4

group_vars/pulmap.yml
=> Add zlib1g-dev to pulmap rails dependencies

group_vars/solr8cloud/production.yml, group_vars/solr8cloud/staging.yml
our mirror now has the desired dist.
closes #1318
=> solr cloud: remove use of apache archive

playbooks/pulmap_production.yml, playbooks/pulmap_staging.yml
otherwise the sidekiq and sneakers are not installed
Co-authored-by: Eliot Jordan <eliotj@princeton.edu>
=> add the running on server variable

group_vars/approvals/approvals_prod.yml, playbooks/approvals_production.yml
point to datadog role
this closes #1338
=> add datadog variables to approvals

group_vars/all/vars.yml, playbooks/libstatic_production.yml, playbooks/libstatic_staging.yml, playbooks/libwww_production.yml, playbooks/libwww_staging.yml, playbooks/locator_production.yml, playbooks/locator_staging.yml, playbooks/mudd_production.yml, playbooks/mudd_staging.yml, playbooks/pas_production.yml, playbooks/pas_production_code.yml, playbooks/pas_staging.yml, playbooks/pas_staging_code.yml, playbooks/perconadb_production.yml, playbooks/perconadb_staging.yml, playbooks/pulmap_production.yml, playbooks/pulmap_staging.yml, playbooks/recap_production.yml, playbooks/recap_staging.yml, playbooks/ruby_office.yml, playbooks/solr8cloud_production.yml
this allows running on server to work predictably
closes issue #1297
Co-authored-by: carolyncole <1599081+carolyncole@users.noreply.github.com>
=> add global running on server

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
Necessary for getting rid of Kakadu.
=> [Figgy] Install OpenJPEG

group_vars/all/vars.yml
Co-authored-by: Anna Headley <anna.headley@gmail.com>
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
=> Update the ol_solr_url to the solr8 cloud

group_vars/figgy_staging.yml, playbooks/figgy_staging.yml, roles/pulibrary.figgy/defaults/main.yml, roles/pulibrary.nodejs/molecule/default/molecule.yml, roles/pulibrary.nodejs/molecule/default/playbook.yml, roles/pulibrary.nodejs/molecule/default/prepare.yml, roles/pulibrary.nodejs/molecule/default/tests/test_nodejs.py, roles/pulibrary.nodejs/tasks/main.yml
=> Updating NodeJS to 12.x LTS releases for the pulibrary.figgy Role

group_vars/cantaloupe/production.yml, group_vars/cantaloupe/staging.yml
We immediately got complaints and the production server crashed.
=> [Cantaloupe] Revert to KakaduDemoProcessor

group_vars/dss/dss_production.yml
=> Update dss solr url to use solr 8

group_vars/lib-jobs/prod.yml, group_vars/lib-jobs/staging.yml, playbooks/lib_jobs_production.yml, playbooks/lib_jobs_staging.yml, roles/pulibrary.lib-jobs/meta/main.yml, roles/pulibrary.lib-jobs/vars/main.yml
Done in code mobbing session with @carolyncole
=> added rails role to lib_jobs role as dependency and configured it

.github/workflows/molecule_tests.yml, roles/pulibrary.vips/.yamllint, roles/pulibrary.vips/README.md, roles/pulibrary.vips/defaults/main.yml, roles/pulibrary.vips/handlers/main.yml, roles/pulibrary.vips/meta/main.yml, roles/pulibrary.vips/molecule/default/Dockerfile.j2, roles/pulibrary.vips/molecule/default/INSTALL.rst, roles/pulibrary.vips/molecule/default/molecule.yml, roles/pulibrary.vips/molecule/default/playbook.yml, roles/pulibrary.vips/molecule/default/tests/test_default.py, roles/pulibrary.vips/molecule/default/yaml-lint.yml, roles/pulibrary.vips/tasks/main.yml, roles/pulibrary.vips/templates/ldconfig.vips.conf, roles/pulibrary.vips/vars/main.yml
Will be required to use VIPS to generate pyramidal tiffs.
=> Add VIPS Role.

README.md
included are the different sorts of files to look for as hints based on
my search results yesterday
=> this adds the steps for modifying passwords

roles/pulibrary.bibdata/defaults/main.yml, roles/pulibrary.bibdata/meta/main.yml, roles/pulibrary.postgresql/README.md, roles/pulibrary.postgresql/tasks/main.yml
Update the readme for required variables
=> Making sure that postges is restarted after access is changed

group_vars/dss/dss_production.yml, playbooks/dss_production.yml
also had to update where the production playbook was pointing for its variables
=> [DSS] Updating production to point at postgres

group_vars/dss/dss_production.yml, roles/pulibrary.dss/vars/main.yml
refs https://github.com/pulibrary/DSS/pull/158
=> [DSS] Adding production google analytics id

roles/pulibrary.oracle.client/handlers/main.yml, roles/pulibrary.oracle.client/tasks/main.yml
=> add a ruby config file to link oracle client

roles/pulibrary.figgy/templates/nginx_extra_config
I'm not sure how to test this
resolves #3812
=> Enable CORS for pul logo given in manifests

group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww-staging.yml, group_vars/locator/locator-prod.yml, group_vars/locator/locator-staging.yml, group_vars/mudd/mudd-prod.yml, group_vars/mudd/mudd-staging.yml, group_vars/pas/pas-production.yml, group_vars/pas/pas-staging.yml, group_vars/recap/recap-prod.yml, group_vars/recap/recap-staging.yml, playbooks/locator_production.yml, playbooks/locator_staging.yml, roles/pulibrary.libwww/molecule/default/playbook.yml, roles/pulibrary.pas/README.md, roles/pulibrary.pas_code/README.md
Having the loadbalancer in the mix is causing errors.
fixes #1471
=> Moving to mariadb-prod1 and mariadb-staging1

group_vars/libwww/libwww-prod.yml, group_vars/locator/locator-prod.yml, group_vars/mudd/mudd-prod.yml, group_vars/pas/pas-production.yml, group_vars/recap/recap-prod.yml, roles/pulibrary.pas/README.md, roles/pulibrary.pas_code/README.md
That is the real machine name...
I tried running the locator playbook and that failed with the code in master, but passes with this new code.
=> Changing all instances of maria-prod1 to mariadb-prod1

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
=> Configure ACTIVE_STORAGE_ROOT for figgy

group_vars/libwww/libwww-prod.yml, roles/pulibrary.apache2/defaults/main.yml, roles/pulibrary.apache2/tasks/main.yml, roles/pulibrary.apache2/templates/vhosts24.conf.j2, roles/pulibrary.libwww/defaults/main.yml, roles/pulibrary.libwww/tasks/main.yml, roles/pulibrary.php/defaults/main.yml, roles/pulibrary.php/molecule/default/playbook.yml, roles/pulibrary.php/molecule/default/tests/test_php.py, roles/pulibrary.php/tasks/main.yml, roles/pulibrary.php/vars/main.yml
Installed on staging servers for testing purposes
Installed on production
Co-authored: Francis Kayiwa <kayiwa@pobox.com>
=> Adding datadog php apm trace

group_vars/recap/recap-staging.yml
=> Moving recap staging to stand alone percona

group_vars/locator/locator-prod.yml, group_vars/locator/locator-staging.yml, roles/pulibrary.locator/tasks/main.yml
=> Moving locator to local percona

group_vars/pas/pas-staging.yml, playbooks/pas_staging_code.yml
=> Moving pas staging to stand alone percona

roles/pulibrary.libwww/defaults/main.yml
@kayiwa I thought about separating these into different services and then settled on the fact that since the apache logs are intertwined they should all be the same service.  Unfortunately the separate service got committed accidentally.  This PR puts them back together.
=> Decided this should really be in one service since the logs are combined

roles/pulibrary.recap-www/templates/settings.php.j2
@carolyncole @axamei for https://github.com/pulibrary/recap/pull/131
=> Add install profile standard to recap settings.php conf.

group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/staging.yml
This was run on bibdata-staging1.princeton.edu
=> Adding Hathi environment variables

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
=> Install ocrmypdf on Figgy servers

group_vars/pulmap_staging.yml
=> Use figgy_staging_rabbit_host variable in pulmap-staging

.github/workflows/molecule_tests.yml, group_vars/figgy_staging.yml, host_vars/lib-proc9.princeton.edu.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/pulibrary.figgy_filewatcher_worker/.yamllint, roles/pulibrary.figgy_filewatcher_worker/README.md, roles/pulibrary.figgy_filewatcher_worker/defaults/main.yml, roles/pulibrary.figgy_filewatcher_worker/handlers/main.yml, roles/pulibrary.figgy_filewatcher_worker/meta/main.yml, roles/pulibrary.figgy_filewatcher_worker/molecule/default/Dockerfile.j2, roles/pulibrary.figgy_filewatcher_worker/molecule/default/INSTALL.rst, roles/pulibrary.figgy_filewatcher_worker/molecule/default/molecule.yml, roles/pulibrary.figgy_filewatcher_worker/molecule/default/playbook.yml, roles/pulibrary.figgy_filewatcher_worker/molecule/default/tests/test_default.py, roles/pulibrary.figgy_filewatcher_worker/molecule/default/yaml-lint.yml, roles/pulibrary.figgy_filewatcher_worker/tasks/main.yml, roles/pulibrary.figgy_filewatcher_worker/templates/filewatcher.service, roles/pulibrary.figgy_filewatcher_worker/tests/inventory, roles/pulibrary.figgy_filewatcher_worker/tests/test.yml, roles/pulibrary.figgy_filewatcher_worker/vars/main.yml
Closes #1583 
Related to: https://github.com/pulibrary/figgy/pull/3957
=> Add figgy filewatcher service

roles/pulibrary.sidekiq_worker/defaults/main.yml
=> Create top-level 'high' queue for sidekiq workers

roles/pulibrary.bibdata/tasks/samba_client.yml
add ignore_errors in the second mount task
=> Update title of the task

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
=> [NGINX] Adding proxy pass for islamic project to dpul site

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
=> Changing to redirect since proxy pass did not  work

roles/pulibrary.nginxplus/tasks/adjust_ulimit.yml, roles/pulibrary.nginxplus/tasks/main.yml, roles/pulibrary.nginxplus/templates/nginx_ulimit.conf.j2
- limit when the nginxplus role is running
- we are bumping up the ulimit for the nginx user
this will close issue #1630
=> 1630 increase ulimit nginx

group_vars/all/vars.yml
=> add regina's keys to deploy user

group_vars/bibdata/staging.yml, hosts
we also add variables to connect the staging server to the staging
cluster
this will close #1450
=> this adds the bibdata-staging2 vm to the hosts file

roles/pulibrary.figgy/tasks/main.yml
=> Add poppler to figgy machines

roles/pulibrary.figgy/tasks/main.yml, roles/pulibrary.vips/tasks/main.yml
=> Move poppler install to vips role

group_vars/figgy_production.yml, group_vars/figgy_staging.yml, roles/pulibrary.figgy/tasks/main.yml
Used for automatic ingest of CDL items.
Necessary for https://github.com/pulibrary/figgy/pull/4157
=> Create CDL Scans Mount

group_vars/dpul_production.yml, group_vars/dpul_staging.yml
refs pulibrary/pomegranate#821
=> DPUL upgrade nodejs to 12.x

group_vars/pulmap.yml, group_vars/pulmap_staging.yml
=> Pulmap NodeJS 12

group_vars/pulfalight/staging.yml
Resolves https://github.com/pulibrary/pulfalight/issues/339
=> Updates the APPLICATION_HOST and APPLICATION_PORT env. variables for pulfalight

roles/pulibrary.drupal9/tasks/main.yml
=> [Researchdata] Adding drush to deploy's path

group_vars/bibdata/production.yml
=> Add Hathi vars in bibdata prod

.github/workflows/molecule_tests.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/pulibrary.memcached/.ansible-lint, roles/pulibrary.memcached/.yamllint, roles/pulibrary.memcached/LICENSE, roles/pulibrary.memcached/README.md, roles/pulibrary.memcached/defaults/main.yml, roles/pulibrary.memcached/handlers/main.yml, roles/pulibrary.memcached/meta/main.yml, roles/pulibrary.memcached/molecule/default/Dockerfile.j2, roles/pulibrary.memcached/molecule/default/INSTALL.rst, roles/pulibrary.memcached/molecule/default/molecule.yml, roles/pulibrary.memcached/molecule/default/playbook.yml, roles/pulibrary.memcached/molecule/default/tests/test_default.py, roles/pulibrary.memcached/molecule/default/yaml-lint.yml, roles/pulibrary.memcached/tasks/main.yml, roles/pulibrary.memcached/templates/memcached-Debian.conf.j2, roles/pulibrary.memcached/templates/memcached-RedHat.conf.j2, roles/pulibrary.memcached/vars/Debian.yml, roles/pulibrary.memcached/vars/RedHat.yml, roles/pulibrary.memcached/vars/main.yml
We'll be able to use this for Figgy web caching.
=> Add Memcached

roles/pulibrary.common/tasks/main.yml, roles/pulibrary.passenger/tasks/main.yml
bibdata-staging1 is not bionic so we should ignore the errors
=> Updating to work on bibdata-staging1

group_vars/figgy_production.yml
figgy2 wasn't able to reach memcached before this.
=> [Figgy] Bind Figgy's memcached to a public IP.

run_molecule.py
=> use main instead of master

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
=> Redirecting research-data on the main library site to the new home page

group_vars/bibdata/production.yml, roles/pulibrary.bibdata/meta/main.yml
comment out role: pulibrary.hr_share from bibdata/meta/main.yml
Co-authored-by: Carolyn Cole <cac9@princeton.edu>
=> Adds bibdata_db_port in group_vars

group_vars/libstatic/libstatic-prod.yml, group_vars/libstatic/libstatic-staging.yml, roles/pulibrary.libstatic/defaults/main.yml, roles/pulibrary.libstatic/molecule/default/tests/test_libstatic.py, roles/pulibrary.libstatic/tasks/main.yml, roles/pulibrary.libstatic/templates/lib-static-site.conf.j2, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Added Capping Liberty
Added Pathe Baby
Added Thankful Nation
Added Hogarth
fixes #1792
=> Adding more static sites to lib-static-staging

group_vars/all/vars.yml, group_vars/figgy/production.yml
=> Updating to hackartisan

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
Removes more sites from libphp-prod
=> Updating nginx to point at the new static sites

group_vars/lib-jobs/prod.yml, group_vars/lib-jobs/staging.yml, roles/pulibrary.lib-jobs/meta/main.yml, roles/pulibrary.lib-jobs/vars/main.yml
Also add new postgres variables
fixes #1780
=> [lib_Jobs] Add hr share to lib_jobs hosts

group_vars/ezproxy/prod.yml, hosts, playbooks/ezproxy_prod.yml
@kevinreiss this is based on our discussion from earlier today
=> ezproxy-prod1 set up

roles/pulibrary.researchdata/tasks/main.yml
Co-Authored-by: Axa Mei Liauw <aliauw@princeton.edu>
=> Updating the cron for researchdata

group_vars/researchdata/researchdata_prod.yml, group_vars/researchdata/researchdata_staging.yml, roles/pulibrary.drupal9/defaults/main.yml, roles/pulibrary.drupal9/molecule/default/tests/test_drupal9.py, roles/pulibrary.drupal9/templates/settings.php.j2
=> Allow more than one name for the drupal site

group_vars/cicognara_production.yml
Progresses https://github.com/pulibrary/cicognara-rails/issues/474
=> [Cicognara] Use Solr8 for Production.

group_vars/bibdata/alma_staging.yml, hosts, playbooks/bibdata_alma_staging.yml, playbooks/bibdata_production.yml, roles/bibdata/meta/main.yml, roles/deploy_user/tasks/main.yml, roles/hr_share/tasks/main.yml
This also fixes a couple issues I ran into while running this playbook:
* app_configs being 0644 made it unable to be navigated to.
* As per #1794, dms-smbserve is unroutable, so use an IP.
Closes #1794
=> [Bibdata] Add bibdata-alma-staging

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
closes pulibrary/figgy#4338
closes pulibrary/figgy#3887
closes pulibrary/figgy#3892
closes pulibrary/figgy#3934
=> [Figgy] Add GAPI Scope to env vars.

group_vars/libwww/libwww-staging.yml, roles/libwww/defaults/main.yml, roles/libwww/meta/main.yml
=> Adding mailcatcher to library-staging

hosts
=> add lib-orange-staging2

.github/workflows/molecule_tests.yml, .tool-versions, Pipfile, Pipfile.lock, requirements.txt
=> update python, ansible and molecule

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
=> add a redirect to libcal

roles/solrcloud/tasks/install.yml
=> add the uri module

roles/libwww/templates/special_collections_settings.php.j2
=> [libwww] Adding additional tags to special collections editors

playbooks/pas_production.yml, playbooks/pas_staging.yml, roles/drupal/molecule/default/verify.yml, roles/drupal/tasks/main.yml, roles/libwww/meta/main.yml, roles/libwww/molecule/default/verify.yml, roles/libwww/tasks/main.yml, roles/locator/tasks/main.yml, roles/matomo/molecule/default/verify.yml, roles/matomo/tasks/configure.yml, roles/matomo/tasks/install.yml, roles/matomo/tasks/main.yml, roles/pas/molecule/default/verify.yml, roles/pas/tasks/main.yml, roles/php/README.md, roles/php/defaults/main.yml, roles/php/meta/main.yml, roles/php/molecule/default/verify.yml, roles/php/tasks/configure-nginx.yml, roles/php/tasks/configure.yml, roles/php/tasks/main.yml, roles/php/tasks/mod-php.yml, roles/php/tasks/php-cli.yml
=> update default PHP version to 7.4

group_vars/bibdata/alma_staging.yml, playbooks/bibdata_alma_staging.yml
=> add datadog variables in bibdata-alma-staging

group_vars/solr8cloud/production.yml
advances pulibrary/pul_solr#215
=> Add bundler version to solr8cloud production

hosts
This was forgotten in the last PR...
=> Updating hosts file for fpul-prod machines

group_vars/all/vars.yml
=> add Hector to Deploy User

roles/apache2/molecule/default/converge.yml, roles/common/defaults/main.yml, roles/common/molecule/default/converge.yml, roles/common/molecule/default/verify.yml, roles/common/tasks/main.yml, roles/composer/molecule/default/converge.yml, roles/drush/molecule/default/converge.yml
`"Failed to update apt cache: unknown reason"`
co-authored-by: Francis Kayiwa <kayiwa@users.noreply.github.com>
fixes #2112
=> Update the yarn key to avoid issue

group_vars/approvals/approvals_staging.yml
That is where the staging database truely resides
=> Updating to point at production postgres

group_vars/orangelight/alma_qa.yml
refs pulibrary/orangelight#2332
=> Add USE_ALMA switch to catalog-alma-qa

group_vars/solrcloud.yml, group_vars/solrcloud_staging.yml, playbooks/solrcloud_production.yml, playbooks/solrcloud_staging.yml
WIP add backups to solr7 boxes
refs pulibrary/pul_solr#257
closes #2142
=> Prepare solr 7 boxes for backups

roles/ojs/defaults/main.yml, roles/ojs/tasks/main.yml, roles/ojs/templates/shibboleth2.xml.j2
Co-authored: Francis Kayiwa <kayiwa@users.noreply.github.com>
Co-authored: Axa Mei Liauw <aliauw@princeton.edu>
=> Updating to 3.2.1 and php 7.4

.github/workflows/molecule_tests.yml
Co-authored-by: Carolyn Cole <cac9@princeton.edu>
closes #2168
=> remove apparmor from running

group_vars/dataspace/production.yml, group_vars/oar/production.yml
=> Upgrade postgres to 13

group_vars/bibdata/alma_staging.yml, group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/production.yml, group_vars/bibdata/staging.yml
This will make sure we do not accidentally get a full dump
=> [BIBDATA] Add incremental directory to the path

group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/production.yml
This was already done on staging, but forgotten for production
Actually it looks like it was on the server, but no committed to ansible.
=> [BIBDATA] creating a shared location between production servers for campus access files

roles/libwww/tasks/main.yml
refs #1507
Low hanging solution to "help" with the apache issue
=> [LIBWWW] allow deploy to reboot the server

group_vars/bibdata/alma_staging.yml, group_vars/orangelight/alma_qa.yml
=> Update the solr collection name in the alma staging boxes

group_vars/bibdata/alma_staging.yml
=> [Bibdata] Use SCSB Staging Bucket for Alma QA

group_vars/libwww/libwww-prod.yml, roles/datadog/defaults/main.yml, roles/datadog/tasks/agent6.yml, roles/libwww/vars/main.yml, roles/php/vars/main.yml
Allows apache to send data while running, not just on restart
=> Upgrading datadog php trace module

group_vars/orangelight/alma_qa.yml
refs pulibrary/orangelight#2430
=> Use mailcatcher on catalog-alma-qa

roles/ojs/tasks/main.yml, roles/ojs/templates/config.inc.php.j2, roles/ojs/templates/ojs.conf.j2, roles/ojs/templates/virtualhost.conf.j2
Connected to https://github.com/pulibrary/openpublishing/issues/24
=> Enable restful URLs for OJS

roles/nginxplus/files/conf/http/lib-sc-staging.conf
Which is needed for proper login with CAS
=> [special-collections] Adding proxy_ssl_server_name

hosts
=> Update host name for catalog-alma-qa

roles/lib_jobs/tasks/main.yml
deploy will be the one running these jobs, not www-data
=> Making the user deploy for the voucher mounts

roles/nginxplus/files/conf/http/pulfalight-prod.conf
Should help with an issue with PACSCL
=> [Pulfalight] Increase connect timeout.

roles/nginxplus/files/conf/http/library-prod.conf, roles/nginxplus/files/conf/http/library-staging.conf
Also, modify the match string to conform to Drupal
=> LIBWWW Adding caching on staging

roles/nginxplus/files/conf/http/pulfalight-prod.conf
Fixes indexing issues with PACSCL.
=> [Pulfalight] Add max_fails param to prevent immediate upstream failure.

group_vars/bibdata/production.yml, hosts, roles/bibdata/defaults/main.yml, roles/bibdata/tasks/samba_client.yml
this adds a new host for bibdata-workers
=> add new host and variables

group_vars/bibdata/bibdata_workers.yml, roles/bibdata/meta/main.yml
=> Add timezone on bibdata role

group_vars/bibdata/alma_staging.yml
=> [bibdata-alma-staging] Use staging scsb s3 bucket

group_vars/bibdata/alma_production.yml, group_vars/bibdata/alma_staging.yml, group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/production.yml, group_vars/bibdata/staging.yml
=> bibdata: Set owner for samba shares

playbooks/deploy_user.yml
=> add a deploy playbook

group_vars/bibdata/alma_staging.yml, playbooks/bibdata_alma_staging.yml, roles/bibdata/tasks/mounts.yml
=> Fix write permissions for bibdata-alma-staging

playbooks/bibdata_alma_production.yml, playbooks/bibdata_alma_staging.yml
=> Fix permissions on bibdata alma production boxes

group_vars/all/vars.yml
=> add xander to deploy users

roles/deploy_user/handlers/main.yml, roles/deploy_user/tasks/main.yml
=> Use service instead of systemd syntax for handler

group_vars/bibdata/alma_staging.yml, group_vars/bibdata/alma_workers.yml, playbooks/bibdata_alma_production.yml
should resolve honeybadger errors
https://app.honeybadger.io/projects/54497/faults/79785330
=> Set bibdata-alma boxes to eastern time zone

group_vars/orangelight/alma_prod.yml, group_vars/orangelight/alma_qa.yml, group_vars/orangelight/production.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml, playbooks/orangelight_toggle_readonly.yml
=> Add playbook to toggle orangelight's read-only mode

playbooks/figgy_production.yml, roles/rabbitmq/tasks/main.yml
These were a few fixes I had to do to get Ansible to run on Figgy's prod boxes.
=> [Figgy] Fixes for production run.

architecture-decisions/0004-key-scope
=> Add ADR for key scope

group_vars/bibdata/alma_production.yml, group_vars/bibdata/alma_staging.yml, group_vars/bibdata/alma_workers.yml, playbooks/bibdata_alma_production.yml, playbooks/bibdata_alma_staging.yml
Closes https://github.com/pulibrary/bibdata/issues/1418
=> Add campus_access_files to bibdata alma machines

group_vars/bibdata/alma_staging.yml
to resolve https://app.honeybadger.io/projects/54497/faults/79966005
=> [bibdata] Correct rebuild index name

roles/lib_jobs/tasks/main.yml, roles/lib_jobs/vars/main.yml
Also allow deploy to write to the peoplesoft mount
=> [LIB_JOBS] Adding voucher status and fund adjustment paths

group_vars/bibdata/alma_staging.yml
follow up from https://github.com/pulibrary/princeton_ansible/pull/2323
=> [Bibdata] Use new vault variable names for aws buckets

group_vars/bibdata/alma_production.yml, group_vars/bibdata/alma_staging.yml, group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/production.yml, group_vars/bibdata/staging.yml
Closes https://github.com/pulibrary/bibdata/issues/1466
=> [Bibdata] Fix SCSB delete directory path.

group_vars/bibdata/alma_production.yml
This is what's been created in solr and it's symmetrical to the current
`catalog-rebuild` alias.
re: https://app.honeybadger.io/projects/54497/faults/80165903
=> Use catalog-alma-rebuild as index name

group_vars/bibdata/alma_staging.yml, hosts, playbooks/bibdata_alma_staging.yml
Refs https://github.com/pulibrary/bibdata/issues/1417
=> [Bibdata] Add bibdata worker to staging.

group_vars/bibdata/alma_staging.yml
Now that we've split our env vars for reads vs writes we can read from prod
=> [Bibdata] set alma-staging to pull scsb partner files from prod

roles/nginxplus/files/conf/http/bibdata-alma.conf, roles/nginxplus/files/conf/http/bibdata-prod.conf, roles/nginxplus/files/conf/http/catalog-alma.conf, roles/nginxplus/files/conf/http/catalog-prod.conf
Work towards https://github.com/pulibrary/princeton_ansible/issues/2328
=> [Bibdata/Orangelight] Prepare load balancer for Alma cutover.

hosts, playbooks/bibdata_alma_production.yml
Refs https://github.com/pulibrary/bibdata/pull/1502
=> [Bibdata] Add bibdata-alma-worker2-4

group_vars/dpul_staging.yml
Connected to https://github.com/pulibrary/dpul/issues/822
=> Move dpul-staging to solr8

roles/nginxplus/files/conf/http/bibdata-alma-staging.conf, roles/nginxplus/files/conf/http/bibdata-alma.conf, roles/nginxplus/files/conf/http/catalog-alma-qa.conf, roles/nginxplus/files/conf/http/catalog-alma.conf
During final migration phase
closes pulibrary/bibdata#1492
=> Take alma-dependent services off the load balancer

roles/bibdata/tasks/mounts.yml, roles/rails_app/tasks/main.yml
This allow you to run just the update to the configs a playbook with ' --tags site_config'
=> Adding a tag to site configs

.githooks/pre-commit, README.md, bin/setup
This requires bin/setup to get running.
=> Add pre-commit hook to prevent committing unvaulted vault files.

group_vars/lib_jobs/prod.yml
=> Changing lib-jobs prod to look at the prod peoplesoft

group_vars/bibdata/alma_production.yml, group_vars/bibdata/alma_staging.yml
=> Write traject logs to datadog

roles/nginxplus/files/conf/http/bibdata-alma-staging.conf, roles/nginxplus/files/conf/http/bibdata-alma.conf, roles/nginxplus/files/conf/http/catalog-alma-qa.conf, roles/nginxplus/files/conf/http/catalog-alma.conf
=> Re-enable bibdata alma web UIs

group_vars/orangelight/alma_prod.yml, group_vars/orangelight/alma_qa.yml
After the load balancer cutover, we will run these changes
refs #2328
=> [orangelight alma] update group vars for cutover

roles/nginxplus/files/conf/http/catalog-prod.conf
=> [catalog] set active health check to fail faster

group_vars/orangelight/alma_prod.yml
=> Add in alma_prod.yml env vars for smtp_host

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, roles/rabbitmq/tasks/main.yml
Work towards https://github.com/pulibrary/figgy/issues/4593
=> [Figgy] Add sidekiq pro keys to Figgy.

hosts, roles/nginxplus/files/conf/http/catalog-prod.conf
=> add catalog3

group_vars/solr8cloud/production.yml
=> Fix check used for solr uptime monitor

hosts, roles/bibdata_sqs_poller/handlers/main.yml, roles/bibdata_sqs_poller/templates/sqs-poller.service
closes pulibrary/bibdata#1586
closes #2427
=> [Bibdata] Move RAILS_ENV to start of poller execution

group_vars/bibdata/production.yml, group_vars/bibdata/staging.yml, hosts
* 2 Sidekiq threads/box (2 CPUs on each box)
* 2 workers in prod (any more maxes out Solr CPU)
=> [Bibdata] Scale bibdata workers appropriately.

.github/workflows/molecule_tests.yml, group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml, playbooks/oawaiver_production.yml, playbooks/oawaiver_staging.yml, roles/oawaiver/.ansible-lint, roles/oawaiver/.yamllint, roles/oawaiver/README.md, roles/oawaiver/defaults/main.yml, roles/oawaiver/handlers/main.yml, roles/oawaiver/meta/main.yml, roles/oawaiver/molecule/default/converge.yml, roles/oawaiver/molecule/default/molecule.yml, roles/oawaiver/molecule/default/verify.yml, roles/oawaiver/tasks/main.yml, roles/oawaiver/tests/inventory, roles/oawaiver/tests/test.yml, roles/oawaiver/vars/main.yml
Resolves https://github.com/pulibrary/oawaiver/issues/24
=> Implementing a Role for the oawaiver Rails application

group_vars/approvals/approvals_prod.yml
fixes #2319
In production I have four requests total.
Prior to the change: (see the number 13 at the end)
```
deploy@lib-approvals-prod1:/opt/approvals/current$ bundle exec rails c
Loading staging environment (Rails 5.2.3)
irb(main):001:0>  me = StaffProfile.find_by(email: 'cac9@princeton.edu')
StaffProfile Load (39.4ms)  SELECT  "staff_profiles".* FROM "staff_profiles" WHERE "staff_profiles"."email" = $1 LIMIT $2  [["email", "cac9@princeton.edu"], ["LIMIT", 1]]
=> #<StaffProfile id: 111, user_id: 111, department_id: 4, biweekly: false, given_name: "Carolyn Ann", surname: "Cole", email: "cac9@princeton.edu", created_at: "2020-01-27 20:39:45", updated_at: "2021-08-21 00:20:13", supervisor_id: 148, location_id: 1, vacation_balance: 0.21675e3, sick_balance: 0.21025e3, personal_balance: …
```
=> [APPROVALS] Updating production rails env to be production

group_vars/special_collections/special_collections_prod.yml
fixes #2220
@kayiwa  this one is for you.  Better late than never...
=> [Special Collections] Moving to mariadb prod2 database server

roles/nginxplus/files/conf/http/oawaiver-prod.conf
=> add oawaiver http redirect server block

group_vars/orangelight/alma_qa.yml
=> point alma_qa, bibdata_base to bibdata_prod

roles/nginxplus/files/conf/http/getit_dev.conf, roles/nginxplus/files/conf/http/getit_prod.conf
=> [GETIT] Updating https rules to match http rules, which work

group_vars/orangelight/alma_prod.yml
refs pulibrary/orangelight#2600
=> [orangelight] Prep for database migration

roles/nginxplus/files/conf/http/getit_dev.conf, roles/nginxplus/files/conf/http/getit_prod.conf
=> Adding access online to getit catalog redirect

group_vars/mudd/mudd-prod.yml, group_vars/mudd/mudd-staging.yml, roles/mudd/vars/main.yml
Also allow staging to be the rails staging environment
=> [MUDD-DBS] Fix links when on the local machine

playbooks/dss_production.yml, roles/dss/vars/main.yml
Also setting the bundler version to allow for deployments
=> Updating the production playbook so it runs

group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww-staging.yml, roles/nodejs/tasks/main.yml
Also updating the node role to install a version that is not 12
=> Updating the library machines to have node 11 installed

hosts, playbooks/postgresql_db_migration.yml
- preliminary_postgres steps
- this dumps rsyncs and restores a database
=> i2356 postgres update

group_vars/dpul_staging.yml
For testing DPUL prod data in staging.
=> [Do not merge] Set dpul-staging to point to figgy-prod

playbooks/libstatic_production.yml, roles/libstatic/defaults/main.yml, roles/libstatic/tasks/main.yml
Staging was working based on server intervention, but I did not realize that at the time
=> Updating the identity file and host checking to work

roles/nginxplus/files/conf/http/catalog-staging.conf
See pulibrary/orangelight#2546
Co-authored-by: James R. Griffin III <jrgriffiniii@gmail.com>
Co-authored-by: Anna Headley <anna.headley@gmail.com>
Co-authored-by: Eliot Jordan <eliot.jordan@gmail.com>
Co-authored-by: Trey Pendragon <tpendragon@princeton.edu>
Make sure to check with the main branch that we are not overwriting previous changes.
=> Configures nginx to point to the new OL staging environment.

group_vars/libstatic/libstatic-prod.yml, playbooks/libstatic_production.yml
=> Adding datadog config to libstatic

group_vars/ojs/dev.yml, group_vars/ojs/production.yml, group_vars/ojs/staging.yml, playbooks/ojs_staging.yml, roles/ojs/templates/script.exp.j2
Enable Japanese locale for OJS
=> Enable Japanese UI locale

group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml
=> Update pulmap to use solr8

playbooks/nginxplus_production.yml
Removes `ERROR! conflicting action statements: service, state`
=> Fixing the nginx playbook so that it runs

roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf
Based on @kayiwa finding the issue!
=> Point nginx at the REAL server

roles/nginxplus/files/conf/http/vireo_staging.conf
Work toward https://github.com/pulibrary/drds-catchall/issues/13
=> Vireo-staging nginxplus config

roles/nginxplus/files/conf/http/vireo_staging.conf
Advances https://github.com/pulibrary/drds-catchall/issues/19
=> Integrating support for WebSockets for Vireo 4 deployments by providig additional HTTP headers within the NGINX configuration file

group_vars/figgy/production.yml
Draft until this index is live.
=> [Figgy] Configure Figgy to use Solr 8.

roles/nginxplus/files/conf/http/vireo_prod.conf
add the vireo production configuration
Co-authored-by: James R. Griffin III <jrgriffiniii@gmail.com>
=> add a vireo prod config

roles/nginxplus/files/conf/http/vireo_staging.conf
Connected to https://github.com/pulibrary/princeton_ansible/issues/2585
=> When we use port 443 we also need https

roles/nginxplus/files/conf/http/lib-sc-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
=> Increase proxy timeout for lib-sc-prod.

roles/nginxplus/files/conf/http/library-prod.conf, roles/nginxplus/files/conf/http/library-staging.conf
=> Update the timeout for libwww to something very large

roles/nginxplus/files/conf/http/bibdata-alma-staging.conf, roles/nginxplus/files/conf/http/bibdata-alma.conf, roles/nginxplus/files/conf/http/bibdata-prod.conf, roles/nginxplus/files/conf/http/bibdata-staging.conf
Also removed empty config files for nginx
=> Update the timeout for bibdata to something very large

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
on staging only (for the moment) change to the new system.
The old proxy to the windows server will still be utilized in prod
=> [NGINXPLUS] Changing the lockers pages on staging

roles/shibboleth/tasks/apache_config.yml, roles/vireo/meta/main.yml, roles/vireo/molecule/default/converge.yml, roles/vireo/tasks/main.yml, roles/vireo/tasks/shibd_config.yml, roles/vireo/templates/vireo.conf.j2
If ServerName and UseCanonicalName are not set, then shibboleth
redirection will not work.
=> Fix shibboleth redirect issue

README.md
Closes #958.
Updates the main project README to reflect our current CI system.
=> CI runs on GitHub Actions now

roles/figgy/molecule/default/verify.yml, roles/figgy/tasks/main.yml
=> Add cogeo-mosaic to figgy machines

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
Closes https://github.com/pulibrary/figgy/issues/4881
=> Add TILESERVER_URL env variable to figgy prod and staging boxes

roles/ojs/tasks/main.yml
Fixes https://github.com/pulibrary/openpublishing/issues/38
=> Fix ownership of OJS uploads directory

group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml
Ran and tested on pulmap staging.
Closes #2663
=> Update pulmap to ruby 2.7

group_vars/lae/production.yml, group_vars/lae/staging.yml
Tested on staging.
Closes #2666
=> Update lae ruby to 2.7

group_vars/dpul_production.yml
=> [DPUL] send nginx logs to datadog

.github/workflows/molecule_tests.yml, group_vars/orangelight/alma_prod.yml, group_vars/orangelight/alma_qa.yml, group_vars/orangelight/staging.yml, playbooks/orangelight_alma_prod.yml, playbooks/orangelight_alma_qa.yml, roles/orangelight/.ansible-lint, roles/orangelight/.travis.yml, roles/orangelight/.yamllint, roles/orangelight/README.md, roles/orangelight/defaults/main.yml, roles/orangelight/handlers/main.yml, roles/orangelight/meta/main.yml, roles/orangelight/molecule/default/converge.yml, roles/orangelight/molecule/default/molecule.yml, roles/orangelight/molecule/default/verify.yml, roles/orangelight/tasks/main.yml, roles/orangelight/tests/inventory, roles/orangelight/tests/test.yml, roles/orangelight/vars/main.yml
Adding molecule testing in for the orangelight role
fixes #2676. @tpendragon any insight into why you did this would be appreciated
=> Updating orangelight ruby to 2.75

group_vars/lockers_and_study_spaces/lockers_and_study_spaces_prod.yml, group_vars/lockers_and_study_spaces/lockers_and_study_spaces_staging.yml, roles/lockers_and_study_spaces/vars/main.yml
Should be merged before https://github.com/pulibrary/lockers_and_study_spaces/pull/62
=> [LOCKERS] Upgrading to ruby 2.7.5

group_vars/vireo/staging.yml, roles/shibboleth/files/attribute-map.xml, roles/vireo/tasks/main.yml, roles/vireo/templates/application.yaml.j2, roles/vireo/templates/vireo.conf.j2
Work toward https://github.com/pulibrary/rdss-catchall/issues/37
=> Improved mapping of shibboleth attributes for vireo

group_vars/orangelight/alma_qa.yml, group_vars/orangelight/staging.yml
=> Update solr alias for catalog-staging and catalog-qa

group_vars/libwww/libwww-staging.yml, roles/libwww/defaults/main.yml, roles/libwww/templates/update.sql.j2, roles/mariadb/tasks/main.yml
This is setup via capistrano, not ansible.  These are just confusing and out of date.
=> Removing solr references in libwww role

group_vars/lockers_and_study_spaces/lockers_and_study_spaces_prod.yml, roles/datadog/tasks/agent6.yml, roles/datadog/templates/nginx.status.conf
Also add nginx status config for data dog, so we can use the datadog nginx config
=> Updating lockers and study spaces for data dog

roles/simple_annotation/defaults/main.yml
=> Updated SaS tag to latest

roles/nginxplus/files/conf/http/pulfalight-staging.conf
=> [Pulfalight] lock staging behind VPN

roles/ojs/tasks/main.yml
=> Added task to make public uploads directory writeable

group_vars/pdc_discovery/common.yml
Resolves https://github.com/pulibrary/pdc_discovery/issues/129
=> Updating Ruby to release 2.7 and Node to Fermium LTS for the pdc_discovery roles

group_vars/lae/production.yml, group_vars/lae/staging.yml
This is necessary in order to resolve https://github.com/pulibrary/lae-blacklight/issues/293
=> Updating Node to Fermium LTS for the lae Role

group_vars/geaccirc/geaccirc_prod.yml
Should be merged and run in conjunction with https://github.com/pulibrary/geaccirc/pull/3
=> [GEACCIRC] Updating to ruby 2.7

roles/nginxplus/files/conf/http/cdh_prod_geniza.conf
we now have a canonical name that we want all server blocks to point to
this closes #2768
=> make all server names point to canonical name

group_vars/friends_of_pul/friends_of_pul_prod.yml
This is in production, so it should be merged...
=> Moving to mariadb-prod1 for the database

roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf
=> Add least-time directives to Figgy.

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
Draft until tested in staging.
=> [Figgy] Update to Ruby 2.7

group_vars/libwww/libwww-prod.yml
=> Add discovery utils to datadog logs

group_vars/abid/production.yml, group_vars/abid/staging.yml, group_vars/appdeploy/production.yml, group_vars/approvals/approvals_prod.yml, group_vars/approvals/approvals_staging.yml, group_vars/dpul_production.yml, group_vars/dpul_staging.yml, group_vars/figgy/production.yml, group_vars/figgy/staging.yml, group_vars/lae/production.yml, group_vars/lae/staging.yml, group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww-staging.yml, group_vars/lockers_and_study_spaces/lockers_and_study_spaces_prod.yml, group_vars/lockers_and_study_spaces/lockers_and_study_spaces_staging.yml, group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml, group_vars/ouranos/staging.yml, group_vars/pdc_discovery/common.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/staging.yml, group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml, group_vars/vireo/common.yml, roles/approvals/meta/main.yml, roles/approvals/tasks/main.yml, roles/bibdata/vars/main.yml, roles/lib_jobs/vars/main.yml, roles/oawaiver/molecule/default/converge.yml, roles/ouranos/molecule/default/converge.yml
the new nodejs role downloads the binary version of the file. We add the
values matched on the vms
=> update nodejs variables

group_vars/repec/repec_prod.yml, group_vars/repec/repec_staging.yml, roles/repec/vars/main.yml
=> Upgrade to ruby 2.7.5 set node: v12.22.5

group_vars/pdc_discovery/common.yml, group_vars/pdc_discovery/production.yml, group_vars/pdc_discovery/staging.yml, playbooks/postgresql_db_migration.yml
this migrates pdc_discovery to our improved replicating postgresql
environment.
=> updates variables for postgresql migration

group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml
add migration variables for oawaiver
=> add postgresql production variables for oawaiver

group_vars/abid/production.yml, group_vars/postgresql/production.yml, playbooks/postgresql_production.yml, roles/postgresql/defaults/main.yml
We are migrating abid to the new replicating postgresql environment
=> add postgresql production variables for abid

roles/nginxplus/files/conf/http/pdc-discovery_prod.conf
Fixes https://github.com/pulibrary/pdc_discovery/issues/202
=> Make PDC Discovery production available outside Princeton network

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
Remove SVN variables as part of resolving [#4955](https://github.com/pulibrary/figgy/issues/4955)
=> Remove SVN variables

roles/nginxplus/files/conf/http/libimages.conf
libimages has loris2 paths for legacy resources.
Refs https://github.com/pulibrary/figgy/issues/5022
=> Support loris2 links.

group_vars/dpul_production.yml, group_vars/dpul_staging.yml
=> Upgrade DPUL to Ruby 2.7

group_vars/dpul_production.yml, group_vars/dpul_staging.yml
=> Add postgres_port variable to dpul playbooks

roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf, roles/nginxplus/files/conf/http/pdc-discovery_prod.conf
- add discovery path for production
- add pdc-describe configuration
=> add pdc-describe configuration

roles/abid/meta/main.yml, roles/abid/molecule/default/Dockerfile.j2, roles/abid/molecule/default/INSTALL.rst, roles/abid/molecule/default/converge.yml, roles/abid/molecule/default/molecule.yml, roles/abid/molecule/default/verify.yml
- add molecule infrastructure
- add role_name
The first in a series of auditing all our roles to future proof them for
updating ansible
=> i2861 abid fqdn

roles/approvals/.ansible-lint, roles/approvals/meta/main.yml, roles/approvals/tasks/main.yml
- fix linting from molecule
- add fqdn modules
=> i2861 approvals fqdn

roles/nginxplus/files/conf/http/pulfa_old.conf
=> Put pulfa.princeton.edu behind VPN.

group_vars/orangelight/qa.yml
Closes #2798.
The first commit fixes the references in the QA variables.
Keeping this a draft PR until  the open questions on the issue are answered.
=> update vars to use catalog-qa instead of catalog-alma-qa

playbooks/deploy_user.yml
Co-authored-by: Carolyn Cole <cac9@princeton.edu>
Co-authored-by: Hector Correa <hector@hectorcorrea.com>
Co-authored-by: Anna Headley <anna.headley@gmail.com>
Co-authored-by: Alicia Cozine <879121+acozine@users.noreply.github.com>
=> Add a name and correct YAML syntax in deploy user playbook

playbooks/postgresql_db_migration.yml
Just a little tidying up.
Related to #2735.
=> adds name for pgsql backup playbook

roles/nginxplus/files/conf/http/pdc-describe_prod.conf
Fixes https://github.com/pulibrary/pdc_describe/issues/51
=> Redirect root requests to application for pdc-describe-prod

group_vars/pdc_describe/main.yml, roles/nginxplus/files/conf/http/pdc-describe_staging.conf, roles/passenger/README.md, roles/passenger/meta/main.yml, roles/rails_app/README.md
Fixes https://github.com/pulibrary/pdc_describe/issues/41
@kayiwa and @acozine The new `ruby_s` role worked right away! 🎉
=> Upgrade pdc_describe to ruby 3.0.3

roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf, roles/nginxplus/files/conf/http/pdc-discovery_prod.conf, roles/nginxplus/files/conf/http/pdc-discovery_staging.conf
Fixes https://github.com/pulibrary/pdc_describe/issues/51
=> Nginxplus health checks need to use subdirectory uri

.github/workflows/molecule_tests.yml, roles/ruby_s/molecule/default/verify.yml, roles/ruby_s/tasks/cleanup.yml, roles/ruby_s/tasks/main.yml
This will close #2962 Hat tip to @carolyncole
=> add a new condition for a machine with no ruby

group_vars/mysql/production.yml, playbooks/mysql.yml
configures our mysql to send APM and logs to datadog
closes #2969
=> add datadog

roles/ezproxy/tasks/main.yml
we also make the role use fqcn
closes #2994
=> make cloning safe to allow role to be idempotent

playbooks/mysql_db_migration.yml, playbooks/postgresql_db_migration.yml
- cleanup truthyness and spacing
- add ssh key creation
=> manage ssh keys

roles/postgresql/tasks/create_db.yml, roles/postgresql/tasks/create_users.yml
=> use the community.postgres FQCN

group_vars/bibdata/production.yml
=> Update datadog tls domain for bibdata

group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml, roles/oawaiver/defaults/main.yml, roles/oawaiver/molecule/default/converge.yml, roles/oawaiver/molecule/default/verify.yml
=> Ensuring that Ruby 3.0.3 and Bundler 2.3.11 are installed for the oawaiver server environments

roles/nginxplus/files/conf/http/ojs-staging.conf, roles/nginxplus/files/conf/http/openbooks-staging.conf, roles/nginxplus/files/conf/http/openbooks.conf, roles/nginxplus/files/conf/http/openpublishing.conf
Nginx by default does not allow file uploads > 1 Mb
Fixes https://github.com/pulibrary/openpublishing/issues/40
=> Increase file size upload limits

roles/ojs/tasks/check_ojs_installation.yml, roles/ojs/tasks/enable_php_uploads.yml, roles/ojs/tasks/main.yml, roles/php/tasks/configure.yml
=> Increase PHP settings in apache2 for file uploads via POST (OJS only)

group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml
=> Update Pulmap NodeJS to 16 LTS

group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml
=> Update Pulmap Node version to 16.15.0

group_vars/oawaiver/production.yml, playbooks/oawaiver_production.yml
Resolves https://github.com/pulibrary/oawaiver/issues/71, and also updates the Datadog apt key
=> Adding Datadog to oawaiver.princeton.edu and oawaiver-staging.princeton.edu

group_vars/lae/production.yml, group_vars/lae/staging.yml
refs pulibrary/lae-blacklight#317
companion to https://github.com/pulibrary/lae-blacklight/pull/319
This has been run on staging.
=> [LAE] Upgrade node to 16

group_vars/dpul_production.yml
=> [DPUL] migrate prod to solr 8

playbooks/deploy_user.yml
The PR will prevent the playbook from locking up machines
Co-authored-by: Ryan Laddusaw<rladdusaw@users.noreply.github.com>
Co-authored-by: James R. Griffin III <jrgriffiniii@users.noreply.github.com>
=> add serial running of playbook

group_vars/pdc_describe/staging.yml
Moved the DATACITE env values to the proper location.
(since https://github.com/pulibrary/princeton_ansible/pull/3099 was incomplete)
=> Moved the DATACITE settings to the proper section

roles/bibdata/tasks/main.yml, roles/bibdata/tasks/mounts.yml, roles/bibdata/tasks/redis_overcommit_memory.yml
- add fqrn
- replace deprecated with_items with the loop
=> bibdata fqrn

roles/capistrano/tasks/main.yml, roles/drupal/tasks/main.yml
=> i3055: Mark drupal git repo as safe

group_vars/pdc_describe/production.yml
This allows us to test on production without creating items we can not delete
fixes https://github.com/pulibrary/pdc_describe/issues/203
=> [PDC-DESCRIBE] Changing to staging values for datacite

group_vars/dpul_production.yml
=> Add some staging boxes to cert checks

roles/nginxplus/files/conf/http/pdc-discovery_prod.conf, roles/nginxplus/files/conf/http/pdc-discovery_staging.conf
Work toward https://github.com/pulibrary/pdc_discovery/issues/311
Work toward https://github.com/pulibrary/pdc_discovery/issues/317
=> Set up load balancing for pdc_discovery

group_vars/globus/common.yml, playbooks/aws_ec2.yml
Also update to newest ami
Additionally stop errors when user is already defined
=> Allow Globus name to be set

roles/bibdata/tasks/mounts.yml
=> [BIBDATA] Correct file permissions, groups, and samba creds

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
=> Upgrade figgy node version to 16.15.0

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, roles/figgy/defaults/main.yml, roles/figgy/tasks/main.yml
=> Remove simple-tiles from figgy

group_vars/dpul_staging.yml
=> [DPUL] Configure redis url for staging

roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf
=> Ensuring that there are no file upload limits for the pdc-describe hosts

group_vars/dpul/production.yml, group_vars/dpul/staging.yml
=> Add sidekiq pro to dpul

group_vars/pulmap/pulmap_production.yml
=> Update pulmap rabbit server value

README.md
when using asdf using the command `asdf exec` will correctly add the gem
to your ruby version
=> reliably add lastpass-ansible

playbooks/dpul.yml
not sure when this was lost, but dpul should run datadog.
=> Add datadog to dpul role

princeton_ansible_env.sh, princeton_ansible_fish_env.sh
this adds protecting vault commits as part of a launching lastpass
=> run bin setup

group_vars/all/vars.yml, group_vars/libwww/production.yml, group_vars/locator/production.yml, group_vars/locator/staging.yml, group_vars/mudd/mudd-staging.yml, group_vars/percona/prod.yml, group_vars/percona/staging.yml, group_vars/recap/common.yml, group_vars/recap/production.yml, group_vars/special_collections/production.yml
=> We no longer use the vault_xtradb_root_password variable

group_vars/libwww/common.yml
=> i3288: upgrade nodejs to 14 for library website

group_vars/orangelight/qa.yml
=> Update bibdata_base in orangelight/qa.yml

roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/common/vars/main.yml
Add's the `dust` utility to our VMs https://github.com/bootandy/dust
=> add rust based du utility

group_vars/orangelight/common.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
=> Remove unused variables

roles/libstatic/defaults/main.yml, roles/libstatic/tasks/main.yml, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
- Adds "Amp Up the Archives" training static site
- Ensures correct permissions for cloned repositories
Closes #3136
=> Add Amp Up the Archives training to static site

roles/nginxplus/files/conf/http/templates/pudl_proxy_pass.conf
Closes #3318
Deployed and working.
=> Redirect pudl arks to correct URL

group_vars/all/vars.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/staging.yml, playbooks/pulfalight.yml
Adds global list of netids allowed to login into sidekiq and sets required variable in Pulfalight app config.
=> Add list of authorized sidekiq users

inventory/all_projects/cdhweb, inventory/all_projects/derrida, inventory/all_projects/geniza, inventory/all_projects/pemm, inventory/all_projects/prosody, inventory/by_environment/production, inventory/by_environment/staging
right now the cdh vms are not getting the weekly updates.
this addresses that
=> add all the cdh vms to inventory

playbooks/globus_certs.yml
convert the documented [steps here](https://docs.globus.org/globus-connect-server/v5.4/#upgrading_globus_connect_server) into a playbook to update globus certificates
=> follow globus certificate update

roles/nginxplus/files/conf/http/cdh_prod_web.conf, roles/nginxplus/files/conf/http/cdh_test_web.conf
this will add new domain names under cdh
=> add hc3 and hc3-test permanent redirects

playbooks/openbooks.yml
=> Consolidated openbooks playbooks

group_vars/lae/production.yml
refs pulibrary/lae-blacklight#333
=> [LAE] use an alias for production solr collection

group_vars/pulmap/pulmap_production.yml, group_vars/pulmap/pulmap_staging.yml, roles/pulmap/vars/main.yml
=> Update pulmap to ruby 3.1

roles/drush/tasks/main.yml
=> FPUL: override drush superuser install warning

group_vars/dss/staging.yml, roles/dss/vars/main.yml
=> Added key and env value

group_vars/pdc_describe/staging.yml, playbooks/pdc_describe.yml
=> Ensuring that pdc-describe-staging1 and pdc-describe-staging2 have MailCatcher installed

roles/nginxplus/files/conf/http/slavery-dev.conf
adds configuration for slavery-dev.princeton.edu
=> add pas-dev config file

roles/ojs/tasks/main.yml
Fixes https://github.com/pulibrary/openpublishing/issues/56
=> Fix permissions issue for OJS file uploads

group_vars/lockers_and_study_spaces/production.yml, group_vars/lockers_and_study_spaces/staging.yml
closes #3420 
I ran the playbook on staging and deployed https://github.com/pulibrary/lockers_and_study_spaces/pull/149
=> Update nodejs to 16.14.2

roles/ojs/tasks/main.yml
=> Removing unneeded chmod

group_vars/special_collections/common.yml
=> Special collections site needs to run on PHP 8.0

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
refs https://github.com/pulibrary/princeton_ansible/issues/3164
=> update bundler version for figgy

group_vars/libwww/common.yml, playbooks/libwww_staging.yml, roles/drupal/meta/main.yml, roles/libwww/meta/main.yml, roles/libwww/molecule/default/verify.yml, roles/libwww/vars/main.yml, roles/php/defaults/main.yml, roles/php/meta/main.yml, roles/php/tasks/main.yml
=> Use php 8.0 for libwww

roles/common/defaults/main.yml, roles/common/tasks/main.yml
the [procs](https://github.com/dalance/procs) tool allows us to see what
processes are running in a way that improves on the venerable `ps`
we alphabetize the packages
=> add the procs tool

roles/imagemagick/README.md, roles/imagemagick/meta/main.yml, roles/imagemagick/molecule/default/converge.yml, roles/imagemagick/molecule/default/verify.yml, roles/imagemagick/tasks/main.yml
adds fqrns to imagemagick role
=> add fqrns to imagemagick role

group_vars/recap/common.yml
=> Upgrade ReCAP PHP version to 8.1

roles/ruby_s/tasks/cleanup.yml
=> Remove ruby-minitest by force

group_vars/dss/common.yml, playbooks/dss.yml
Helps with https://github.com/pulibrary/DSS/issues/299
Sibling PR: https://github.com/pulibrary/DSS/pull/300
=> Upgrade DSS node version

group_vars/pas/dev.yml, group_vars/pas/production.yml, group_vars/pas/staging.yml
=> Set pas_db_driver by environment for PAS

group_vars/dpul/production.yml, group_vars/dpul/staging.yml
=> Update DPUL to node 16

roles/ealapps/tasks/main.yml
=> [ealapps] install sendmail

group_vars/video_reserves/staging.yml, roles/video_reserves/templates/config.tpl.j2
Helps with https://github.com/PrincetonUniversityLibrary/video_reserves/issues/27
=> Video reserves cas

group_vars/video_reserves/production.yml, group_vars/video_reserves/staging.yml
- Use correct environment variable for mysql user name for both prod and staging
- Correct prod cert_path variable based on staging cert_path
Connected to PrincetonUniversityLibrary/video_reserves#27
=> Match video_reserves production and staging

roles/figgy_pubsub_worker/templates/pubsub.service
=> Update Figgy pubsub service rake command

group_vars/mudd/common.yml, playbooks/mudd.yml, roles/mudd/vars/main.yml
Sibling PR: https://github.com/pulibrary/mudd-dbs/pull/94
=> [mudd] Upgrade ruby to 3.1

group_vars/bibdata/common.yml, group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml, roles/bibdata/vars/main.yml
Move ruby vars to group_vars/common.yml
=> cleanup stale ruby variables(unused) from qa and production.

group_vars/repec/common.yml
Sibling PR: https://github.com/pulibrary/repecwp/pull/84
=> [repec] upgrade node to 16

roles/ealapps/templates/apache2-site.conf.j2
closes #3538 
I ran this on staging 12/15
=> [ealapps] Add apache rewrite rule

roles/pas/tasks/main.yml
Also, alphabetize the list of apt packages,
because alphabetizing is fun
=> [pas] i3551: add bcmath php mod

group_vars/pas/staging.yml
I ran this playbook on staging 12/16.
=> pas-staging on craft 4

group_vars/bibdata/common.yml
Sibling PR: https://github.com/pulibrary/bibdata/pull/2051
I ran this on staging 12/16
=> [bibdata] Node 16

roles/ealapps/tasks/main.yml
closes #3542 
I ran this on staging 12/15
=> [ealapps] i3542: recursively chmod temp directory

group_vars/geaccirc/common.yml, playbooks/geaccirc.yml
- successfully run on geaccirc-staging
- Changing order of vars_files so precedence is given to environment-specific file
Connected to pulibrary/geaccirc#16
=> [geaccirc] Upgrade to Ruby 3.1

group_vars/lockers_and_study_spaces/production.yml, group_vars/lockers_and_study_spaces/staging.yml, roles/lockers_and_study_spaces/vars/main.yml
=> Upgrade ruby-version for lockers

group_vars/friends_of_pul/common.yml, group_vars/libwww/common.yml, group_vars/pas/common.yml, roles/friends_of_pul/tasks/main.yml, roles/libwww/tasks/main.yml, roles/pas/tasks/main.yml, roles/php/defaults/main.yml, roles/php/tasks/mod-php.yml
=> Set memory limit 512M in apache2/php.ini

group_vars/lib_jobs/common.yml, roles/lib_jobs/vars/main.yml, roles/ruby_s/tasks/main.yml
Connected pulibrary/lib_jobs#429
Run on staging, both lib-jobs and aspace_helpers successfully deployed.
=> [lib_jobs] Upgrade to Ruby 3.1.2

group_vars/approvals/common.yml, group_vars/approvals/production.yml, group_vars/approvals/staging.yml, playbooks/approvals.yml, roles/approvals/vars/main.yml
=> [approvals] Upgrade ruby to 3.0.0

roles/video_reserves/templates/apache2-site.conf.j2
- The default page will end up being hrc/vod/clip.php
- This allows us to remove duplicate code without breaking existing links
=> [video_reserves] Update DirectoryIndex

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
=> [ealapps] Separate staging and prod proxy-pass

roles/nginxplus/files/conf/http/ealapps_staging.conf
=> Unblock ealapps from the web application firewall

group_vars/ealapps/production.yml, group_vars/ealapps/staging.yml, roles/ealapps/templates/connection_mysql.php.j2
=> Ealapp domain env var

README.md
=> Documentation for rekeying the vault

group_vars/video_reserves/production.yml, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
=> Add videoreserves to load balancer

README.md
new docs were introduced in #3599
=> Remove old documentation for rekeying the vault

roles/tomcat8/handlers/main.yml, roles/tomcat8/molecule/default/converge.yml, roles/tomcat8/molecule/default/verify.yml, roles/tomcat8/tasks/main.yml
adding fully qualified role names
=> make tomcat8 a fqnrole

group_vars/pas/common.yml, group_vars/pas/production.yml, playbooks/pas.yml
=> Move pas prod to craft 4

inventory/by_environment/production, playbooks/os_updates.yml
we had ansible-tower and any redhat based OSes to be eligible for patch
tuesday
=> add ansible-tower1 to patch Tuesday

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Introduce website database list redirects to libguides database list and individual resources into library-staging.princeton.edu
=> Test libguides database link rewrites.

group_vars/pdc_describe/production.yml
For real this time.  The previous PR was  the file in pdc-discovery...   That was also going to cause issues at some later date, so fixing it should not be a problem. 
Also add the /describe as that is where the application runs...
=> Updating the host to be the load balanced host pdc-describe-prod

inventory/all_projects/_orphans, inventory/by_environment/production
adding libserv39 to be patched every tuesday
=> add libserv39 to patch tuesday

roles/nginxplus/files/conf/http/dss-staging.conf
PR disables dss-staging.princeton.edu
=> disable WAF for dss-staging

group_vars/lib_jobs/common.yml, roles/lib_jobs/vars/main.yml
Sibling pr: https://github.com/pulibrary/lib_jobs/pull/452
=> [lib-jobs] Use nodejs 16

roles/lib_solr/molecule/default/converge.yml, roles/lib_solr/tasks/main.yml, roles/solrcloud/handlers/main.yml, roles/solrcloud/meta/main.yml, roles/solrcloud/molecule/default/converge.yml, roles/solrcloud/tasks/config.yml, roles/solrcloud/tasks/install.yml, roles/solrcloud/tasks/main.yml, roles/solrcloud/tasks/service.yml
unsure if we need both of these roles.
=> convert lib_solr and solrcloud in FQRN

inventory/all_projects/_orphans, inventory/by_environment/production
include this server to the patch tuesday group
=> [server maintenance] add libserv31 

roles/lib_jobs/tasks/main.yml
Closes #3675
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
=> [lib_jobs] Remove unneeded steps for mounting

roles/bind9/tasks/main.yml
=> Remove bind 9 server start from molecule

roles/ruby_s/tasks/install_bundler.yml, roles/ruby_s/tasks/install_from_source.yml, roles/ruby_s/tasks/main.yml
Run for putting a new version of bundler on tigerdata-staging
=> Allow bundler version to change independent of ruby

playbooks/deploy_code.yml
We want to be able to deploy code from Tower.
First attempt, very much a draft.
=> draft playbook for capistrano deploys

inventory/all_projects/byzantine, inventory/by_environment/staging, inventory/by_service/apache, roles/nginxplus/files/conf/http/byzantine-tsp_prod.conf, roles/nginxplus/files/conf/http/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
This adds the new byzantine staging server to the nginx role.
Connected to #3704
=> [byzantine] Add byzantine staging environment

roles/lib_jobs/vars/main.yml
=> [lib_jobs] Remove freetds dependency

roles/nginxplus/files/conf/http/pulfalight-prod.conf
refs pulibrary/pulfalight#1220
=> [pulfalight] don't serve findingaids site from findingaids-beta anymore

roles/ojs/tasks/main.yml
Gets around the missing ja_JP file
fixes #3725
=> Checking out a specific version of the OJS code

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
this removes the destination of the hishi collection away from the
application to search query on the catalog
closes #3706
=> [libwww] add proxy for hishi collection

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
use redirect instead of proxy_pass for the catalog-staging
=> [libwww] hishi redirect

group_vars/mudd/common.yml, group_vars/mudd/production.yml, group_vars/mudd/staging.yml
Sibling PR: https://github.com/pulibrary/mudd-dbs/pull/104
I ran this on staging today, March 13.
=> [mudd] Ruby 3.2

inventory/all_projects/app_deploy, inventory/by_environment/production, playbooks/appdeploy.yml
this changes the playbook to follow the pattern for playbooks
adds the app_deploy inventory to production
closes #3756
=> [appdeploy] add heaven machine to patch tuesday

roles/nginxplus/files/conf/http/confluence-prod.conf
=> [nginxplus] add confluence-prod1

group_vars/nfsserver/common.yml, group_vars/nfsserver/production.yml, group_vars/nfsserver/staging.yml, inventory/all_projects/nfsserver, inventory/by_environment/production, inventory/by_environment/staging, playbooks/nfsserver.yml, roles/lib_jobs/tasks/main.yml, roles/nfsserver/meta/main.yml, roles/nfsserver/tasks/main.yml
- add nfs file servers to inventory
- enable creation of mounts through a loop
- deploy role addition to nfs
- create the open_marc_records mount
=> [libjob] create an open marc records mount

playbooks/incommon_certbot.yml
in the event where one has multiple domains we add a new variable
this will cause #3745
=> [nginxplus] multiple domains

group_vars/ealapps/production.yml, group_vars/recap/staging.yml, playbooks/ealapps.yml
- add recap db credentials to dev
- add apache-status check for ealapps
=> [eal-apps] enable datadog alerts

playbooks/lib_jobs.yml, roles/lib_jobs/tasks/main.yml, roles/nfsserver/tasks/main.yml
this allows us to have posix mounts with IP addresses
=> [libjobs] create posix mounts

playbooks/deploy_code.yml
=> add var for slack channel

group_vars/lib_jobs/common.yml, roles/lib_jobs/defaults/main.yml, roles/lib_jobs/tasks/main.yml
=> Adding symlink into lib jobs shared folder

group_vars/pdc_describe/main.yml
the 3.0.3 version fails with an OpenSSL error
=> [pdc-describe] update to jammy jellyfish

playbooks/deploy_user.yml
Tidies comments, restructures hosts on deploy_user playbook.
Builds on #3789.
=> Update docs & hosts for deploy user playbook

playbooks/lib_sftp.yml, roles/system_ldap/tasks/main.yml, roles/system_ldap/vars/main.yml
make sure directory is owned by same user
make the playbook have documentation on how to add a user
=> [lib-sftp] add aspace directory

group_vars/ezproxy/production.yml, roles/ezproxy/handlers/main.yml, roles/ezproxy/tasks/main.yml
=> [ezproxy] add certbot installation

group_vars/pdc_describe/production.yml, playbooks/pdc_describe.yml
pairs with: https://github.com/pulibrary/pdc_describe/pull/1094
=> Adding redis and sidekiq to pdc-describe

playbooks/prompt.yml
the spartan information attempts to match our bionic ones
=> [jammy vms] improve prompt

roles/libstatic/defaults/main.yml, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Test on libwww-staging before also updating the prod proxy pass.
=> Purge libphp prod

roles/obsd_httpd/files/dev_env.conf, roles/obsd_httpd/files/production_env.conf, roles/obsd_httpd/files/staging_env.conf, roles/obsd_httpd/handlers/main.yml, roles/obsd_httpd/tasks/main.yml
- add task to install nginx
- add configuration and files for nginx
=> [dataspace/oar] move to nginx

playbooks/deploy_code.yml
Also adds a link to the logs...
=> [TOWER DEPLOY] Adding user information to starting slack message

group_vars/libwww/common.yml, group_vars/nfsserver/common.yml, group_vars/nfsserver/production.yml, group_vars/nfsserver/staging.yml, inventory/all_projects/special_collections, playbooks/libwww.yml, playbooks/nfsserver.yml, playbooks/special_collections.yml, roles/libwww/tasks/main.yml, roles/nfsserver/defaults/main.yml, roles/nfsserver/molecule/default/converge.yml, roles/nfsserver/tasks/main.yml, roles/nfsserver/vars/main.yml, roles/special_collections/tasks/main.yml
- add nfs client installation
- add variables instead of ip addresses
- add special collections to use nfs mount
=> [libwww and special collections] add nfs fileshare mounts

playbooks/deploy_code.yml
https://ansible-tower.princeton.edu/#/jobs/playbook/883/output has sidekiq information because it truly deployed my branch
This allows for changes to the capistrano tasks in the feature branch to be run (as pointed out by @maxkadel )
=> [TOWER-DEPLOY] Adding branch to git checkout

roles/obsd_httpd/files/dev_env.conf, roles/obsd_httpd/files/production_env.conf, roles/obsd_httpd/files/staging_env.conf
this will close https://github.com/pulibrary/dspace-development/issues/755
we also use json logging
=> [dataspace] increase client size

group_vars/pdc_describe/production.yml
Fixes the sidekiq restart
Before PR: https://ansible-tower.princeton.edu/#/jobs/playbook/987
After PR: https://ansible-tower.princeton.edu/#/jobs/playbook/989
=> [PDC-DESCRIBE] Fix sidekiq restart on production

roles/ezproxy/tasks/main.yml
=> [ezproxy] allow ezproxy user to restart

inventory/by_cloud/aws
=> Groups of groups need the :children suffix
