pulibrary/princeton_ansible

plum.yml
this uses PUL's oracle java 8 (does the version of Java matter here?)
=> point to PUL Library oracle java 8 role

group_vars/all/vars.yml, roles/pulibrary.deploy-user/defaults/main.yml, roles/pulibrary.deploy-user/handlers/main.yml
We have a couple of roles that expect a user not named `deploy` this change allows us to do so. 
Variables can be passed like so
```
ansible-playbook --limit 1.2.3.5 -e system_user=deploy plum.yml -b
```
=> System user

roles/pulibrary.deploy-user/defaults/main.yml
This allows us in non-vagrant settings to pass the -e flag with `generic_app_user` variable to create a user not named deploy but we otherwise use deploy user as the default
=> allow passing of a generic variable user name

ansible.cfg
ansible has deprecated sudo for become.
=> get rid of the deprecation annoying warning

Vagrant/laeVagrantfile, group_vars/lae_production.yml, install_external_roles.yml, lae.yml, roles/pulibrary.blacklight-app/defaults/main.yml, roles/pulibrary.blacklight-app/meta/main.yml, roles/pulibrary.blacklight-app/tasks/main.yml, roles/pulibrary.figgy/tasks/main.yml
Advances #92 by addressing the following:
- Generalizing a new Role for Blacklight Apps
- Introducing a cron job for clearing old Blacklight searches and Devise guest accounts
=> Schedules cron jobs for maintaining Blacklight Apps

roles/pulibrary.dss/tasks/main.yml
in the event where mariadb is remote the repository addition is skipped
by the playbook. this add the repo to install the client dev headers
=> install mariadb repositories

roles/pulibrary.passenger/templates/nginx.conf.j2
This fixes Figgy's gzip of static assets when behind a load balancer.
=> Fix gzip for proxied web requests.

group_vars/orangelight.yml, orangelight.yml, roles/pulibrary.orangelight/meta/main.yml, roles/pulibrary.orangelight/tasks/main.yml
- Updates the Orangelight Role to use the pulibrary.blacklight-app as a dependency
- Resolves #113 by adding an Orangelight cron task for generating the Sitemap
- Resolves #114 by ensuring that the APPLICATION_HOST and APPLICATION_HOST_PROTOCOL Rails env. variables are exposed to the OL environment
=> Adds the Orangelight cron task for Sitemap generation and sets both APPLICATION_HOST and APPLICATION_HOST_PROTOCOL

roles/pulibrary.ruby/tasks/main.yml
=> Uses the Brightbox PPA (https://www.brightbox.com/docs/ruby/ubuntu/) in order to update Ruby to the latest 2.4.x release

roles/pulibrary.ruby/defaults/main.yml, roles/pulibrary.ruby/tasks/main.yml
Thank you very much for this @hackmastera - after a review and testing your solution for #186, I can only offer some additional comments, and would please propose that `/opt/install` be changed to `/opt/ruby` for the `install_path`.
Also, is it necessary to ensure that `software-properties-common` be removed?  Most of the included packages appear to be for a system installation of Python, glib, and for CA certificate management:
https://packages.ubuntu.com/xenial/software-properties-common
=> Adding some additional code comments and using /opt/ruby as the installation directory

roles/pulibrary.ruby/tasks/main.yml
Otherwise provisioning is blocked on certain environments until #189 is merged
=> Removes downgrading Bundler

group_vars/orangelight.yml, group_vars/orangelight_staging.yml, roles/pulibrary.orangelight/templates/default.j2
=> Removing all references to the deprecated domain names `puls*.princeton.edu` and `pulsearch*.princeton.edu`

roles/pulibrary.bibdata/tasks/main.yml
=> Ensures that the backward compatible `include` is used for releases prior to Ansible 2.4

figgy.yml, orangelight.yml
=> Ensuring that the pulibrary.ansible-datadog Role is only included when Vagrant is not used for provisioning

hosts
this adds a third mariadb host to prevent the "split-brain" problems
that happen on restart
=> add a new mariadb host

roles/pulibrary.bind9/tasks/main.yml
this will prevent our machines from flooding OIT's DNS servers
We have a new ticket where `lib-proc5` this time was misbehaving.
=> use the libraries dns forwarder

group_vars/dpul_production.yml, group_vars/dss_production.yml, group_vars/figgy_production.yml, group_vars/lae_production.yml, group_vars/pulmap.yml
Closes #326. Updates all production solr urls with the exception of Orangelight.
=> Update production solr core names to match SolrCloud naming scheme

roles/pulibrary.bibdata/tasks/redis_overcommit_memory.yml
@kayiwa, would it be a better practice to set the overcommit_memory in the pulibray.redis defaults/main.yml file with a default value and then reference it in any other playbook? If yes, would it be ok to let the default value as 0? From what I've seen so far the servers have it set as 0.
=> Set redis-server overcommit_memory to 1 for bibdata-worker2

group_vars/orangelight_staging.yml, roles/pulibrary.orangelight/templates/nginx_extra_config
Allows the /catalog route to be accessed via AJAX on catalog-staging environment.
=> allow ajax calls from catalog-staging

roles/pulibrary.ruby/tasks/main.yml
It has to load before bundler has done its business to allow tighter integration with capistrano
=> Install whenever directly outside of bundler

roles/pulibrary.ruby/tasks/main.yml
This reverts commit bf3b0844f882e019b4cb428b5a397ef244083635.
Turns out we need whenever on the pulbot machine, not the target
machines
=> Revert "Install whenever directly outside of bundler"

host_vars/lib-solr1.princeton.edu.yml, roles/pulibrary.solrcloud/templates/solr.in.sh.j2
Fixes #374
See 
* https://github.com/pulibrary/pul_solr/blob/master/architecture-decisions/0002-increase-zookeeper-timeout.md
* https://github.com/pulibrary/pul_solr/blob/master/architecture-decisions/0003-remove-memory-tuning.md
=> Increase ZooKeeper timeout, reduce heap size and memory tuning for lib-solr1 only

.travis.yml
Given the lack of support for VM-based environments beyond Ubuntu 14.04 releases (which blocks the installation and usage of Python 3.7.x releases in tests), this ensures that Travis CI is the preferred CI solution.
=> Adds Travis CI for testing against multiple releases of Python

roles/pulibrary.passenger/tasks/main.yml, roles/pulibrary.passenger/vars/main.yml
=> Ensures that the libnginx-mod-http-passenger package is installed (rather than passenger) for NGINX/Passenger on Ubuntu 18.04 LTS)

roles/pulibrary.redis/defaults/main.yml
We can revert this later, but for now our apps aren't set up with this expectation which got added later - so anything we provision with redis is breaking.
=> Don't password redis by default.

group_vars/archivesspace_staging.yml, hosts, playbooks/archivesspace_staging.yml, roles/pulibrary.archivesspace/tasks/main.yml
Also addresses the following:
- Deprecates unsupported Oracle releases of Java 8 in favor of OpenJDK releases
- Ensures that MariaDB server is installed when provisioning for DBs accessed on localhost
=> Implements a separate Playbook for provisioning ArchivesSpace installations into a staging environment

roles/pulibrary.mariadbserver/tasks/main.yml
We made this change during linting, but did not realize it broke 'molecule test'
This PR just reverts the change so that `molecule test` is green
=> Fixing mariadb role

README.md
This PR rearranges the Prerequisite section to make the Setup your environment section more noticeable
Also adds instructions for setting up a role so molecule can be run independently on it.
Also Includes instructions for connecting to the coverage docker container
fixes #500
=> Update Readme to include additional molecule instructions

README.md
There was a typo in the instructions, which I found when I tried to run them.
Additionally two steps were missing for setting up the new role to run with the global molecule build.
=> Update Readme to fix role creation instructions

group_vars/solrcloud.yml
Closes #555.
Can someone run the solrcloud playbook for this?
=> exclude distrib=false queries from the datadog logs

roles/pulibrary.deploy-user/tasks/main.yml
This is causing issues with deploy being able to ssh into the box.
The directory should already be created,  but the tests do not have any deploy users
Changing the task to only run when we are testing along with setting the mode correctly.
fixes #562
=> Changing the mode to allow user directory access

roles/pulibrary.figgy/tasks/main.yml
Recurse sets properties of all files within the directory, which is not
what we want. `state: directory` already creates required subdirectories
recursively, so we should be fine.
=> Don't use recurse to create figgy derivatives mount directory

group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww.yml, playbooks/libwww-prod.yml, playbooks/libwww.yml, roles/pulibrary.libwww/defaults/main.yml, roles/pulibrary.libwww/defaults/mariadb.yml, roles/pulibrary.libwww/molecule/default/playbook.yml
Default file in a role will not override defaults in another role.  We want to override defaults from mariadb
in libwww, but we want them the same for all servers.  To make sure out variables get precedence we are
including them as a separate variable file in all the playbooks.
=> Changing how we pass default mariadb vars

.gitattributes
There's no pattern but this modification allows ansible-vault to always
run
=> periodically I will get the odd-length string error

group_vars/recap/recap-prod.yml
During the change from `recap-prod` to `recap` we needed to update the base url.
=> Changing the base url now that we are named recap

playbooks/orangelight_workers.yml, roles/pulibrary.timezone-eastern/tasks/main.yml
Using the local timezone will make it easier to anticipate daylight savings for cron jobs.
=> adds role to set eastern timezone

roles/pulibrary.deploy-user/defaults/main.yml
The are times when we do not also want 1001 (system user for postgres
etc.,) as the uid. This allows for that
=> there are instances where 1001 is taken

group_vars/consul/consul-staging.yml, group_vars/lib-svn/staging.yml, hosts, playbooks/lib-consul-staging.yml, roles/pulibrary.consul/defaults/main.yml
in addition we pass the variable that allows tasks to run in a VM that
would be stopped for "container" reasons.
=> we add a playbook for consul staging

roles/pulibrary.perconaxdb/files/permissive.sql
The main library site could not load the database without this additonal persmission
=> Needed to allow loading of large database dump

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
NJMaps was in there previously, so the duplicate cause the configuration to be invalid.
=> Removing duplicate njmaps proxy

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Any exhitbit that used to be housed at rbsc will get forwarded to library/specialcollections/<exhibit>
To get them to work out of the box we put them at the base level library/<exhibit>
The apps work when access through the rbsc site, but if anyone still has an old rbsc/<exhibit> url they will get forwarded to library/special_collections/<exhibit> which does not exists.
=> Adding rules for special-collections

Pipfile, Pipfile.lock, roles/pulibrary.postgresql/tasks/main.yml, roles/pulibrary.samba/defaults/main.yml
we remained stuck at ansible 2.7 because of a travis or circle limitation. 
The postresql role changes were deprecation and linting errors that resulted from this change.
=> Ansible v290

roles/pulibrary.mariadb/tasks/manage_contents.yml
@kayiwa I had issues running my mudd production playbook.  It created me some really strange users without the host and password. (Note the host of localhost and the blank password)
```
| localhost                      | mudd-prod                             | *29852FB89EEA52B876EF38AF364A792255EB2F5B |
| %                              | mudd-prod                             |                                           |
```
I'm not entirely certain why the host line was removed, so this may break something else, although I did include the default to omit, which should make it work for a item that does not have a host or a password.
=> Added host and password variables for the privileges to be created correctly

roles/pulibrary.pas_code/tasks/main.yml
In a previous the version was changed to master and then got reset to running_version.  This just sets it back to the right version.
@kayiwa I'm tagging you on this, because the Percona PR changed this, and I want to be certain there was really no reason to.
=> Changing to master as running_version no longer exists

roles/pulibrary.blacklight-app/tasks/main.yml
master branch was broken for nodejs, but there isn't a way (AFAICT) to re-run a specific failed role once it is cached. So making a change that will force the nodejs to re-run.
=> make string declaration explicit

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Currently https://library-staging.princeton.edu/republic & https://library-staging.princeton.edu/firestone/renovations are missing, but https://library-staging.princeton.edu/firestone/renovations/ and https://library-staging.princeton.edu/republic/ respond.
Adding additional redirect so the base url will redirect.
=> Allows redirect of base url also

group_vars/libstatic/libstatic-prod.yml, group_vars/libstatic/libstatic-staging.yml, playbooks/libstatic-prod.yml, roles/pulibrary.libstatic/molecule/default/tests/test_libstatic.py, roles/pulibrary.libstatic/tasks/main.yml, roles/pulibrary.libstatic/templates/lib-static-site.conf.j2
Moving republic to a sub-url of firestone-staging.princeton.edu
Eventually the host will move to lib-static-staging.princeton.edu
=> Added playbook and var files for production server

group_vars/solrcloud_staging.yml
Currently deployed. Seems pretty good so far
=> try 2gb of heap memory for solr staging cloud nodes

roles/pulibrary.cantaloupe/tasks/config.yml, roles/pulibrary.cantaloupe/templates/cantaloupe.conf.j2
Cantalouple runs as this user and the software needs a ulimit higher
than the default. closes issue #1077
=> add ulimit to the pudl user

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Should fix `peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream`
=> turning on proxy_ssl_server_name for proxy pass rules

hosts, playbooks/elixir_test.yml
so it can find its group_vars file
=> Add underscore to elixir_test host

roles/pulibrary.solr/defaults/main.yml, roles/pulibrary.solr/molecule/default/tests/test_default.py, roles/pulibrary.solr/tasks/user.yml
we no longer use solr versions below 5
in addition switch the default user from solr to deploy.
create the solr directory
instead of the /var/solr use for consistency with the solr-cloud role
make sure the deploy user owns
the solr directory.
this closes issue #1119
Co-authored-by: Carolyn Cole <cac9@princeton.edu>
=> Fixing up the solr role to work with pul_solr repo

roles/pulibrary.lib-jobs/vars/main.yml, roles/pulibrary.libwww/molecule/default/tests/test_libwww.py, roles/pulibrary.libwww/tasks/main.yml
Drupal's cron should run every hour. On libwww the production site will now run at the top of every hour with special collections following at 10 minutes after.
=> Drupal cron needs to run every hour.

group_vars/mudd/mudd-prod.yml, group_vars/mudd/mudd-staging.yml
db_port is now required for the mariadb role
=> Fixing up the variables so that the  staging playbook runs.

host_vars/lib-solr1.princeton.edu.yml
This was missed when we recently decreased heap size; no reason it
should be different so removing it.
=> Don't override default heap size for lib-solr1

roles/pulibrary.deploy-user/README.md
The groupid role on physical hardware is non-deterministic. Physical
hardware (a legacy problem) is not always built consistently and will on
occasion have the `systems` user in addition to the `pulsys` user and
create this problem.
This closes #1200
=> improve role documentation

group_vars/orangelight_staging.yml, group_vars/solrcloud_staging.yml, group_vars/zookeeper_staging.yml, playbooks/orangelight_staging.yml, playbooks/solrcloud_staging.yml, playbooks/zookeeper_staging.yml
Maybe in future we should keep the vars but switch on / off the role inclusion?
Assuming we may want to be able to add / remove these as time goes on, which
seems reasonable.
=> Add staging solr, zk, and catalog back to datadog

roles/pulibrary.nginxplus/files/error.html
right now it waits for the health check of nginx to determine if the upstream is healthy
this change removes that
=> our error page should not be cached

group_vars/all/vars.yml, group_vars/approvals/approvals_staging.yml
I had to remove the entry in all to get the override to process.
Additionally I had to upgrade bundler to get it to point at the new ruby.
I also had to ssh onto the box and restart nginx.
=> Moving approvals to ruby 2.6

roles/pulibrary.lib-svn/tasks/main.yml
subversion expects this to have the same name as the pre-commit.tmpl file
this closes issue #1259
=> subversion is specific

group_vars/orangelight_workers.yml
Addresses errors on lib-pulindexer1 that the browse lists can't load due to psql not being installed:
```
cp: cannot stat '/tmp/call_number_browse_s.sorted': No such file or directory
sh: 1: psql: not found
sh: 1: psql: not found
sh: 1: psql: not found
sh: 1: psql: not found
sh: 1: psql: not found
```
=> psql client required to load ol browse lists

roles/pulibrary.common/molecule/default/tests/test_common.py, roles/pulibrary.common/tasks/main.yml
add htop to common to allow ability to determine what is going on with machines
also get rid of the python-apt warning
this closes issue #1270
=> add htop and python-apt

roles/pulibrary.solrcloud/tasks/config.yml
wget adds each new file, appending them with a digit. We were still
getting an old jar and it seems perhaps load order isn't guaranteed with
this method. using get_url will replace the file each time. Since these
files are pulled from the pul_solr git repository we can still easily
revert them if needed.
For existing solrcloud servers, we may want to move the latest copy of each jar
to the file location with no digit appended and delete the others to prevent
unintended consequences from this PR.
=> Solrcloud: Use get_url instead of wget for OL's jars

group_vars/solr8cloud/staging.yml, roles/pulibrary.common/tasks/main.yml, roles/pulibrary.solrcloud/defaults/main.yml, roles/pulibrary.solrcloud/tasks/config.yml, roles/pulibrary.solrcloud/vars/main.yml
These jetty config files were added in during https://github.com/pulibrary/princeton_ansible/pull/314/files#diff-bc10ecbc9a1130f0fc92d984791827b5R43. Unfortunately those config files differ between Solr 7 and Solr 8, resulting in a bug making solr boxes being unable to connect to one another during query. We don't seem to change any of the configuration in our local group_vars, but we may have changed the numbers when they first went in.
@jrgriffiniii do you remember when you first made this role if these were variables brought over from somewhere else, or if we changed any of the numbers initially?
=> Remove Jetty Configuration causing issues with Solr 8.x

group_vars/orangelight.yml, group_vars/orangelight_staging.yml, roles/pulibrary.orangelight/meta/main.yml
The plan is to use the new ENV variables in the orangelight config/environments/production.rb on the rails side to use pony express in production and mailcatcher on staging.
These were not needed in Approvals, since the approvals staging server uses the staging environment, but in orangelight both staging and production use the production environment.
refs https://github.com/pulibrary/orangelight/issues/1971
=> [Orangelight] Adding mailcatcher to orangelight-staging

group_vars/solrcloud.yml, group_vars/solrcloud_staging.yml
Use Figgy / DPUL for prod and DPUL / pulmap for staging
orangelight checks now only run on solr 8 cloud machines
=> Update solr 7 cloud http checks off migrated collections

group_vars/figgy_production.yml, group_vars/figgy_staging.yml
These were removed from figgy in
https://github.com/pulibrary/figgy/pull/1483/files
fixes #333
fixes #239
=> [Figgy] Remove PLUM env vars.

roles/pulibrary.common/defaults/main.yml
without this package nokogiri and libxml fail.
=> add the zlib-dev package is needed by nokogiri

group_vars/libwww/libwww-prod.yml, group_vars/pas/pas-production.yml, group_vars/recap/recap-prod.yml, playbooks/pas_production_code.yml
Updates Special Collections, PAS, and Recap database pointers to pint to the new local stand alone percona server
@kayiwa this PR is setting us up for tomorrow morning.  We will need to run from this branch
```
ansible-playbook playbooks/libwww_production.yml
ansible-vault view group_vars/all/vault.yml 
ssh pulsys@mariadb-prod3
sudo su - 
mysqldump -h <ip> -u root -p  special_collections_prod > special_collections_prod-5-13-2020.sql
mysql special_collections_prod < special_collections_prod-5-13-2020.sql
exit
exit
ansible-playbook playbooks/recap_production.yml
ssh pulsys@mariadb-prod3
sudo su - 
mysqldump -h <ip> -u root -p  recap_prod > recap_prod-5-13-2020.sql
mysql recap-prod < recap_prod-5-13-2020.sql
exit
exit
ansible-playbook playbooks/pas_production_code.yml
ssh …
```
=> Updating production for local percona

roles/pulibrary.passenger/tasks/main.yml
this allows up to allow the modification of the repo URL and runs free
standing `apt-get update`
this impacts any project that depends on passenger/nginx
closes #1535
=> upstream modified the repo URL which

group_vars/orangelight/production.yml, playbooks/orangelight_production.yml
Also added orangelight role to playbook
And turned off mailcatcher
Copied working version from approvals playbook.
```
TASK [tell everyone on slack you ran an ansible playbook] ************************************************
fatal: [lib-orange-prod2.princeton.edu -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [lib-orange-prod6.princeton.edu -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [lib-orange-prod4.princeton.edu -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a …
```
=> Do not error on slack

host_vars/figgy1.princeton.edu.yml, host_vars/lib-proc9.princeton.edu.yml, playbooks/figgy_production.yml
Closes #1601 
The `figgy_rabbitmq_host` and `figgy_filewatcher_host ` variables  need to be set for all hosts for the conditional checks to work. I could not coax Ansible to let me only set them to true for a single server. Since we are only using this flag on a single server per condition, it seems reasonable that we can set the server name in the playbook directly.
=> Use inventory_hostname instead of variable for running roles conditionally

playbooks/figgy_production.yml
this uninstalls the latest version of mediainfo so the role can run
this fixes the [figgy] processing machines inability to install figgy
this will close #1600
=> uninstall mediainfo

roles/pulibrary.redis/tasks/main.yml, roles/pulibrary.redis/templates/redis_ulimit.conf.j2
the [bibdata] roles need a higher ulimit for the redis application
this closes #1560
=> increase ulimit for redis

group_vars/postgresql/gcp_production.yml, group_vars/postgresql/gcp_staging.yml, group_vars/postgresql/staging.yml, host_vars/gcp_postgres_prod1.yml, host_vars/gcp_postgres_prod2.yml, host_vars/gcp_postgres_staging1.yml, host_vars/gcp_postgres_staging2.yml, host_vars/lib-postgres-staging1.princeton.edu.yml, host_vars/lib-postgres-staging2.princeton.edu.yml
removes the use of master in our [postgresql] staging and google cloud clusters
=> remove use of master and replace with leader

roles/pulibrary.dataspace/tasks/dataspace_config.yml
until upstream aws makes awscli available on the "cheeseshop" (pip.org) let's at least use python3
=> use python 3 instead of python2

roles/pulibrary.dataspace/templates/dspace.conf.j2
to resolve the previously created handle arks we strip occurrences of jspui
this closes #1683
=> remove jspui path in response

roles/pulibrary.cantaloupe/templates/production_nginx_config.j2
There's no reason to redirect anymore - all the files are copied over. This is one step in getting rid of libimages1.
=> Stop redirecting libimages2 errors to libimages1.

group_vars/bibdata/production.yml
Gets past this error when running the playbook:
=> Added new postgres vars to bibdata-prod

hosts
This is in preparation for monitoring (look towards bottom of file)
where will need to define specific groups and children to run ansible
against
this will be needed by #1784 but no reason not to take advantage of this now
=> allow cleaner lumping of grouped applications

roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
This will point to the Drupal site to restore search functionality for students.
=> Update proxy pass to use Drupal site for Pathe Baby

roles/orangelight/vars/main.yml
This isolates the updates introduced in https://github.com/pulibrary/princeton_ansible/issues/1315 for just the `orangelight` Role.
=> Updating the Node.js release to the 12.x series (LTS Erbium) for the orangelight Role

group_vars/bibdata/alma_staging.yml
Allows for the correct URLs to be generated for reindexing tasks.
=> [Bibdata] Add APPLICATION_URL to group_vars

README.md
Change the instructions to export a variable and then use it in the following commands so there is not as much thought needed to create a new role
=> Allow creation of role with exported variable

roles/pas/tasks/main.yml
fixes https://github.com/PrincetonUniversityLibrary/pas-craft3/issues/15
=> Adding dom dependency that is no longer there by default in 7.4

group_vars/all/vars.yml, roles/bibdata/tasks/samba_server.yml
Closes #2059
Without the `state: directory` it tried to adjust permissions for a directory which may not be there.
=> [Bibdata] Fix Bibdata role for bibdata-alma-staging.

group_vars/libwww/libwww-prod.yml, group_vars/libwww/libwww-staging.yml, roles/capistrano/defaults/main.yml, roles/capistrano/tasks/main.yml, roles/drupal/vars/main.yml, roles/libwww/defaults/main.yml, roles/libwww/molecule/default/verify.yml, roles/libwww/tasks/main.yml
Allow libwww to run whenever so that we can maintain the cron tab with the code
Left Special Collections cron in, since we have yet to look at whenever for that codebase
=> Removing cron responsibility from ansible for libwww

hosts
Library-prod2 does not exists, but library-prod4 does.  Updating host list to match actual machines
=> Fixing host list for library-prod

roles/perconaxdb/defaults/main.yml, roles/perconaxdb/vars/main.yml
There is an error on any role that uses percona that is saying this is needed for example (https://github.com/pulibrary/princeton_ansible/runs/2227801992)
fixes #2191
=> [PERCONA] Adding server package percona-xtradb-cluster-server

playbooks/pulmap_production.yml
We need that apt-cache business and datadog doesn't have common as a
dependency
=> Reorder roles in the pulmap playbook so common runs first

.gitattributes
nginx files are now no longer vaulted.  This causes errors when trying to amend commits or run a git diff.
fixes #2240
=> Updating gitattributes to reflect unvaulted files

group_vars/all/vars.yml
Today may not be the day, but some day in the near future, I believe my SSH keys should be removed from our production servers.
=> Remove access to servers for administrators

roles/bibdata/vars/main.yml
This was run on bibdata, bibdata staging, bibdata worker boxes, and bibdata-alma-staging
closes pulibrary/bibdata#752
=> Update bibdata boxes to node 12

roles/bibdata/tasks/samba_server.yml
We do not want it owned by deploy as we can not write to it if it is
=> Removing campus access from list

group_vars/pas/pas-production.yml
Currently the datadog check just sees the logs.  This would put PAS on the apache dashboard
=> [PAS] move pas into datadog apache check

galaxy.yml
With the galaxy.yml file added, I'm able to install this repository as a collection of roles.
Here's what I put in my `requirements.yml` (version set to this branch for testing to confirm):
```
collections:
- name: https://github.com/pulibrary/princeton_ansible.git
type: git
version: galaxy-collection
```
And then I installed with `ansible-galaxy install -r requirements.yml`
I put in what I thought would be reasonable defaults for the galaxy.yml; the only thing I wasn't sure about was version because AFAIK you don't version this repository.  Here is the [documentation on galaxy.yml fields](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta)
=> Add galaxy.yml to allow installing as a collection

playbooks/orangelight_workers.yml
The role was renamed but hadn't been updated in this playbook
=> Update timezome role in orangelight workers

roles/nginxplus/files/conf/http/cdh_geniza_prod.conf, roles/nginxplus/files/conf/http/cdh_test_geniza.conf
- add cPanel ip to test site to give access from old PGP site
- restrict production site to campus/vpn+cPanel while in development
Please confirm I did this right! I just copied the other examples
=> Adjust IP access to CDH geniza sites

roles/nginxplus/files/conf/http/cdh_geniza_prod.conf, roles/nginxplus/files/conf/http/cdh_test_geniza.conf
configures cdh-test-geniza and cdh-test-geniza as redirect locations so we don't have two different location blocks and two different urls
=> Make test-geniza.cdh and geniza.cdh the canonical hostnames

playbooks/orangelight_alma_prod.yml, playbooks/orangelight_alma_qa.yml
Closes #2318 
Closes https://github.com/pulibrary/orangelight/issues/2492
Playbook changes were run on alma-qa and alma-prod. Logs are showing up in datadog.
=> Add datadog to orangelight alma

group_vars/bibdata/alma_staging.yml, group_vars/bibdata/alma_workers.yml, group_vars/bibdata/bibdata_workers.yml, group_vars/bibdata/staging.yml, group_vars/cantaloupe/production.yml, group_vars/cantaloupe/staging.yml, group_vars/geoserver.yml, group_vars/smb_serve/production.yml, roles/bibdata/tasks/samba_client.yml, roles/nodejs/tasks/main.yml, roles/samba/templates/smb.conf.j2
fixes pulibrary/bibdata#1457
The smb.conf file was somehow coming up with 511 file and directory permissions even though we had configuration and a default value asking it to do otherwise. We ended up just hard-coding these values because there isn't a use case for any other value on any of our boxes.
Note this has been run on bibdata-alma production boxes.
=> [Bibdata] fix write errors

roles/solrcloud/defaults/main.yml, roles/solrcloud/templates/solr.in.sh.j2
A short timeout causes large updates to fail.
=> [Solrcloud] Increase jetty idle timeout

hosts, playbooks/bibdata_alma_production.yml, playbooks/bibdata_alma_staging.yml, roles/bibdata/meta/main.yml
This just installs Sidekiq on any alma-prod hosts with *worker in the
name, in case we want to add more later.
=> [Bibdata] Install sidekiq only on alma-worker1-3.

README.md, roles/deploy_user/.yamllint, roles/deploy_user/molecule/default/prepare.yml, roles/deploy_user/tasks/main.yml, roles/example/yamllint
This shouldn't be necessary but the sshd handler does not work as
expected. We currently waste time over and over again tracking down
why the deploy user can't log in on newly built boxes, so let's fix that.
=> Restart sshd after deploy_user reconfigures it

group_vars/orangelight/alma_qa.yml
This was updated directly on the box (since lpass login was erroring).
=> [orangelight qa] Update rabbit server to new figgy staging machine

group_vars/orangelight/alma_qa.yml
Makes sure Orangelight QA points to bibdata **staging** instead of bibdata production.
=> Uses bibdata-staging (instead of bib data production)

group_vars/oawaiver/production.yml
This ensures that the environment variables are instead parsed for setting the SMTP host for oawaiver deployments.
=> Adding the SMTP host and port for the production oawaiver hosts

roles/oar/templates/oar_nginx.conf.j2
This is necessary in order to advance https://github.com/pulibrary/dspace-development/issues/465
=> Ensuring that the /rt4ds endpoint is accessible over the HTTP for OAR deployments

roles/libstatic/defaults/main.yml, roles/libstatic/molecule/default/verify.yml
We had to revert this change, because the search did not work in the static site
https://github.com/pulibrary/pathebaby/issues/3
=> Pathe is a drupal site not a static site

group_vars/all/vars.yml
@kayiwa How do we add him to the pulsys keys also?  He is missing for ruby-office for pulsys
refs #2466
=> Adding Paul Diskin's key

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
This is the first step in moving visual_materials/maps from lib-dbserver
=> Adding a proxy pass to maps on lib static

roles/nginxplus/files/conf/http/vireo_staging.conf
We are changing the vireo strategy away from pointing the load balancer
directly at tomcat (port 8080). Instead, we'll point it at apache2,
running on port 443.
Connected to https://github.com/pulibrary/princeton_ansible/issues/2585
=> Load balancer must point to 443 to pick up shib config

hosts, playbooks/upgrade_apache.yml
Supersedes #2598.
Follows up on #2597 by:
=> fixes indents on task, removes hosts that don't run apache

roles/solrcloud/templates/solr.in.sh.j2
Figgy was timing out on large updates.
This has been deployed, as we're unsure if it'll fix our issue.
Refs https://github.com/pulibrary/figgy/issues/4802
=> Configure stall time to be very high.

roles/nginxplus/files/conf/http/dss-prod.conf, roles/nginxplus/files/conf/http/dss-staging.conf
=> Update the timeout for DSS to something very large

roles/nginxplus/files/conf/http/maps-prod.conf, roles/nginxplus/files/conf/http/maps-staging.conf
=> Update the timeout for maps to something very large

roles/nginxplus/files/conf/http/slavery-prod.conf, roles/nginxplus/files/conf/http/slavery-staging.conf
=> Update the timeout for slavery to something very large

roles/nginxplus/files/conf/http/lib-mudd-prod.conf, roles/nginxplus/files/conf/http/lib-mudd-staging.conf
=> Update the timeout for mudd-dbs to something very large

roles/nginxplus/files/conf/http/catalog-alma-qa.conf, roles/nginxplus/files/conf/http/catalog-alma.conf, roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-qa.conf
Also removes empty NGINX config files
=> Update the timeout for catalog to something very large

roles/nginxplus/files/conf/http/locator-prod.conf, roles/nginxplus/files/conf/http/locator-staging.conf
=> Update the timeout for locator to something very large

roles/drupal/tasks/main.yml, roles/mariadb/tasks/main.yml, roles/mariadb/tasks/manage_contents.yml, roles/mariadbserver/tasks/main.yml, roles/molecule_mariadb/tasks/main.yml
Supersedes #2562, which got a bunch of merge commits in it by mistake.
Updates the mirrors for mariadb. The old mirror disappeared, which was causing apt commands to fail.
=> remove digitalocean repo

roles/nginxplus/files/conf/http/confluence-prod.conf, roles/nginxplus/files/conf/http/confluence-staging.conf
=> Update the timeout for confluence to something very large

.github/workflows/molecule_tests.yml
To make it easier to maintain the molecule test suite, this branch:
- alphabetizes the existing list of roles in .github/workflows/molecule_tests.yml
- deduplicates the existing list
- adds all other roles in the repo in their alphabetized position
The molecule file now reflects the current state of the repo, though that may not be the ideal state (some roles may be obsolete). 
I wasn't entirely sure why some roles were commented out, so I went with the "countryside rule" of "leave it how you found it." If a role was commented, I left it commented. And I added the missing roles as comments, in case they were left out for a reason.
=> Alphabetize roles for Molecule testing

roles/shibboleth/README.md
Closes #2634.
Adds a note for future users who need to install Shibboleth about the apache config requirements, with a link to the example in the Vireo role.
=> adds note about apache config settings and link to vireo example

playbooks/nginxplus_production.yml, playbooks/nginxplus_production_rebuild.yml, roles/nginxplus/README.md, roles/nginxplus/tasks/conf/upload-config.yml
Closes #2639 
The current nginxplus playbook installs datadog and adds the deploy user (plus a bunch of common setup tasks), then installs nginxplus from scratch. This is overkill for the kinds of updates we do regularly, and it's slow to run.
To address these challenges, this PR:
Once this is merged, we should be able to run `ansible-playbook playbooks/nginxplus_production.yml -t SSL` to upload new/replaced SSL certs and keys.
If possible, let's wait to merge this until we can test it in the staging environment we're creating.
=> Revise nginxplus playbook and role

hosts, roles/bind9/tasks/main.yml, roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/tasks/conf/upload-config.yml
Closes #2654.
Closes [figgy#4868](https://github.com/pulibrary/figgy/issues/4868). 
Adds the two new Figgy web VMs to our inventory. Updates the bind9 role to use local DNS.
=> Adds new Figgy servers, updates bind9 role

group_vars/vireo/staging.yml, roles/vireo/tasks/apache_config.yml, roles/vireo/tasks/main.yml, roles/vireo/templates/vireo.conf.j2
This fixes an error where the vireo application can't access javascript
via the ws protocol
Work toward https://github.com/pulibrary/rdss-catchall/issues/32
=> Allow ws proxying for vireo

playbooks/figgy_production.yml
I realize this exacerbates https://github.com/pulibrary/princeton_ansible/issues/1204 but the common role does have to run first so I propose merging this until we get a chance to work that issue.
=> [Figgy] run common first

group_vars/dpul_production.yml
Run this on DPUL because we already have datadog running and paid for
there (vs appdeploy), and it's already configured for TLS checking one
domain.
=> [DPUL] Add certificate checks for all of DLS' applications.

group_vars/lae/production.yml, group_vars/lae/staging.yml
Reverts pulibrary/princeton_ansible#2668
This project needs much more work than simple upgrading to ruby 2.7. This PR reverses that PR until we have time to devote to LAE.
=> Revert "Update lae ruby to 2.7"

playbooks/figgy_production.yml
refs pulibrary/figgy#4916
It looks like this (note text has been adjusted since this screenshot was taken):
=> Add a flashy debug message to the end of figgy webserver tasks

roles/appdeploy/molecule/default/verify.yml, roles/figgy/tasks/main.yml
Closes #2683.
Fixes two recent test failures:
Error: linting failed in the figgy role because we were upgrading a package without any checks and balances
Fix: add a version parameter to the task
Error: verification failed in the appdeploy role because the verification test required a specific version of `forever`, but the install task installed the latest version, so as soon as a new version was released, the test started to fail
Fix: change the test to be version-agnostic
=> Fix failing tests

roles/libwww/templates/proxy_pass_rules.j2
Closes #2491.
For now, the branch just comments out the ProxyPass rules connecting `/LibraryStaff` to `https://lib-dbserver.princeton.edu/LibraryStaff`. 
I'm not sure what this content was or where it has gone. Should there be a different redirect in place? Possibly to the [Library Staff](https://library.princeton.edu/staff) page?
=> Removes ProxyPass rules for /LibraryStaff

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
Closes #2529.
Removes proxypass redirect from `/voyagerapps` to `https://lib-dbserver.princeton.edu/voyagerapps/`.
=> removes proxypass for voyagerapps

roles/solr/tasks/links.yml
Fixes a test failure uncovered in an idempotence test on #2693. The test failure was:
```
TASK [solr : Link Config Directories] ******************************************
ok: [instance] => (item={'core_name': 'catalog', 'config_name': 'catalog-production'})
Warning: : Cannot set fs attributes on a non-existent symlink target. follow
should be set to False to avoid this.
```
Here's a link to the test run where the failure turned up:
https://github.com/pulibrary/princeton_ansible/runs/5023030869?check_suite_focus=true 
This PR sets the `follow` param on the `file` module to `false`, as the test failure message suggested.
=> Fixes idempotence test failure in Solr role

hosts, playbooks/lib_svn_production.yml, playbooks/pulmap_production.yml, playbooks/solrcloud_production.yml, playbooks/zookeeper_production.yml
Closes #181.
Group names for all projects with both staging and production groups now reflect the environment name as well as the project name. No more `project` and `project_staging`.  However, some groups use `stage` instead of `staging` and `prod` instead of `production`. Should I update those group names as well? Or are we okay with a little variation as long as the group clearly indicates the environment it's targeting?
=> explicitly adds 'production' to all host groups for production machines

roles/nginxplus/files/conf/http/library-prod.conf
we are removing old aliases to redirect to library.princeton.edu
we will not include certs because we expect these names to die
closes #1620
=> add two new blocks for firestone and stokes

roles/nginxplus/files/conf/http/lib-statistics-prod.conf
Closes #2115 (eventually).
This PR refers to the cert names from #2116. I'm opening it as a draft, however, because I have mostly copied the contents from other examples in the repo (specifically confluence and lib-static). I'm not sure if I used `lib-statistics-prod` and plain `lib-statistics` in the right places. I'm also not sure if additional steps are necessary to close #2115.
=> adds config for lib-statistics production site

playbooks/nginxplus_production.yml
Related to #2647.
closes #2733
When running the nginx playbooks with `--tags update_conf`, the `reload` task in the role ran, because it was tagged with `always`. However, the `restart nginx for realsies` task in the playbook did not run. If this task doesn't run, sites go down.
This PR adds `tags: always` to both tasks in the nginx production playbook.
=> nginx playbook needs 'always' tags on restart and announcement

roles/samba/tasks/main.yml
when we install samba we need to add `cifs-utils` in order to create a mount
that works.
closes #2744
=> samba role needs cifs-utils to fully function

hosts, roles/dpul/tasks/main.yml, roles/nginxplus/files/conf/http/dpul-staging.conf
Required updates to the dpul role to fix directory ownership of symlink to mounted shared/uploads.
Remove dpul-staging1 because we're going to rebuild it. We'll add it back
when it's ready
refs pulibrary/dpul#1296
=> [DPUL] Fix uploads directory ownership and use new dpul-staging2

playbooks/nginxplus_production.yml, roles/nginxplus/README.md
Closes #2751. Related to #2732.
The nginxplus role has two tags that shorten execution time for common tasks. Document those tags in the playbook and in the role README. 
Add comments to the playbook and the role README about running load-balancer updates with `-limit` in case of unexpected turbulence.
=> Adds guidance to nginxplus role README and playbooks

hosts
Closes #2752.
When the new dpul-staging infrastructure is ready to go, we'll need to merge this hostsfile change so future updates will apply to both machines. 
Related to #2748.
=> adds new dpul-staging1 to hosts file

roles/nginxplus/files/conf/http/dpul-staging.conf
Closes #2759.
Adds the new dpul-staging1 server to the load balancer config.
The new server was already added to the Ansible hosts file by #2755.
=> adds dpul-staging1 to load balancer

playbooks/lae.yml, playbooks/pdc_discovery.yml
We currently have multiple playbooks for each project, one per environment. In most pairs, the only differences are the `hosts` and the `vars_files`. To streamline the repository, simplify maintenance, and reduce the risk of drift, we'd like to reduce this duplication where possible.
This branch creates two "unified" playbooks as proofs of concept:
- lae.yml
- pdc_discovery.yml
Each playbook can run be against production or staging. Both run against staging by default. The `hosts` and the `vars_files` are defined based on the variable `runtime_env` (though may be `ansible_env` would be better?). The existing playbooks are still there for comparison purposes.
This PR should stay a draft until these two playbooks have been tested. If the unified playbooks work, next steps would include:
- …
=> Deduplicate playbooks

roles/nginxplus/files/conf/http/cdh_prod_geniza.conf
removing the trailing slash on the proxy url — currently it's resulting in a double-slash in the url
=> Remove extra slashes on proxied geniza urls

hosts, playbooks/postgresql_db_migration.yml
As part of #2735 we want a playbook that will dump existing databases from the old hardware, transfer the dump to the new hardware, and import the data into postgres on the new hardware.
This PR updated an existing playbook to do the full end-to-end db migration. We tested this playbook on the ojs_staging database, and it worked a charm!
=> Fix the postgres backup-and-restore playbook

roles/nginxplus/files/conf/http/pdc-discovery_prod.conf, roles/nginxplus/files/conf/http/pdc-discovery_staging.conf
the pdc-discovery project prefers to have a path added for their application
we add the path to the root of the domain which is a desired goal of the
project
=> add a path to pdc-discovery

group_vars/pdc_discovery/production.yml, roles/nginxplus/files/conf/http/pdc-discovery_prod.conf
Also, PDC Discovery production should point at the load balanced solr
Work toward https://github.com/pulibrary/pdc_discovery/issues/169
=> Configure PDC Discovery to deliver at subdirectory

group_vars/pulfalight/production.yml
Closes #2810.
We discovered today that pulfalight was pointing to an individual Solr box instead of using the load balancer to access Solr. This updates the config to use the load balancer.
=> switch pulfalight vars to use load-balanced Solr8

playbooks/library_solr_production.yml, playbooks/library_solr_staging.yml
The library drupal indexes were moved back into the cloud now that it is stable.
Leaving as a draft for now until we decide this is all stable.  Should be merged when https://github.com/pulibrary/pul_solr/pull/318 is merged.
=> Removing playbooks for library solr machines

playbooks/postgresql_db_migration.yml
This PR updates the playbook for dumping and restoring postgresql databases:
- removes `ignore_errors`
- makes tasks that might take a long time asynchronous
- updates the comments in light of today's testing
- changes the `hosts` line, because we do not have separate `postgres_prod` and `postgres_staging` groups in our hosts file yet
=> Update the Postgres db backup playbook

hosts, playbooks/studio_processors.yml
Roel reported seeing `permission denied (publickey)` when trying to do the rake ingest of LAE material on the new studio processing machine. This is a baby step toward automating management of the studio processing machines - I think it will solve the immediate problem and I hope it will give us a foundation to build on, so we can automate whatever else needs to be installed/managed on those machines.
=> Automate access to the new studio machine

roles/nginxplus/tasks/main.yml, roles/nginxplus/tasks/plus/setup-debian.yml
the nginxplus pkg repos are down. This allows the playbook to run
=> ignore apt get errors

roles/appdeploy/defaults/main.yml, roles/appdeploy/molecule/default/converge.yml, roles/appdeploy/tasks/main.yml, roles/nodejs/README.md, roles/nodejs/defaults/main.yml, roles/nodejs/molecule/default/verify.yml, roles/nodejs/tasks/main.yml, roles/nodejs/vars/main.yml, roles/rails_app/tasks/main.yml
This PR eliminates the need for `apt` versions of node. Instead we download specific binaries from the nodejs project to install node. 
- add nodejs variables
- add specific node version info
It will supercede #2796 and #2787
=> build nodejs

group_vars/pulfalight/production.yml, group_vars/pulfalight/staging.yml, roles/nodejs/README.md, roles/nodejs/tasks/main.yml
With the recent changes to the nodejs role, we can specify an exact version of NodeJS for each app.
This PR specifies the version for pulfalight, which should match https://github.com/pulibrary/pulfalight/blob/main/.tool-versions#L2.
=> specifies nodejs version for pulfalight

group_vars/orangelight/production.yml, group_vars/orangelight/staging.yml, roles/orangelight/vars/main.yml
This upgrades qa to the new default version (16)
=> Keep Orangelight production and staging on Node 12

group_vars/approvals/approvals_prod.yml, group_vars/approvals/approvals_staging.yml
closes #2831 
closes #2832
I ran this on approvals staging and it upgraded node to v12.22.5 and ruby version to 2.7.5
=> [Approvals] Upgrade ruby version to 2.7.5 and node to v12.22.5

playbooks/approvals.yml
When I ran the approvals playbook in production it failed because of #2082.
I followed @carolyncole solution in https://github.com/pulibrary/princeton_ansible/commit/f7cfd34f6b9dd0b69991f936870764b55d9aeca3 and moved datadog role below the approvals role to avoid issue #2082
=> [Approvals] move datadog role below approvals 

playbooks/postgresql_db_migration.yml
In our original testing, we were able to use `restore` alone, because we had already created the named database. However, `restore` does not create the new db when used in a clean environment. 
This PR updates the playbook so it first creates the new db, then restores the data for that db from the backup.
=> Fix postgresql db backup playbook

group_vars/bibdata/staging.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
The staging and QA environments for bibdata and orangelight were migrated to our fresh, new postgresql infrastructure today. This PR updates the group variables so any future playbook runs will keep the correct configuration. 
=> updates bibdata and orangelight postgres vars for migrated env

group_vars/bibdata/production.yml, group_vars/orangelight/production.yml, group_vars/postgresql/production.yml, host_vars/lib-postgres-prod2.princeton.edu.yml, host_vars/lib-postgres-prod3.princeton.edu.yml, hosts, playbooks/orangelight_production.yml, playbooks/postgresql_production.yml, playbooks/postgresql_staging.yml, roles/postgresql/tasks/repmgr.yml
We are migrating the production catalog to use our shiny, new postgresql replicated environment. This PR updates the variables for bibdata and orangelight to match the new settings.
Do not merge until after the migration is complete and the dust has settled.
=> updates production vars for bibdata and orangelight

group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml
this update oawaiver to ruby 2.7 
the tool versions on [oawaiver](https://github.com/pulibrary/oawaiver/blob/main/.tool-versions)
suggest that this has already happened.
if yes. It closes https://github.com/pulibrary/oawaiver/issues/56
=> upgrade ruby to 2.7.5

roles/nginxplus/files/conf/http/pdc-discovery_prod.conf, roles/nginxplus/files/conf/http/pdc-discovery_staging.conf
Eventually, we want https://datacommons.princeton.edu
to be a separate application from
https://datacommons.princeton.edu/discovery. However, until that top
level content has been populated, send traffic to /discovery.
Fixes https://github.com/pulibrary/pdc_discovery/issues/232
=> Redirect top level traffic to /discovery

roles/nginxplus/files/conf/http/library-prod.conf, roles/nginxplus/files/conf/http/library-staging.conf
Transfer traffic to whichever nodes are responding the fastest.
nginx documentation: https://nginx.org/en/docs/http/ngx_http_upstream_module.html#least_time
Similar to https://github.com/pulibrary/princeton_ansible/issues/2790
=> Update load balancing strategy for the library website.

roles/nginxplus/files/conf/http/libimages.conf
Refs #2619 and pulibrary/figgy#5022
I don't think we need a new certificate - I downloaded the cert info and it looks like @kayiwa was clever and added both `libimages` and `libimages1` to the same cert:
```
X509v3 Subject Alternative Name:
DNS:libimages.princeton.edu, DNS:libimages1.princeton.edu
```
=> Handle libimages at iiif.princeton.edu

roles/php/molecule/default/converge.yml, roles/rvm/molecule/default/converge.yml
We were seeing failures on tests in the `common` role when called by molecule from `rvm` and `php` roles. The error was:
```
"The conditional check 'running_on_server' failed. The error was: error while evaluating conditional (running_on_server): 'running_on_server' is undefined
```
Which was strange, because the `converge.yml` playbook for the `common` role clearly set `running_on_server: false`. 
It looks like Molecule only loads vars from the converge playbook of the role that kicks off a test run, not from any dependent roles. So it wasn't the `common` role that was causing the problem. This should fix the issue globally.
=> make all converge playbooks include running_on_server

roles/common/tasks/main.yml
The task being removed here is causing idempotency failures on a bunch of roles.
The original problem was an apt repo that disappeared. The original workaround was added as part of #2499. I'm hoping that the broken repo has now been removed from our machines and we can delete the workaround task.
=> removes workaround for obsolete apt issue

roles/ruby/tasks/main.yml
Closes #2276.
I tested this by:
- installing Ruby 2.7 using the ruby role
- running the role again with `ruby_version` set to `ruby2.6`
- SSH'ing to the box before, between, and after the two playbook runs
=> Ruby role checks ruby version before installing

.gitignore, .tool-versions
I rely heavily on [direnv](https://direnv.net/) to de-clutter my
profile. Furthermore it has an [asdf-plugin](https://github.com/asdf-community/asdf-direnv) that -thus far- feels faster than the `asdf-shims`
Also removes vagrant references
=> clean up .gitignore, allow use of direnv

roles/postgresql/defaults/main.yml, roles/postgresql/tasks/create_db.yml
Closes #2815.
- Sets the task that creates databases to `run_once`.
- Corrects the name of the psql admin password var.
- Tried re-using `application_db_*` variables for the `pg_hba` configuration task, but ultimately gave database connections access to `all` in `pg_hba.conf` so they can create databases - this helped #2871 work but we may be able to change it in future - added a comment for Future Us.
=> Postgresql fixes

playbooks/postgresql_db_migration.yml
the documentation refers to a project that doesn't actually exist. this
improves it to make it useful for PUL developers
=> improve playbook example

playbooks/approvals.yml
fixes
```
fatal: [lib-approvals-staging1.princeton.edu]: FAILED! => {"msg": "The conditional check 'runtime_env == \"prod\"' failed. The error was: error while evaluating conditional (runtime_env == \"prod\"): 'runtime_env' is undefined\n\nThe error appears to be in '/Users/colec/projects/princeton_ansible/roles/datadog/tasks/pkg-debian.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install apt-transport-https\n  ^ here\n"}
```
=> allow approvals playbook to run

playbooks/abid.yml, playbooks/annotations.yml, playbooks/ansible_tower.yml, playbooks/appdeploy_production.yml, playbooks/approvals.yml, playbooks/bibdata.yml, playbooks/deploy_user.yml, playbooks/lae.yml, playbooks/remove_user.yml, playbooks/researchdata.yml, playbooks/ruby_office.yml, playbooks/studio_processors.yml, playbooks/upgrade_apache.yml, playbooks/zookeeper.yml
Partial fix for #2852.
Starts updating playbooks to mention the play name when they send an alert to slack.
Uses `community.general.slack` in the slack task.
Updates playbooks starting with `a` and `b` and playbooks that have already been consolidated (see #2726).
=> Includes ansible play name in slack alerts, uses FQCN for slack module

roles/postgresql/tasks/repmgr.yml
Closes #2943.
Closes #2945.
For 2943:
If the task that generates that variable is skipped, Ansible cannot evaluate the conditions on the next task.
The fix was to change the order of the conditions so that when `postgresql_is_local` is true, the task is skipped without evaluating the contents of `pgpass_stat`.
For 2945:
This was left over from testing on google cloud.
=> tidies up repomgr tasks

roles/postgresql/tasks/create_users.yml
One task in the postgresql role uses the `postgres` and `replicant` users, printing out their passwords in the output. Currently anyone who can run that role can also access those passwords, but as we move to Tower/the Platform, that will not necessarily be true.
This PR sets `no_log: true` on that task.
=> Set no_log on postgresql tasks with sensitive data

roles/nginxplus/files/conf/http/cdh_prod_geniza.conf
small tweak to the indexcards redirect — I think based on how it's behaving that `$request_uri` includes the `/indexcards` portion of the url, since right now it's getting doubled  on the redirect
=> Revise indexcards redirect with request uri

playbooks/update_expired_certs.yml
we occasionally have upstream projects certificates expire. This playbook will
update this on a VM
=> install ca-certificates

hosts, roles/bibdata/.yamllint, roles/bibdata/tasks/main.yml
Closes #2965.
Removes the `bibdata_workers` group and the obsolete `bibdata-worker2` VM from the hosts file.
A check for references to the `bibdata_workers` group turned up [this task](https://github.com/pulibrary/princeton_ansible/blob/abf065ba53dcf51d9a85fcacd23783d1eceb1358/roles/bibdata/tasks/redis_overcommit_memory.yml) in the bibdata role that looks like it should execute only on worker boxes.
I added a condition to the task include statement so that task will only execute on worker boxes, but I'm not sure if that's the correct logic or not.
=> Remove bibdata-worker2, update bibdata task to run only on worker boxes

playbooks/remove_datadog.yml
Related to #2966.
This playbook quickly and easily removed the Datadog agent from two VMs. I'm adding it to the repo in case we need to do this again in future.
=> adds playbook to remove datadog from hosts or groups

group_vars/bibdata/qa.yml
closes #3038 
I ran the playbook on bibdata-qa and confirmed that the `SQS_QUEUE_URL` env is not in the box.
=> Temporarily deactivate the sqs_queue url in bibdata-qa

playbooks/bibdata.yml
I'd like not to load sqs-poller service in bibdata-qa.
This is a temporary change until we fix https://github.com/pulibrary/bibdata/issues/1867
=> temporary change- dont run sqs poller service in bibdata-qa

roles/postgresql/tasks/create_users.yml
Closes #3042.
When running on multiple VMs, the postgresql tasks that create users will cause failures on the first run. This marks those tasks `run_once` to avoid race conditions.
=> make db user tasks 'run_once' to avoid failures

playbooks/deploy_user.yml
This PR incorporates the comments from #3030, letting folks know why running the `deploy_user` playbook on all hosts during the work-day is not a great idea.
=> annotate deploy user playbook

hosts, roles/nginxplus/files/conf/http/pulfalight-prod.conf
Traffic to pulfalight no longer requires extra hardware. Removing the three surge VMs from the rotation. 
Related to #2911.
=> removes pulfalight surge boxes from hosts file

playbooks/aws_group_access.yml
this play book gives devs a wee bit more access than the default
=> create a playbook to grant devs aws aws_group_access

playbooks/update_expired_certs.yml
if you pass the missing recv_key variable this will replace the missing
keys
=> we add a fix to expired certs not running

roles/nginxplus/files/conf/http/dss-prod.conf, roles/nginxplus/files/conf/http/dss-staging.conf
The root page is a redirect, which fails health checks. /catalog will
exercise Solr.
=> [DSS] Use the /catalog path for health checking DSS

group_vars/all/vars.yml
We want to add SSH keys to our VMs for new employees.
Vickie can't currently generate keys, so her entry is commented out for now.
Robert's keys should be ready today.
=> adds Robert and Vickie's SSH keys from GitHub

roles/nginxplus/files/conf/http/lib-solr-staging.conf, roles/nginxplus/files/conf/http/lib-solr8-staging.conf
the stricter http requests of the WAF make our services look like
attacks
=> disable waf on solr

roles/common/molecule/default/converge.yml, roles/common/molecule/default/verify.yml
fixes 'fqcn-builtins: Use FQCN for builtin actions' lint errors
=> Updating common to pass molecule

hosts
It's broken and it seems easier to make a new box.
refs pulibrary/figgy#5328
=> [figgy] Remove lib-proc8

roles/passenger/meta/main.yml, roles/passenger/molecule/default/Dockerfile.j2, roles/passenger/tasks/main.yml
this allows nginx to rotate the error logs
remove references to xenial which we no longer use
this closes #3150
=> add passenger-config to the postrotate

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml
This ensures that the `413` errors are no longer raised for form `POST` file uploads
=> Ensuring that the client_max_body_size is set to 0 for pdc-describe NGINX config. files

group_vars/dss/production.yml, group_vars/dss/staging.yml
we have encountered migration problems that require a revert back to the
lib-postgres3 database
=> reverts back to lib-postgres3

.tool-versions
I've been using ruby 2.7.5 for a while for the lpass integration, and it's been working well.
=> Use ruby 2.7.5

playbooks/lib_jobs.yml
closes #3179 
Example output:
```
TASK [post role reminders] ********************************************************************************************************************
ok: [lib-jobs-staging1.princeton.edu] => {
"msg": [
"Possible Things left to do:",
"- deploy lib_jobs and aspace_helpers",
""
]
}
```
=> i3179: post-role reminders for lib-jobs

playbooks/researchdata.yml
Without this role, the researchdata playbook doesn't know that it should replace the datadog api_key in the datadog config files.
=> [Researchdata] add missing datadog role to prod

playbooks/postgresql_db_migration.yml
Bibdata and orangelight both have qa environments.  The qa databases are on the staging postgres boxes.  However, this playbook assumes that the app's environment and the database's environment are named the same.
This PR separates out the `runtime_env` into two variables: `runtime_env` and `app_runtime_env` so that you can do something like:
```
ansible-playbook -e project_name=bibdata -e runtime_env=staging -e app_runtime_env=qa -e dest_host=lib-postgres-staging2.princeton.edu playbooks/postgresql_db_migration.yml --limit lib-postgres-staging3.princeton.edu
```
=> Allow database backup for qa environments

roles/mudd/tasks/main.yml
With `0644` permissions on this directory and file, deploying to staging fails.  Switching to `0744` allows the deploy to go through.
I also added fully qualified module names.
=> Mudd-dbs: file permissions to allow deploy

roles/common/tasks/main.yml
we currently have the playbook stop running when apt-get update step
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
Co-authored-by: Tyler Wade <twade968@users.noreply.github.com>
=> add ignore error while we wait for a robust solution

playbooks/nginxplus.yml, playbooks/nginxplus_production_rebuild.yml
We changed the inventory group name from `nginx` to `nginx_production`. Now we need to explicitly load group_vars and call the correct group name.
We should not need the group_vars for the second play . . .
=> explicitly add nginx group_vars, use new inventory groups

group_vars/figgy/production.yml, playbooks/figgy_production.yml
Something's stealing files out of the cdl_scans folder and we can't
figure out what it is. To get things moving again, we're going to switch
to a subfolder.
Refs pulibrary/figgy#5396
=> [Figgy] Change CDL ingest folder.

playbooks/remove_app_configs.yml, roles/deploy_user/tasks/main.yml, roles/rails_app/tasks/main.yml
closes #3308 
The .bashrc line that causes this error was previously added as part of the deploy_user role, but it is really only needed in the rails_app role, so I moved it to the rails_app role.
This PR also includes a separate one-time playbook to remove all those .bashrc lines from the apache servers.  I wasn't sure if it should be part of this repo or not, since it probably won't be very useful after it is run...
[Example deployment logs before](https://gist.github.com/pulbot/5d972e59c4b436856ff9bbbc4379d89f) running the remove_app_configs playbook vs. [after](https://gist.github.com/pulbot/d6fe94e21d1cc10767d3262b867d20d2)
=> I3308 app configs is only for rails

group_vars/appdeploy/production.yml
If you don't give an environment, pulbot defaults to deploying to production. This runs the risk of accidental deployments to production. 
We're shifting to having most ansible-playbooks defaulting to staging, and running on production if that environment is explicitly passed as an argument - this follows that pattern. (see also https://github.com/pulibrary/hubot-deploy/blob/main/src/scripts/deploy.coffee#L26). 
shoutout to @tpendragon for pointing to the right spots to change.
=> Change pulbot default env from prod to staging

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
remove the multi-use of amp_training
Co-authored-by: Eliot Jordan <eliotjordan@users.noreply.github.com>
Co-authored-by: Stephanie Ayers <stephayers@users.noreply.github.com>
=> add a syntax nginx semi colon

inventory/all_projects/postgresql
Today we saw outages in production when we ran the new "apt update" playbook against all staging machines. Traced the problem to an inventory issue.
Because `lib-postgres3` contains both production and staging databases, originally we put the machine in both the `postgresql_production` and `postgresql_staging` groups. Keeping it in only the production group for now.
The eventual fix for this problem is to separate prod and staging fully, see #2735.
=> keep lib-postgres3 only for prod

playbooks/libstatic_production.yml, roles/libstatic/defaults/main.yml
- Use https for cloning to avoid ssh errors
=> Use correct hosts alias

group_vars/ojs/main.yml, roles/ojs/defaults/main.yml, roles/ojs/tasks/install_ojs.yml, roles/ojs/tasks/main.yml, roles/omp/tasks/main.yml, roles/php/handlers/main.yml, roles/php/tasks/configure-nginx.yml, roles/php/tasks/configure.yml, roles/php/tasks/main.yml, roles/postgres/tasks/main.yml, roles/psql/tasks/main.yml, roles/redis/tasks/main.yml, roles/samba/tasks/main.yml, roles/solrcloud/tasks/main.yml, roles/zookeeper/tasks/main.yml
Closes #3305.
The use of `include` without any indication of what to include (role? tasks? vars?) is deprecated and the functionality will disappear in Ansible 2.16. Using the specific directives is clearer, anyway.
This PR updates the few instances we still had of generic `include` directives.
=> updates all bare 'include' statements to 'include_tasks'

inventory/by_environment/production, playbooks/os_updates.yml
we are removing the loadbalancers because having both restart
immediately after the other would be disastrous
=> remove nginxplus production

roles/abid/molecule/default/converge.yml, roles/apache2/molecule/default/converge.yml, roles/appdeploy/molecule/default/converge.yml, roles/approvals/molecule/default/converge.yml, roles/bibdata_sqs_poller/molecule/default/converge.yml, roles/composer/molecule/default/converge.yml, roles/dpul/molecule/default/converge.yml, roles/drupal/molecule/default/converge.yml, roles/drupal9/molecule/default/converge.yml, roles/drush/molecule/default/converge.yml, roles/friends_of_pul/molecule/default/converge.yml, roles/geaccirc/molecule/default/converge.yml, roles/lockers_and_study_spaces/molecule/default/converge.yml, roles/mysql/molecule/default/converge.yml, roles/ouranos/molecule/default/converge.yml, roles/pas/molecule/default/converge.yml, roles/pgbouncer/molecule/default/playbook.yml, roles/php/molecule/default/converge.yml, roles/postgresql/molecule/default/converge.yml, roles/researchdata/molecule/default/converge.yml, roles/rvm/molecule/default/converge.yml, roles/special_collections/molecule/default/converge.yml, roles/studio_proc/molecule/default/converge.yml
Partial fix for #3013.
Without a pre-task to update the cache, the common role usually fails with `fatal: [instance]: FAILED! => {"changed": false, "msg": "No package matching 'htop' is available"}`. So we need to update the cache explicitly for testing before we can remove the `update_cache: true` settings from tasks within various roles.
=> Ensure all roles update the cache for CI

roles/drupal9/defaults/main.yml, roles/drupal9/meta/main.yml, roles/drupal9/molecule/default/converge.yml, roles/drupal9/tasks/main.yml, roles/php/handlers/main.yml, roles/php/tasks/configure-apache2.yml, roles/php/tasks/configure-nginx.yml, roles/php/tasks/main.yml
A first attempt to fix #3013 ran into an idempotence failure on the `drupal9` role. This turned out be caused by a conflict in apt. You cannot install both `nodejs-dev` and `php7.4-dev` with apt - when you install the second one, apt uninstalls the first one.
We agreed to install NodeJS from source rather than as an apt package.
Fixing this problem uncovered a failure in the PHP role. Although the role accepted either apache2 or nginx as its webserver, some tasks hardcoded apache2 as the server to restart.
This PR fixes both of these issues.
=> Update drupal9 and PHP roles to pass CI

roles/rails_app/handlers/main.yml, roles/rails_app/tasks/main.yml
Closes #3257.
Adds a handler for restarting nginx to the rails_app role. With this in place we should be able to use the `site_config` tag to refresh configuration without running the entire rails_app role and all of its dependencies, but still restart nginx to use the new config.
=> triggers an nginx restart when new config gets loaded

roles/nginxplus/files/conf/http/cdh_test_web.conf, roles/nginxplus/files/conf/http/templates/cdh_hc3.conf
There is a need to preserve access to the old hc3 CMS
=> add a redirect to the legacy hc3 website

roles/ruby_s/molecule/default/converge.yml
the role will occasionally run longer than the alloted 10 minutes and
will subsequently fail idempotence.
I am unable to find the pattern for this and certainly not on CI.
Connected to #3455.
=> the ruby_s role occasionally fails idempotence

roles/ruby_s/tasks/cleanup.yml
Closes #3491.
Removes the old ruby packages installed by `apt` using a wildcard instead of listing all the installed packages. This is cleaner, quicker, and works more reliably.
=> remove ruby packages using wildcard

roles/ealapps/tasks/main.yml
Uses the ansible.builtin.cron module to create cron jobs for ealapps.
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
All tests passed.  I want to confirm that the files were generated correctly before finalizing this (will do so first thing on Thu 12/8).
=> Ealapps cron jobs

inventory/by_environment/sandbox, playbooks/rapid7_install.yml
We installed Rapid7 on a sandbox machine and tried rebooting it, and the Rapid7 agent restarted successfully. Removing the dummy tasks in the playbook.
=> updates rapid7 after testing on sandbox vms

.github/workflows/molecule_tests.yml
This shaves a solid 90 seconds off of each job run (except the very first one to run with a given python version or requirements.txt, of course).  Hopefully this will translate into more available runners on busy days with a lot of PRs. 🤞
=> Cache python environment (including pip dependencies) in github actions

roles/ealapps/tasks/main.yml
closes #3537 
Sibling PR: https://github.com/PrincetonUniversityLibrary/ealapps/pull/16
I ran this on staging 12/15, using a `--start-at-task` so I didn't clobber the apache config change from #3543
=> [ealapps] i3537: send mail to mailcatcher instead of sendmail on staging

roles/ealapps/tasks/main.yml
- These were on staging, but not in the role, and were required for composer to install correctly on production
Ran on production and was able to use Capistrano to deploy
=> [ealapps] Add required php modules

roles/nginxplus/files/conf/http/library-prod.conf
Follow up to #3568.
Removes all reference to `lib-prod.princeton.edu`.
=> also remove the config that refers to lib-prod cert and key

playbooks/os_updates.yml
this will bump up the time it takes to run all the updates with a
minimal disruptive penalty.
An odd number is also preferable because occasionally the playbook fails
when paired servers are included.
=> add the number of servers this runs

group_vars/oawaiver/production.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/staging.yml, roles/pulfalight/molecule/default/converge.yml, roles/pulfalight/vars/main.yml
Closes #2708.
Grepping through the repo turned up these places where `solr_version` was being set (often incorrectly) but no place where it was being used (in other words, no instances of `{{ solr_version }}`). 
This PR removes the unused variables.
=> removes unused 'solr_version' variable

roles/nginxplus/defaults/main.yml, roles/nginxplus/templates/nginx.conf.j2
Closes #2556.
Supersedes #2648.
We've seen some failures of playbooks with the error:
```
nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size
```
This PR overrides the [default setting](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_max_size) of `512` for  the `server_names_hash_max_size`, making the  stated setting `1024`, which should still be well within the capabilities of the nginxplus servers.
=> Expand nginx server hash table

playbooks/nginxplus.yml
Partial fix for #3319.
Adds a failure task at the beginning of the nginx playbook.
I didn't add it to the larger `nginx_production_rebuild` playbook, and I'm not sure if we want to add it there. That playbook rebuilds the load-balancing infrastructure from scratch.
=> Nginx playbook should fail if run without '--limit'

playbooks/ealapps.yml
Closes #3573.
Brings the ealapps playbook into line with our other playbooks by connecting as the `pulsys` user.
Includes a comment showing how to override the connection user if necessary.
=> use pulsys for the ealapps playbook

group_vars/pdc_discovery/production.yml
Currently it is pointing at pdc-describe-prod1 which is the physical host.  This is causing URLs generated by the application to be incorrect and unreachable
fixes https://github.com/pulibrary/pdc_describe/issues/768
=> Updating the host to be the load balanced host pdc-describe-prod

playbooks/pdc_describe.yml, playbooks/pdc_discovery.yml, playbooks/repec.yml
Partial fix for #2852.
Updates the slack messages in the `pdc_describe` and `pdc_discovery` playbooks.
Also updates the slack message and play name in the `repec` playbook.
=> More slack message updates

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Testing in staging, this PR moves the new redirect rules for prod. It also removes them for staging to at the point of go live staff can still refer to the old list for a period of time to help resolve any outstanding discrepancies that remain post migration.
=> [libwww] Move Database list redirects for libguides into Production.

inventory/by_environment/production
the pulmirror vm is not included in the patch tuesday group
this adds it
will close #3685
=> [ansible operations] add pulmirror vm

README.md
The old command now causes and error and will not work.
```
princeton_ansible) colec in ~/projects/princeton_ansible (tiger-data) > molecule init role roles/$your_new_role --driver-name docker
CRITICAL Outside collections you must mention role namespace like: molecule init role 'acme.myrole'. Be sure you use only lowercase characters and underlines. See https://galaxy.ansible.com/docs/contributing/creating_role.html
```
Must cd into roles and then run the init command
```
(princeton_ansible) colec in ~/projects/princeton_ansible (tiger-data) > cd roles
(princeton_ansible) colec in ~/projects/princeton_ansible/roles (tiger-data) > molecule init role $your_new_role --driver-name docker 
INFO     Initializing new role tigerdata...
```
=> [README] Update for CRITICAL Outside collections you must mention role namespace

roles/oawaiver/molecule/default/converge.yml, roles/oawaiver/molecule/default/verify.yml, roles/rails_app/handlers/main.yml, roles/ruby_s/tasks/install_bundler.yml
it fails on CI because it expects a deterministic configuration we
cannot provide
=> [ansible] unbreak main branch 

roles/common/tasks/main.yml, roles/ruby_s/molecule/default/converge.yml
we need snapd installed on VMs and not containers
this is a fix to allow a new container to run for #3724
which fails to get a new container
=> [ansible] common role snapd

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
- ~This should only be run when we're ready to switch the Byzantine production site~
This has been run successfully on the load balancers.
=> Add Byzantine to library proxy-pass

roles/common/defaults/main.yml
libyaml is not present in jammy and makes the `ruby_s` role fail to
build
=> [ruby_s] add libyaml to common

group_vars/orangelight/production.yml, group_vars/zookeeper/zookeeper_production.yml
Currently most projects have a datadog tag for `environment: production`.
This PR changes the two outliers to follow this convention. Baby steps!
=> make ddog environment tags parallel

group_vars/ealapps/production.yml
Ran successfully on prod and now see monitor here - https://app.datadoghq.com/monitors/65339664?from_ts=1681295019631&to_ts=1681309419631&eval_ts=1681305403550&q=host%3Aeal-apps-prod1
=> Add TLS for datadog on ealapps

playbooks/deploy_user.yml, roles/deploy_user/tasks/main.yml
Because we want folks to rotate their SSH keys periodically, we want to make it easy to deploy new keys. This PR:
- Adds two refinements to the deploy_user role and playbook:
- use `run_once` on the task that pulls keys from GitHub (which takes a long, long time)
- adds a tag called `update_keys` to the two tasks in the `deploy_user` role - when we only need to update keys, this will make the process much quicker, because we won't be running all the other tasks (creating the deploy user, allowing the `authorized_keys` file, etc.) on existing/built VMs
- Updates the documentation in the playbook
- Comments out the `serial: 2` setting
- when run with `serial`, Ansible runs any `run_once` tasks once per group, so with `serial: 2` we would get at most a 50% speed improvement; I hope that with …
=> Make deploy_user playbook & role quicker

group_vars/pdc_describe/staging.yml
We upgraded to ruby 3.1.0 so we need to update the mailcatcher location to match
Fixes:
* https://github.com/pulibrary/pdc_describe/issues/1085
=> Update install location for mailcatcher

roles/towerdeploy/tasks/main.yml
Closes #3824 
Add the `activesupport` gem to the list of gems we install on the new `appdeploy` machine for use by capistrano when deploying from Ansible Tower.
=> install activesupport on towerdeploy for dpul

group_vars/all/vars.yml
Students no longer working for PUL.
=> Remove student ssh and sidekiq keys

roles/nginxplus/templates/nginx.conf.j2
we will use backwards compatible best practices for TLS
adopted from Mozilla
closes #3832
=> [nginxplus tls] improve our TLS scores

playbooks/bsd_updates.yml, playbooks/os_updates.yml
doas replaced sudo from OpenBSD base. doas does not propagate
the environment variables from the original session. Ansible has a way
to specify environment variables per task. This workaround allows us to
automatically update our BSD servers
=> [patch Tuesday] split openbsd playbook

roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf
The load balancer was converting HEAD requests to GET requests, resulting in Uppy not being able to do resumable uploads for Figgy (it uses a HEAD request to see the state of the previous upload.)
Pulled from https://serverfault.com/questions/530763/nginx-proxy-cache-key-and-head-get-request and tested.
=> [Figgy] Cache HEAD requests separately from GET requests.

group_vars/all/vars.yml
Removes the key for `heaven`, which is now retired.
Removes the key for Taylor.
=> Updates keys list for deploy and pulsys users

group_vars/all/vars.yml
Deploying via ansible tower still depends on the heaven key.  We should remove the heaven key eventually, but we're re-adding it now so that we can keep deploying.
Previously, if the deploy_user role had been run on a box to remove the heaven key, appdeploy could no longer ssh into the box to deploy.  This affected lib-jobs production, bibdata production, pdc_describe, and possibly figgy.
To get your app deployable again after this is merged: `ansible-playbook playbooks/deploy_user.yml -e runtime_env="[your_env]" --limit=[your_group_of_servers]`
=> Add heaven key back

roles/byzantine/tasks/main.yml
the byzantine vms did not have NFS mounts added
=> [byzantine] add nfs mounts

inventory/by_cloud/aws
if a Globus VM goes down it will get a new IP address from AWS. We are
providing with an Elastic one to prevent the inability to connect
=> [pdc-globus] use elastic IP

group_vars/redis/production.yml
There were a couple config options missing for datadog to collect metrics on on our redis infrastructure.
=> [Redis] Collect metrics for datadog

roles/orangelight/meta/main.yml
- This allows us to skip the creation of a cron job that was causing issues.
- In order for it to take full effect, you need to ssh onto each box and delete the cron job manually
```
ssh deploy@one-of-the-servers
crontab -e
crontab -l
```
Connected to #4039 
Connected to https://github.com/pulibrary/orangelight/issues/3610
=> [orangelight] Use rails_app role not blacklight_app

inventory/all_projects/_orphans
We have quite a few mysterious entries in our inventory. Can we clarify what these machines are, what they do, and how important they are?
This PR begins by noting the current use of libserv144.
We might also consider adding "hosted on" information to 
https://lib-confluence.princeton.edu/display/IT/Service+Catalog+Data as part of this effort.
=> Updates inventory, esp. orphans

roles/nginxplus/files/conf/http/lib-solr8-prod.conf, roles/nginxplus/files/conf/http/lib-solr8-staging.conf, roles/nginxplus/files/conf/http/lib-solr9-prod.conf, roles/nginxplus/files/conf/http/lib-solr9-staging.conf
the loadbalancer keeps favoring one of our boxes because we've been
defaulting on round robin. we will use the least_time instead
load balancing method where a request is passed to the server with the least average response time and least number of active connections, taking into account weights of servers
incomplete requests are also taken into account with the inflight
parameter
=> [solr] change our upstream algorithm

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-staging.conf
When a human user visits the catalog using a web browser, it causes a burst of ~16 requests for all the images, javascript, etc.  To reduce the chance that bursts like this would cause nginx to block a human user, let's increase the burst setting, but keep the rate limit in place to block traffic that is consistently making many requests/second.
We ran this on 19 July, 2023.
=> [Catalog] increase burst for catalog rate limit

roles/lib_svn/tasks/main.yml
Previously the task was outputting each user's secret to the console, this makes it so that it does not log those secrets.
=> [lib_jobs] Do not log SVN secrets

group_vars/bibdata/production.yml
Ran this on 14 July, and bibdata machines started showing up on the nginx dashboard in datadog.
=> [Bibdata] Add datadog nginx status check

inventory/all_projects/cdh
Working on #2227, we discovered that the CDH folks don't have access to the load balancers. This is a shared resource, so they should be able to access it.
=> allow CDH to access load balancers

group_vars/orangelight/common.yml
Closes #4055 
Connected to https://github.com/pulibrary/orangelight/issues/3629
=> [orangelight] Add env for redis_db

roles/vips/defaults/main.yml, roles/vips/tasks/main.yml
This makes sure it uninstalls an old version of vips if it exists, and sets the default higher.
New vips has faster PDF processing. Work towards pulibrary/figgy#5937
=> [Figgy] Upgrade VIPs

playbooks/fix_apt_issues.yml
Closes #2082.
We already had a playbook called `update_expired_certs.yml` that fixes expired apt keys. This PR:
- adds a task to remove obsolete apt repos from our sources.list
- changes the playbook name to avoid confusion about which "certs" (SSL? Apt?) and to reflect the playbook's expanded capability
=> Automates fixing obsolete apt repos

roles/postgresql/README.md
the `README` did not have helpful examples to allow us to know what
variables are needed to create a new database and database connection
=> [postgresql] improve readme

roles/nginxplus/files/conf/http/approvals-prod.conf, roles/nginxplus/files/conf/http/approvals-staging.conf, roles/nginxplus/files/conf/http/byzantine-tsp_prod.conf, roles/nginxplus/files/conf/http/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/catalog-qa.conf, roles/nginxplus/files/conf/http/catalog-staging.conf, roles/nginxplus/files/conf/http/library-prod.conf, roles/nginxplus/files/conf/http/library-staging.conf, roles/nginxplus/files/conf/http/locator-prod.conf, roles/nginxplus/files/conf/http/locator-staging.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-prod.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf, roles/nginxplus/files/conf/http/recap-prod.conf, roles/nginxplus/files/conf/http/recap-staging.conf, roles/nginxplus/files/conf/http/repec-prod.conf, roles/nginxplus/files/conf/http/repec-staging.conf, roles/nginxplus/files/conf/http/researchdata_prod.conf, roles/nginxplus/files/conf/http/researchdata_staging.conf, roles/nginxplus/files/conf/http/slavery-prod.conf, roles/nginxplus/files/conf/http/slavery-staging.conf, roles/nginxplus/files/conf/http/videoreserves_prod.conf, roles/nginxplus/files/conf/http/videoreserves_staging.conf
Updates nginx config for DACS sites - allows errors to be passed through load balancer for monitoring, etc. 
Has not been run on load balancer yet (as of 8/11/2023)
=> [nginx] Update DACS nginx error handling

roles/nginxplus/files/conf/http/templates/errors.conf
Closes #4134.
No idea how the old config actually worked. But this seems to do the trick.
Keeps the `error` and `ratelimit` locations private, but adds a non-private location stanza for the image.
=> [nginx] add config stanza for logo

roles/nginxplus/tasks/validate.yml
Closes #2749.
Sets the 'always' tag on the config validation task. This task gets included in the role run when the target is our load balancers (nginxplus). It should run whether or not we pass `-t update_config`. If it fails, the handler to reload the config (which runs at the end of the role) shouldn't run, and the hard restart at the end of the playbook shouldn't run either.
Not sure what the `command` module will consider to be a failure, though. We may need to add a `failed_when` condition to control that. Let's test this by putting some bad config on a branch and trying to upload it to the inactive LB using the playbook before we merge.
=> [Nginx] set 'always' tag on nginx validation

roles/figgy/meta/main.yml
Removes the figgy dependency on the kakadu role.
Kakadu is still referenced in these locations:
- 'all' group vars (in `extra_path`)
- 'cantaloupe' group vars
- the cantaloupe playbook
- the `task/main.yml` file in the sidekiq workers role
=> [Figgy] figgy does not use kakadu any more

roles/nginxplus/files/conf/http/catalog-prod.conf
They're eating up our Alma calls.
This is deployed.
=> Block Bytespider from the catalog.

roles/nginxplus/files/conf/http/templates/datacommons-describe.conf, roles/nginxplus/files/conf/http/templates/datacommons-discovery.conf
these make the `nginx -t` fail
created an issue here https://github.com/pulibrary/princeton_ansible/issues/4200
=> [datacommons] remove health checks

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-staging.conf
Part of today's incident response. We still need to allow referred traffic to .ris and .endpoint resources to go through. Implementing this to preserve our Alma API quote in the meantime.
Related to #4203.
Co-authored-by: Anna Headley hackartisan@users.noreply.github.com
Co-authored-by: Bess Sadler bess@users.noreply.github.com
Co-authored-by: Carolyn Cole carolyncole@users.noreply.github.com
Co-authored-by: Esmé Cowles escowles@users.noreply.github.com
Co-authored-by: Kevin Reiss kevinreiss@users.noreply.github.com
Co-authored-by: Mark Zelesky mzelesky@users.noreply.github.com
Co-authored-by: Max Kadel maxkadel@users.noreply.github.com
Co-authored-by: regineheberlein regineheberlein@users.noreply.github.com
Co-authored-by: …
=> block .ris and .endnote on catalog prod

group_vars/tigerdata/production.yml
This follows the changes proposed during the Datadog Book Club session held on 09/08/2023:
Co-authored-by: [Bess Sadler](mailto:bess@users.noreply.github.com)
Co-authored-by: [Alicia Cozine](mailto:acozine@users.noreply.github.com)
Co-authored-by: [Anna Headley](mailto:hackartisan@users.noreply.github.com)
Co-authored-by: [Max Kadel](mailto:maxkadel@users.noreply.github.com)
=> Ensuring that the Datadog logs for NGINX on TigerData hosts specify that these are associated with the `tigerdata` service

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, roles/rails_app/defaults/main.yml, roles/rails_app/handlers/main.yml, roles/rails_app/tasks/main.yml
This means we don't have to deploy to restart things after a site
config change.
=> [Rails App] Allow for more than nginx to restart after updating config.

playbooks/geoserver_production.yml, playbooks/lib_smb_serve_production.yml
Closes #2852.
These are the last playbooks that still sent `{{ inventory_hostname }} completed` to slack.
=> update slack alerts for lib-smb and geoserver playbooks

group_vars/bibdata/staging.yml
also bibdata-samba is configured with fqdn
this points to the correct vm
=> [bibdata] fix redis on bibdata

inventory/all_projects/allsearch, playbooks/allsearch_api.yml
Adds a very minimal playbook for allsearch (all it does is run common and add a deploy user), hopefully it's a good starting point for future work.
I ran this on staging on 14 September.
=> Add deploy user to allsearch boxes

playbooks/cicognara.yml, playbooks/postgresql.yml, playbooks/pulfalight.yml, roles/postgresql/meta/main.yml, roles/rails_app/meta/main.yml
It's both a "set a server up" playbook and a "apps include this" playbook - for "set a server up" it should be in the playbook, for "apps include this" common not being a dependency will allow us to optimize setting up required databases.
This also tags the postgresql role includes with "postgresql." By tagging postgresql we can run playbooks and just have it set up access/databases/users. This is useful for migrations. (see step 3 here: https://github.com/pulibrary/pulfalight/issues/1319)
=> [Postgresql] Move postgresql common role to playbook.

roles/dpul/meta/main.yml
solrcloud shouldn't be there at all, and the rest are covered by
rails_app.
=> [DPUL] Remove inaccurate dependencies from dpul

group_vars/nfsserver/staging.yml, inventory/all_projects/cdh, roles/nfsserver/defaults/main.yml, roles/nfsserver/tasks/main.yml
- add lib-fs-staging access for CDH folks Co-authored-by: Rebecca Sutton Koeser <rlskoeser@users.noreply.github.com>
- add prosody test machine to have nfs access
- add all the cdh test servers to the nfs exports Co-authored-by: Rebecca Sutton Koeser <rlskoeser@users.noreply.github.com>
=> [cdh] add cdh vms to nfs

roles/nginxplus/files/conf/http/nagios-staging.conf, roles/nginxplus/files/conf/http/prometheus-staging.conf
the upstream server doesn't send host information back to client
=> [nginxplus] prometheus and nagios

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf
Closes https://github.com/pulibrary/allsearch_api/issues/45
Based on #4072 - using a lower burst rate, because this application does not download a bunch of assets when first loading the page, as the Catalog does.
=> [allsearch-api] Rate limit requests / sec

playbooks/incommon_certbot.yml, playbooks/incommon_certbot_multi.yml
Adding a cert is necessary but not sufficient for adding or updating a site on the load balancer. To avoid unexpected behavior, we should not restart nginx when we add the cert - we should only restart nginx when we deploy the new/updated config that uses the cert.
=> do not restart nginx when creating new certs

group_vars/imagecat_rails/production.yml
This reverts commit af77c01c7ba8851119e21ffb1acb4652ce1f48a3.
We need to use the data that we have been loading in the old db.
Refs pulibrary/imagecat-rails#156
=> Revert "point production server to new database (#4344)"

roles/nginxplus/files/conf/http/allsearch-api_staging.conf, roles/nginxplus/files/conf/http/allsearch_prod.conf, roles/nginxplus/files/conf/http/allsearch_staging.conf
Creates a frontend prod site config.
Creates a frontend staging site config.
Fixes a typo in the api staging site config.
Related to https://github.com/pulibrary/allsearch_frontend/issues/2.
* The letsencrypt certs do not yet exist. Run the certbot playbook before deploying these changes!
=> [allsearch] Adds and updates allsearch nginx config files

roles/recap_www/templates/settings.php.j2
Part of https://github.com/pulibrary/recap/issues/199
Sibling PR: https://github.com/pulibrary/recap/pull/257
I ran this on staging on 2 October, 2023
=> [recap] Set config_sync_directory to a real directory

roles/nginxplus/files/cdh-error.html, roles/nginxplus/files/cdh-forbidden.html, roles/nginxplus/files/error.html, roles/nginxplus/files/index.html, roles/nginxplus/files/ratelimit.html
closes #4329 
The image file can always be found at /pul-logo-new.svg, but the error page might appear at a path like /my/error/is/here.html.  Using an absolute path to refer to the image means that the application layer doesn't have to try to scramble to find an image at /my/error/is/pul-logo-new.svg, sparing us some Honeybadger noise.
=> i4329: Load balancer error page should use absolute path to image file

roles/nginxplus/files/conf/http/cdh_test_sandbox.conf
I have an app running on the sandbox that apparently requires connection upgrade headers when proxied by nginx. I have these settings in the nginx config on the sandbox server and when I access that server via ssh port forwarding the app works; when I disable these, I get an error about a web socket connection. When it is working in sandbox nginx and I access it through the load balancer it does not work. I'm hoping this configuration will allow it to work through lib-adc.
=> Add connection upgrade headers to CDH sandbox proxy location

roles/nginxplus/files/conf/http/pdc-orcid_prod.conf, roles/nginxplus/files/conf/http/pdc-orcid_staging.conf
the DNS names are registered for the name
pdc-orcid-staging.princeton.edu and
pdc-orcid-prod.princeton.edu which will be network restricted during the test period
related to #4363
=> [pdc-orcid] loadbalancer setup

group_vars/postgresql/production.yml, roles/postgresql/templates/postgresql.conf.j2
Closes #4357.
Updates the postgresql configuration:
- simplifies the log file name
- explicitly logs all statements
- updates the log file mode so the datadog user can read it
- uses log entry prefix recommended in datadog docs
Updates the production group vars for postgres to match the new config. We hope this will enable the datadog service.
=> Get postgresql logs onto Datadog

group_vars/postgresql/production.yml
We had these two datadog config params backwards. This PR resets them to do what we want for our postgres logs:
- `service` can be any string; this is what shows up in Datadog UI as a way to filter the logs view - we set it to `postgres_cluster`, which is more descriptive than `database`
- `sourcecategory` is the type of log - we set this to `database`, which is more accurate than `postgresql_logs`
=> update service and sourcecategory for pgsql in datadog

inventory/all_projects/_orphans, inventory/by_environment/production
The pulsys user playbook was not running on the load balancers. I suspect neither was the apt update playbook.
Root cause was that those playbooks run by environment, as defined by the files in `inventory/by_environment`, like `inventory/by_environment/production.yml`. The load balancers were not in the production group. 
This PR adds a group for the load balancers in the `_orphans` file and adds the `load_balancers` group to 'production' meta-group.
=> [inventory] adds group for LBs

playbooks/nginxplus.yml, playbooks/nginxplus_production_rebuild.yml
Closes #4381.
If no tag is passed at runtime, the output of the notification will say:
Ansible is now running `update loadbalancer configuration` with the `all` tag on lib-adc2.
Are there other playbooks we want to add this functionality to?
=> notify when nginx playbooks start, with tags

roles/nginxplus/files/conf/http/allsearch_staging.conf
the second vm was missing on the loadbalancer. This adds it
Co-authored-by: Kim Leaman <kelea99@users.noreply.github.com>
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
=> [allsearch] add second vm

group_vars/postgresql/production.yml
Partial fix for #4369.
Using datadog-agent 6.46 lets the postgresql check succeed.
```
postgres (13.7.0)
-----------------
Instance ID: postgres:e38e16b591127b8f [WARNING]
Configuration Source: file:/etc/datadog-agent/conf.d/postgres.d/conf.yaml
Total Runs: 2
Metric Samples: Last Run: 135,013, Total: 135,791
Events: Last Run: 0, Total: 0
Database Monitoring Activity Samples: Last Run: 2, Total: 2
Database Monitoring Metadata Samples: Last Run: 134,014, Total: 134,017
Database Monitoring Query Samples: Last Run: 3, Total: 3
Service Checks: Last Run: 1, Total: 2
Average Execution Time : 79ms
Last Execution Date : 2023-10-20 18:51:08 UTC (1697827868000)
Last Successful Execution Date : 2023-10-20 18:51:08 UTC (1697827868000)
metadata:
resolved_hostname: lib-postgres-prod1
version.major: 15 …
```
=> install older datadog-agent on postgres to support pg checks

group_vars/nginxplus/main.yml, playbooks/nginxplus.yml, roles/nginxplus/defaults/main.yml
We are working to move most configs over to a template instead of static configs. In the meantime, however, we can make running the nginxplus playbook safer by only running the 'cleanup' tasks when we absolutely need to.
This PR also tries to organize the variables for the nginx role a little better:
- eliminates duplication (identical vars set to identical settings in group_vars and role defaults/main.yml) - hoping to save us from some vars-precedence issues in future
- puts vars in active use into the group_vars
- removes vars that are not in active use from the group_vars so we know which vars we are using and why
=> Make running the nginx playbook safer

playbooks/incommon_certbot.yml, playbooks/incommon_certbot_multi.yml, playbooks/incommon_certbot_revoke.yml, playbooks/nginxplus.yml, roles/nginxplus/files/conf/http/orcid_prod.conf
Also adding more information into the playbook comments for certificates
Additionally revoked the existing certificate using the new playbook and ran
```
ansible-playbook -v -e domain_name=orcid -e add_san_name="orcid-prod" --limit lib-adc2.princeton.edu playbooks/incommon_certbot_multi.yml
ansible-playbook -v -e domain_name=orcid -e add_san_name="orcid-prod" --limit lib-adc1.princeton.edu playbooks/incommon_certbot_multi.yml
```
=> Updating orcid-prod to also be know as orcid

roles/nginxplus/files/conf/http/lib-solr9-prod.conf
solr-prod2 is connecting to the wrong zookeeper ensemble
we are commenting it out to prevent the loadbalancer from sending traffic to it
Co-authored-by: Hector Correa <hectorcorrea@users.noreply.github.com>
=> [solr-prod9] stop traffic

group_vars/orangelight/common.yml, group_vars/orangelight/production.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/qa.yml, group_vars/pulfalight/staging.yml, roles/redis/README.md
Note that orangelight QA and orangelight prod both are and have been pointing at db 7 on the central prod redis host.
closes #4294
closes #4046
advances pulibrary/pulfalight#1323
=> Introduce and document consistent scheme for central redis db usage

group_vars/orangelight/staging.yml
The mailcatcher service was not running on the catalog-staging boxes.  This is because it's looking for the mailcatcher binary at `/var/lib/gems/3.1.0/gems/mailcatcher-0.8.1/bin/mailcatcher`, when it is actually at the default location of `/usr/local/bin/mailcatcher`
I ran this on catalog-staging today, and confirmed that after `systemctl daemon-reload && service mailcatchter restart`, mailcatcher is running again.
=> [catalog-staging] use the default mailcatcher path

playbooks/nginxplus_production_rebuild.yml, roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-qa.conf, roles/nginxplus/files/conf/http/catalog-staging.conf, roles/nginxplus/files/conf/http/templates/errors-without-404.conf
Closes https://github.com/pulibrary/orangelight/issues/3732.
Creates an error config page that handles most errors on the load balancer, but allows 404s to be handled by the underlying application.
Changes the catalog config to use this new error config page.
Other applications can now update their configs to use this as desired.
=> allow catalog to use custom 404s

group_vars/ealapps/staging.yml
migrate database to use mysql-dev1 
this is running mariadb-10.6 (mysql 8)
=> [ealapps] migrate db

group_vars/orangelight/qa.yml
closes #4455 
Orangelight currently only uses redis for rack mini profiler, but this safeguards against future collisions should we use redis more extensively in Orangelight in the future.
I ran this on staging today, 27 November.
=> Use Redis database #8 for Orangelight QA

group_vars/ealapps/staging.yml, playbooks/ealapps.yml
this adds a new jammy vm for eal-apps-staging1
playbook runs successfully.
files need to be `rsync'ed`
=> [ealapps] upgrade eal to jammy

roles/nginxplus/files/conf/http/ansible-tower_prod.conf
We now have two VMs for our Tower/Controller.
This PR adds the second one to the config for the load balancer.
=> adds second box to Tower config on nginxplus

roles/solrcloud/defaults/main.yml, roles/solrcloud/templates/solr.in.sh.j2
The changes from #4067 were never deployed to production. We are now seeing issues in Solr, and wondering if we should use the older configuration.
Closes #4483.
=> partially reverts PR #4067

roles/pas/tasks/main.yml
Related to https://github.com/PrincetonUniversityLibrary/pas-craft3/issues/102
Sibling PR: https://github.com/PrincetonUniversityLibrary/pas-craft3/pull/108
=> [pas] manage .env file in the capistrano shared directory, rather than the home directory

roles/nginxplus/files/conf/http/maps-prod.conf
See [incident report](https://docs.google.com/document/d/1b7rjSdW7DKXC9B2MlEuHcn7XkMdbjZBuek2Pn1A_5zA/edit)
=> Add a least_time algorithm to maps to fix -no live upstreams while connecting to upstream-

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Two projects in ealapps (oclcpinyin, addpinyin-plugin-marcedit) have been moved to github.  This PR implements the redirects from the old site.
=> ealapps pinyin projects redirect to github

group_vars/pulfalight/qa.yml, roles/passenger/defaults/main.yml, roles/passenger/templates/nginx.conf.j2
This helps avoid gem version conflicts like the one encountered in
https://github.com/pulibrary/pulfalight/pull/1353
=> Configure passenger to load bundler before loading app

group_vars/tigerdata/common.yml
fixes 
```
App 1234797 output: Error: The application encountered the following error: You have already activated base64 0.1.1, but your Gemfile requires base64 0.2.0. Since base64 is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports base64 as a default gem. (Gem::LoadError)
```
=> [tigerdata] Allow newer bundler

roles/nginxplus/files/conf/http/lib-jobs-staging.conf
load balancer is pointing to wrong VM
=> [lib-jobs] point load balancer to correct vm

roles/solrcloud/tasks/main.yml
- the solr8cloud (no d) has an undocumented cifs mount to diglibata
- this mount allows us to save backups
- we add this to the new solr8d cluster
closes #4598
=> [solr8cloud] add cifs mount

roles/common/defaults/main.yml, roles/common/tasks/main.yml
the #4601 PR added an upstream fd-find which it turns out lags way behind this PR unbreaks the common role
=> update fd-find to 9.0.0

keys/TowerKey.pub, roles/common/templates/pulsys_keys.j2
Our new Ansible Tower instance is mostly working. I regenerated an SSH key (ed25519) on the ansible-tower1 box for the new installation. There's already a Credential in Tower for this, so we can use it for Template (playbook) runs. This PR adds the public key to the repo.
=> [Tower] adds public key for Tower to pulsys SSH template and to keys dir

inventory/by_cloud/google_cloud
Partial fix for #4018.
This provides connection details for our Google cloud resources. However, we still need to provide connection details for our AWS cloud resources.
=> adds bastion info for GCP hosts

roles/nginxplus/files/conf/http/ansible-tower_prod.conf
Closes #4043.
Attempt to fix issue 4043 with nginx config. Very much WIP.
=> Configure nginx to allow tower to call /websocket/

roles/redis/tasks/main.yml
not finding a use case for why we would install redis and not start it
Closes #4589
=> [redis] ensure redis starts

roles/postgresql/tasks/main.yml
Fixes:
```
TASK [postgresql : PostgreSQL | add pg_stat_statements extension to the default db] ****************************************************************************************************
fatal: [tigerdata-staging2.princeton.edu]: FAILED! => {"changed": false, "module_stderr": "sudo: unknown user postgres\nsudo: error initializing audit plugin sudoers_audit\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [tigerdata-staging1.princeton.edu]: FAILED! => {"changed": false, "module_stderr": "sudo: unknown user postgres\nsudo: error initializing audit plugin sudoers_audit\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
refs #4618
=> [POSTGRES] Removing the failing task until a better solution can be found

roles/nfsserver/tasks/main.yml
while idmap is enabled on the NFS servers we need to add the FQDN or it will export this are princeton.edu
related to #4622
=> [nfsserver] add fqdn

group_vars/allsearch_frontend/production.yml, group_vars/allsearch_frontend/staging.yml, roles/allsearch_frontend/templates/env.j2
This URL will be used for availability API calls
Helps with https://github.com/pulibrary/allsearch_frontend/issues/166
I ran this on staging on 7 February, 2024
=> [allsearch-frontend] add envvar for bibdata url

playbooks/nginxplus.yml
When somebody runs the nginx playbook, it notifies slack. The message already included the play name, the tags (showing `all` if the playbook was run with no tags), and the server it ran against.
This change discovers the git branch and adds it to the slack message. This is useful in the moment when someone is running updates to the nginx config. It's also useful after the fact if we need to figure out which branch was used the last time our config was updated.
=> Includes git branch in slack notification for nginx playbook

group_vars/tigerdata/common.yml, roles/ruby_s/tasks/install_bundler.yml
Setting up the new version of bundler to be a default
=> [TIGERDATA] Updating tigerdata bundler version to allow passenger to run

group_vars/orangelight/common.yml
See also [Orangelight PR](https://github.com/pulibrary/orangelight/pull/3961)
Connected to pulibrary/dacs_handbook#157
=> [Orangelight] Upgrade node to v18.19.1

roles/pas/meta/main.yml, roles/pas/tasks/main.yml
PAS no longer uses node for anything, so let's remove it from this role.  I'm also removing it from the boxes manually with:
```
```
I did this on staging today, ran the playbook, then deployed, and I didn't see any problems.
closes https://github.com/PrincetonUniversityLibrary/pas-craft3/issues/113
=> [pas] remove node role

group_vars/allsearch_api/common.yml, roles/rails_app/meta/main.yml
I manually removed it from the staging boxes, then ran the playbook with this branch on staging, then deployed.  It looked like it works well without node.
Here's how I removed it manually:
```
```
closes https://github.com/pulibrary/allsearch_api/issues/197
=> Don't install node for allsearch_api

group_vars/researchdata/common.yml, roles/drupal9/meta/main.yml, roles/drupal9/tasks/main.yml
We no longer use nodejs for this drupal site.
Today, I manually deleted node from the staging box with:
```
```
Then ran the playbook with this branch and deployed.  Everything worked as expected.
closes https://github.com/pulibrary/researchdata/issues/273
=> [researchdata] don't install nodejs

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
the lib-db-server name is no longer available
this points the service to the lib-static-prod server.
possibly related to #4592
=> [lib-static-prod] visual resources 

group_vars/recap/common.yml, roles/drupal/meta/main.yml, roles/drupal/tasks/main.yml
We no longer use nodejs for this drupal site.
Today, I manually deleted node from the staging box with:
```
```
Then ran the playbook with this branch and deployed.  Everything worked as expected.
closes https://github.com/pulibrary/recap/issues/266
=> [recap] don't install nodejs

group_vars/byzantine/common.yml
We no longer use nodejs for this drupal site.
Today, I manually deleted node from the staging box with:
```
sudo apt-get remove -y yarn nodejs
```
Then ran the playbook with this branch and deployed.  Everything worked as expected.
closes https://github.com/pulibrary/byzantine_translations/issues/53
To check that the staging site was working as expected, I did `ssh -L 1234:localhost:80 deploy@byzantine-tsp-staging[12]`, and then checked localhost:1234 in my browser
=> [byzantine] don't install node

group_vars/friends_of_pul/common.yml
We no longer use nodejs for this drupal site.
Today, I manually deleted node from the staging box with:
```
sudo rm -rf /usr/local/node-v1*
```
Then ran the playbook with this branch and deployed.  Everything worked as expected.
closes https://github.com/pulibrary/friends_of_pul/issues/146
=> [friends] don't install node

group_vars/mudd/common.yml
Update node to 20.11.1
Remove bundler_version
Initially I removed node from the box. I purged all the node packages and then when I tried to add node back mudd-staging complained about bundler (yes). Even though the x version of bundler was installed and set as the default it couldn’t see it. I removed the y version of bundler that was also installed. It still didn’t want to look the x version, even though it was installed. I removed the x version and then ran the playbook with bundler_version x. Nothing was installed. 
In the end I manually installed the x version of bundler.
=> [mudd-db] Update node to 20.11.1

Pipfile
add the dependabot PR #4677 to match our pipenv
the dependabot only updates the `requirements.txt` file
running `pipenv install -r requirements.txt` from #4677 allows our pipenv environment to match it.
=> [prancible] add dependabot PR

playbooks/utils/enable_redis_on_restart.yml
fixes #4707
See enabled on the third line down... Prior to running the playbook it stated disabled
```
pulsys@tigerdata-staging2:~$ sudo systemctl status redis-server
● redis-server.service - Advanced key-value store
Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2024-02-28 13:33:16 UTC; 1min 1s ago
Docs: http://redis.io/documentation,
man:redis-server(1)
Main PID: 456492 (redis-server)
Status: "Ready to accept connections"
Tasks: 6 (limit: 9347)
Memory: 3.1M
CPU: 218ms
CGroup: /system.slice/redis-server.service
└─456492 "/usr/bin/redis-server 0.0.0.0:6379" "" "" "" "" "" "" "" "" ""
Feb 28 13:33:16 tigerdata-staging2 systemd[1]: Starting Advanced key-value store...
Feb 28 13:33:16 tigerdata-staging2 …
```
=> Adding a playbook to enable redis

inventory/all_projects/dpul, inventory/all_projects/lae, inventory/all_projects/pulmap
Partial fix for #4662.
Part our upgrade-to-Jammy-Jellyfish project. This PR adds the newly created Jammy VMs for pulmap, dpul, and lae-blacklight to our inventory for Princeton Ansible. 
Related to:
https://github.com/pulibrary/lae-blacklight/issues/365
https://github.com/pulibrary/dpul/issues/1493
https://github.com/pulibrary/pulmap/issues/1187
=> adds new jammy VMs for dpul, lae, and maps to inventory

roles/common/tasks/vector.yml
Datadog has acquired Vector, so all the packages moved to them.
Pulled from https://vector.dev/highlights/2023-11-07-new-linux-repos/
=> [Common] Fix Vector.

group_vars/figgy/staging.yml, inventory/all_projects/figgy, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/mediainfo/defaults/main.yml, roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf, roles/rabbitmq/tasks/main.yml
For now this leaves Figgy connected to figgy1.princeton.edu just for Redis until tonight, when the workers finish processing their jobs and I can migrate redis data to figgy-web-prod1.
=> [Figgy] Upgrade to Jammy

roles/nginxplus/files/conf/http/lae-prod.conf, roles/nginxplus/files/conf/http/lae-staging.conf
Closes #4650 
Sets Real-IP header to enable access logging:
https://github.com/pulibrary/princeton_ansible/blob/main/roles/passenger/templates/passenger.j2#L12-L15
=> Set X-Real-IP header for lae to fix access logging

group_vars/dpul/production.yml, group_vars/figgy/production_webserver.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/production_workers.yml, group_vars/pulmap/production.yml, playbooks/pulfalight.yml
Powers a health status monitor for no extra money, on a per-host basis: https://app.datadoghq.com/monitors/140962600?view=spans
=> [Figgy/DPUL/Pulfalight/Maps] Add an HTTP check for health endpoints.

group_vars/dpul/production.yml, group_vars/figgy/production_webserver.yml, group_vars/pulfalight/production.yml, group_vars/pulmap/production.yml
This'll let us create more nuanced monitors.
=> [Figgy/DPUL/Maps/Pulfalight] Use per-service datadog health checks.

inventory/all_projects/lib-jobs, roles/nginxplus/files/conf/http/lib-jobs-prod.conf
The lib-jobs-prod1 VM was still bionic. This change updates it to jammy and puts them in production
=> [lib-jobs] add lib-jobs-prod1

inventory/all_projects/annotations, inventory/by_cloud/google_cloud
Related to #4745.
The annotations VMs have been powered off but not fully decommissioned. However, they are causing failures in Ansible. This PR comments them out; when we decommission them, we can remove the entire file for the project, along with any references to the group.
This PR also adds a python interpreter definition for the GCP bastion. This should take care of this warning: `Platform openbsd on host bastion-staging.pulcloud.io is using the discovered Python interpreter at /usr/local/bin/python3.9, but future installation of another Python interpreter could change the meaning of that path.`
=> comments out annotations boxes, adds python interpreter for GCP bastion

group_vars/all/vars.yml
Partial fix for #4787.
Removes SSH keys for Favour. We also need to:
=> remove keys for Favour

roles/sidekiq_worker/defaults/main.yml
This fixes pulibrary/pulfalight#1398
I added it as a default since this is the default queue Rails uses to background mail and I never want this to happen again.
=> [Pulfalight] Add the `mailers` queue to Sidekiq.

roles/friends_of_pul/handlers/main.yml
The documentation says we should use restarted, rather than restart, as the state: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html#parameter-state
This caused an intermittent failure in the friends_of_pul playbook (it only failed in cases where the handler was notified by a change made in the id_mapping lineinfile).
=> [friends] correct state in ansible.builtin.service call

group_vars/pas/staging.yml
Mailcatcher runs fine without a version. If we upgrade the gem without re-running the whole role, the mailcatcher service fails when we've specified a version.
There is a role default that sets the mailcatcher location to `/usr/local/bin/mailcatcher`, which works just fine. So, don't specify anything in group vars.
=> remove mailcatcher version from PAS group vars

playbooks/bibdata.yml, roles/passenger/tasks/main.yml
When the Sidekiq role (which depends on the Passenger role downstream), which is limited to worker boxes, is run *after* the bibdata role (which depends on the Passenger role downstream), when it notifies the "restart nginx" handler, it notifies it with the limit to worker boxes last, and applies that limit. If we put the Sidekiq role first, and the bibdata role second, the last notification to the handler is made without the limit, meaning nginx is restarted on the web boxes.
- Use role name in handler, to ensure it does not use handler from another role.
Closes #4824
=> [bibdata] Run sidekiq role first so that handlers are notified last without conditional

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-staging.conf
This PR persists a change that we made live in the nginx configs yesterday, amidst this [DDOS event](https://docs.google.com/document/d/1YhY2JOVoiAF5vTrDoofQZ5HAlYe8sH8Fuzh4vX_Nykw/edit).
This rate limit is still more generous than what we encourage in our robots.txt.  The burst of 80 should still allow human users to use the site (including all js, css, image files) without interruption.
=> [catalog] Lower the rate limit

playbooks/bibdata.yml
- When the deploy_user role starts as limited to worker boxes, the "build authorized keys file" task fails
=> [bibdata] Fix unintended consequences of conditional on sidekiq_worker role

group_vars/bibdata/staging.yml, playbooks/bibdata.yml, roles/bibdata/meta/main.yml, roles/bibdata/molecule/default/converge.yml, roles/bibdata_sqs_poller/meta/main.yml, roles/bibdata_sqs_poller/molecule/default/converge.yml
- Move role dependencies for testing to converge.yml
- List all roles that are actually needed, comment out roles that are currently duplicates
~As a nice side effect, test runs appear to be [much faster on average](https://github.com/pulibrary/princeton_ansible/actions/workflows/molecule_tests.yml?query=branch%3Abibdata_move_roles_to_playbook+is%3Asuccess)~
To verify, switch to fresh staging VMs, run the playbook, deploy bibdata to the fresh staging VMs, and trigger an incremental update on the Alma sandbox.
Performed the above on April 9-10. 2024, and successfully built the boxes and ran jobs on Sidekiq.
=> [bibdata] Move dependencies into playbook to reduce repetition

inventory/by_cloud/google_cloud, inventory/by_environment/production, inventory/by_environment/staging, playbooks/utils/check_os_versions.yml
Partial fix for #3897.
Adds an `obsd` group that sets `doas` for the privilege escalation method for all GCP OpenBSD boxes.
Removes the `annotations` groups from the `staging` and `production` supergroups.
Sets `hosts: all` for the Check OS playbook, so we don't miss strays (not all boxes are included in the three `env` groups - `staging` and `qa` and `production`).
Shows the distro as well as the version in the playbook output.
=> Inventory and OS-discovery improvements

inventory/all_projects/dpul, inventory/all_projects/figgy, inventory/all_projects/lae, inventory/all_projects/pulmap
Closes #4750.
This PR tidies our inventory. It also reflects a lot of work in our VM environment and on our firewall.
We have deleted all DLS VMs running Bionic Beaver, as well as all related firewall rules and objects. Note that OIT will repurpose these IPs, so we may need to update our known_hosts files.
Here's the list of deleted VMs:
- Dpul1 - 128.112.203.160/32
- Dpul2 - 128.112.203.158/32
- dpul-staging1 - 128.112.202.27/32
- dpul-staging2 - - 128.112.204.67/32
- Figgy1 128.112.201.194/32
- Figgy2 128.112.203.9/32
- Figgy3 128.112.200.144/32
- Figgy-Staging1 128.112.202.216/32
- Figgy-Staging2 128.112.200.42/32
- Figgy-Web-Prod-2 (with a DASH!) 128.112.204.63/32
- Figgy-Web-Prod-4 (with a DASH!) 128.112.204.62/32
- lae1 - 128.112.202.137/32
- lael2 - 128.112.203.148/32
- …
=> Decommission DLS Bionic VMs

playbooks/utils/security_theater.yml
we have been using the "library" as an attribute and it needs "Library
Systems" this fixes rapid7s implementation.
closes #4820
=> [rapid7] correct the group attribute

roles/nginxplus/README.md, roles/nginxplus/files/fail2ban/nginx-badbots-filter.conf, roles/nginxplus/files/fail2ban/nginx-badbots-restriction.conf, roles/nginxplus/files/fail2ban/nginx-limit-req.conf, roles/nginxplus/handlers/main.yml, roles/nginxplus/molecule/default/converge.yml, roles/nginxplus/molecule/default/molecule.yml, roles/nginxplus/tasks/main.yml, roles/nginxplus/tasks/prerequisites/install-prerequisites.yml
Related to this [DDOS incident](https://docs.google.com/document/d/1YhY2JOVoiAF5vTrDoofQZ5HAlYe8sH8Fuzh4vX_Nykw/edit).
When an IP address repeatedly makes so many requests to a site that has rate limiting configured that nginx rate limits them several times, fail2ban and ufw will work together to reject all requests from that IP for an hour for all load-balanced resources.
We ran this on both load balancers today, 5 April 2024.
=> Add fail2ban and enable ufw on load balancers

inventory/all_projects/zookeeper
I think the zookeeper inventory hasn't kept pace with the Solr cloud changes.
When we [updated the Solr8 cloud](https://github.com/pulibrary/princeton_ansible/pull/4587/files#diff-a27de0ecaa34c807588fafc5c43509e72fb3261580dbcaba32f1633da341b07c), we changed the staging solr config to look at new zookeeper boxes, but we didn't update the zookeeper inventory.
This might need more cleanup. I cannot SSH to some of the zookeeper prod boxes in the inventory - we may have obsolete boxes listed there too.
=> updates zookeeper inventory, round 1

playbooks/bibdata.yml
I believe running the poller daemon on multiple servers per environment is causing Postgres database locks, because four servers are trying to create the same exact object at the same time.
This PR limits installing the daemon on one machine, but it does not remove it from machines where it is already installed.
See also https://github.com/pulibrary/bibdata/pull/2362
=> [bibdata] Only run the poller daemon on one server per environment

roles/bibdata/tasks/main.yml
We've had continuing difficulties with getting Passenger, Rubygems, Ruby, and Bundler to play nicely with each other.
This is what worked to get the new bibdata boxes into a state where you can just deploy to them and they work, without having to run anything on the command line.
It is not pretty. But it works. For now.
=> [bibdata] Cludge to create consistent working systems with consistent rubygems and bundler

roles/denyhost/vars/main.yml
Affiliated ServiceNow ticket to remove rules from PanOS: TKT0419458
=> [prancible] move Deny001-Deny005 from panOS to AWS denylist

playbooks/utils/remove_rapid7.yml, playbooks/utils/security_theater.yml
the Rapid7 uninstaller fails to clean up after itself. Any subsequent
attempts to reinstall rapid7 on a VM leaves the application systemd
process registered.
Removing the directory allows us to have these conditional step
Crowdstrike is left registered so it is easier to reinstall
closes #4894
=> [security theater] OIT apps

roles/nginxplus/files/conf/http/cdh_prod_prosody.conf, roles/nginxplus/files/conf/http/cdh_prod_shakespeareandco.conf, roles/nginxplus/files/conf/http/cdh_test_shakespeareandco.conf
Closes #4913.
Add proxy timeouts to shxco site configs.
Also removes extra comment from prosody config.
=> [nginxplus] Extend timeouts for Shakespeare and Co sites

playbooks/postfix.yml, roles/postfix/README.md, roles/postfix/tasks/main.yml, roles/postfix/tasks/update_config.yml, roles/postfix/templates/mynetworks.j2, roles/postfix/vars/main.yml
- **template a file instead of copy a file**
- **add empty relay host address**
- **use a template instead of lineinfile module**
- **add pointers on how to add a VM to the list of allowed relays**
closes #4891
=> [postfix] replacement ponyexpr

roles/nodejs/defaults/main.yml, roles/nodejs/tasks/main.yml
We may sometimes want to use npm as our package manager (as for the new static_tables app), and we don't want to install yarn if we don't need it.
=> Make use of yarn for pkg management optional

playbooks/nginxplus.yml
We've been seeing connection failures for both Solr and PostgreSQL, and we're trying to eliminate the ones that have known causes. One known cause is Patch [Mon/Tues]day. The other is load balancer restarts. 
This PR adds a special message for the nginx restart play, which would let us track that known cause more easily.
=> add an easy-to-find message for nginx restarts

roles/static_tables/files/default.conf
Using Vite to build the application has move the root directory we need to serve up to /dist
=> Moved root to /dist for the vite build

group_vars/checkmk/local_check_templates/logrotatecheck.j2, group_vars/checkmk/rule_rails.yml, playbooks/utils/checkmk_add_local_checks.yml
also changed the file name on the server to .sh instead of .j2
fixes #4871
=> Adding bash script for monitoring log rotate

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, roles/passenger/README.md, roles/passenger/templates/nginx.conf.j2
I ran the figgy staging role with and without this variable defined. When not defined, it continues to use the passenger defaults. when defined, it sets the number of processes and warms them.
closes pulibrary/figgy#6398
=> [passenger] Add a variable to set number of passenger processes

group_vars/pdc_discovery/main.yml, group_vars/pdc_discovery/production.yml, group_vars/pdc_discovery/staging.yml, playbooks/pdc_discovery.yml
rename common to main to reflect latest practice
There is no difference in the output:
=> [PDCDisocvery] Factor out the common vars into main

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Connected to https://github.com/pulibrary/static-tables/issues/130
Run successfully on both load balancers.
=> [static_tables] Use marquand-catalogs for catalog path

group_vars/solr8cloud/staging.yml, inventory/all_projects/solr8cloud, roles/nginxplus/files/conf/http/lib-solr8-prod.conf, roles/solrcloud/defaults/main.yml, roles/solrcloud/templates/solr.in.sh.j2
Partial fix for #4858.
We are upgrading the VMs in our Solr8 cluster to run on Ubuntu 22 (Jammy). The default Java on Jammy is Java 17. Back in Java 9, the settings for garbage collection and logging changed.
This [post](https://blog.gceasy.io/2017/10/17/43-gc-logging-flags-removed-in-java-9/) has a great chart of the pre-9 and post-9 settings for gc logging. See also the [openJDK documentation](https://openjdk.org/jeps/158) with examples.
With these settings, Solr8 runs happily on Jammy. We should update the Solr9 cluster to use these settings for consistency and to prepare for the next migration step.
We will build one Jammy Solr8 VM from this branch at a time, add it to the cluster, replicate to it, then decommission an old box. Once we have replaced all VMs in the cluster with Jammy …
=> Run Solr8 on Jammy with Java >9

inventory/all_projects/cdh
Closes #4977.
Updates our inventory so we can maintain and manage these VMs. These are new Jammy VMs.
The `cdh-derrida1` and `cdh-derrida-crawl1` boxes are replacements, so you may see a remote host ID error when you first try to SSH in.
=> adds prod derrida VMs to CDH inventory

roles/nginxplus/files/conf/http/checkmk_prod.conf, roles/nginxplus/files/conf/http/pulcheck_staging.conf
=> Redirects the CheckMK sites

group_vars/solr8cloud/production.yml, group_vars/solr8cloud/staging.yml
This allows us to do two things related to memory troubleshooting:
1. Allows us to run jmap, which is part of these instructions:
https://github.com/pulibrary/pul_solr?tab=readme-ov-file#heap-dump
2. Allows the oom_killer to automatically dump the heap by providing
the jstack command, see
https://solr.apache.org/guide/8_7/jvm-settings.html
I ran this on lib-solr-staging4d today, and confirmed:
* I can still `sudo systemctl restart solr`, and solr still works!
* I can use jmap to create a heap dump of the solr process, after temporarily setting PrivateTmp=false in the systemd service
* The jstack binary is now available and in the path
Helps with https://github.com/pulibrary/orangelight/issues/3601
=> [solr8] Install the JDK, not just the JRE

roles/nginxplus/files/conf/http/dev/nomad.conf
It submits JSON sometimes, which app protect doesn't like.
=> [Nomad] Disable app protect for nomad.

group_vars/all/vars.yml
These are the public keys for the GitHub user account for lm4677 (welcome!)
=> Adding the public keys for user 20LM22

roles/nginxplus/files/conf/http/cdh_prod_prodigy.conf, roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
I added port 8080 to the upstream declaration, because the service is running on port 8080 - this is an ASGI application, so we can't run it through nginx/passenger. 
I'm getting a circular redirect when I try to access the public url for the test site. The block I removed looks like the culprit to me, but I did test this on the active load balancer and reloaded nginx but it didn't solve the problem.
=> cdh-test-prodigy updates: proxy port 8080 on upstream; remove circular redirect

roles/nginxplus/files/conf/http/dev/nomad.conf
Pulled from
https://developer.hashicorp.com/nomad/tutorials/manage-clusters/reverse-proxy-ui
This fixes log streaming and exec from the UI when behind a load balancer.
=> [Nomad] Update nomad reverse proxy configuration.

group_vars/all/vars.yml
this adds denzil to library users and ops team
=> [prancible] add Denzil Keys

group_vars/all/vars.yml, group_vars/allsearch_api/common.yml, group_vars/allsearch_api/production.yml, group_vars/allsearch_api/staging.yml, group_vars/dpul/production.yml, group_vars/dpul/production_solr.yml, group_vars/dpul/staging.yml, group_vars/dpul/staging_solr.yml, group_vars/orangelight/common.yml, group_vars/orangelight/production.yml, group_vars/orangelight/production_solr.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/qa_solr.yml, group_vars/orangelight/staging.yml, group_vars/orangelight/staging_solr.yml, group_vars/pulfalight/production.yml, group_vars/pulfalight/production_solr.yml, group_vars/pulfalight/qa.yml, group_vars/pulfalight/qa_solr.yml, group_vars/pulfalight/staging.yml, group_vars/pulfalight/staging_solr.yml, group_vars/pulmap/production.yml, group_vars/pulmap/production_solr.yml, group_vars/pulmap/staging.yml, group_vars/pulmap/staging_solr.yml, playbooks/allsearch_api.yml, playbooks/dpul.yml, playbooks/orangelight.yml, playbooks/pulfalight.yml, playbooks/pulmap.yml
Allsearch-api uses the Solr of certain apps directly (catalog, dpul, pulfalight, maps), so we need to find a way to keep these in sync. 
Since they are all rails apps, we don't want allsearch-api to use their entire config files, because there are conflicting variables, so splitting solr into its own config files by environment.
Connected to #5013
=> I5013 share solr vars

roles/postfix/vars/main.yml
Bibdata should not be sending emails, remove from allow-list
Connected to https://github.com/pulibrary/bibdata/issues/2404 and https://github.com/pulibrary/bibdata/pull/2406
=> [bibdata-postfix] Bibdata should not be sending emails, remove from allow-list

playbooks/monit.yml, roles/monit/README.md, roles/monit/defaults/main.yml, roles/monit/handlers/main.yml, roles/monit/meta/main.yml, roles/monit/tasks/main.yml, roles/monit/templates/apache2_monit.conf.j2, roles/monit/tests/inventory, roles/monit/tests/test.yml, roles/monit/vars/main.yml
This role will install monit on an endpoint. It will monitor the apache2
service and restart it when it fails
related to #4719
=> [globus] install monit

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf
Closes #5069 
I ran this on both load balancers today (25 June)
=> [loadbalancer + allsearch-api] set the X-Real-IP header to prevent logs from being filtered out

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf, roles/nginxplus/files/conf/http/templates/errors-in-json-format.conf, roles/nginxplus/files/error.json, roles/nginxplus/files/forbidden.json, roles/nginxplus/files/ratelimit.json, roles/nginxplus/files/too_large.json, roles/nginxplus/tasks/localhost.yml
This allows 400 and 500 JSON responses through from the application, and returns other errors in JSON format, rather than the standard "Something went wrong" html page.
Closes #4396
For background information on why we'd like to offer JSON errors, see [this ADR in allsearch_api](https://github.com/pulibrary/allsearch_api/blob/main/architecture-decisions/001_error_output.md)
I ran this on both load balancers today.
=> [allsearch-api] Error statuses in JSON format

roles/nginxplus/files/conf/http/cdh_prod_shakespeareandco.conf
Closes #1340.
Updates the nginx configuration for the production Shakespeare & Co. site to use the custom CDH error page instead of the old "prod-maintenance" page.
=> [nginx] use CDH error page for prod shakespeare and co

playbooks/utils/firewall_update.yml
Closes #4892.
We have cleaned up the data in the firewall enough now that we can pull exact IP addresses (with `/32` at the end). This change will find the exact IP and return rules for it.
Still fails if the FQDN is not represented in the firewall at all. We can make a separate ticket for that if we decide to handle it.
=> Pull exact IPs in the firewall playbook

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Closes #5089.
Many of the org-wide issues templates make no sense in this repo. This PR includes the most relevant templates for issues in prancible.
=> Override the default org-wide issue templates

bin/first-time-setup.sh
it fails because we did not have a ruby plugin and resorts to using the
macOS cooties
This fixes that
closes #5094
=> [prancible] fix bin setup 

roles/nginxplus/files/conf/http/cdh_prod_prodigy.conf, roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
This switches the nginxplus config for cdh-prodigy and cdh-test-prodigy from proxying port 8080 to port 80
I discovered that I need to serve out content alongside the application, so I'm setting up nginx on the VMs to proxy the 8080 port and serve out static content.
=> Proxy prodigy servers on port 80 instead of 8080

roles/nginxplus/files/conf/http/templates/pudl_proxy_pass.conf
Closes #4566.
Currently PUDL URLs with `viewer.php` return errors. We should be able to redirect them. Doesn't work yet, but hoping to figure this out soon.
=> first attempt to redirect PUDL viewer URLs

roles/monit/defaults/main.yml, roles/monit/templates/monit.conf.j2
we will monitor the apache2 error logs. When monit matches on apache2
was restarted it will also restart globus
related to #5061
=> [globus] another restart for globus

group_vars/tigerdata/common.yml
Resolves https://github.com/pulibrary/tiger-data-app/issues/776
=> Ensuring that tiger-data-app utilizes NodeJS 18.14.0 releases

group_vars/nfsserver/production.yml
merged the last [PR](https://github.com/pulibrary/princeton_ansible/pull/5134) too hastily. This allows the cdh-web{3,4} vms access
to the shares.
=> [cdh] access to nfs mounts

roles/towerdeploy/defaults/main.yml
Closes #5137.
Update to Capistrano 3.18 to match the recent [update to orcid_princeton](https://github.com/pulibrary/orcid_princeton/pull/165/commits/3952fd792eaa38bee0c990ee34af01e6380c7535).
Should be backwards-compatible.
=> updates capistrano version for towerdeploy

inventory/by_environment/production, inventory/by_environment/staging, inventory/by_team/dacs
The locator is deprecated and was mostly removed a couple days ago. This just removes it from the inventory.
=> Remove locator from inventory

playbooks/utils/checkmk_agent.yml
Up to now host names in CheckMK have reflected our inventory host names, including the `.princeton.edu` extension. However, the VMs in vSphere/VMware do not have the `.princeton.edu` extension. This discrepancy has interfered with the "piggybacking" functionality which combines data gathered directly from the agent on a VM with data gathered from vSphere. 
Instead of creating a regex rule in CheckMK to map the host names to the vSphere names, this PR would strip the `.princeton.edu` (which is not all that useful) from the host names. I've run this for the ORCID staging project, we can test whether it enables piggybacking or not.
=> [CheckMK] strip the '.princeton.edu' from inventory for checkmk host names

.github/ISSUE_TEMPLATE/new_vm.md
Closes #5128.
Creates a template for requesting new VMs. This is not meant to be a required form. It's more of a place to gather whatever information the requester has about a request for new resources.
Builds on [existing documentation](https://github.com/pulibrary/pul-it-handbook/blob/main/services/new_vms_for_devs.md).
=> adds a template for requesting VMs

inventory/all_projects/openbooks
As part of auditing our response to a recent CVE, we discovered that updates were not reaching the openbooks-prod1 VM. It turned out the line had been commented out in our inventory.
This PR restores openbooks-prod1 to the inventory so it will get updates along with our other servers.
=> add openbooks-prod1 back into inventory

playbooks/utils/clean_up_alma_dir.yml
Closes [bibdata issue 2401.](https://github.com/pulibrary/bibdata/issues/2401) and [lib_jobs issue 795](https://github.com/pulibrary/lib_jobs/issues/795)
This playbook should find, list, and delete all files in the /alma directories older than  limit we set. For testing purposes, setting the limit to 20 weeks and running against staging.
=> Adds playbook to delete old files from /alma directory

.github/ISSUE_TEMPLATE/bug_report.md
Updates the 'bug report' template by adding a section explicitly calling for errors from log files or STDOUT/STDERR.
=> Specifically request error messages for bug reports, with hint

playbooks/checkmk.yml
the playbook was failing with the absence of the post_task. We also add
a comment on the playbook on the need to run `ansible-galaxy collection install checkmk.general --force` if the playbook fails to run in a new environment
closes #5161
=> [checkmk] enable checkmk playbook to run

playbooks/utils/clean_up_alma_dir.yml
With this PR, we see a single list of the files to be deleted in each directory, instead of a section for each file with connection details, etc.
We also tested the playbook in Tower, and it seems to be working well.
Partial fix for https://github.com/pulibrary/princeton_ansible/issues/5178
=> Tidy up alma cleanup playbook

playbooks/utils/checkmk_agent.yml
For VMs in our private IP space, CheckMK needs an IP to fully monitor those VMs.
This PR uses a pre-existing variable in the CheckMK agent role to populate the IP from Ansible facts when adding hosts to CheckMK.
It also removes a debug task we used to confirm the regex that strips the `.princeton.edu` or `.lib.princeton.edu` from inventory names for CheckMK. We've tested that functionality and it works well. No need to debug forever.
=> Includes IP from Ansible facts when adding hosts to CheckMK

roles/nginxplus/files/conf/http/videoreserves_prod.conf
Previously, we only allowed requests to videoreserves-prod.princeton.edu if you were on the Princeton network.  Other users needed to access the site via a library.princeton.edu proxy pass rule.
We are going to get rid of that proxy pass rule as part of the website migration, so we're telling the load balancer to allow traffic to this domain.
Closes #5189 
I ran this on the prod load balancer today, 22 July 2024
=> [video_reserves] Allow all traffic to videoreserves-prod.princeton.edu, not just princeton network

playbooks/utils/vm_reboot.yml
As a developer, I want to be able to reboot a VM as needed. This PR will add that capability in Tower.
We can't test in Tower until a skeleton version of the playbook has been merged to the `main` branch, so we will merge this early and work out the details in another branch.
=> Adds a draft playbook to reboot a single VM

playbooks/utils/vm_reboot.yml
Follows up on #5176.
Once this is merged, Tower users can view VM details (host/datacenter and storage locations) for any VM in our inventory. By default the Tower template just views details, but a survey gives you the option of rebooting the VM.
So far it only works in the staging environment, but the steps to enable it in production are on Tower, not in this repo.
=> Supports rebooting a VM from Tower

playbooks/utils/vSphere_audit.yml
This playbook returns information about:
- templates in vSphere
- hosts in vSphere
- datastores in vSphere
Eventually, this will support creating VMs from Tower.
For now, the playbook only gathers information. We can add more active tasks to it in a branch once this one is merged to main.
=> Minimalist playbook to view info from vSphere

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Instead, do a 301 Moved Permanently redirect
Helps with #5150, I ran it on both load balancers today (30 July)
=> [libwww] Don't proxy pass library-staging to repec-staging

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
Instead, do a 301 Moved Permanently redirect
This is the prod version of #5213 , I'm running it on the prod load balancer now.
closes #5150
=> [libwww] Don't proxy pass library-prod to repec-prod

roles/nginxplus/files/conf/http/catalog-staging.conf
The catalog application servers are already able to handle requests for gzipped assets, which is great, because that can make things much faster for users.
However, before this commit, the load balancer was causing us to lose this feature. Fortunately, telling the load balancer to use HTTP 1.1 (instead of the default 1.0) allows the content negotiation to still happen.
Helps with pulibrary/orangelight#4054
I ran this on the prod load balancers, and confirmed that when I go to catalog-staging.princeton.edu, lighthouse no longer complains about "Enable text compression"
=> [orangelight-staging] send compressed assets if available and requested by the user's browser

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-qa.conf
This extends #5218 to the production and qa environments.
The catalog application servers are already able to handle requests for gzipped assets, which is great, because that can make things much faster for users.
However, before this commit, the load balancer was causing us to lose this feature. Fortunately, telling the load balancer to use HTTP 1.1 (instead of the default 1.0) allows the content negotiation to still happen.
Helps with pulibrary/orangelight#4054
I ran this on the prod load balancer today (5 August, 2024)
=> [orangelight] send compressed assets if available and requested by the user's browser: qa and prod

tower_ees/execution-environment.yml
Update to #4754.
Follows up on #4782.
We need to rebuild the standard Tower Execution Environment (EE) and include the checkmk.general collection in it. This PR adds the collection to the build instruction file for our standard EE.
=> adds checkmk to the roles in our standard EE

roles/nginxplus/files/conf/http/pdc-discovery_prod.conf
instead of using our loadbalancer to determine the health of the
application. Let's use the application to determine its health
related to #5113
Co-authored-by: James R. Griffin III <jrgriffiniii@users.noreply.github.com>
Co-authored-by: Kate Lynch <kelynch@users.noreply.github.com>
=> [pdc-discovery] health check

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
I've learned that web content for course in canvas outside of ARES exists that points at the library.princeton.edu to view reserves content. Putting in a redirect just for the clip.php file as opposed to bring all the proxy rules back. Canvas folks tell me it's not practical for them to update URLs in this part of the system.
=> Add redirect for clip.php file.

roles/nginxplus/files/conf/http/eal_prod.conf
Previously, users could access ealapps from outside Princeton via a library.princeton.edu proxy_pass rule.
With the website migration, this proxy_pass rule will no longer exist, so we need to make eal.lib.princeton.edu itself serve traffic from non-princeton IPs.
Thanks to Max for finding this.
I ran this on both prod load balancers today, and confirmed that I can access https://eal.lib.princeton.edu/EALJ/ without the VPN.
=> [ealapps] Serve ealapps via load balancer to non-princeton IPs

inventory/by_environment/production, inventory/by_environment/staging
- I cannot run the pulsys playbook on this server without adding it to the production inventory.
=> Add eal_production to inventory by environment

roles/nginxplus/files/conf/http/cdh_prod_prodigy.conf, roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
as a short-term fix, we want to only run prodigy from one server because the "sticky" option isn't working properly and it's resulting in our students getting the same tasks twice and total counts to be inconsistent
the "sticky" option seems like it should solve this but it's not working based on the behavior we're seeing
=> Disable second server for cdh prodigy load balancer config

group_vars/friends_of_pul/production.yml, group_vars/friends_of_pul/staging.yml
Prior to this change, the friends sites displayed no CSS, since the CSS links included the old domain names.
I ran this on staging and prod.
=> [friends] update $base_url for new domain names

inventory/by_environment/production, inventory/by_environment/staging
Today I ran the `utils/checkmk_agent.yml` playbook and got this set of errors:
```
[WARNING]:  * Failed to parse /Users/alicia/projects/princeton_ansible/inventory/by_environment/production with ini plugin:
/Users/alicia/projects/princeton_ansible/inventory/by_environment/production:34: Section [production:children] includes undefined
group: mediaflux_production
[WARNING]:  * Failed to parse /Users/alicia/projects/princeton_ansible/inventory/by_environment/production with yaml plugin: We
were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 2 (char 1)
Syntax Error while loading YAML.   did not find expected <document start>  The error appears to be in
'/Users/alicia/projects/princeton_ansible/inventory/by_environment/produc …
```
=> Fix inventory to avoid error messages

playbooks/utils/veeam_backup_list.yml
We currently manually maintain a spreadsheet of which VMs are backed up on which days. However, the actual backups are done based on tags in vSphere. So we should be able to pull this information from vSphere at any time.
As usual for automation with vSphere or the firewall, we need a minimal version of the playbook merged to main before we can test more functionality in Ansible Tower.
=> Adds skeleton playbook for VEEAM backup query

roles/nginxplus/files/conf/http/mflux_ci.conf
the java server is not handling the headers like we expect
lets forward the client headers to start
=> [mflux] add forwarding headers

inventory/all_projects/lockers_and_study_spaces, roles/nginxplus/files/conf/http/lockers-and-study-spaces-prod.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf
we add two new vms back up to the loadbalancer
closes #5263
=> [lockers] add two vms back

group_vars/nomad_clients.yml, group_vars/nomad_cluster.yml, inventory/all_projects/nomad, roles/ansible-nomad/defaults/main.yml, roles/ansible-nomad/tasks/main.yml, roles/ansible-nomad/vars/RedHat.yml, roles/common/tasks/main.yml, roles/pul_nomad/molecule/default/group_vars/nomad_clients.yml, roles/pul_nomad/molecule/default/group_vars/nomad_cluster.yml, roles/pul_nomad/molecule/default/molecule.yml, roles/pul_nomad/molecule/default/prepare.yml, roles/pul_nomad/molecule/default/verify.yml, roles/pul_nomad/tasks/main.yml
This is a draft to try out installing consul/nomad servers and clients with Rocky linux alongside Debian, so we can use Podman clients. cc @kayiwa 
There are some local modifications to the nomad role here. I'm trying to get them pushed upstream here: https://github.com/ansible-community/ansible-nomad/pull/197
=> [Nomad] Nomad w/ Podman & Rocky Linux

roles/nginxplus/files/conf/http/lib-sc-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
This site has been migrated to OIT WDS, so there is no need for it to be public outside our network.
This blocks both versions from off-campus:
* https://lib-sc-prod.princeton.edu/
* https://library-migrated.lib.princeton.edu/special-collections
Based on #5270
=> [special collections] block access outside the princeton network

playbooks/utils/veeam_backup_list.yml
This playbook returns a summary of the tags we have in vSphere, how many VMs are being backed up for each tag, and the total disk size being backed up for each tag.
May need to be updated for use in production, where we have at least one tag we may want to ignore.
This playbook contains some good data-wrangling task examples.
=> Refines playbook to view vSphere data on Veeam backups

playbooks/utils/vm_reboot.yml
This playbook can now be run in Tower in staging or in production.
This PR clarifies a task name (you may or may not be rebooting the VM) and adds a reminder about the format of our vCenter host names.
=> Updates the "new kicker" playbook

roles/mflux/tasks/main.yml
If fd is needed, it should be reintroduced in a separate pr.
=> [TigerData] Remove fd because it cannot be installed on rocky linux

roles/common/handlers/main.yml, roles/common/tasks/main.yml, roles/common/templates/logrotate_timer.j2
Closes #5256.
Adds an override to all our servers for the systemd logrotate timer. With the default settings in this template, systemd will check the logs to see if they are large enough to warrant rotation (as defined by files in `/etc/logrotate.d`):
- 20 seconds after a service is restarted
- every 10 minutes thereafter
With this setting, even with large amounts of data going to a log, we should retain enough disk space for the service to continue uninterrupted.
=> adds template and task to override the default systemd logrotate timer

playbooks/utils/common_only.yml
The `common` role sometimes fails when trying to install new tools or update packages. This PR creates a playbook that just runs the common role, so we can run it across our infrastructure for quicker and easier maintenance.
Long-term, it would be great to run this playbook when we build new infrastructure, and on existing infrastructure on a regular schedule. Then we could remove the `common` role from most of our playbooks.
=> Adds a maintenance playbook that just runs the 'common' role

roles/nginxplus/files/conf/http/cdh_prod_web.conf
This change makes the new version of the CDH website live and keeps the old version running at cdh-beta in case we need to reference the old site during the transition period.
=> Swap cdh web production and pre-production servers

group_vars/vsphere/production.yml, group_vars/vsphere/staging.yml, playbooks/utils/replace_vm_host.yml
The playbook now runs from Tower in either production or staging (there is a Tower Template for each environment for now, because the network names are not consistent across environments). It shows VM disk usage correctly, and it puts the replacement VM into the same folder in vSphere that the old VM was in.
I've removed the tags for now. They were useful for testing, but I think they might be tricky to manage in the long term. We could reinstate them and have multiple Tower Templates build off the same playbook with different tags . . . but let's talk about the use cases. 
When this gets merged, we should update the Tower templates so they no longer ask for a source control branch name.
=> Polishing up the build-a-vm playbook

playbooks/utils/vm_reboot.yml
Now that we know how to gather data from vSphere about CPU, memory, disk space, and more, we can enhance the view provided by our view-details-and-reboot-if-needed playbook. 
The task now returns the host (with note about the location), MAC address, CPU, memory, storage amount, and storage location.
=> Give more information about VMs in playbook output

group_vars/orangelight/qa.yml
I ran this on qa, followed by `ansible orangelight_qa -m shell -a "sudo systemctl daemon-reload && sudo systemctl restart mailcatcher" -u pulsys`
I then confirmed that mailcatcher was running on all of them with `ansible orangelight_qa -m shell -a "sudo systemctl status mailcatcher" -u pulsys`
Closes #5333
=> [orangelight] update mailcatcher path for qa

playbooks/utils/veeam_backup_list.yml
We add tags to VMs we want to back up with VEEAM. Each tag reflects the location and OS of the VM plus which day of the week it gets backed up. Best practice is to add a tag for "don't back this VM up" to any VMs we do not want to back up with VEEAM. This way we know for sure that the lack of a backup is intentional, and not an oversight.
This PR expands the VEEAM backup playbook to report a list of VMs that have no tags, so we can audit vSphere, make decisions about which VMs to back up, and keep the tags up to date.
=> Update the veeam backups to show a list of VMs with no tags

playbooks/os_updates.yml
Closes #5168.
Since the `yum` module does not have a `clean` option, uses a `command` task instead.
We ran into a problem trying to run this on Tower when the RHEL boxes did get updated - because the Tower job rebooted the VM on which the Tower job was running . . . So this PR now reboots only RH-family VMs that are NOT Tower-related, and sends a slack alert to the ops team to reboot the Ansible machines by hand.
=> implements 'clean' step for yum repos

group_vars/nfsserver/staging.yml
we added the hosts to the exports without mount paths
neglected to add this mounts
related to #5299
=> [cdh] add htr machines

roles/nginxplus/files/conf/http/dev/cdh_test_htr.conf
This application includes an ASGI component, which is proxied by the nginx on our cdh-test-htr VMs. I think these are the configuration changes that are needed to allow nginx to proxy the websockets / ASGI.
=> Update cdh_test_htr config : add configurations for proxying websockets

group_vars/tigerdata/production.yml, group_vars/tigerdata/qa.yml, group_vars/tigerdata/staging.yml
https://pulmirror.princeton.edu/mirror/node/dist/latest-v20.x/ does not support any releases in the 20.17 series (please see https://github.com/pulibrary/princeton_ansible/pull/5339 and https://github.com/pulibrary/tigerdata-app/pull/923 for reference)
=> Downgrading NodeJS to 20.15.1 for TigerData

group_vars/all/vars.yml
Adding CDH postdoc @cmroughan to list of CDH keys - she's working with me on the HTR project and it will be helpful for her to have ssh access to the test-htr VMs.
=> Add @cmroughan to list of CDH github keys

group_vars/bibdata/staging.yml, roles/passenger/defaults/main.yml, roles/passenger/templates/passenger.j2
[Bibdata-staging]Set bibdata-staging.lib to use dev load balancer by providing real IP variable in group_vars/bibdata/staging.yml
[Passenger]templatize dev and prod load balancer IPs make default to be prod load balance IPs. see: roles/passenger/defaults/main.yml Update roles/passenger/templates/passenger.j2
=> [Bibdata-staging][Passenger] Set bibdata-staging.lib to use dev load balancer;templatize dev and prod load balancer IPs

inventory/all_projects/cdh
this enables the cdh users to have access to the dev loadbalancers
alphabetize the names for production
=> [cdh] add dev loadbalancers

playbooks/utils/expand_disk.yml
Playbook successfully expands disk. Need a way to handle disks that are already expanded.
```
TASK [view the logical volume] ************************************************************************************************************************************
ok: [sandbox-bd4538.lib.princeton.edu] => {
"logical_volume": {
"changed": true,
"cmd": [
"sudo",
"lvdisplay"
],
"delta": "0:00:00.061315",
"end": "2024-09-16 15:56:45.772973",
"failed": false,
"msg": "",
"rc": 0,
"start": "2024-09-16 15:56:45.711658",
"stderr": "",
"stderr_lines": [],
"stdout": "  --- Logical volume ---\n  LV Path                /dev/ubuntu-vg/ubuntu-lv\n  LV Name                ubuntu-lv\n  VG Name                ubuntu-vg\n  LV UUID                VBfBWL-Uc6c-x54u-xmYF-16kH-NfbB-uMu9Ft\n  LV Write Access …
```
=> Expand disk

group_vars/tigerdata/production.yml
This has been applied to production.  See https://tigerdata-prod.princeton.edu/mediaflux_info
fixes https://github.com/pulibrary/tigerdata-app/issues/927
=> [TIGERDATA] Making the production mediaflux the production default

roles/nginxplus/files/conf/http/static_prod.conf, roles/nginxplus/files/conf/http/templates/libweb2-redirects.conf
Partial fix for #5294. 
Adds a redirect for the old libweb2 URL.
Adds nginxplus config for the new site within libstatic.
Once this is confirmed as working, we can decommission the old infrastructure.
=> Migrating libweb2 to the static site

roles/postfix/defaults/main.yml, roles/postfix/meta/main.yml, roles/postfix/tasks/main.yml
~~in order for certbot to renew we will need a webserver to run on the
endpoint for .acme files~~
Closes #5023
=> [ponyexpress] enable TLS

roles/pul_nomad/tasks/main.yml
For some reason Nomad's using Consul's registered agent token to remove services, so failed deployments weren't going away. This fixes it.
=> [Nomad] Grant node tokens the proper ACLs

roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
Updating the nginx config to allow large headers for the cdh prodigy test server.
---
=> [cdh-prodigy-test] Update nginx config to allow large headers

group_vars/geaccirc/common.yml, roles/geaccirc/tasks/main.yml
Part of https://github.com/pulibrary/geaccirc/issues/59
Updates bundler version
=> [Geaccirc] Updates bundler version

group_vars/video_reserves/production.yml, group_vars/video_reserves/staging.yml, roles/video_reserves/meta/main.yml, roles/video_reserves/tasks/main.yml, roles/video_reserves/templates/config.tpl.j2
We needed a database for the administrative interface of this application. Now that we have removed this interface, we no longer need a database or mysql dependency.
Helps with PrincetonUniversityLibrary/video_reserves#81
I ran this on staging today, 30 September.
=> [videoreserves] Remove database

inventory/by_cloud/google_cloud, inventory/by_environment/production, inventory/by_environment/staging, playbooks/utils/security_theater.yml
add keys for BigFix (needed for RHEL based boxes)
Install RHEL for BigFix and Rapid7.
We do not have the keys for CrowdStrike to complete install without
manual intervention.
related to #5347 
=> [prancible] BigFix and Rapid7

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-qa.conf, roles/nginxplus/files/conf/http/catalog-staging.conf
Without this, login and forms were failing in the catalog.  In the logs we saw: HTTP Origin header (https://catalog-staging.princeton.edu) didn't match request.base_url (http://catalog-staging.princeton.edu)
=> [orangelight] Add X-Forwarded-Proto https to the catalog load balancer config

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf, roles/nginxplus/files/conf/http/approvals_prod.conf, roles/nginxplus/files/conf/http/approvals_staging.conf, roles/nginxplus/files/conf/http/bibdata_prod.conf, roles/nginxplus/files/conf/http/bibdata_qa.conf, roles/nginxplus/files/conf/http/dev/bibdata_staging.conf, roles/nginxplus/files/conf/http/dss-prod.conf, roles/nginxplus/files/conf/http/dss-staging.conf, roles/nginxplus/files/conf/http/geaccirc.conf, roles/nginxplus/files/conf/http/geaccirc_staging.conf, roles/nginxplus/files/conf/http/lib-jobs-prod.conf, roles/nginxplus/files/conf/http/lib-jobs-staging.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-prod.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf
closes #5403
Add proxy_set_header X-Forwarded-Proto https; in the dacs nginx conf files
to fix `HTTP Origin header (https://repec-prod.princeton.edu) didn't match request.base_url (http://repec-prod.princeton.edu)`
=> [#5403] Add proxy_set_header X-Forwarded-Proto https; in the dacs nginx conf files

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml
the production and qa servers were populated with the wrong real_ip
this fix adds them to the passenger nginx config
=> [bibdata] add loadbalancers

roles/passenger/defaults/main.yml
We still don't understand why, but the dev/staging IPs were getting written to the production config by mistake in bibdata. Making this clearer for Future Us.
=> Comment out the dev/staging IPs in the passenger role

inventory/all_projects/abid
Updates inventory to reflect the migration of the abid servers to private IPs, the .lib domain, and the staging loadbalancer.
=> Update abid-staging2 inventory entry - it's now in the .lib domain

roles/pul_nomad/files/dnsmasq-11-podman.conf, roles/pul_nomad/files/dnsmasq.conf, roles/pul_nomad/tasks/main.yml
DNSMasq on the hosts has to listen to everything but the LAN interface, so it can resolve queries coming from the podman interface.
=> [Nomad] Update DNS to allow podman containers to use Consul DNS.

roles/nginxplus/files/conf/http/catalog-qa.conf
Something is broken with passenger on catalog-qa1, and the health checks are filling up the disk with errors quickly
=> [orangelight] Remove catalog-qa1 from the load balancer

playbooks/utils/checkmk_add_local_checks.yml, playbooks/utils/checkmk_add_rule.yml, playbooks/utils/checkmk_agent.yml
When we ran the playbooks to add local checks recently, we noticed that the documentation in the playbooks themselves was mostly copy-pasta.
This PR clarifies the docs in the three CheckMK playbooks. It also changes the `hosts` line for all three, so they will only run in staging by default.
=> Update docs in CheckMK playbooks

roles/nginxplus/files/conf/http/dev/gitlab_staging.conf
With app_protect enabled, this page never loads because the WAF blocks one of the graphql responses: https://gitlab-staging.lib.princeton.edu/js7389/jane-test
=> [gitlab] Turn off WAF for now in staging

playbooks/utils/replace_vm_host.yml
Closes #5423.
The basic requirements are met in this branch - see https://ansible-tower.princeton.edu/#/jobs/playbook/7184/output for a run in Tower.  We updated the Tower template survey about which network to put the new VM on - it's not required and there's no default, so if you do nothing, your new VM comes up in the same network as your old VM. 
We could make this even better by updating the `Print out relevant details of old VM` and `Print out relevant details of new VM` tasks to include a line about which network they were/are on.
=> Preserves the network when replacing a VM

roles/nginxplus/files/conf/http/slavery-staging.conf
I ran this on both load balancer machines.  Before this PR, trying to go to https://slavery-staging.princeton.edu/ just gave the "Something went wrong"
=> [PAS] let the load balancer know that the app server is on the .lib network

group_vars/recap/common.yml, group_vars/recap/production.yml, group_vars/recap/staging.yml
Previously, the playbook was installing php 8.3 but php-8.1-gd, so when composer tried to check for the gd extension from PHP 8.3, it failed
Closes https://github.com/pulibrary/recap/issues/269
=> [recap] Set prod php_version to 8.3

playbooks/utils/replace_vm_host.yml
Up until now, the name of the private network was different in our vSphere prod and vSphere staging environments. @jkazmier-PUL updated vSphere so the name is the same in both envs, and it also matches OIT's designation. 
This PR updates the name of the network in the replace-a-vm playbook.
It also adds the network to the output comparing the old VM to its replacement.
=> updates vSphere name of private network; prod & staging now match

playbooks/utils/replace_vm_host.yml
The recently added diagnostic output that shows the network was failing because we were relying on a default setting for VMs in the public network.
This PR sets a network explicitly for both possible cases (public network and private network). It also removes the default settings for clarity.
=> fix broken replace-a-vm playbook

tower_ees/security-tools-ee.yml
Creates a new EE for the security playbook.
Installs the crowdstrike.falcon collection and necessary tools. 
Omits some other collections we don't need for that playbook.
=> adds an EE with the CrowdStrike collection

group_vars/all/vars.yml
add new devs to get pulsys user access
=> [cdh] devs added

roles/pul_nomad/files/dnsmasq.conf
It's unnecessary, and things break if on boot up the interface doesn't exist yet.
The specific breakage is that Consul queries don't work with this option after a reboot (like from patch monday/tuesday), until you reboot `dnsmasq`.
=> [Nomad] Don't bind interfaces for dnsmasq.

roles/nginxplus/files/conf/http/pdc-describe_prod.conf
Removes `pdc-describe-prod2` from the load balancer so that it stops taking new jobs and lets the `prod1` and `prod3` take care of new jobs.
See https://github.com/pulibrary/pdc_describe/issues/1983
=> Removed pdc-describe-prod2 from the load balancer

group_vars/nomad/dpulc/staging.yml
leave solr_url for now, it won't be used when we deploy the new code and
we can remove it after
refs pulibrary/dpul-collections#104
=> [dpul-collections] Add solr base url environment variable

roles/postfix/vars/main.yml
this adds all the production vms from cdh to our MTA allow list
closes #5307
=> [postfix] allow cdh vms

roles/nginxplus/files/conf/http/oawaiver-prod.conf, roles/nginxplus/files/conf/http/oawaiver-staging.conf
fixes #5108
It did mark OAWAIVER as unhealthy when I deployed https://github.com/pulibrary/oawaiver/pull/216
And back to healthy when I deployed main:
=> [NGINXPLUS] Updating oawaiver to point at health.json for health check

roles/nginxplus/files/conf/http/bibdata_prod.conf, roles/nginxplus/files/conf/http/bibdata_qa.conf, roles/nginxplus/files/conf/http/dev/bibdata_staging.conf
Checked against [bibdata branch intentionally breaking configuration](https://github.com/pulibrary/bibdata/compare/main...health-monitor-fail) and it successfully did not serve the broken server
Successfully run on all load balancers - 2 dev, 2 prod
=> [bibdata] add health.json for health check uri

roles/nginxplus/files/conf/http/lib-jobs-prod.conf, roles/nginxplus/files/conf/http/lib-jobs-staging.conf
Deploying bad branch to staging leads nginx to serve only the good branch
Staging version run on production load balancer - not run with production change against load balancer yet.
Closes #5107
=> [lib_jobs] Add health checks against health endpoint

roles/nginxplus/files/conf/http/pdc-describe_prod.conf
Re-adds PDC Describe server 2 back to the load balancer so that it starts serving web requests again.
We had removed it on https://github.com/pulibrary/princeton_ansible/pull/5491 because we wanted to prevent it from taking more background jobs, but now that the Sidekiq queue on that server has been cleared it is safe to add the server back to the load balancer.
Closes https://github.com/pulibrary/pdc_describe/issues/1983
=> [PDC_DESCRIBE] Adds server back to the load balancer

playbooks/utils/vm_reboot.yml
Sometimes a VM gets into a weird state (mostly this seems to happen to Windows VMs) and using the `reboot guest OS` option does not work.
This PR offers two new options for interacting with VMs:
- power off, for a VM we don't need any more
- restart, which is the equivalent of powering a VM off and then on again
We need to update the survey on the Tower template to include these two options and make it clear that `restart` is only for stuck VMs.
Also alphabetizes the fields we pull from vSphere and includes the IP of the VM in the output.
=> Add options for managing VMs

playbooks/utils/replace_vm_host.yml
Because of [this bug](https://github.com/ansible-collections/community.vmware/issues/2124), we can't bring up a new VM with a custom MAC address. But we were able to streamline the replace-a-vm playbook a bit.
Also adds more debugging output to help when things go wrong.
=> Streamline vm replace

roles/nginxplus/templates/etc_nginx.conf.j2
our waf is currently not logging. This will enable logs to be written
under the app_protect directory
addresses #5565
=> [nginxplus] enable waf logging

roles/nginxplus/files/conf/http/dev/gitlab_staging.conf, roles/nginxplus/files/conf/http/gitlab_prod.conf
Related to #5561.
Production gitlab was complaining about fetching files. Compared to staging (which was fine) we discovered that we had inconsistent settings for the WAF.
=> turn app protect off and WAF logging on for Future Us on gitlab servers

roles/common/tasks/vector.yml
Closes #5529 
Ensures vector will always be enabled on reboots and starts after it is installed.
Tested on Ubuntu. 
Not tested on Redhat.
=> Add task to start and enable vector

.github/workflows/deny_host_check.yml, roles/denyhost/checks/valid_ips.t
We accidentally blocked ourselves at the firewall level in #5582 (fixed in #5583).  This adds a check to CI to alert us if we're about to do that again.
=> Add a check to make sure we don't block ourselves using the denylist

roles/nginxplus/files/conf/http/catalog-prod.conf
We observed a pattern:
1. While we had heavy bot traffic, the healthcheck would fail or timeout when the load balancer contacted it
2. In the nginx dashboard, we saw that these healthcecks would cause the VM to be taken out of the rotation.
3. The two remaining application servers had to deal with an increased amount of bot traffic with their friend down.
4. Their healthcheck started failing too.
This PR only partially helps with this issue, by increasing the number of healthchecks required before taking a VM out of rotation, and reducing the number of healthchecks required before adding it back.
A better fix would be to increase the amount of time before a request times out, and adding more application servers to handle the load.
=> [orangelight] Make it harder for the load balancer healthcheck to take the catalog down

group_vars/orangelight/common.yml
This increases the number of simultaneous requests that passenger will work on. The tradeoff is that more simultaneous requests will require more memory to process.
According to the passenger documentation, we could safely process about 28 simultaneous requests (rather than our current 6) with the current memory usage patterns and memory available on the boxes:
https://www.phusionpassenger.com/library/config/nginx/optimization/#tuning-the-application-process-and-thread-count
Perhaps this could make the catalog more resilient to large spikes in bot traffic?
Creating as a draft PR so that we can discuss.  I ran this on catalog3 today (December 4)
=> [orangelight] increase the passenger max pool size

group_vars/orangelight/common.yml
After analyzing our resource usage on our Orangelight webservers we decided to increase the Passenger thread count to 30 to handle more requests with the available resources.
=> Increase passenger thread count to 30

roles/pul_nomad/files/auto_update_override.conf, roles/pul_nomad/handlers/main.yml, roles/pul_nomad/tasks/main.yml
We were filling up disk with unused images.
Pulled from https://github.com/hashicorp/nomad-driver-podman/issues/363 and https://github.com/dani-garcia/vaultwarden/discussions/4362
Closes #5602
=> [Nomad] Prune podman containers nightly.

group_vars/allsearch_api/common.yml, group_vars/allsearch_api/staging.yml, roles/ruby_s/defaults/main.yml, roles/ruby_s/tasks/install_from_source.yml
Recent versions of Ruby 3.3 will automatically compile the yjit if they notice that the rust compiler is installed.
Rails 7.2 (which Allsearch API uses) automatically uses the YJIT if it is available.
Trying this out to see if it boosts performance at all (which we can monitor in the datadog APM).
One way to check if the YJIT is installed is with the following shell command:
```
ruby -e 'puts "YJIT is#{defined?(RubyVM::YJIT) ? "" : " not"} installed"'
```
=> [allsearch api] compile ruby with the YJIT in staging

playbooks/nginxplus.yml
our nginxplus is now more resilient to crashes thanks to this work https://github.com/pulibrary/princeton_ansible/pull/5557
the tasks within the role call for nginxplus to be reloaded
closes #5607
=> [nginxplus] remove restart task

group_vars/pulfalight/production.yml, roles/nginxplus/files/conf/http/pulfalight-prod.conf, roles/passenger/templates/passenger.j2
This does a few things:
1. Adds nginx logs
1. Filters local health checks out of nginx logs (for all apps).
1. Forwards the real IP so they don't get filtered, and we can group on them in DataDog.
Refs pulibrary/pulfalight#1469
=> [Pulfalight] Add nginx stats & logs for pulfalight to Datadog.

group_vars/bibdata/common.yml
See related sftp ticket: https://github.com/pulibrary/princeton_ansible/issues/4938
=> Comment out deploy_id_rsa_private_key in bibdata commons so that we can run the bibdata playbook successfully

group_vars/figgy/production.yml, roles/sidekiq_worker/tasks/main.yml
And we have a backed-up queue.
This has been run already on most of figgy's workers.
=> Figgy worker boxes appear to have more capacity for sidekiq threads

playbooks/os_updates.yml
the yum update sometimes fails with an upstream update. This allows the
playbook to and update to continue using the dnf module with provides a
few more options
closes #5635
=> [prancible] os update fails

roles/mflux/tasks/custom-roles.yml, roles/mflux/tasks/docker.yml
Makes sure the docker development instance can run the content queries when logged in via the cas user
Create a new instance and published it with this code `ansible-playbook playbooks/mflux-docker.yml --ask-vault-pass -e platform_base=arm64 -e docker_base_image=rockylinux:9 -e docker_tag=cas-login` for folks to use on thier machines
=> [MFLUX] Add roles for users to query

group_vars/abid/staging.yml, playbooks/abid.yml
we will use sandboxes for our ufw experiments this makes abid staging
stay up
=> [abid] remove ufw role

roles/nginxplus/files/fail2ban/nginx-badbots-filter.conf
we have found these bots in our logs and add them to the list of bots
that fail2ban will filter out
Co-authored-by: James R. Griffin III <jrgriffiniii@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
=> [nginxplus] add new bots

roles/nginxplus/files/fail2ban/nginx-badbots-filter.conf
Previously, we were trying to match CLF formatted logs in access.log.  But our access log is in a JSON format, so we needed to adjust the fail2ban failregex accordingl[fail2ban/nginxplus] Change format of fail2ban match
Previously, we were trying to match CLF formatted logs in access.log.  But our access log is in a JSON format, so we needed to adjust the fail2ban failregex accordingly
=> [fail2ban/nginxplus] Change format of fail2ban match

group_vars/bibdata/common.yml
part of https://github.com/pulibrary/bibdata/pull/2566
After the 2 PRs are merged we will need to update the production VMs.
=> [Bibdata] bibdata#2557 update ruby to 3.3.6

inventory/all_projects/nomad
Partially addresses https://github.com/pulibrary/ops-catchall/issues/121.
We created two new production nomad VMs today. This adds them to inventory.
=> adds two new nomad clients for imagecat

inventory/all_projects/_orphans, inventory/all_projects/nginxplus
move the focal vms to the orphaned group. This will remain here for another 30 days and go through the decommissioning process.
related to #5670 
The migration is needed since focal end of life is in the spring of 2025. [More here](https://gitlab.lib.princeton.edu/ops/team-handbook/-/issues/6)
=> [nginxplus] upgrade to jammy

inventory/all_projects/_orphans, inventory/all_projects/nginxplus
we cannot determine why the virtual loadbalancers kept yoyoing with the
new vms
this reverts to the physical hardware
=> [nginxplus] revert back to physical hardware

roles/nginxplus/files/fail2ban/nginx-badbots-filter.conf
adding more bots to to be banned by fail2ban. This list was taken from a
combination of the code4lib bots channel and from [Dark Visitors](https://darkvisitors.com/agents)
=> [nginxplus] add more bots

group_vars/lib_jobs/common.yml
[Previously was upgraded to 3.3.6](https://github.com/pulibrary/princeton_ansible/pull/5695/files#diff-ae5fbc1cda18cdbaba672b09e350eba48bf2cd04fdd48fc5a8968b1eb430fc88R23)
=> [Lib Jobs] Upgrade ruby to 3.4.1

inventory/all_projects/nomad
Partial fix for https://github.com/pulibrary/ops-catchall/issues/121.
Adds new inventory entries for new Nomad staging servers for DLS.
=> adds new staging nomad boxes for imagecat to inventory

roles/nginxplus/tasks/prerequisites/install-prerequisites.yml
Updated the copy module to include a "notify" to restart fail2ban service when changing the fail2ban config files.
The dev environments had a pending fail2ban config change at: /etc/fail2ban/filter.d/nginx-badbots.conf
Which trigged an automatic restart of the fail2ban service when running the playbook: active (running) since Mon 2025-01-06 15:22:06 UTC; 41s ago
=> Updated the copy module to include a notify to restart fail2ban service.

roles/ealapps/meta/main.yml, roles/ealapps/molecule/default/molecule.yml, roles/ealapps/tasks/main.yml, roles/mysql/tasks/main.yml, roles/php/molecule/default/molecule.yml, roles/php/molecule/default/verify.yml, roles/php/tasks/main.yml
The ppa from ondrej defaults to Debian sid. We cleaned up the role to tie it to jammy or whatever version of ubuntu.
=> [ealapps] Use image from ghcr registry instead of quay

roles/ruby_s/tasks/cleanup.yml, roles/ruby_s/tasks/install_from_source.yml
I installed a new ruby version (3.3.6 with YJIT) on both dss-staging1 and dss-staging2. I used this commit for dss-staging2, but not dss-staging1 for the sake of comparison. Running the playbook took:
* 15:53.25 on dss-staging1 without this commit
* 9:55.20 on dss-staging2 with this commit
=> [ruby_s] Run make in parallel

roles/nginx/tasks/main.yml
This step can be a bit flaky in an idempotence check.  For example: https://github.com/pulibrary/princeton_ansible/actions/runs/12656596039/job/35269514546
My guess is that some package version was updated between when `molecule converge` ran and `molecule idempotence` ran, which led to this step being "changed".
We can exclude a step from running during the idempotence checks with the molecule-idempotence-notest tag, hopefully this helps!
=> [nginx] exclude apt cache from idempotence check

group_vars/orangelight/common.yml, playbooks/orangelight.yml, roles/deploy_user/tasks/main.yml, roles/orangelight/meta/main.yml, roles/orangelight/molecule/default/converge.yml
Connected to https://github.com/pulibrary/orangelight/issues/4609
This adds the sidekiq role to the orangelight playbook.  A few things to note:
- Some role dependencies are moved from the orangelight role to the orangelight playbook.  This is because, when they were in the role, time-consuming tasks like the `ruby_s` tasks would run twice: first for the sidekiq boxes, then again for non-sidekiq boxes.  Now that they are in the playbook, placed before the `sidekiq` role, `ruby_s` (and other tasks like `bind9`) only run once.
- The `sidekiq_worker_name` does not contain the name of the application, as it does for bibdata.  This is so we can simply run `systemctl restart sidekiq`, rather than having to figure out the application-specific sidekiq name.
=> [orangelight] Add sidekiq

inventory/by_environment/production, inventory/by_environment/staging
This resolves the following warnings:
```
[WARNING]:  * Failed to parse /Users/sandbergj/repos/princeton_ansible/inventory/by_environment/production with ini plugin: /Users/sandbergj/repos/princeton_ansible/inventory/by_environment/production:12: Section [production:children] includes undefined group: cicognara_production [WARNING]:  * Failed to parse /Users/sandbergj/repos/princeton_ansible/inventory/by_environment/production with yaml plugin: We were unable to read either as JSON nor YAML, these are the errors we got from
each: JSON: Expecting value: line 1 column 2 (char 1)  Syntax Error while loading YAML.   did not find expected <document start>  The error appears to be in
'/Users/sandbergj/repos/princeton_ansible/inventory/by_environment/production': line 2, column 1, but may be …
```
=> Remove old inventory warnings

playbooks/lib_sftp.yml, roles/lib_sftp/tasks/main.yml
Two users write to the /alma/aspace directory: the alma user and the aspace user.  They are both part of the same group, but the group needs write permissions to the directory.
=> [lib-sftp] make /alma/aspace directory group-writeable

group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml, roles/ruby_s/defaults/main.yml
Also, add two default variables to the ruby_s role to automatically update the mailcatcher path when the ruby_version_override variable changes. These default variables could be overriden in the group_vars if needed.
I ran this on staging and qa, and confirmed that the systemd service is now looking at the new path.
=> [orangelight] Update mailcatcher paths

roles/mailcatcher/tasks/main.yml
pkg-config can sometimes be necessary for compiling the sqlite3 gem's C extensions, see [this failure of the lib-jobs playbook](https://ansible-tower.princeton.edu/#/jobs/playbook/10600/output).
=> [mailcatcher] Add pkg-config dependency

roles/lib_sftp/tasks/main.yml
Updated group to `pusvc-g` from `domain users` in `roles/lib_sftp/tasks/main.yml` 
Closes #5723
=> Update group ownership in lib_sftp/tasks to `pusvc-g`

playbooks/Gitlab.yml, playbooks/aws_group_access.yml, playbooks/byzantine.yml, playbooks/ezproxy.yml, playbooks/figgy_db_migration.yml, playbooks/friends_of_pul.yml, playbooks/lib_jobs.yml, playbooks/lib_sftp.yml, playbooks/libruby.yml, playbooks/libwww.yml, playbooks/mysql_db_migration.yml, playbooks/orangelight_toggle_readonly.yml, playbooks/orcid.yml, playbooks/pas.yml, playbooks/pdc_describe.yml, playbooks/pdc_discovery.yml, playbooks/postgresql_db_migration.yml, playbooks/recap.yml, playbooks/special_collections.yml, playbooks/video_reserves.yml, playbooks/whichiso.yml
Receiving deprecation warnings on playbooks that lists for vars will not be used in Ansible v2.18.
Changing Vars sections to dictionaries by removing the `-` from the items.
Testing each playbook  with lists in the vars section using --check before and after making the change:
example `ansible-playbook playbooks/utils/expand_disk.yml --check`
Closes #5293
=> Changed vars from list to dictionaries in playbooks

roles/nginxplus/files/fail2ban/nginx-badbots-filter.conf
The [fail2ban documentation](https://github.com/fail2ban/fail2ban/wiki/Best-practice) says that if we don't need DNS resolution, we should use `<ADDR>` instead of `<HOST>`.
I confirmed using `fail2ban-regex` that it produces the same results on a sample of 10,000 log entries, and that it is consistently a little faster.
=> [fail2ban] Use <ADDR> rather than <HOST> when we only need an IP address

playbooks/utils/checkmk_add_sftp_check.yml
our initial install had used cpanimus but and we didn't rememeber this
until the second vm was added
related to #5728
=> [check_mk] sftp check

roles/nginxplus/files/fail2ban/nginx-bad-httpbots.conf, roles/nginxplus/files/fail2ban/nginx-f_inclusive.conf, roles/nginxplus/tasks/prerequisites/install-prerequisites.yml
we have had queries that have a large number of facets. This filter will
look for 8 of these for blacklight. It works with blacklight 7. IPs
found will be banned
Co-authored-by: Jason Casden <cazzerson@users.noreply.github.com>
Co-authored-by: David Romani <unc-david-romani@users.noreply.github.com>
=> [nginxplus] fail2ban blacklight filter

roles/nginxplus/files/conf/http/ojs-prod.conf
The VM doesn't exist anymore and this caused 'nginx -t' to fail
=> Remove ojs-prod1.princeton.edu from the load balancer

roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf
Added 4 lines to lockers-and-study-spaces-staging.conf to restrict access to princeton IPs
Successfully ran the playbook on production
closes #5742 
=> update lockers-and-study-spaces-staging.conf 

roles/nginxplus/files/fail2ban/nginx-bad-httpbots.conf, roles/nginxplus/files/fail2ban/nginx-f_inclusive.conf
@christinach and I found that the current fail2ban configuration is stressing our load balancers -- maxing out 2 CPUs and it is having trouble keeping up with the volume.
While testing locally with fail2ban-regex, looking for 15 facets applied is more than 20 times faster than looking for 20 facets. This reduces the number of facets accordingly, while relaxing the number of such requests that an IP needs to make before being banned.
=> [fail2ban] Reject requests with 15 facets, rather than 20

roles/nginxplus/files/conf/http/cdh_test_derrida.conf
the cdh-test-derrida was giving us a TLS error. This change removes it
related to #5764
=> [cdh] ssl error

inventory/all_projects/nginxplus
remove the focal loadbalancers from nginxplus inventory they will remain on the orphaned inventory until we sunset them
related to #5670
=> [nginxplus] remove focal load balancers

playbooks/nginxplus.yml
we install and configure datadog for our production servers. we also fix a bug where the production did not have the domain added to it.
closes #5776
=> install and configure datadog when running in production

playbooks/lib_sftp.yml
lib-sftp will not be sending logs to datadog, so we don't need the role reference
closes #5709
=> removed references to datadog role

inventory/all_projects/postgresql, playbooks/postgresql.yml, roles/common/tasks/main.yml, roles/postgresql/defaults/main.yml, roles/postgresql/tasks/create_db.yml, roles/postgresql/tasks/extensions.yml, roles/postgresql/tasks/main.yml, roles/postgresql/tasks/pg_hba.yml, roles/postgresql/templates/logrotate.d.postgresql.j2, roles/postgresql/templates/rh_postgresql.conf.j2
Install and configure postgresql 13 on Rocky Linux
Related to #5590
=> I5590 migrate ansible tower db

roles/postgresql/tasks/main.yml
the enable postgresql task reports a failure even though the service is
still running. We comment it out and the role runs successfully
=> [postgresql] remove enable postgresql

group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml, roles/rails_app/meta/main.yml
Advances https://github.com/pulibrary/oawaiver/issues/232 by addressing the following:
- Updating Node.js to release 18.20.6 for oawaiver server hosts
- Ensuring that PostgreSQL server is not installed when postgres_is_local is true for the oawaiver Role
=> Updating Node.js to release 18.20.6 for oawaiver server hosts

group_vars/allsearch_api/common.yml, group_vars/allsearch_api/staging.yml, playbooks/allsearch_api.yml
Relies on https://github.com/pulibrary/allsearch_api/pull/334 being deployed
=> [allsearch api] Ruby 3.4.1 with YJIT

group_vars/checkmk/rule_adc.yml
we need to make sure logrotate runs on our loadbalancer. this makes it
so we will get an alert when it doesn't
closes #5794
=> [nginxplus] add logrotate monitor

inventory/by_environment/production, inventory/by_environment/staging
we removed researchdata production from inventory but left out the
corresponding group in the environment
related to #5679
=> [researchdata] fix inventory

inventory/by_service/apache, inventory/by_team/dacs
references to libwww_production in inventory/by_team/dacs and inventory/by_service/apache were causing errors when running playbooks
related to #5651
=> removed references to deleted undefined hosts

inventory/all_projects/checkmk, roles/nginxplus/files/conf/http/pulmonitor_staging.conf
we add the two out of band monitors to the ansible inventory
we configure the loadbalancer to route traffic to them
related to #5818
uncommitted work to rename the sites was done inside checkmk
=> [checkmk] add OOBM machines

group_vars/dpul/production.yml
This has been run; ready to merge
closes pulibrary/dpul#1600
=> [DPUL] add a datadog http check for the mount health monitor

inventory/all_projects/mflux
This fixes a yml parse warning
=> Match mflux name to what's in inventory/by_environment/production

playbooks/utils/gitlab_api.yml
We cannot set up a template in Tower until the playbook exists in the main branch.
This branch adds a minimalist playbook to make it possible to test this functionality in Tower.
Related to #5886
=> adds skeleton playbook so we can set up a Tower template

roles/postfix/vars/main.yml
Partially addresses #5820.
This change adds the Tower VMs to support email notifications. Email notifications come from the Tower UI rather than from playbook/template execution. I've already run the playbook from the branch and tested the alert in the Tower UI. Last step for #5820 is to specify the conditions for alerting.
=> add tower boxes to postfix allow list

roles/libstatic/defaults/main.yml
At least partially addresses #5859.
=> Remove static tables referrence from libstaic role.

playbooks/utils/chronyd.yml
make all our VMS use the same ntp servers that our ESXi hosts use. We are otherwise getting false alerts about what time things happen
related to #5893
=> [prancible] add a playbook that configures ntp server

roles/ansible-consul/templates/consul_systemd.service.j2
This was allowing Nomad to start up before Consul.
See https://github.com/hashicorp/nomad/pull/24964
Refs #5864
=> [Nomad] Systemd should wait for Consul to join to be marked as up.

playbooks/pulsys_user.yml
Closes #5243.
The pulsys user playbook sometimes runs in Tower without adding keys to any VMs because no hosts match either play. This PR ~~adds variables for matching hosts~~ sets a fact when each play runs, and adds a third play that forces failure if neither of the first two plays ~~has any matching hosts~~ runs.
~~Could use a test run @maxkadel.~~
Update: I figured out the most common use case - if I use `limit` to run on a specific VM or group and then select an `environment` setting that does not include the VM or group, the playbook will behave as described in #5243. Here's the [Tower run](https://ansible-tower.princeton.edu/#/jobs/playbook/13669/output) that tested the functionality of this branch.
=> Pulsys keys playbook fails if no hosts match at all

tower_ees/execution-environment.yml
This should help with this failing tower job: https://ansible-tower.princeton.edu/#/templates/job_template/73
We have not yet built a new execution environment with the new collection.
=> Add mysql collection to Execution Environment

nomad/traefik-wall/deploy/bot-plugin-staging.tpl.yml, nomad/traefik-wall/deploy/traefik.tpl.yml
Anyone on our wireless shouldn't be hit with captcha - this upgrades the plugin and fixes the config so it's fine.
=> [Traefik Wall] Fix wireless IPs being hit with captcha.

playbooks/utils/check_os_versions.yml
With `become` set to true in the check_os_versions playbook, we see this error on some machines:
`fatal: [prds-dataspace-dtn1]: FAILED! => {"msg": "Missing sudo password"}`
The playbook gathers facts and reports them. We shouldn't need sudo/become for that.
=> Don't use become/sudo in check_os_versions.yml

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml, nomad/traefik-wall/deploy/bot-plugin-staging.tpl.yml, nomad/traefik-wall/deploy/sites/sites-production.yml
This makes sure we only rewrite `?f[]=` if it's right after the first slash in a path, so it no longer matches on `https://catalog.princeton.edu/catalog/?f[subject_facet][]=Catrysse%2C+Wim+1973-%E2%80%94Exhibitions`
=> [Traefik Wall] Fix redirect for production Catalog.

roles/pas/templates/env-craft4.j2
This addresses the following warning, which fills up the logs at /var/log/apache2/error.log:
```
PHP Warning:  Undefined array key ENVIRONMENT in /opt/pas_cap/releases/20250310191309/bootstrap.php on line 22
```
=> [pas] add missing environment variable

roles/nginxplus/files/conf/http/dpul-prod.conf, roles/nginxplus/files/conf/http/dpul-staging.conf
This will prevent passenger from filtering out all logs for DPUL.
Necessary work to implement #5948
=> [DPUL] Add X-Real-IP to DPUL

roles/nginxplus/files/conf/http/templates/libweb2-redirects.conf, roles/nginxplus/files/conf/http/templates/libweb5-redirects.conf
Closes #5967.
In #5368 we deleted the wrong redirect file. We should have deleted the redirects for libweb2; instead we deleted the redirects for libweb5. This PR fixes our mistake.
=> Restore libweb5-redirects.conf, delete libweb2-redirects.conf

inventory/by_cloud/google_cloud
Explicitly setting the path for python3 should fix the error we've been seeing in Tower:
```
Platform unknown on host gcp_oar_staging1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.15/reference_appendices/interpreter_discovery.html for more information.
```
=> For GCP hosts, use installed python at /usr/bin/python3

roles/nginxplus/files/conf/http/dev/milberg_staging.conf, roles/nginxplus/files/conf/http/dev/static_staging.conf
add a configuration that allows milberg-staging on the dev loadbalancer
we are exposing the .git directory. Migrate milberg to use nomad 
related to #5961
=> add a configuration for milberg-staging

roles/nginxplus/files/conf/http/milberg_production.conf, roles/nginxplus/files/conf/http/static_prod.conf
the milberg site exposes the .git directory. This PR makes this impossible. 
Closes #5961
=> add milberg configuration for production

group_vars/nfsserver/qa.yml
move the bibdata-qa1 to the private network. This allows us to see if the reduce the noise from failing cifs mounts from checkmk
=> move bibdata to the private network

playbooks/postfix.yml, roles/postfix/tasks/main.yml
The mail servers host their own SSL certificates. They auto-renew, so we don't normally interact with them much. However, when we rebuild a mail server using the postfix role, we create fresh certificates. When we do that, we need to revoke the previous certificates, or they will propagate endlessly. This PR adds a reminder to slack to the tasks file for the postfix role.
=> Add a reminder about revoking old certs

playbooks/utils/gitlab_api.yml
Our GitLab API call was not pulling all our tickets into Airtable. The limitation turned out to be [pagination](https://docs.gitlab.com/api/issues/#issues-pagination) - by default API calls are limited to 20 per page.
This PR sets `per_page` to `100` and also limits by `state=opened`. This enables the GitLab-Airtable connection to work as long as the number of open tickets stays under 100 per repo in GitLab.
If we need more, we can first pull the number of pages using the `x-total-pages` parameter. See [this forum post](https://forum.gitlab.com/t/rest-api-seems-to-only-return-the-first-20-resource-label-events-for-the-issue/63268).
=> Expand GitLab API call to pull up to 100 open tickets to Airtable

group_vars/nfsserver/production.yml, roles/postfix/vars/main.yml
add the new IP to our NFS exports
this is to reduce the CIFS alerts
remove library servers from postfix allow list
=> [pas] move to private network

group_vars/nfsserver/qa.yml
we are moving all hosts to the private network to reduce the CIFS mounts
noise from our monitoring
=> [bibdata] move to private network

group_vars/figgy/production.yml
we are moving the worker boxes to the private network to reduce the
CIFS noise on CheckMK.
Running the playbook to add the VM to the db server failed until this
change
=> [figgy] move worker-prod4 to private network

inventory/all_projects/cdh, inventory/by_cloud/google_cloud
these two hosts are no longer in use and report as unavailable during os
and security updates
=> [prancible] remove hosts

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml, nomad/traefik-wall/deploy/bot-plugin-staging.tpl.yml
Collector systems needs to be able to query Figgy catalog URLs with parameters - these are their IPs, they should be let through the bot wall.
=> [Traefik Wall] Add collector systems to exempt IPs.

inventory/all_projects/checkmk
our canary host was not getting patched. This adds the host to the pulcheck group so it will get patched on Tuesdays
=> add canary host to inventory

group_vars/bibdata/qa.yml, group_vars/dpul/staging.yml, playbooks/bibdata.yml, playbooks/dpul.yml
We need a service that connected to one of our NFS shares to compare
performance and rule out networking issues. This seemed lowest impact.
=> [Bibdata] Add Prometheus to Bibdata QA / DPUL Staging

roles/orangelight/tasks/main.yml
theres a discrepancy with file ownership for brownfield hosts with will sometimes have root own the files
followup work on #6042
=> [orangelight] remove deploy user file owner ship

group_vars/video_reserves/production.yml, group_vars/video_reserves/staging.yml, roles/video_reserves/tasks/main.yml
Ansible thought we were using PHP 8.3, but the staging and prod servers were using 8.4 instead, and missing some needed php modules.
Closes https://github.com/PrincetonUniversityLibrary/video_reserves/issues/92
=> [videoreserves] Install needed php modules for PHP 8.4

group_vars/lib_jobs/common.yml
As of https://github.com/pulibrary/lib_jobs/pull/907, it is no longer needed.
Helps with https://github.com/pulibrary/lib_jobs/issues/896
I ran this on staging, and also manually removed the node and yarn binaries from the staging boxes.
=> [lib-jobs] Don't install node

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, roles/figgy/tasks/main.yml
They liked this name better.
This has been run, and the old mounts removed with
`ansible figgy_staging -u pulsys -become -m ansible.posix.mount -a "name=/mnt/hosted_illiad/ILL_OCR_Scans state=absent"`
(same with prod)
Work for pulibrary/figgy#6412
=> [Figgy] Update ILL OCR mount name.

playbooks/utils/checkmk_add_logsize_check.yml
we get a warning from datadog when the disk is about to fill up.
This playbook installs a checkmk local check and warns us with a
parametrized size of the security log is too large
we can then force a logrotate.
This will eventually be obsolete by better logroation
related to #6075
=> [nginxplus] monitor logs

roles/nginxplus/files/conf/http/slavery-prod.conf
The server exists and the app has been successfully deployed to it via the cap task defined in the application config.
=> Add second pas prod server back.

group_vars/nomad_cluster.yml, roles/ansible-consul/tasks/main.yml, roles/ansible-consul/tasks/nix.yml, roles/pul_nomad/tasks/main.yml
On Nomad, DNS was falling down to 8.8.8.8. We want it to pull from whatever DNS gave the machine, which is the PUL nameservers.
This was causing propagation of internal IPs to take ~8 hours.
=> Remove default DNS servers from dnsmasq

roles/bibdata/tasks/main.yml
Our library_standard_numbers gem depends on a rust crate named rb-sys, which depends on clang.
See https://ansible-tower.princeton.edu/#/jobs/playbook/18192/output
This is a prerequisite to https://github.com/pulibrary/bibdata/pull/2698
=> [bibdata] Install clang

playbooks/utils/security_theater.yml
Our security-install playbook started failing a few weeks ago when OIT upgraded the install package versions. They have now renamed the package files to use `latest` instead of including the version number. 
This works fine in our playbook except for the step that configures Rapid7 with the token - that needs the full path with the version number to run the script. However, we tested the playbook without that task on a new VM and OIT says it worked fine.
Leaving that task in the playbook for now, commented out, in case we see issues in the future. If we need to reinstate it, we will need to add tasks that search the path and return the version number.
=> [Rapid7] Use 'latest' instead of hardcoded version

group_vars/nginxplus/main.yml, playbooks/mysql.yml, playbooks/pdc_describe_redis.yml, playbooks/postgresql.yml, playbooks/solr8cloud.yml, playbooks/solr9cloud.yml, playbooks/solrcloud.yml, playbooks/zookeeper.yml, playbooks/zookeeper_solr8.yml
Work towards #6126.
Nginx+ is set up to still install Datadog, but only send logs. I'm hoping that pulls it off infrastructure billing.
=> [Datadog] Remove non-application, CheckMK monitored hosts.

inventory/all_projects/bitcurator, inventory/by_environment/production
Added bitcurator machines to inventory/all_projects/bitcurator under [bitcurator_production]. Added bitcurator_production to inventory/by_environment/production
Related to #6142
=> Add bitcurator VMs to inventory

roles/postfix/vars/main.yml
Remove abid-production{1,2}.princeton.edu as these machines have been decomissioned. 
Closes #6166
=> Remove abid-production{1,2}

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml, nomad/traefik-wall/deploy/sites/sites-production.yml, roles/nginxplus/files/conf/http/datacommons.conf
Since PDC Discovery is hosted at a sub-path (`/discovery`), we have to:
* Allow the load balancer to redirect `/challenge` to the discovery boxes.
* Bot wall monitor `/discovery/catalog`
* Redirect `/discovery/?f[]=` to `/discovery/catalog?f[]=`
=> [Datacommons] Finish bot wall implementation

inventory/all_projects/reservoir
Corrects the FQDN for reservoir-staging{1,2} vms added with #6178
=> Correct FQDN for reservoir-staging VM

group_vars/checkmk/production.yml, group_vars/checkmk/staging.yml, roles/nginxplus/files/conf/http/pulmonitor_production.conf, roles/nginxplus/files/conf/http/pulmonitor_staging.conf, roles/postfix/vars/main.yml
we add a configuration for checkmk production.
we have allowed access outside VPN and are using RFC-1918 hosted VMS
we don't think this matters
=> [checkmk] add prod config

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml
Sometimes it's not ?f[]=, it's &f[]=, this covers that case.
We were seeing this for findingaids:
`/?+Grau+&f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&f%5Bnames_ssim%5D%5B%5D=Museo+nacional+de+historia+Mexico&range%5Bdate_range_sim%5D%5Bbegin%5D=1902&range%5Bdate_range_sim%5D%5Bend%5D=1904&sort=creator_sort+desc`
=> [Traefik] Improve regex to capture more facet queries.

group_vars/dss/common.yml
closes https://github.com/pulibrary/DSS/issues/530
use latest node version 24.x
Release comes out on [4/22/2025](https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule)
See also https://github.com/pulibrary/DSS/pull/553
=> [DSS] Use latest node version 24.x

roles/common/files/vector.yaml, roles/common/tasks/vector.yml
They take up a non-trivial amount of disk space.  Eventually, we will want to send real logs to pulemetry, but it is not quite ready yet.  This configuration is taken from the basic config on the boxes, except that it uses a "file" sink to send the entries to /dev/null
I ran this on bibdata-worker-staging[12], where it did stop sending those demo logs to the syslog.
=> [common] don't send vector's demo logs to the syslog

inventory/by_environment/staging
In `inventory/by_environment/staging` the group `kennyloggin_staging` was mispelled as `kennylogging-staging`.
Closes #6208
=> Correct typo for kennyloggin_staging

group_vars/nginxplus/main.yml
MOST of the 302s are for bots redirecting to Traefik.
This is a visibility loss for sure, but we're ingesting way too many logs right now. Hopefully we can switch to Loki soon. This should cut our log ingestion in half.
=> [Datadog] Skip logging load balancer 302s

inventory/by_environment/staging
I couldn't run some playbooks because of errors like this one:
```
(princeton_ansible) ➜  princeton_ansible git:(orangelight_ci_key) ansible-playbook playbooks/deploy_user.yml --tags update_keys -e runtime_env=staging --limit=orangelight_staging
> [WARNING]:  * Failed to parse /Users/max/projects/princeton_ansible/inventory/by_environment/staging with ini plugin:
/Users/max/projects/princeton_ansible/inventory/by_environment/staging:24: Section [staging_2:children] includes undefined group: lib_fs_cdh_conf_prosody
```
=> Remove undefined environments - were causing parsing problems

roles/nginxplus/files/conf/http/lae-prod.conf, roles/nginxplus/files/conf/http/pulfalight-prod.conf
the default loadbalancer loadbalancer config blocks traffic we are explicitly saying on these apps that the waf should be disabled
=> enable waf blocking

nomad/circleci_deployer/Dockerfile
Connected to https://github.com/pulibrary/orangelight/issues/4879
In order to use Capybara to drive a browser to test deployed environments, we need to be able to install Chrome and Chromedriver, which requires gnupg2
Failed CI run https://app.circleci.com/pipelines/github/pulibrary/orangelight/6788/workflows/65468fae-6eaa-459a-856d-3ce6a7861db7/jobs/35251
=> [circleci] Add gnupg2 for Chrome install

roles/solr9cloud/tasks/backup_mounts.yml
we are having the solr servers fail to reboot if the diglibdata is unavailable, this ensures that the server will boot even when the backup mounts are not readily available
this is related to https://github.com/pulibrary/pdc_discovery/issues/807
=> [solrcloud] ensure servers reboot

roles/nginxplus/files/conf/http/cdh_test_prosody.conf
by default we have nginx WAF enabled. We disable it for this upstream
closes #6304
=> [nginxplus] disable waf for prosody

playbooks/utils/tigerdata_nfs_mount.yml
the variables could get us into trouble on machines that do not have the tigerdata mount. We require a user to pass these for the playbook to work
related to <https://github.com/Princeton-CDH/cdh-ansible/issues/277>
=> [tigerdata/nfs] mount tigerdata

group_vars/lib_jobs/common.yml, roles/lib_jobs/defaults/main.yml, roles/lib_jobs/tasks/main.yml
the variables for logrotate are made consistent with the common role but we prefix the name of the role and call them within the role and the group vars. we may need to test at a later date if the variables in the `group_vars/lib_jobs/common.yml` are even needed.
closes #6324
End to end test performed with
=> [lib_jobs] fix failure of cron jobs

group_vars/orcid/main.yml
Hanami deploys on the rails role.   We may want to consider renaming that role to something like ruby-webapp, but for the moment these are all the changes that are required to deploy a hanami application to the server
=> Adding variables for Hanami environment

playbooks/utils/checkmk_agent.yml
Partially addresses #5718.
This PR adds documentation to the playbook about what is required to run it locally.
It also adds a pre-task that stops the playbook if you do not use 'limit'. Since we must define which CheckMK service and which folder to add VMs to, it seems smart to force everyone to use 'limit' - otherwise we risk having all our VMs added to a single CheckMK service and folder.
=> [CheckMK] expands playbook documentation, requires 'limit'

group_vars/tigerdata/ci.yml, group_vars/tigerdata/common.yml, group_vars/tigerdata/production.yml, group_vars/tigerdata/qa.yml, group_vars/tigerdata/staging.yml
This advances https://github.com/pulibrary/tigerdata-app/issues/1598
=> Upgrading TigerData hosts to use Node.js 22.9.0 releases

inventory/all_projects/_orphans, inventory/all_projects/sandboxes
We had a `sandboxes` group in the `_orphans` file in inventory. We also had a dedicated file in `all_projects` called `sandboxes` with another group and a different list of VMs.
This PR removes one obsolete sandbox VM (sandbox-rl36671), deduplicates, consolidates, and alphabetizes the others.
=> removes sandbox-rl36671 from inventory, consolidates sandbox entries

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml
Prior to this commit, running the bibdata playbook led to the following line in ~deploy/app_configs/bibdata:
```
export BIBDATA_IP_ALLOWLIST=""128.112.200.203 128.112.204.114""
```
And when you ran `env | grep -i allowlist`, you got:
```
BIBDATA_IP_ALLOWLIST=128.112.200.203
```
And when you log into a new SSH session, you got this distracting error:
```
-bash: export: `128.112.204.114': not a valid identifier
```
Since #6368 was merged, we no longer need to supply double quotes for this environment variable, so let's remove them so we only have one pair of quotes.
I have run this on staging and qa.
=> Use only one pair of double quotes for Bibdata allow list

inventory/by_cloud/google_cloud
Related to #6357.
Connections through our jump hosts to GCP resources were failing in Tower with an error about accepting the host key. 
This PR sets an SSH argument that accepts the host key the first time it's encountered. When added as a variable to a Template in Tower, this SSH argument allowed Tower to gather facts on a GCP machine. Adding it to our inventory should continue to allow access from Tower without changing our approach to other infrastructure.
=> Enable Tower to connect to GCP hosts

inventory/by_cloud/google_cloud
More follow-up on #6385 and #6379.
As currently written in the main branch, the ssh options for gcp resources behind the bastion hosts are not correctly pulled into Tower.
We need:
`ansible_ssh_common_args: -o ProxyCommand="ssh -o 'ForwardAgent yes' -o 'StrictHostKeyChecking=accept-new' -q pulsys@bastion-prod.pulcloud.io -W %h:%p"`
Tower has:
`"ansible_ssh_common_args": "'-o ProxyCommand=\"ssh '-o ForwardAgent yes' '-o StrictHostKeyChecking=accept-new' -q pulsys@bastion-prod.pulcloud.io -W %h:%p\"'"`
This PR tries three different approaches to quotations and escaping for the gcp inventory. Again, we need to merge these to main so we can test them in Tower. If one of them works correctly, I'll follow up with a PR to fix the other two.
Fingers crossed.
=> Seeking the right combination of quotes and escaping for GCP inventory vars

roles/common/defaults/main.yml, roles/common/molecule/default/group_vars/all.yml, roles/shibboleth/molecule/default/converge.yml
As part of #6357, we discovered that Ubuntu 24.04 LTS "Noble Nombat" requires `python3-setuptools` instead of  `python-setuptools` as a package name.
I logged into a sandbox VM running Ubuntu 22.04 LTS "Jammy Jellyfish", and it accepted either package name, confirming that the setup tools are installed in both cases.
This PR makes the common role support both Noble and Jammy.
=> updates all mentions of python-setuptools to python3-setuptools

inventory/all_projects/cantaloupe, inventory/by_cloud/google_cloud, inventory/by_environment/staging, roles/common/tasks/main.yml
Partial fix for #6357.
This exempts the OpenBSD machines from our usual tool-installation tasks. Most things (like tmux) are already built into OpenBSD. Everything else is unnecessary on the few OpenBSD machines we run.
Also removes iiif-staging1 from inventory. It doesn't exist any more, which is why it was unreachable.
=> Fix staging failures in Tower

roles/towerdeploy/defaults/main.yml, roles/towerdeploy/molecule/default/verify.yml
The new Hanami ORCID application utilizes a newer version of Capistrano.  This should allow that application and older ones to deploy.
=> [TOWER] Update tower to allow for newer version of capistrano

group_vars/orangelight/common.yml
With the duplicate quotes, only the first username in the array actually gets added to the `ORANGELIGHT_ADMIN_NETIDS` environment variable, and everybody else does not get access to the flipflop features.
=> [orangelight] Remove unnecessary duplicate quotes from environment variable

roles/nginxplus/files/conf/http/dpul-collections-prod.conf
Closes pulibrary/dpul-collections#492
=> Put dpulc-prod behind the load bot wall.

inventory/by_environment/staging
Closes #6406.
After we got rid of the `lib_svn` groups in #6419, Ansible started complaining about the `pas_staging_upgrade` group.
The warnings about `allsearch_api_*` seem to be generic "this inventory file has issues" warnings that just return the first group name in the file. They have disappeared on this branch.
Removes a stray reference to the `pas_staging_upgrade` group.
=> Tidy inventory, get rid of playbook warnings

roles/common/tasks/main.yml
Our common role is setup assuming our virtual machines have checkmk
we add a task that checks for the checkmk binary. If it is present the
logrotate file is added. Otherwise it skips
=> [common] check for checkmk

group_vars/figgy/common.yml
This will let us queue things that are below "default", but above "low",
so that bulk ingests won't prevent other things.
Work towards pulibrary/figgy#6765
=> Add a bulk queue to Figgy.

roles/postfix/molecule/default/verify.yml, roles/postfix/tasks/main.yml, roles/postfix/vars/main.yml
our relayhost has a different domain name than the upstream relay.
we do not actually send mail but route to another relay
closes #6322
=> [ponyexpr] remove acme certs

playbooks/utils/incommon_certbot_revoke.yml
When we changed the name of the EAL site from eal-apps.princeton.edu to eal.lib.princeton.edu, we changed the config file name and generated new SSL certificates, but the old certs and the old config file were still on the load balancers. When the certs came up for renewal, we revoked the obsolete ones . . . which meant the obsolete config file was looking for cert files that no longer existed.
This PR adds a safety check to the revoke-a-cert playbook, with a message if the `nginx -t` config check fails.
It also removes the duplicate entry for `vars_files` and hard-codes the slack alerts channel.
=> Playbook to revoke SSL certs should check `nginx -t` for safety

playbooks/postfix.yml
related to #6322 we no longer have TLS on our relays
=> [postfix] remove announcement

group_vars/all/vars.yml
Remove Ryan Jensen's SSH keys as part of offboarding.
=> Remove Ryan Jensen from SSH keys

nomad/circleci_deployer/deploy/all.hcl
The Nomad boxes that ran the CircleCI jobs were running out of disk. The
disk clears out when the job on Nomad ends, so this setting makes it so
the runner restarts after every task. When it finishes a task, it shuts
it down, and Nomad spins it back up.
Yay containers.
=> [CircleCI Deployer] Restart worker after every job.

roles/solrcloud/tasks/main.yml
Partial fix for #6476.
We mount the Isilon share directly to `/solr/data/backup` instead of mounting it to `/mnt/solrbackup` and then adding a bind mount from `/mnt/solrbackup` to `/solr/data/backup`.
Once we confirm that this allows the lead Solr box to write backups and reboot with no drama, the next step is to send backups to GCE.
=> simplify the backup mounts in solr8

group_vars/figgy_production_cluster.yml, roles/postgresql/defaults/main.yml, roles/postgresql/templates/postgresql.conf.j2
We were having postgres timeouts which was resulting in some items not
being able to be ingested in Figgy. This value allowed those items to
ingest. The relevant honeybadger error:
https://app.honeybadger.io/projects/53391/faults/119695976
Closes https://github.com/pulibrary/figgy/issues/6800
Related to https://github.com/pulibrary/princeton_ansible/issues/2305
This will only change the setting for Figgy, and keep the default for
the other postgres cluster.
=> [Figgy + Postgresql] Set keepalive timeout lower.

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml
Now that the worker boxes have 4 CPUs, they are able to handle 3 sidekiq threads comfortably.  This amount of simultaneous indexing does not seem to negatively impact solr 9 performance.
=> [bibdata] increase number of sidekiq threads from 2 to 3

inventory/by_cloud/google_cloud
Only the VMs that are behind the bastion hosts need IP addresses.
=> [prancible] only use necessary IP addresses in cloud inventory

group_vars/checkmk/shared.yml
I hope this will fix the Tower error in the checkmk playbook about "a later version is already installed". 
Also, our automation should reflect the current reality.
=> updates version of checkmk to match what we are running

group_vars/lib_jobs/common.yml, roles/lib_jobs/tasks/main.yml
Previously, the playbook failed with the error:
```
'svn_host' is undefined
```
I successfully ran this on lib-jobs staging
=> [lib-jobs] More svn cleanup
