group_vars/friends_of_pul/staging.yml, group_vars/libwww/staging.yml, group_vars/orangelight/staging.yml, group_vars/special_collections/staging.yml, playbooks/friends_of_pul.yml, playbooks/libwww.yml, playbooks/orangelight.yml, roles/libwww/meta/main.yml, roles/orangelight/meta/main.yml
orangelight
friends_of_pul
libwww
this will close #3823
=> [libwww,orangelight,fpul,sc] enable mailcatcher

group_vars/lib_jobs/common.yml
Inspired by #3261
Part of https://github.com/pulibrary/lib_jobs/issues/371
I ran this on staging today (May 16, 2023)
=> [lib-jobs] add list of admin users to an envvar

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml, roles/datadog/tasks/agent6.yml
Advances:
* https://github.com/pulibrary/pdc_describe/issues/1000
=> Suppress DataDog traffic from the load balancer

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml
Advances https://github.com/pulibrary/pdc_describe/issues/1000
=> Do not send sidekiq traces to DataDog APM

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml
Advances https://github.com/pulibrary/pdc_describe/issues/1000
=> Exclude low value sidekiq operations, but not ALL sidekiq operations

Pipfile, Pipfile.lock, requirements.txt
=> update specific version of requests

group_vars/orangelight/common.yml, group_vars/orangelight/production.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
=> [orangelight] Add new Redis boxes

playbooks/os_updates.yml
our playbook was not uninstalling packages not needed on the Ubuntu vms
this will close #3968
=> remove unneeded dependencies

.github/workflows/molecule_tests.yml, Pipfile
- remove the failing AGENT tools directory.
- updating to new molecule version
=> [ansible/molecule] restart our runners

group_vars/imagecat_rails/main.yml
=> Adding aws-cli to imagecat rails defaults

playbooks/lib_jobs.yml, roles/subversion/tasks/main.yml
connected to https://github.com/pulibrary/lib_jobs/issues/516
=> add subversion to lib-jobs

group_vars/libwww/staging.yml
- Also, the versions of bundler were different on the two staging servers, which was causing errors when running the playbook, so I upgraded bundler on both so they would match
=> [libwww] Update staging to use new staging redis

inventory/by_cloud/aws
we encountered a failure and a VM booting up with a new IP address.
=> [pdc-globus] update elastic IP

group_vars/all/vars.yml
=> add Sean to deploy users

roles/figgy_pubsub_worker/tasks/main.yml
Co-authored-by: Robert-Anthony Lee-Faison
<leefaisonr@users.noreply.github.com>
=> Update figgy_pubsub_worker role with fqrn

group_vars/sftp/production.yml
=> [lib_sftp] Change deploy_user_id on prod because id already existed

roles/ojs/handlers/main.yml, roles/ojs/molecule/default/molecule.yml, roles/ojs/tasks/automate_backups.yml, roles/ojs/tasks/check_ojs_installation.yml, roles/ojs/tasks/clean.yml, roles/ojs/tasks/install_ojs.yml, roles/ojs/tasks/install_prerequisites.yml, roles/ojs/tasks/main.yml
=> add linting to OJS role. Make the role user fqrn

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
=> Redirecting to new sales catalog site in production

group_vars/special_collections/staging.yml, roles/nginxplus/files/conf/http/lib-sc-staging.conf
both VMs now run jammy-jellyfish and can be placed on loadbalancer
=> [special collections] add second vm

playbooks/prompt.yml
this PR makes the prompt look bash like
=> [jammy vm] update zsh

roles/datadog/README.md
Update the datadog role's documentation, as recommended by @hackartisan in https://github.com/pulibrary/princeton_ansible/pull/4042#issuecomment-1618314237
=> Datadog role example gathers the correct nginx information

group_vars/bibdata/staging.yml
closes https://github.com/pulibrary/princeton_ansible/issues/4056
=> Update SFTP_ALMA_BASE_PATH in bibdata staging

group_vars/recap/staging.yml, roles/nginxplus/files/conf/http/recap-staging.conf
point vms to mariadb-dev with running on jammy
=> [recap] add jammy vm to loadbalancer

group_vars/pdc_describe/production.yml
refs https://github.com/pulibrary/pdc_describe/issues/409
=> Updating the configuration file to point to production datacite instead of staging datacite

roles/memcached/tasks/main.yml
Fixes the install task per @kayiwa's comment in  #4024
=> I2861 memcached fqrn

group_vars/pulfalight/qa.yml
closes pulibrary/pulfalight#1301
=> [pulfalight] Use the same sidekiq workers name on all machines

roles/lib_svn/templates/ead_pre_commit.sh.j2
- Has been run on the staging environment only, waiting testing Closes #4083
=> [lib_jobs] Return to default SVN pre-commit hook

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml
Needed for https://github.com/pulibrary/pdc_describe/pull/1387
The buckets have been defined in S3:
=> New preservation bucket values for PDC Describe

group_vars/dss/production.yml, roles/dss/vars/main.yml
Removes GA ID from vars files relating to #4038
=> [dss] remove GA ID from vars

group_vars/all/vars.yml
Co-authored-by: Favour Nwogbo <favournwogbo21@users.noreply.github.com>
=> Adding Favours github keys to deploy and pulsys

group_vars/pdc_describe/main.yml, group_vars/pdc_describe/staging.yml
upgrade postgresql version
this will close #4092
=> [pdc-describe] update postgresql version

group_vars/pdc_describe/main.yml, group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml, group_vars/pdc_discovery/common.yml, group_vars/pdc_discovery/production.yml, group_vars/pdc_discovery/staging.yml
=> [pd{escribe/iscovery] move to new postgres host

roles/system_ldap/tasks/main.yml
=> [lib_jobs] Create datasync directory on sftp

roles/nginxplus/files/conf/http/pulmonitor_staging.conf
=> [pulmonitor] add nginx config

group_vars/abid/staging.yml, inventory/all_projects/abid, roles/nginxplus/files/conf/http/abid-staging.conf
- upgrade version of ruby to 3.1.3
- add a new jammy vm
- related to https://github.com/pulibrary/abid/issues/130
=> [abid] upgrade to jammy

inventory/all_projects/postgresql
=> [postgresql] add new jammy vm

group_vars/orangelight/qa.yml
=> #4160 update some more envs for qa env

group_vars/tigerdata/production.yml
Advances https://github.com/pulibrary/tiger-data-app/issues/88
=> Ensuring that the TigerData DataDog configuration is at parity with the config. for PDC Describe

group_vars/figgy/staging.yml
=> [Figgy] Migrate figgy staging to postgres15

roles/nginxplus/files/conf/http/pdc-describe_prod.conf
Fixes https://github.com/pulibrary/pdc_describe/issues/1406
=> Make PDC Describe public (remove VPN restriction)

group_vars/pdc_describe/main.yml
Needs to be done in coordination with https://github.com/pulibrary/pdc_describe/pull/1486
=> Upgrading Node Js to 18.17

inventory/all_projects/cdh
- add new jammy vms for cdh
- add shakespeare and web vms
=> [cdh] add jammy virtual machines

playbooks/figgy_production.yml
remove the needless point to a none existent role
=> [figgy] remove postgres

roles/nginxplus/files/conf/http/templates/datacommons-describe.conf, roles/nginxplus/files/conf/http/templates/datacommons-discovery.conf
Ref https://github.com/pulibrary/princeton_ansible/issues/4194
=> Use full URLs in datacommons nginxplus config

roles/nginxplus/files/conf/http/catalog-staging.conf
Co-authored-by: Esmé Cowles <escowles@users.noreply.github.com>
Co-authored-by: Mark Zelesky <mzelesky@users.noreply.github.com>
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
=> [catalog] blocking endnote and RIS

group_vars/dss/common.yml, group_vars/dss/staging.yml, inventory/all_projects/dss, roles/nginxplus/files/conf/http/dss-staging.conf
- add new jammy VM for dss
- update version of nodejs
- update version of postgresql to 15
=> [dss] upgrade node version

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml
Related to https://github.com/pulibrary/bibdata/issues/2239
=> [bibdata] Add envvars for Alma's SRU URL

group_vars/pdc_discovery/common.yml, group_vars/pdc_discovery/production.yml
Change the value of pdc_discovery_host_name to datacommons
Ref https://github.com/pulibrary/pdc_discovery/issues/498
=> Add Access-Control-Allow-Origin for pdc-discovery-prod

group_vars/lib_jobs/common.yml, group_vars/lib_jobs/staging.yml, group_vars/nfsserver/staging.yml, inventory/all_projects/lib-jobs, roles/lib_jobs/tasks/main.yml
- update version of node 18.17.0
- update version of postgresql
- add jammy based vm
- add lib-jobs-staging to nfs file share
- install nfs-common client for nfs fileserver connection
=> [lib-jobs] upgrade nodejs

roles/nginxplus/files/conf/http/cdh_test_sandbox.conf
this disables the check for client size
=> [cdh] disable client size check

group_vars/lib_jobs/production.yml, group_vars/nfsserver/production.yml, inventory/all_projects/lib-jobs, roles/nginxplus/files/conf/http/lib-jobs-prod.conf
- point lib-jobs to the new jammy db server
- add inventory of new jammy vms.
- add lib-jobs-prod2 to nfs-server
=> [lib-jobs] update lib-jobs

group_vars/pdc_describe/production.yml, group_vars/pdc_describe/staging.yml
Co-authored-by: James R. Griffin III <jrgriffiniii@users.noreply.github.com>
=> Label PDC Describe logs in DataDog with a service

group_vars/pdc_discovery/production.yml, group_vars/pdc_discovery/staging.yml, playbooks/pdc_discovery.yml
Fixes https://github.com/pulibrary/pdc_discovery/issues/504
=> Add PDC Discovery to DataDog

group_vars/bibdata/staging.yml, inventory/all_projects/bibdata, roles/nginxplus/files/conf/http/bibdata-staging.conf
- add jammy virtual machines for bibdata
- upgrade node version and point to new database server
=> [bibdata] upgrade nodejs

group_vars/oawaiver/staging.yml, roles/oawaiver/molecule/default/converge.yml, roles/oawaiver/vars/main.yml
Also needed to remove the vars/main.yml indication that postgres was 15 since it is really 13
fixes #4246
=> [OAWAIVER] adding staging config file

group_vars/lockers_and_study_spaces/production.yml, inventory/all_projects/lockers_and_study_spaces, roles/nginxplus/files/conf/http/lockers-and-study-spaces-prod.conf
- add jammy virtual machine to inventory and loadbalancer
- migrate to jammy database
relates to #3476
=> [lockers-and-study] upgrade nodejs and OS

playbooks/figgy_production.yml, playbooks/figgy_staging.yml
Partial fix for #2852.
Adds play names and provides a slack message with more detail for the two figgy playbooks.
=> updates slack message, adds play names to figgy playbooks

group_vars/mudd/common.yml, group_vars/mudd/staging.yml
- upgrade node version
- upgrade postgresql version
=> [mudd] upgrade node

group_vars/oawaiver/staging.yml, inventory/all_projects/oawaiver, roles/nginxplus/files/conf/http/oawaiver-staging.conf
- use jammy vm instead of bionic
- upgrade version of node and database
- upgrade ruby and bundler versions
=> [oawaiver] upgrade node 

group_vars/orangelight/qa.yml
=> Point catalog-qa to catalog-alma-production-rebuild #4252

group_vars/oawaiver/production.yml, inventory/all_projects/oawaiver, roles/nginxplus/files/conf/http/oawaiver-prod.conf
- add jammy vm to inventory
- upgrade database and oawaiver nodejs Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
=> [oawaiver] upgrade node

group_vars/orangelight/common.yml, group_vars/orangelight/staging.yml, inventory/all_projects/orangelight, roles/nginxplus/files/conf/http/catalog-staging.conf
=> I3476 catalog staging update

group_vars/allsearch_api/staging.yml, playbooks/allsearch_api.yml
=> Update group_vars staging with inventory_hostname and correct env

group_vars/repec/common.yml, group_vars/repec/staging.yml
- upgrade node version
- upgrade postgresql version
=> [repec] upgrade staging

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf
related to https://github.com/pulibrary/allsearch_rails_api/issues/10
=> [allsearch] add names to loadbalancer

group_vars/abid/production.yml, playbooks/cicognara.yml, playbooks/postgresql.yml, playbooks/pulfalight.yml, roles/postgresql/meta/main.yml, roles/rails_app/meta/main.yml
Runbook here: https://github.com/pulibrary/abid/issues/132
This has been run.
=> [Abid] Upgrade to Postgres 15

group_vars/repec/production.yml, inventory/all_projects/repec, roles/nginxplus/files/conf/http/repec-prod.conf
- add the jammy virtual machine to inventory
- upgrade postgresql to 15 and node version
=> [repec] upgrade production vm

roles/nginxplus/files/conf/http/catalog-prod.conf
=> [catalog] upgrade orangelight

roles/nginxplus/files/conf/http/lib-static-staging.conf
=> fixes key typo - should be .pem not .key

group_vars/pulmap/production.yml, group_vars/pulmap/staging.yml
Refs pulibrary/pulmap#1164
This has been done, ready to merge.
=> [Pulmap] Update to Postgresql 15

group_vars/orangelight/production.yml, inventory/all_projects/orangelight, roles/nginxplus/files/conf/http/catalog-prod.conf
- migrate to new postgresql server
- comment out bionic vms
=> [catalog] update production

playbooks/upgrade_redis.yml, roles/redis/templates/redis.conf.j2
=> Upgrade redis to 7.2.1

group_vars/pulmap/production.yml, group_vars/pulmap/staging.yml
This allows maps1/2 to talk to the same redis.
=> [Pulmap] Bind redis to 0.0.0.0

group_vars/allsearch_api/common.yml
Forgot to commit this change, sorry!
=> [allsearch] api database followup

group_vars/allsearch_api/common.yml, group_vars/allsearch_api/production.yml
Connected to https://github.com/pulibrary/allsearch_rails_api/issues/74
=> [allsearch_api] Renaming git repo, rename dirs

roles/nginxplus/files/conf/http/nagios-staging.conf, roles/nginxplus/files/conf/http/prometheus-staging.conf
files for prometheus-staging and nagios-staging
=> [nginxplus] add new config files

group_vars/figgy/production.yml
migrate to the new figgy-db-prod1
=> [figgy] migrate to new db

group_vars/dpul/production.yml, group_vars/dpul/staging.yml
Refs https://github.com/pulibrary/dpul/issues/1478
This has been run and migrated.
=> [DPUL] Upgrade to Postgres 15

group_vars/figgy/staging.yml, inventory/all_projects/figgy, playbooks/figgy_staging.yml, roles/figgy/meta/main.yml
We aren't serving it yet; it's the new jammy box.
Also add mediainfo tags we can use to target figuring that out when we
work on it.
=> [Figgy] exclude figgy-web-staging-1 from inventory

roles/nginxplus/files/conf/http/prometheus-staging.conf
remove restriction to allow google cloud auth
=> [nginxplus] prometheus config

group_vars/pulmap/production.yml, group_vars/pulmap/staging.yml, roles/nodejs/defaults/main.yml, roles/nodejs/vars/main.yml
=> Allow nodejs to be downloaded from alternative urls

roles/bibdata/molecule/default/molecule.yml, roles/ezproxy/molecule/default/molecule.yml, roles/passenger/molecule/default/molecule.yml, roles/system_ldap/tasks/main.yml
ensure presence of alphabetized directories
will close #4036
=> [sftp] create directories

group_vars/allsearch_frontend/common.yml, inventory/all_projects/allsearch, inventory/by_environment/staging, playbooks/allsearch_frontend.yml
helps with #4327 
I ran this on staging on 28 September, 2023.
=> [allsearch-frontend] add a very basic playbook

inventory/all_projects/allsearch, inventory/by_environment/production
Related to https://github.com/pulibrary/allsearch_frontend/issues/2.
=> [allsearch] adds allsearch frontend prod to inventory

roles/researchdata/tasks/main.yml
=> Add pg_trgm extension

group_vars/imagecat_rails/main.yml, group_vars/imagecat_rails/staging.yml
point to the new database server
related to https://github.com/pulibrary/imagecat-rails/issues/147
=> [imagecat] migrate to postgres15

group_vars/imagecat_rails/production.yml
this will close https://github.com/pulibrary/imagecat-rails/issues/147
=> [imagecat] upgrade prod

group_vars/allsearch_frontend/common.yml, playbooks/allsearch_frontend.yml
Added deploy user and capistrano
=> [allsearch-frontend] Make app deployable

group_vars/allsearch_frontend/common.yml, playbooks/allsearch_frontend.yml
include staging environment name
=> [allsearch frontend] add passenger

group_vars/pdc_describe/production.yml, group_vars/pdc_discovery/production.yml
migrate pdc-describe to new database server
migrate pdc-discovery to new database server
related to #4246
=> [pdc-describe/pdc-discovery] migrate to be db server

group_vars/allsearch_frontend/production.yml, group_vars/allsearch_frontend/staging.yml
=> [allsearch-frontend] i4327: complete the allsearch frontend playbook

group_vars/researchdata/staging.yml
move researchdata to new db server
related #4246
=> [prds] migrate staging database

group_vars/tigerdata/common.yml, group_vars/tigerdata/production.yml, group_vars/tigerdata/staging.yml
- add postgresql version to 15
- migrate to new db server
- migrate to new db server
related to #4246
=> [tigerdata] upgrade postgresql

group_vars/bibdata/production.yml
upgrade version of postgresql database
point to new database server
=> [bibdata] update node version

inventory/all_projects/pdc_orcid, inventory/by_environment/production, inventory/by_environment/staging
add the new staging and production vms
this will close #4362
=> [pdc-orcid] add new hardware

roles/nginxplus/files/conf/http/imagecat_prod.conf
add new ACME managed certs to point to
=> [imagecat] move new name

group_vars/nginxplus/main.yml, playbooks/nginxplus.yml, playbooks/nginxplus_production_rebuild.yml
This PR would notify both the `#ansible-alerts` channel and the `#infrastructure` channel on slack when someone starts an nginxplus playbook. 
Follow-up to #4382.
=> Notify infrastructure

playbooks/nginxplus.yml, roles/nginxplus/files/conf/http/openbooks.conf
- the curly braces need to be quoted when they are the first item
- remove unneeded ssl_certificates in location block
closes #4393
=> [nginx] make playbook work

roles/nginxplus/files/conf/http/researchdata_staging.conf
eliminates the
````bash
The requested URL was rejected. Please consult with your administrator.
````
error
=> [researchdata] disable waf

group_vars/allsearch_frontend/production.yml, group_vars/allsearch_frontend/staging.yml, roles/allsearch_frontend/templates/env.j2
Added a required config for pulibrary/allsearch_frontend#41
=> Added allsearch api url

group_vars/imagecat_rails/production.yml, roles/nginxplus/files/conf/http/imagecat_prod.conf
add the imagecat-prod name to loadbalancer
related to https://github.com/pulibrary/imagecat-rails/issues/147
=> [imagecat] upgrade database

roles/approvals/tasks/main.yml, roles/drupal9/tasks/capistrano_setup.yml, roles/nodejs/defaults/main.yml, roles/php/tasks/main.yml, roles/rails_app/tasks/main.yml
allow the deploy user to use `systemctl` commands to start, restart, stop the nginx webserver
this will close #4380
=> [rails apps] allow use of systemctl

playbooks/redis_upgrade.yml, roles/redis/molecule/default/molecule.yml, roles/redis/tasks/main.yml
- upgrade the ppa repo for redis
- playbook to upgrade redis package only
closes #4355
=> [redis] upgrade redis ppa

playbooks/os_updates.yml
include a tidy up step to the maintenance
=> [os maintenance] add a cleanup step

inventory/all_projects/allsearch
This adds a new staging server
this will close https://github.com/pulibrary/allsearch_api/issues/96
=> [allsearch_api] add new server

inventory/all_projects/cdh
grant users to cdh staff to postgresql 15 servers
=> [postgresql] add cdh

roles/nginxplus/files/conf/http/abid_prod.conf, roles/nginxplus/files/conf/http/abid_staging.conf, roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf, roles/nginxplus/files/conf/http/allsearch_prod.conf, roles/nginxplus/files/conf/http/allsearch_staging.conf, roles/nginxplus/files/conf/http/annotations_prod.conf, roles/nginxplus/files/conf/http/annotations_staging.conf, roles/nginxplus/files/conf/http/ansible-tower_prod.conf, roles/nginxplus/files/conf/http/approvals_prod.conf, roles/nginxplus/files/conf/http/approvals_staging.conf, roles/nginxplus/files/conf/http/arks.conf, roles/nginxplus/files/conf/http/bibdata_prod.conf, roles/nginxplus/files/conf/http/bibdata_qa.conf, roles/nginxplus/files/conf/http/bibdata_staging.conf, roles/nginxplus/files/conf/http/byzantine-tsp_prod.conf, roles/nginxplus/files/conf/http/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-qa.conf, roles/nginxplus/files/conf/http/cicognara-org.conf, roles/nginxplus/files/conf/http/confluence-staging.conf, roles/nginxplus/files/conf/http/datacommons.conf, roles/nginxplus/files/conf/http/dpul-staging.conf
- add errors for abid
- add errors for allsearch
- add errors for annotations
- add errors for ansible-tower
- add errors for approvals
- add errors for arkss
- add errors for bibdata
- add errors for byzantine-tsp
- add errors for catalog
- add errors for cicognara
- add errors for confluence
- add errors for datacommons
- add errors for dpul
related to #4142
=> [nginxplus] reduce nginxplus warning

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
=> Add geodata urls to Figgy

roles/nginxplus/files/conf/http/confluence-prod.conf, roles/nginxplus/files/conf/http/confluence-staging.conf
=> Comment out proxy errors

group_vars/orcid/main.yml, group_vars/orcid/production.yml, group_vars/orcid/staging.yml
fixes https://github.com/pulibrary/orcid_princeton/issues/85
=> [ORCID] Changing the production server to be pointed at the sandbox for now

group_vars/pulfalight/production.yml, group_vars/pulfalight/qa.yml, group_vars/pulfalight/staging.yml
refs #pulibrary/pulfalight#1314
=> [pulfalight] Update to node 18

roles/nginxplus/files/conf/http/lib-solr9-prod.conf
the server has been configured to connect again
=> [solr9cloud] return server back

group_vars/lae/production.yml, group_vars/lae/staging.yml
Upgrade node on lae to 18.18.0
=> Upgrade node on lae

roles/rails_app/handlers/main.yml, roles/rails_app/tasks/main.yml
- Only restart rails services that are defined on the box
- Allow skipping the rails services restart
closes #4315
helpful for pulibrary/pulfalight#1323
=> Skip rails services restart if it's not there or manually

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
Refs https://github.com/pulibrary/princeton_ansible/issues/3476
=> Upgrade figgy node to 18.18.0

group_vars/orangelight/common.yml
=> Added search and race teams as admins

group_vars/postgres_production_cluster.yml, inventory/all_projects/postgresql
- add postgresql production cluster
- add postgresql warm standby server
=> [postgresql] add warm standby

group_vars/solr9cloud/production.yml, group_vars/solr9cloud/staging.yml
Fixes this datadog monitor: https://app.datadoghq.com/monitors/134239727?source=monitor_notif&live=1h
=> [solr] Update the url used for the http_check on solr 9 boxes

roles/nginxplus/files/conf/http/tigerdata_prod.conf
point tigerdata-prod certs to the new SAN name
closes #4472
=> [tigerdata] create new names

group_vars/byzantine/staging.yml, inventory/all_projects/byzantine
=> [byzantine] migrate database

group_vars/abid/production.yml, group_vars/abid/staging.yml
refs pulibrary/abid#131
This has been run on staging. corresponding abid PR is https://github.com/pulibrary/abid/pull/142
=> [abid] Upgrade node to 18

group_vars/locator/staging.yml
=> upgrade configs for new database related to #4477

group_vars/recap/staging.yml
point the application to the new dev server
=> [recap] upgrade recap-staging

group_vars/all/vars.yml
allow Jaymee to deploy/login etc., to our VMS
Co-authored-by: Jaymee Hyppolite <jaymeeh@users.noreply.github.com>
=> [deploy] add jaymee keys

group_vars/special_collections/staging.yml
=> [special collections] upgrade mariadb

group_vars/all/vars.yml
- grant Jeri access to cdh vms
- remove robert from ops group and add jaymee to pulsys users
=> [pulsys/deploy] add new user

inventory/all_projects/mysql, roles/mysql/tasks/main.yml
add pkg-config to allow playbook to complete
=> [mysql] add jammy vm

group_vars/libwww/production.yml, group_vars/libwww/staging.yml, group_vars/locator/production.yml, group_vars/pas/production.yml
- point libwww_prod to jammy vm
- point locator databases to the jammy VM
- point pas to the new jammy VM
=> [libwww, locator, pas] upgrade to jammy VM

group_vars/byzantine/staging.yml
adds upgraded database to byzantine-tsp-staging
=> [byzantine] update configs for jammy vm

group_vars/ealapps/staging.yml
adds upgraded database to eal-apps-staging
=> [ealapps] update configs for jammy vm 

group_vars/recap/production.yml, group_vars/special_collections/production.yml, group_vars/video_reserves/production.yml
- update db configurations to point to new jammy vm for recap
- point special_collection db to the new jammy VM
- point video reserves to new jammy vm
=> [recap, special collection, video_reserves] upgrade to maria 10.6

roles/nginxplus/files/conf/http/datacommons.conf
Proposed in order to resolve https://github.com/pulibrary/pdc_describe/issues/1630. However, it should be noted that the user independently uploaded the file successfully before these proposed changes were tested within the production environment.
=> Ensuring that the NGINXPlus configuration for datacommons.princeton.edu disables the limitation on HTTP request body size length

group_vars/pas/staging.yml
adds upgraded database to slavery-staging1
=> [pas] adds jammy DB to staging

group_vars/special_collections/staging.yml, group_vars/video_reserves/staging.yml
adds upgraded databases to special_collections_staging and video_reserves_staging
=> [special collections, video_reserves] adds upgraded jammy databases to staging

group_vars/libwww/production.yml, group_vars/locator/production.yml, group_vars/pas/production.yml, group_vars/recap/production.yml, group_vars/special_collections/production.yml, group_vars/video_reserves/production.yml
migrate libwww to new mysql-db-prod1 db
=> [allphp apps] migrate db

group_vars/friends_of_pul/production.yml
upgrade the fpul application server to jammy
=> [fpul] migrate fpul to jammy

group_vars/locator/staging.yml
adds upgraded databases to locator_staging, locator_staging_stage, and locator_staging_production
=> [locator] upgrade staging databases to mariadb 10.6

roles/nginxplus/files/conf/http/datacommons_staging.conf
point the pdc-describe and pdc-discovery to run behind the new domain
closes #4515
=> [datacommons] add a new domain

group_vars/video_reserves/staging.yml
upgrade lib-vr-staging1 to jammy
=> [videoreserves] upgrade to jammy

group_vars/libwww/common.yml, roles/drupal/tasks/main.yml, roles/libwww/tasks/main.yml, roles/libwww/vars/main.yml
- update staging vms to jammy
- update to php_version 8.1
- gulp is needed to install on jammy
- redis-tools are needed to connect to redis server
=> [library-website] update to jammy

group_vars/libwww/common.yml
=> [libwww] upgrade nodejs

roles/apache2/templates/vhosts24.conf.j2
=> [apache2] increase cookie limit

group_vars/pas/staging.yml, inventory/all_projects/pas
we have upgraded the VM to jammy
=> [pas] upgrade vm to jammy

group_vars/ealapps/production.yml, group_vars/pas/production.yml, group_vars/special_collections/common.yml
- make special collections use php 8.1 for jammy Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
- update ealapps and pas to use jammy php
=> [somephp apps] upgrade to jammy

group_vars/locator/common.yml, group_vars/locator/production.yml, group_vars/locator/staging.yml, group_vars/recap/common.yml, roles/drupal/README.md, roles/drupal/defaults/main.yml, roles/mysql/README.md
remove occurences of the unused vault_maria password
=> [locator recap] update to jammy

roles/nginxplus/files/conf/http/cdh_test_prosody.conf
test the jammy VM on the loadbalancer
=> [prosody] test jammy

group_vars/nfsserver/production.yml, inventory/all_projects/cdh, roles/nginxplus/files/conf/http/cdh_prod_prosody.conf, roles/nginxplus/files/conf/http/cdh_test_prosody.conf
comment out the cdh-prosody1 bionic VM
uncomment out the cdh-test-prosody1 jammy VM
=> [cdh/prosody] upgrade to jammy

group_vars/libwww/production.yml
point to the correct special collection db server
will close #4504
=> [libwww] move to jammy redis

group_vars/bibdata/production.yml, group_vars/bibdata/staging.yml, group_vars/nfsserver/production.yml, group_vars/nfsserver/staging.yml, roles/bibdata/tasks/main.yml, roles/bibdata/tasks/mounts.yml, roles/nfsserver/defaults/main.yml, roles/nfsserver/tasks/main.yml
- create new bibdata mount
- add bibdata-alma-worker-staging2
- add production bibdata vms to nfs mount
will close #4507
=> [bibdata] add nfs mounts

playbooks/os_updates.yml
some of our servers are filling up disk space because of retained files. This task fixes that
=> [os-updates] clean up space

group_vars/nfsserver/production.yml, inventory/all_projects/cdh, roles/nginxplus/files/conf/http/cdh_prod_shakespeareandco.conf, roles/nginxplus/files/conf/http/cdh_test_shakespeareandco.conf
- add cdh-shxco jammy VM
- add shxco vms to loadbalancer config
- add cdh-shxco2 to nfs production mount exports
=> [cdh/shxco] upgrade to jammy

playbooks/os_updates.yml
comment out task to clean the local repository related to i4567
=> [os_updates] i4567 comment out apt clean task in maintenance playbook

group_vars/bibdata/qa.yml, group_vars/nfsserver/qa.yml, inventory/all_projects/bibdata, roles/nginxplus/files/conf/http/bibdata_qa.conf, roles/nginxplus/files/conf/http/bibdata_staging.conf
- add new jammy vms back to inventory
- point bibdata to qa postgresql
this closes #4360
=> [bibdata] update to jammy and qa

group_vars/bibdata/qa.yml, group_vars/nfsserver/staging.yml, playbooks/nfsserver.yml
- add nfs mounts
- we need to pass environment variables in playbooks
- YAML files are YAMLitious
=> [bibdata] add nfs staging

group_vars/bibdata/qa.yml, group_vars/nfsserver/common.yml, inventory/all_projects/nfsserver, inventory/by_environment/qa
- add lib-fs-qa server
- point bibdata to qa nfsserver
connect bibdata to nfs-qa fileshare
=> [nfs/bibdata] add qa nfs 

group_vars/orangelight/qa.yml, inventory/all_projects/orangelight, roles/nginxplus/files/conf/http/catalog-qa.conf
add a new indexer-1 machine and bring back the web app vm
deploy application to use new db host
=> [orangelight] add new qa machine

group_vars/all/vars.yml, inventory/all_projects/cdh
- remove lib-postgres-staging3
- grant new cdh dev access to vms
=> [cdh] add new dev

.github/workflows/molecule_tests.yml, roles/common/tasks/main.yml
adds plocate to all our jammy boxes
adds fdfind which is available on the ubuntu repos for jammy
closes #4449
=> [common] this adds plocate to jammy boxes

group_vars/dss/staging.yml, inventory/all_projects/dss, roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/nginxplus/files/conf/http/dss-staging.conf
- upgrade fd-find to use releases from upstream
- add new jammy dss-staging1 VM
- point to the new solr-d cluster
=> [dss] connect to solrd 

group_vars/nfsserver/staging.yml, inventory/all_projects/cdh, roles/common/defaults/main.yml, roles/common/tasks/main.yml
- add derrida vms to the nfsserver exports
- grant cdh folks access to lib-fs-prod vm
- update fd-find to 9.0.0
=> [cdh/derrida] upgrade vms to jammy

inventory/all_projects/ansible_tower
add the new vms to inventory
this will close #4607
=> [ansible] add vms to inventory

inventory/all_projects/_orphans, inventory/all_projects/confluence, inventory/all_projects/postgresql, inventory/all_projects/redis, inventory/by_cloud/google_cloud
these are servers that we shut down or in the process of being sunset
closes #4613
=> [ansible] clean up inventory

inventory/by_environment/production
adding one more after #4614 
these are servers that we shut down or in the process of being sunset
closes https://github.com/pulibrary/princeton_ansible/issues/4613
=> [ansible] i4613_more_inventory_cleanup

group_vars/pdc_discovery/staging.yml
we have a new solr8 cluster.
add the new URL for the application
=> [pdc-discovery] point add new solr URL

inventory/all_projects/byzantine, roles/nginxplus/files/conf/http/byzantine-tsp_prod.conf, roles/nginxplus/files/conf/http/byzantine-tsp_staging.conf
upgrade byzantine to use jammy
=> [byzantine] upgrade vms to jammy

inventory/by_environment/production, inventory/by_environment/staging
Partial fix for #4018.
Not sure this is the best approach; we can discuss here.
=> Adds GCP groups to staging and prod supergroups

roles/nginxplus/files/conf/http/maps-prod.conf
See
https://docs.google.com/document/d/1b7rjSdW7DKXC9B2MlEuHcn7XkMdbjZBuek2Pn1A_5zA/edit for incident notes.
=> [Pulmap] Prevent downtime from passive health checks.

inventory/by_cloud/google_cloud
this server was decommissioned
=> [prancible] inventory

group_vars/tigerdata/common.yml
Ref https://github.com/pulibrary/tiger-data-app/issues/437
=> [TIGERDATA] Upgrade ruby to 3.2.3

roles/nginxplus/files/conf/http/lae-prod.conf, roles/nginxplus/files/conf/http/lae-staging.conf
following the example in #4072
=> [lae] Add rate limiting to staging and prod

roles/nginxplus/files/conf/http/lae-prod.conf
I hate to do it, but it's bringing things down and it's the end of the day.
=> [LAE] Block Dubbot

README.md
all of our images are now on quay
the steps allow one to delete stale containers
=> [prancible] quay repository

group_vars/allsearch_api/common.yml
Sibling PR: https://github.com/pulibrary/allsearch_api/pull/170
=> [allsearch-api] Ruby 3.3

group_vars/allsearch_api/common.yml
I forgot to commit this with #4560  -- sorry!
=> [allsearch-api] Bundler 2.5.6

inventory/all_projects/checkmk, inventory/by_environment/production, inventory/by_environment/staging
the checkmk staging and production vms will be added to our inventory
related to #4624
=> [checkmk] add new hosts

inventory/all_projects/cdh
grant cdh users access to new solr8d staging cluster
related #4666
=> [solr] add cdh users

group_vars/allsearch_frontend/common.yml
Sibling PR: https://github.com/pulibrary/allsearch_frontend/pull/247
=> [allsearch-frontend] node 20.11.1

group_vars/bibdata/common.yml, group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml
Since all environments are now on Jammy, move nodejs version to common.yml
Run and deployed against staging, looks good.
Connected to https://github.com/pulibrary/bibdata/pull/2314
=> Upgrade node

roles/postgresql/tasks/main.yml, roles/pulmap/meta/main.yml
- Also allows running playbooks on Bionic servers.
=> Replace pulmap blacklight_app with rails_app role

group_vars/lib_jobs/common.yml
Resolves pulibrary/lib_jobs#663
Run and deployed on staging and works correctly.
See also pulibrary/lib_jobs#667 - nice to have but not required to run on production
=> [lib_jobs] Both upgrade and preload bundler

inventory/all_projects/_orphans, inventory/by_environment/staging
- **add the sandbox vms to inventory**
=> [prancible] add sandbox vms

group_vars/dss/common.yml
related to https://github.com/pulibrary/DSS/pull/415
related to https://github.com/pulibrary/dacs_handbook/issues/157
=> [DSS-node-20.11.1] update node to 20.11.1

group_vars/approvals/common.yml, group_vars/approvals/production.yml, group_vars/approvals/staging.yml
sibling PR#approvals
related to https://github.com/pulibrary/dacs_handbook/issues/157
=> Update node to 20.1.1

roles/nginxplus/files/conf/http/approvals_prod.conf
updates approval to jammy on both vms
=> [approvals] add lib-approvals-prod1

group_vars/all/vars.yml
this will remove ryans keys from all vms
=> [cdh] remove cdh dev

group_vars/lae/production.yml, playbooks/lae.yml
Work towards https://github.com/pulibrary/lae-blacklight/issues/372
=> [LAE] Add Datadog to LAE

group_vars/geaccirc/common.yml
Closes https://github.com/pulibrary/geaccirc/issues/43
Connected to https://github.com/pulibrary/dacs_handbook/issues/157
=> [geaccirc] Upgrade node

group_vars/orcid/main.yml
Ref https://github.com/pulibrary/orcid_princeton/issues/124
=> [ORCID] Upgrade ruby to 3.2.3

group_vars/bibdata/staging.yml, group_vars/orangelight/staging.yml
Point catalog-staging and bibdata-staging Solr url to lib-solr8d-staging
=> Point catalog-staging and bibdata-staging to the new solr8d staging cluster

group_vars/pulmap/production.yml, inventory/all_projects/pulmap, roles/nginxplus/files/conf/http/maps-prod.conf, roles/nginxplus/files/conf/http/maps-staging.conf, roles/pulmap/tasks/main.yml
Upgrade pulmap to Jammy boxes.
=> [Maps] Jammy Upgrade

group_vars/figgy/production.yml
This is done in production - all the data's been moved.
=> [Figgy] Migrate redis from figgy1 to figgy-web-prod1.

roles/postgresql/tasks/main.yml, roles/postgresql/templates/statistics_conf.j2
make sure the explain configurations persist
the explain configurations will be added to the conf.d directory
closes #3699
=> [postgresql] make the configurations stick

.gitignore, roles/nginxplus/files/conf/http/library-prod.conf, roles/nginxplus/files/conf/http/library-staging.conf
See #[i4740 ](https://github.com/pulibrary/princeton_ansible/issues/4740)
=> [nginxplus] Add X-Frame config to library-staging and library-prod

group_vars/lib_jobs/common.yml, group_vars/lib_jobs/production.yml, group_vars/lib_jobs/staging.yml
closes #4747 
related to https://github.com/pulibrary/lib_jobs/issues/695#issuecomment-1992279085
=> [lib-jobs] Add alma_recap_output_dir for staging and production

group_vars/lib_jobs/common.yml
closes #4755 
I ran the playbook and the env variables are on staging and production.
=> Add rails env variables in common.yml

group_vars/dpul/production.yml, group_vars/figgy/production_webserver.yml, group_vars/pulfalight/production.yml, group_vars/pulmap/production.yml
We check the JSON - if it fails because of the status code then if one goes down they'll all say they're down.
=> [Figgy/DPUL/Pulmap/Pulfalight] Ignore http code check for monitors.

group_vars/dpul/staging.yml, group_vars/lae/staging.yml
add jinja spacing from linter
we need to retire the solr8 cluster and point vms to the new one
related to #4666
=> [dpul] migrate to solr8d

group_vars/all/vars.yml
we remove liz garcia's keys and give john key key based access
this closes #4767
```
=> [prancible] remove liz garcia keys

group_vars/pulmap/staging.yml
we are moving off the bionic solr8 cluster
this is related to #4666
closes https://github.com/pulibrary/pulmap/issues/1201
=> [pulmap] migrate pulmap to solr8d

group_vars/pulfalight/qa.yml, roles/rails_app/README.md
closes pulibrary/pulfalight#1384
=> [pulfalight-qa] use new staging cluster

group_vars/figgy/staging.yml
This has been run and the new index is populating.
refs pulibrary/figgy#6214
=> [Figgy] migrate staging to new solr cluster

group_vars/oawaiver/staging.yml
we are moving solr to the jammy infrastructure
=> [oawaiver] migrate solr

roles/nginxplus/files/conf/http/pulfalight-prod.conf, roles/nginxplus/files/conf/http/pulfalight-qa.conf, roles/nginxplus/files/conf/http/pulfalight-staging.conf
closes pulibrary/pulfalight#1282
=> [pulfalight] allow upstream to serve its 404 page

group_vars/figgy/production_webserver.yml
Work towards https://github.com/pulibrary/figgy/issues/6260
=> [Figgy] Add RabbitMQ Monitoring

group_vars/dpul/production.yml, group_vars/figgy/production_webserver.yml, group_vars/pulfalight/production.yml, group_vars/pulmap/production.yml
=> [Figgy/Maps/DPUL/Pulfalight] Use filtered health monitors.

group_vars/dpul/production.yml, group_vars/figgy/production_webserver.yml, group_vars/pulfalight/production.yml, group_vars/pulmap/production.yml
=> [DLS apps] Fix health check provider filters

inventory/all_projects/oawaiver
=> [oawaiver] add oawaiver-prod1 back into the inventory

inventory/all_projects/oawaiver
=> [oawaiver] adding oawaiver-staging1 back into the inventory

group_vars/figgy/production_webserver.yml
Adds the Figgy PDF file watcher health check to Datadog.
=> [DLS apps] Add PDF file watcher health check

roles/nginxplus/files/conf/http/oawaiver-prod.conf, roles/nginxplus/files/conf/http/oawaiver-staging.conf
=> [nginxplus] add oawaiver VMs back into nginxplus config

group_vars/figgy/production_webserver.yml
advances pulibrary/figgy#6287
this was run.
=> [Figgy] Add sidekiq monitor

group_vars/figgy/production.yml, group_vars/figgy/staging.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml
=> Add figgy-realtime-workers

group_vars/pulfalight/qa.yml, group_vars/pulfalight/staging.yml
=> Add sidekiq pro to pulfalight

group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
=> Update rabbitmq staging host in catalog-qa and catalog-staging

group_vars/figgy/staging.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml, roles/figgy/templates/nginx_extra_config, roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf
=> [Figgy] Add Websocket Configuration

roles/nginxplus/files/conf/http/dss-prod.conf
This persists a change that was done earlier today on the load balancers.
=> [dss] Uncomment an app server from loadbalancer config

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml, inventory/all_projects/redis, inventory/by_environment/qa
- **add the new redis-qa vm to the inventory**
- **change the value of the redis db to point to the redis cluster**
- **add redis URI for production**
-  closes #4836
=> [bibdata] new redis URIs

inventory/all_projects/zookeeper, inventory/by_cloud/google_cloud
related to #[4018](https://github.com/pulibrary/princeton_ansible/issues/4018)
=> updating inventory so that machines are reachable via Tower

group_vars/all/checkmk.yml, playbooks/utils/checkmk_agent.yml
was suggested in https://github.com/pulibrary/princeton_ansible/pull/4652#issuecomment-1965498582
=> [CHECKMK] Move vars to a file so they can eventually be overridden

playbooks/approvals.yml, playbooks/bibdata.yml, playbooks/lib_jobs.yml, roles/approvals/meta/main.yml, roles/approvals/molecule/default/converge.yml, roles/bibdata/molecule/default/converge.yml, roles/hr_share/meta/main.yml, roles/hr_share/molecule/default/converge.yml, roles/lib_jobs/meta/main.yml, roles/lib_jobs/molecule/default/converge.yml, roles/samba/meta/main.yml, roles/samba/molecule/default/converge.yml
- Reduces running the "common" role by 1 in approvals, bibdata, and lib_jobs playbooks
=> [samba] Remove dependency on common

playbooks/utils/temp_files.yml
- **delete unused temp files**
- **pass a variable for those who need deletion to happen more frequently than once a week**
refs #4552
=> [prancible] delete temp files

playbooks/utils/remove_rapid7.yml
Co-authored-by: G. Philippe Menos <gpmenos@users.noreply.github.com>
Co-authored-by: John Kazmierski <jkazmier-pul@users.noreply.github.com>
Co-authored-by: Stephanie Ayers <stephayers@users.noreply.github.com>
=> [rapid7] playbook to uninstall Rapid7

inventory/by_environment/staging
add the staging hosts to inventory
=> [nginxplus] add staging

inventory/all_projects/bibdata
new vms to test SQS poller for coherence
closes #4877
=> [bibdata] add new vms

group_vars/nfsserver/production.yml, group_vars/nfsserver/staging.yml
- **add bibdata staging to allow list**
- **NFS servers require IPs to allow connections**
=> [bibdata/nfs] allow access to NFS servers

roles/denyhost/vars/main.yml
we remove the ban on Francis and leave it as example documentation
=> [prancible] unban Francis

Pipfile, Pipfile.lock
allows us to scaffold our roles better now that molecule no longer
does this
=> [prancible] add ansible-creator

roles/libstatic/defaults/main.yml, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
=> Moved marquand-catalogs to static-tables

roles/denyhost/templates/deny_list.j2, roles/denyhost/vars/main.yml
- **correct YAML markup on a previous PR**
- **place holder for adding descriptions in templates**
- **we may need to YAML'ize it but this unbreaks the FW**
=> [denyhosts] add a description field

inventory/all_projects/static_tables
we add the static-tables vms
closes #4908
=> [static-tables] new VMs

playbooks/static_tables.yml, roles/static_tables/files/default.conf, roles/static_tables/files/nginx.conf, roles/static_tables/handlers/main.yml, roles/static_tables/tasks/main.yml
Currently only works when you git clone into the `/opt/static_tables/current` directory
```
(as deploy)
cd /opt/static_tables/
git clone https://github.com/pulibrary/static-tables.git current
(as pulsys)
sudo systemctl restart nginx
```
=> Static tables playbook

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf, roles/static_tables/files/nginx.conf
Remove unneeded local nginx config
Closes #4934
=> Fix static tables proxy pass rules

roles/denyhost/vars/main.yml
This ASN hit us at DPLA this morning:
Let me know if you want me to do something specific with the description. I just listed the ASN, which shows up IPinfo.io like this:
=> Banned 1.14.128.0/18 (Tencent)

roles/static_tables/files/default.conf
advances pulibrary/static-tables#26
=> [pulibrary/static-tables#26] Add try_files

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Run on load balancers, works.
Closes #4878
=> Static tables direct urls

group_vars/pdc_discovery/production.yml
refs https://github.com/pulibrary/pdc_discovery/issues/626
=> [PDC Discovery] Adding missing quotes around variables

roles/denyhost/vars/main.yml
=> Added 43.155.128.0/18

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Update previous sites to use /special-collections/databases/ path
=> [static_tables] Add more new sites

roles/common/defaults/main.yml
because it is the best and I am constantly installing it
=> Add tree as a default package

inventory/all_projects/nomad, inventory/by_environment/production
Co-authored-by: Sean Warren <seanwarren77@users.noreply.github.com>
=> Added nomad boxes inventory details

roles/nginxplus/files/conf/http/cdh_prod_derrida.conf
=> [cdh] derridas-margins-beta

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Re-order so they're in alphabetical order. Add last two sites.
Run successfully on the load balancers.
=> [static_tables] Add two more proxy-pass rules

group_vars/pdc_discovery/main.yml, group_vars/pdc_discovery/staging.yml
Advances https://github.com/pulibrary/pdc_discovery/issues/603
=> Updating Ruby to release 3.2.4 for PDC Describe

group_vars/orangelight/common.yml, roles/orangelight/tasks/main.yml
We ran this on staging and prod today
=> [Orangelight] Fix broken passenger/bundler interaction

roles/nginxplus/tasks/prerequisites/install-prerequisites.yml
=> [prancible] unbreak CI

group_vars/nginxplus/staging.yml, playbooks/nginxplus_staging.yml, roles/nginxplus/files/conf/http/cdh_prod_derrida.conf, roles/nginxplus/tasks/conf/upload-config.yml
remove the beta name. We will need to change the name and remove the beta label
=> [cdh] retire beta name

playbooks/nginxplus_staging.yml, roles/nginxplus/files/conf/http/dev/nomad.conf
Refs https://github.com/pulibrary/dpul-collections/issues/18
=> [Nomad] Add Nomad to dev load balancer.

playbooks/nginxplus_staging.yml, roles/nginxplus/files/conf/http/dev/dpul-collections-staging.conf
refs pulibrary/dpul-collections#13
=> Add dpul-collections-staging with Nomad lookup

roles/nginxplus/files/conf/http/cdh_prod_derrida.conf
remove all configurations for derridas-margins-beta
=> [cdh] add derrida prod2 vm

playbooks/pulfalight.yml
closes pulibrary/pulfalight#1363
=> Add notification about IP allow lists to pulfalight playbook

group_vars/allsearch_api/common.yml, group_vars/allsearch_api/production.yml, group_vars/allsearch_api/staging.yml
Run successfully on staging and production
This is a first step to ensuring we keep the allsearch api in sync with the applications it consumes
Connected to #5013
=> [allsearch_api] Use environment variables for Solr

inventory/all_projects/cdh, roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
Create the staging loadbalancer name on load balancer
=> [cdh] add prodigy project

roles/nginxplus/files/conf/http/cdh_prod_prodigy.conf, roles/nginxplus/files/conf/http/cdh_test_prodigy.conf
adding new vms and deleting domain we cannot control
=> [cdh] add prod views

README.md, bin/first-time-setup.sh
1. Create a zsh script that handles some of the asdf gotchas
2. Add a Table of Contents with just the steps you need to run a playbook
Closes #5021
=> Clearer instructions for first-time users

roles/postfix/README.md
Added a pointer to the playbook that will need to be run and deleted boilerplate "example playbook" section.
=> [postfix] clarify usage in role README

group_vars/approvals/common.yml, roles/approvals/tasks/main.yml
I ran this on staging and prod today
=> [approvals] install specific rubygems and default bundler versions

group_vars/repec/common.yml, roles/repec/tasks/main.yml
Install specific rubygems; 
Install default bundler; 
Turn on passenger_preload_bundler;
=> [Repec] Fix broken staging VM because of bundler version on staging VM

inventory/all_projects/whichiso, inventory/by_environment/production, inventory/by_environment/staging
=> Add whichiso vms to inventory

roles/nginxplus/files/conf/http/whichiso_prod.conf, roles/nginxplus/files/conf/http/whichiso_staging.conf
=> Add whichiso conf files

group_vars/libwww/staging.yml
CheckMK was warning us that mailcatcher was not running on library-staging[1:2]. When we investigated, it turned out that the gem path was wrong. This PR updates the path. We've already run it against the staging infrastructure.
=> update mailcatcher var to match current gem for libwww

inventory/all_projects/_orphans
Related to https://github.com/pulibrary/ops-catchall/issues/77#event-13245153057
=> [Inventory] Update sandboxes in inventory

inventory/all_projects/cdh, roles/nginxplus/files/conf/http/cdh_prod_web.conf
create a new server block for the beta website that will point to the
new VMs. The cdh-beta name is already part of the SAN cert
closes #5081
=> [cdh] add cdh-web3 and 4

group_vars/pdc_discovery/main.yml
=> Updating to Ruby release 3.3.2 for pdc_discovery

.github/ISSUE_TEMPLATE/maintenance.md
Follow up to #5090. See also #5089.
We decided the maintenance template is also useful.
=> Adds a maintenance template to the issue templates for this repo

roles/nginxplus/files/conf/http/ojs-prod.conf, roles/nginxplus/files/conf/http/openpublishing.conf
- **remove openpublishing references**
- **remove openpublishing references and rename file**
this is related to #5087
we have migrated openpublishing but still have OJS running
=> [ojs] rename openpublishing

inventory/all_projects/mediaflux, inventory/by_environment/production, inventory/by_environment/staging
add media staging and production virtual machines
related to #5124
=> add mediaflux virtual machines

group_vars/orcid/main.yml
Ref https://github.com/pulibrary/orcid_princeton/issues/166
=> [orcid] Upgrade bundler

roles/nginxplus/files/conf/http/tigerdata_prod.conf
tigerdata-app already had it, but I didn't notice there was a second place to change
=> [TIGERDATA] allow tigerdata-prod to have the custom error page

roles/towerdeploy/molecule/default/verify.yml, roles/towerdeploy/tasks/main.yml
Follows up on #5138.
Updates test, adds comment about 'changed' output.
=> Fix tests for towerdeploy role

playbooks/utils/firewall_source_address_delete.yml
=> [#5156] Create a basic playbook for communicating with the test firewall

roles/postfix/vars/main.yml
Work towards https://github.com/pulibrary/figgy/issues/6455
Work towards https://github.com/pulibrary/pulfalight/issues/1426
=> [Postfix] Add new servers allowed to use the mail relay.

group_vars/pdc_discovery/main.yml
=> [PDC-DISCOVERY] Allow strscan to be a different version than the default ruby

group_vars/nfsserver/staging.yml, inventory/all_projects/byzantine, roles/nginxplus/files/conf/http/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/dev/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/dev/templates/errors.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
=> add .lib domain to byzantine sites

group_vars/orangelight/common.yml
Adding Steph and myself to Orangelight admins group, so we can turn banner alerts on/off.
=> Adding Steph and Esmé to Orangelight admins group

roles/common/tasks/main.yml, roles/common/tasks/vector.yml
For now this is mostly accomplished by only doing apt things with Debian systems.
Refs #5098
=> [Common] Add support for Rocky

roles/nginxplus/files/conf/http/allsearch-api_prod.conf, roles/nginxplus/files/conf/http/allsearch-api_staging.conf
=> 5114 allsearch health checks

roles/libstatic/defaults/main.yml
Completes the the first half of https://github.com/pulibrary/princeton_ansible/issues/3891
=> Add cotsen exhibit archive to libstatic.

group_vars/figgy/staging.yml
Refs https://github.com/pulibrary/figgy/pull/6453/files
=> [Figgy] Add Plausible API key to Figgy Staging.

inventory/all_projects/lib-static
this VM is now on the private network and we are adding the DNS to
reflect that
=> [lib-static] update inventory

Pipfile.lock, group_vars/tigerdata/staging.yml, roles/nginxplus/files/conf/http/dev/tigerdata_staging.conf, roles/nginxplus/files/conf/http/tigerdata_prod.conf, roles/nginxplus/files/conf/http/tigerdata_qa.conf, roles/tigerdata/templates/nginx_extra_config.j2
This is necessary in order to support the changes merged from https://github.com/pulibrary/tiger-data-app/pull/770
=> Adding NGINX support for WebSocket requests within TigerData environments

roles/denyhost/vars/main.yml
it was attacking pdc discovery
=> Add a new bad ip

group_vars/libstatic/production.yml, inventory/all_projects/lib-static, inventory/all_projects/static, inventory/by_environment/production, playbooks/libstatic.yml, playbooks/static.yml, roles/libstatic/defaults/main.yml, roles/libstatic/molecule/default/verify.yml, roles/nginxplus/files/conf/http/static_prod.conf
=> I5146 static prod

inventory/all_projects/ealapps, roles/nginxplus/files/conf/http/dev/eal_staging.conf
add a new config for eal on the dev loadbalancer
=> [eal] migrate to private net

inventory/all_projects/orcid, roles/nginxplus/files/conf/http/orcid_prod.conf
Also make inventory group for orcid
refs https://github.com/pulibrary/orcid_princeton/issues/181
=> [NGINX] Allowing production ORCID to be accessed outside the VPN

inventory/all_projects/ealapps, inventory/by_service/apache, playbooks/ealapps.yml, roles/nginxplus/files/conf/http/eal_prod.conf
- **add production vm to inventory**
- **add new production configuration**
- **retire the old eal-apps vm**
related to #5148
=> [EAL] production

inventory/all_projects/_orphans, roles/nginxplus/files/conf/http/dev/sandbox_aspace.conf
- **use port 8080**
- **add aspace-sandbox1 to inventory**
=> [archivesspace] add loadbalance config

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Run successfully on both load balancers.
Closes #5149
=> [video_reserves] Remove libwww proxy-pass rules for video_reserves

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Run successfully on both load balancers
=> Revert video reserves

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf
Tried on staging, ran on load balancers.
=> Rewrite rule for videoreserves

roles/datadog/defaults/main.yml, roles/datadog/molecule/default/converge.yml, roles/datadog/molecule/default/molecule.yml, roles/datadog/tasks/agent6.yml, roles/datadog/tasks/main.yml, roles/datadog/tasks/pkg-debian.yml
- **update datadog expired keys**
- **the datadog keys expire**
=> [prancible] add datadog repo key

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf
=> [libwww] remove proxy pass rules in nginxplus configs for apps affiliated with libserv39

roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
=> [libwww] remove references to applications hosted on lib-static-prod

group_vars/dpul/production.yml, group_vars/dpul/staging.yml, inventory/all_projects/dpul, roles/rails_app/tasks/main.yml
Necessary for upgrading to a new version of Spotlight.
=> [DPUL] Install libidn-dev

group_vars/all/vars.yml
move beck from the devs to the Ops Keys
Co-authored-by: Brionna Johnson <bj4103@users.noreply.github.com>
Co-authored-by: John Kazmierski <jkazmier-PUL@users.noreply.github.com>
=> [prancible] add beck

inventory/all_projects/mediaflux, inventory/all_projects/mflux, roles/nginxplus/files/conf/http/mflux_ci.conf
modify the hostname of mflux-ci1 and create a NGINX config on the
loadbalancer
=> [mediaflux] add world reachable host

inventory/all_projects/orcid, playbooks/utils/checkmk_add_local_checks.yml, playbooks/utils/checkmk_add_rule.yml
also added the checkmk health url for ORCID
refs https://github.com/pulibrary/orcid_princeton/issues/182
=> [CHECK_MK] update the local and role checks to use the new shorter ansible host names

inventory/all_projects/pdc_describe, roles/nginxplus/files/conf/http/pdc-describe_prod.conf
we have a need for a 3rd production VM
closes #5264
=> [pdc-describe] add a new VM

roles/nginxplus/files/conf/http/fpul-prod.conf, roles/nginxplus/files/conf/http/library-prod.conf
currently this website is accessible outside of the princeton network.
closes #5255
=> [libwww] block external access

group_vars/dpul/production.yml, group_vars/dpul/staging.yml
This fixes loading gems for newer Rails versions.
=> [DPUL] Add preload_bundler to nginx

roles/postgresql/templates/postgresql.conf.j2
=> Reduce log level back to default for psql.

group_vars/pdc_describe/main.yml, roles/sidekiq_worker/handlers/main.yml, roles/sidekiq_worker/tasks/main.yml
Also restart the daemon when updating sidekiq
=> [PDC_DESCRIBE] add more threads to sidekiq and connection pool

group_vars/nomad_cluster.yml, roles/ansible-nomad/tasks/install.yml
Performed already - no downtime!
=> [Nomad] Update to 1.8.3

roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf
=> Ensuring that the health checks for PDC Describe URIs resolve to /describe/health.json

roles/mflux/tasks/main.yml
refs [#869](https://app.zenhub.com/workspaces/rdss-61a4f1a12a399b001730f65a/issues/gh/pulibrary/tiger-data-app/869)
=> install the mediaflux desktop and restart mediaflux

group_vars/bibdata/common.yml, roles/bibdata/tasks/main.yml
related to: https://github.com/pulibrary/bibdata/issues/2459
Provisioned bibdata-staging. 
Waiting for an [incremental to finish](https://github.com/pulibrary/bibdata/issues/2451#issue-2474276862) and will provision production.
=> [Bibdata] Upgrade to ruby 3.2.0; Install default bundler 2.5.17

roles/libstatic/defaults/main.yml
Adding two new repos for the SC libserv55 archive and CaMS docs archive.
=> Add new archives for SC and Cams.

inventory/all_projects/_orphans
create a sandbox for regine to work on shared files
=> [aspace] remove files

group_vars/lae/production.yml, group_vars/lae/staging.yml
refs pulibrary/lae-blacklight#391
=> Set "passenger_preload_bundler on;" for lae

group_vars/figgy/production.yml, group_vars/figgy/staging.yml
=> [Figgy] Add preload bundler for Rails 7.1

group_vars/pulmap/production.yml, group_vars/pulmap/staging.yml, playbooks/pulmap.yml, roles/pulmap/tasks/main.yml
Refs https://github.com/pulibrary/pulmap/pull/1226
Ran these with
```
ansible-playbook playbooks/pulmap.yml -t passenger_config -t rubygems -e "nginx_user=www-data"
=> Add pulmap fixes for Rails 7.1

roles/nginxplus/files/conf/http/datacommons.conf
=> Adding healthcheck to datacommons

roles/mflux/tasks/ldap-config.yml
refs https://github.com/pulibrary/tigerdata-app/issues/904
=> [MFLUX] Add in standard roles to princeton users

group_vars/figgy/production_webserver.yml
=> [Figgy] Add an http check for the ingest mount health monitor

roles/mflux/tasks/custom-roles.yml, roles/mflux/tasks/ldap-config.yml, roles/mflux/tasks/server.yml
refs [#904 ](https://github.com/pulibrary/tigerdata-app/issues/904)
=> Adding the pul-lib:developer role and add it to the princeton domain

roles/mflux/tasks/server.yml
=> Adding additional mediaflux configurations

group_vars/nfsserver/staging.yml, inventory/all_projects/bibdata, roles/nginxplus/files/conf/http/dev/bibdata_staging.conf
modify exports for nfs
add new addresses to inventory
move config to dev loadbalancer'
=> move bibdata to private network

inventory/all_projects/pdc_describe
=> Updating inventory for PDC describe redis VM's

group_vars/allsearch_frontend/staging.yml, group_vars/bibdata/staging.yml, group_vars/orangelight/staging.yml, roles/allsearch_frontend/templates/env.j2
Rename bibdata-staging.princeton.edu to bibdata-staging.lib.princeton.edu
Bibdata staging is on adc-dev and using the .lib
=> Rename bibdata staging

inventory/all_projects/pas, inventory/by_environment/staging
=> [PAS] Adding new VM's to new inventory

roles/nginxplus/files/conf/http/slavery-dev.conf
=> [nginxplus] add nginxplus configs for slavery-dev sites

playbooks/utils/create_wapiti_report.yml
closes https://github.com/pulibrary/dacs_handbook/issues/236
Scan and create an html report
=> [DACS#236] Install wapiti in localhost

group_vars/nfsserver/staging.yml, group_vars/pas/staging_upgrade.yml
add the two vms to the NFS export
related to #5354
=> add pas upgrade vms to NFS

group_vars/oawaiver/staging.yml, playbooks/oawaiver.yml
on the staging variables ensure that mailcatcher is installed and
configured :mailbox:
closes #5009
=> [oawaiver] add mailcatcher to staging

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/bibdata/staging.yml
=> [BIBDATA] #2177 Remove unused SCSB_S3_USER_NAME var from the bibdata playbook

roles/postfix/tasks/main.yml
this modification allows postfix to enable port 587 locally
make smarttls work
=> [postfix] enable port 587

roles/postfix/tasks/main.yml
last commit removed listening on port 25
this brings it back with a comment
related to #5023
=> [postfix] enable port 25

roles/postfix/vars/main.yml
slavery-staging-upgrade1.lib.princeton.edu 
slavery-staging-upgrade2.lib.princeton.edu
=> [POSTFIX] adding pas upgrade vms to postfix list

roles/nginxplus/files/conf/http/thesis_central.conf
this adds a permanent redirect for thesis-central
it includes TLS certs
related to https://github.com/pulibrary/rdss-catchall/issues/141
=> [thesis-central] add a nginx config

roles/nginxplus/files/conf/http/dss-prod.conf, roles/nginxplus/files/conf/http/dss-staging.conf
=> Use health check endpoint for staging

inventory/all_projects/orangelight
=> [Orangelight] #5198 Add a healthcheck monitor to checkmk

roles/nginxplus/files/conf/http/repec-prod.conf, roles/nginxplus/files/conf/http/repec-staging.conf
=> [repec] Add X-Forwarded-Proto https

inventory/all_projects/mflux, inventory/by_cloud/google_cloud, inventory/by_environment/qa
=> Add mflux-qa1 to inventory

roles/postfix/vars/main.yml
add the two vms to the relay
related to #5307
=> [cdh] add vms to relay

inventory/all_projects/cdh
Related to this https://github.com/Princeton-CDH/cdh-ansible/pull/240
Allow cdh folk to check mail relay logs
=> [cdh] pony express

roles/postfix/vars/main.yml
libserv14 and 144 are added to the allow list
=> [postfix] new hosts

roles/nginxplus/files/conf/http/dev/tigerdata_staging.conf, roles/nginxplus/files/conf/http/oawaiver-prod.conf, roles/nginxplus/files/conf/http/oawaiver-staging.conf, roles/nginxplus/files/conf/http/orcid_prod.conf, roles/nginxplus/files/conf/http/orcid_staging.conf, roles/nginxplus/files/conf/http/tigerdata_prod.conf, roles/nginxplus/files/conf/http/tigerdata_qa.conf
=> [NGINX] adding https stanza to other RDSS applications

playbooks/mflux-docker.yml, roles/mflux/tasks/main.yml
refs [#969](https://app.zenhub.com/workspaces/rdss-61a4f1a12a399b001730f65a/issues/gh/pulibrary/tigerdata-app/969)
=> upgrading the mediaflux version and pushing a tagged release to docker hub

roles/nginxplus/files/conf/http/dev/dpul-collections-staging.conf
closes pulibrary/dpul-collections#147
=> [DPUL-C] allow websocket traffic

inventory/all_projects/pas
Previously, I was getting the error:
```
fatal: [slavery-staging1.princeton.edu]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"slavery-staging1.princeton.edu\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname slavery-staging1.princeton.edu: nodename nor servname provided, or not known\r\n", "unreachable": true}
```
=> [PAS] update inventory to .lib.princeton.edu domain

inventory/by_cloud/google_cloud
we missed two cdh staging applications in our inventory
this adds geotaste and simrisk
=> add cdh projects to inventory

inventory/all_projects/nomad
add the nomad-client-staging1 vm
this closes #5458
=> [nomad] add new vm

roles/nfsserver/tasks/packages.yml
rocky linux will need dnf not apt
=> [nfsserver] use the right module

group_vars/nomad_clients.yml, group_vars/nomad_clients_workers.yml, inventory/all_projects/nomad
This lets us make jobs prefer going to a certain type of node.
See https://github.com/pulibrary/dpul-collections/pull/117
=> [Nomad] Add node type to metadata.

roles/nginxplus/files/conf/http/catalog-qa.conf
The machine has been rebuilt (see #5431)
=> [prancible] adding catalog-qa1 back to the loadbalancer 

roles/nginxplus/files/conf/http/dev/cdh_test_htr.conf
disable the WAF for htr websites
=> [cdh] disable WAF

roles/nginxplus/files/conf/http/dev/tigerdata_staging.conf, roles/nginxplus/files/conf/http/tigerdata_prod.conf, roles/nginxplus/files/conf/http/tigerdata_qa.conf
Fixes https://github.com/pulibrary/princeton_ansible/issues/5115
=> [tigerdata] Add health.json for health check uri

roles/nginxplus/files/conf/http/geaccirc.conf, roles/nginxplus/files/conf/http/geaccirc_staging.conf
Add a health check to loadbalancer
this will close #5117
=> [geaccirc] add health check

roles/nginxplus/files/conf/http/repec-prod.conf, roles/nginxplus/files/conf/http/repec-staging.conf
Run on all relevant load balancers (both production ones)
Closes #5111
=> [repec] add health check

roles/nginxplus/files/conf/http/lockers-and-study-spaces-prod.conf, roles/nginxplus/files/conf/http/lockers-and-study-spaces-staging.conf
Run on relevant load balancers (both production load balancers)
Closes #5109
=> [lockers] add health check

roles/nginxplus/files/conf/http/dpul-prod.conf, roles/nginxplus/files/conf/http/dpul-staging.conf
Run on both prod load balancers
Closes #5106
=> [dpul] add health check

roles/nginxplus/files/conf/http/pulfalight-prod.conf, roles/nginxplus/files/conf/http/pulfalight-qa.conf, roles/nginxplus/files/conf/http/pulfalight-staging.conf
=> [pulfa] add health check

roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf
=> [Figgy] Use health.json for health checks

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/catalog-staging.conf
have the load balancer configuration check the health gem generated file
to determine health of upstream VM
closes #5116
=> [orangelight] add a health check

group_vars/abid/staging.yml
add port 80 access from the private vlan to the vm
related to #5471
=> [abid] update fw rules

group_vars/orangelight/common.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
- QA still seems broken, but I'm not sure if it's related
- Trying to use a default value in common.yml did not work, because the value in production was always being used, not falling back to the default if it wasn't set in staging or qa
- Needed to update the mailcatcher path
Connected to #5410
=> [orangelight] Fix mailcatcher in staging

inventory/by_cloud/aws
=> [globus] adding lib-ops-globus instance to inventory

roles/common/molecule/default/molecule.yml, roles/nfsserver/molecule/default/converge.yml, roles/nfsserver/molecule/default/molecule.yml, roles/nfsserver/molecule/default/verify.yml
add tests to the nfsserver role
use a new jammy container from github
=> [nfsserver] update container

roles/nginxplus/files/conf/http/approvals_prod.conf, roles/nginxplus/files/conf/http/approvals_staging.conf
get a report on the status of an application to determine if you send
traffic to it based on the health-monitor gem
closes #5534
=> [approvals] add a new health check

README.md
add molecule instruction and how to copy from example role
=> [prancible] molecule initialization

inventory/all_projects/_orphans, playbooks/utils/remove_fd_find.yml, roles/common/defaults/main.yml
update sandbox DNS of one of our hosts
closes #5551
=> [prancible] remove fd-find

group_vars/bibdata/common.yml, group_vars/sftp/staging.yml, playbooks/lib_sftp.yml
the system_ldap role was provided a better name
=> [bibdata] add correct path

group_vars/bibdata/common.yml, group_vars/sftp/staging.yml, playbooks/lib_sftp.yml
=> [bibdata] new path

roles/nginxplus/files/conf/http/catalog-prod.conf, roles/nginxplus/files/conf/http/lib-solr8-prod.conf, roles/nginxplus/files/conf/http/static_prod.conf, roles/nginxplus/files/conf/http/static_tables_prod.conf
this PR disables the WAF on the following applications
catalog
solr8-prod
static-tables
static-prod (added by mistake)
=> [static-tables] disable the WAF

roles/nginxplus/files/conf/http/catalog-staging.conf
Disables the WAF on catalog-staging
=> [catalog-staging] Turn off app_protect_enable

roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf
I want it back on eventually, but I need to get this ticket closed.
Closes pulibrary/figgy#6555
=> [Figgy] Disable Figgy App Protect

roles/nginxplus/files/conf/http/dss-prod.conf
disable WAF on DSS application
related to #5661
=> [DSS] disable WAF

roles/denyhost/vars/main.yml
silence azure based vms crawling
=> [denyhost] azure aggressive crawl

roles/nginxplus/files/conf/http/abid_prod.conf, roles/nginxplus/files/conf/http/dev/abid_staging.conf, roles/nginxplus/files/conf/http/dev/dpul-collections-staging.conf, roles/nginxplus/files/conf/http/dpul-prod.conf, roles/nginxplus/files/conf/http/dpul-staging.conf, roles/nginxplus/files/conf/http/figgy-prod.conf, roles/nginxplus/files/conf/http/figgy-staging.conf, roles/nginxplus/files/conf/http/imagecat_prod.conf, roles/nginxplus/files/conf/http/imagecat_staging.conf, roles/nginxplus/files/conf/http/lae-prod.conf, roles/nginxplus/files/conf/http/lae-staging.conf, roles/nginxplus/files/conf/http/maps-prod.conf, roles/nginxplus/files/conf/http/maps-staging.conf, roles/nginxplus/files/conf/http/pulfalight-prod.conf, roles/nginxplus/files/conf/http/pulfalight-qa.conf, roles/nginxplus/files/conf/http/pulfalight-staging.conf
=> [nginxplus] Add X-Forwarded-Proto headers to all DLS configs

roles/denyhost/vars/main.yml
I ran this playbook on 4 December
=> Block another bad bot that sent excessive traffic to the catalog

inventory/all_projects/orangelight, roles/nginxplus/files/conf/http/catalog-prod.conf
add catalog4 to inventory and loadbalancer
related to #5594
=> [catalog] add new vm

roles/nginxplus/files/conf/http/dev/kennyloggin_staging.conf, roles/nginxplus/templates/etc_nginx.conf.j2
The configuration for our staging loadbalancer
This was built "the hard way"
related to #5479
=> [kennyloggin] staging config

playbooks/allsearch_api.yml
Update bundler version to 2.5.23
=> Update gem system update to 3.5.23

README.md
=> Clean up and update the "usage" section of the README

group_vars/pulfalight/production.yml, playbooks/pulfalight.yml
- **[pulfalight] Increase passenger max pool**
- **[pulfalight] add some datadog tags**
refs pulibrary/pulfalight#1469
=> [pulfalight] increase passenger pool

group_vars/pulmap/production.yml, group_vars/pulmap/staging.yml, roles/pulmap/vars/main.yml
=> Upgrade pulmap ruby and nodejs

roles/figgy/tasks/main.yml
=> [Figgy] Add new ILL shares.

inventory/all_projects/orangelight
=> add catalog-indexer-staging2 to inventory

.github/ISSUE_TEMPLATE/new_vm.md
Moved `Relevant Deadlines` to the top of the template
=> Reorganize new_vm.md content

group_vars/all/vars.yml
remove TWade :sad: from access
=> [prancible] add angel to access

group_vars/pulfalight/production.yml, group_vars/pulfalight/staging.yml, roles/pulfalight/vars/main.yml
advances https://github.com/pulibrary/pulfalight/issues/1465
=> Upgrade ruby and nodejs

inventory/all_projects/nginxplus
these were temporary vms to be a representation of our production focal
vms
related to #5573
=> [nginxplus] remove temp hosts

roles/passenger/tasks/main.yml
Fixing a syntax problem - otherwise only uses one of the tags
=> Fix duplicate key in passenger role

inventory/by_service/cdh, roles/nginxplus/files/conf/http/lib-solr9-staging.conf
this adds cdh to the solr9 servers
=> [cdh] add access to solr9

group_vars/byzantine/staging.yml, group_vars/dss/staging.yml, group_vars/friends_of_pul/staging.yml, group_vars/libwww/staging.yml, group_vars/oawaiver/staging.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml, group_vars/pdc_describe/staging.yml, group_vars/pdc_discovery/staging.yml, group_vars/special_collections/staging.yml, group_vars/tigerdata/qa.yml, group_vars/tigerdata/staging.yml, roles/mailcatcher/defaults/main.yml, roles/mailcatcher/handlers/main.yml, roles/mailcatcher/tasks/main.yml
- Reload daemon when configuration changes
- Helps keep install path consistent with mailcatcher version
Closes #5410
=> Install specific version of mailcatcher

roles/nginxplus/files/conf/http/dev/static_staging.conf, roles/nginxplus/files/conf/http/static_prod.conf, roles/nginxplus/files/conf/http/templates/cicognara_redirect.conf
improve on the regex logic
closes #5560
=> cicognara add a redirect that uses the TLD

group_vars/dpul/production.yml, group_vars/dpul/staging.yml
=> [DPUL] update ruby and node

group_vars/abid/production.yml, group_vars/abid/staging.yml
=> [ABID] Upgrade ruby and node

roles/nginxplus/files/conf/http/cdh_test_geniza.conf
=> [cdh] remove geniza

group_vars/approvals/common.yml
Related ticket https://github.com/pulibrary/approvals/issues/1179
Pair PR https://github.com/pulibrary/approvals/pull/1216
=> [Approvals] Update ruby to 3.3.6

group_vars/orangelight/common.yml, group_vars/orangelight/production.yml, group_vars/orangelight/qa.yml, group_vars/orangelight/staging.yml
=> [catalog] Use ruby 3.3.6 with YJIT for all environments

roles/passenger/templates/passenger.j2
=> Put passenger_app_env back in to passenger configuration

group_vars/abid/production.yml, group_vars/abid/staging.yml
We can't complete the abid language upgrades due to https://github.com/pulibrary/abid/issues/186, so rolling these back while we work on that ticket.
Fixing a few passenger settings noticed in the meantime.
refs pulibrary/abid#181
=> [abid] roll back upgrades and fix passenger settings

group_vars/geaccirc/common.yml
https://github.com/pulibrary/geaccirc/issues/57
I've run this against staging and successfully deployed the application. 
I'm running it now against production
=> [GEACCIRC] Update ruby to 3.3.6

group_vars/pdc_discovery/main.yml, group_vars/pdc_discovery/production.yml
=> [PDC-DISCOVERY] Updating the max passenger pool size

group_vars/dss/common.yml
Helps with https://github.com/pulibrary/DSS/issues/463
=> [DSS] Ruby 3.3

group_vars/repec/common.yml
Closes https://github.com/pulibrary/repecwp/issues/134
Run on staging and production
=> [repec] Upgrade to ruby 3.4.1

.zed/settings.json
- **add zed text editor language server settings**
- **the ansible lint extension config**
- configure this repo to use zed editor
=> [prancible] add zed editor

group_vars/all/vars.yml, playbooks/utils/ufw_firewall.yml, roles/ufw_firewall/README.md, roles/ufw_firewall/defaults/main.yml, roles/ufw_firewall/handlers/main.yml, roles/ufw_firewall/tasks/main.yml, roles/ufw_firewall/templates/before.rules.j2, roles/ufw_firewall/vars/main.yml
Closes  #5492 - creates variables in the group_vars/all for use in ufw_firewall to represent the relevant network segments.
=> [prancible] I5492 add friendly names to ufw

group_vars/orangelight/common.yml, roles/orangelight/tasks/main.yml
I ran this on catalog-staging and catalog-qa2
=> [orangelight] Ruby 3.4.1

group_vars/lockers_and_study_spaces/common.yml
Resolves pulibrary/lockers_and_study_spaces#328
=> [Lockers] Upgrade lockers ruby to 3.4.1

inventory/all_projects/special_collections
This PR removes the files from inventory for Lib-SC-Staging1&2
=> i5407_decommissioning_lib-sc-staging1-2

playbooks/utils/security_theater.yml
adding a pre-tasks section hoping to skip the falcon-sensor role when not necessary
=> [prancible] i5546 make it more obvious when skipping is ok 

roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf
Fixes issue uploading files in PDC Describe
See https://github.com/pulibrary/pdc_describe/issues/2009
=> [PDC Describe] Allow file uploads again

roles/video_reserves/tasks/main.yml, roles/video_reserves/templates/apache2-site.conf.j2
prevent directory traversal of the document root of apache.
related cap PR https://github.com/PrincetonUniversityLibrary/video_reserves/pull/88
closes #5676
=> I5676 directory traversal

group_vars/bibdata/common.yml, roles/bibdata/tasks/main.yml
Pair PR https://github.com/pulibrary/bibdata/pull/2591
=> [Bibdata] Update to ruby 3.4.1

roles/nginxplus/files/conf/http/datacommons.conf, roles/nginxplus/files/conf/http/datacommons_staging.conf, roles/nginxplus/files/conf/http/pdc-describe_prod.conf, roles/nginxplus/files/conf/http/pdc-describe_staging.conf
Fixes issue uploading files in PDC Describe
See https://github.com/pulibrary/pdc_describe/issues/2009
In PR https://github.com/pulibrary/princeton_ansible/pull/5744 we forgot to update the datacommons.conf files.
=> [PDC Describe] Allow file uploads (part 2)

group_vars/nfsserver/cdh_conf_prosody.yml, inventory/all_projects/cdh, inventory/all_projects/nfsserver, inventory/all_projects/prosody, inventory/by_environment/staging, playbooks/cdh_conf_prosody.yml, roles/nfsserver/defaults/main.yml, roles/nfsserver/molecule/default/verify.yml, roles/nfsserver/tasks/directories.yml
we add a new cdh-fs-staging nfsserver
we add a new cdh-conf-prosody vm
the nfsserver has an export that allows connection to the mount.
related to https://gitlab.lib.princeton.edu/ops/team-handbook/-/issues/4
=> [cdh] add new cdh file system

inventory/all_projects/approvals, inventory/by_environment/staging, inventory/by_team/dacs
Adding aprovals-testing1 to ansible inventory
=> Adding VM to ansible inventory

group_vars/solr8cloud/production.yml, group_vars/solr8cloud/staging.yml
=> [Solr] Upgrade ruby on solr machines

roles/nginxplus/files/conf/http/approvals_testing.conf
updated nginxplus role to include approvals-testing
=> updated nginxplus role to include approvals-testing

roles/mediainfo/defaults/main.yml
=> [Figgy] Update mediaserver repository.

inventory/all_projects/lib_sftp
=> Removed lib-sftp-test1-2 from inventory

group_vars/ezproxy/testing.yml
upgrade version to 7.2.12 to match ezproxy-prod
update group_vars with new domain name
=> [ezproxy] update ezproxy-test to latest version

roles/nginxplus/files/conf/http/approvals_testing.conf
This will allow outside testers from Fable to test it tomorrow and Friday
=> [approvals] Make testing environment available outside the VPN

roles/nginxplus/files/conf/http/tigerdata_prod.conf
=> [TIGERDATA] Remove tigerdata-prod from behind the VPN

inventory/all_projects/researchdata
=> Removed researchdata from inventory

README.md, roles/solrcloud/tasks/config.yml, roles/solrcloud/templates/solr9.xml.j2
reintroduce behavior of solr pre 8.6 which allowed arbitrary paths. This will enable backups to continue. 
related to #5753
=> [solrcloud] solr9 backups

roles/nginxplus/files/conf/http/allsearch_staging.conf, roles/nginxplus/files/conf/http/dev/byzantine-tsp_staging.conf, roles/nginxplus/files/conf/http/dev/eal_staging.conf, roles/nginxplus/files/conf/http/dev/static_staging.conf, roles/nginxplus/files/conf/http/slavery-staging.conf, roles/nginxplus/files/conf/http/static_tables_staging.conf, roles/nginxplus/files/conf/http/videoreserves_staging.conf
[allsearch-staging]
[byzantine-tsp_staging]
[eal-staging]
[slavery-dev]
[slavery-staging]
[static-staging]
[static_tables-staging]
[videoreserves-staging]
=> [#5472] Update the rest of the DACS staging applications with 'X-Forwarded-Proto' in nginx conf file

roles/nginxplus/files/conf/http/allsearch_prod.conf, roles/nginxplus/files/conf/http/byzantine-tsp_prod.conf, roles/nginxplus/files/conf/http/byzantine_prod.conf, roles/nginxplus/files/conf/http/eal_prod.conf, roles/nginxplus/files/conf/http/ealapps_prod.conf, roles/nginxplus/files/conf/http/slavery-prod.conf, roles/nginxplus/files/conf/http/static_tables_prod.conf, roles/nginxplus/files/conf/http/videoreserves_prod.conf
[allsearch-prod]
[byzantine-tsp-prod]
[byzantine-prod]
[eal-prod]
[ealapps-prod]
[slavery-dev]
[slavery-prod]
[static_tables-prod]
[videoreserves-prod]
=> [#5472] Update the rest of the DACS applications with 'X-Forwarded-Proto' in nginx conf file

roles/figgy/templates/nginx_extra_config
Closes https://github.com/pulibrary/figgy/issues/6632
=> [Figgy] Add CORS headers for streaming Figgy content

.gitignore, inventory/by_environment/remote
this fixes warning for refering to non-existent host
related to #5829
=> [approvals] remove inventory reference

group_vars/bibdata/common.yml
https://github.com/pulibrary/princeton_ansible/issues/4938
The ticket is resolved
=> Remove comment with related ticket

group_vars/oawaiver/production.yml, group_vars/oawaiver/staging.yml
This is necessary to advance https://github.com/pulibrary/oawaiver/issues/100
=> Updating the Node.js release to v22.13.1 (LTS Jod)

group_vars/nomad_cluster.yml
No particular reason, just good to be caught up.
=> [Nomad] Update Nomad/Consul.

group_vars/all/vars.yml
=> Allow sean warren to log in to sidekiq

inventory/all_projects/checkmk
=> Added forrestal to remote inventory

roles/ansible-nomad/templates/nomad_systemd.service.j2
=> Nomad runs after Consul.

roles/postfix/vars/main.yml
Adding checkmk server to test sending email notification.
=> Added new checkmk servers to mail relay server

group_vars/orangelight/common.yml
Related ticket https://github.com/pulibrary/orangelight/issues/4749
[Friend PR](https://github.com/pulibrary/orangelight/pull/4764)
=> [Orangelight] Use nodejs 23.7.0

inventory/all_projects/pas, roles/nginxplus/files/conf/http/slavery-prod.conf
- adding slavery-prod2 to inventory
- updating nginxplus conf file with slavery-prod2.princeton.edu
=> [pas] i5867 add slavery-prod2

bin/first-time-setup.sh
update asdf install steps in first_time_setup file
asdf has changed what they expect to see in ~/.zshrc
=> updated asdf install steps in the first

roles/nginxplus/files/conf/http/static_prod.conf
=> Renew certs for daviesproject

roles/nginxplus/files/conf/http/getit_dev.conf, roles/nginxplus/files/conf/http/getit_prod.conf
Removed conf files for decommissioning issue [53 on ops-catchall](https://github.com/pulibrary/ops-catchall/issues/53)
=> [getit] remove conf files

roles/nginxplus/files/conf/http/dev/pcdm_staging.conf
use nomad/consul to deploy a web application on a container
related to #5787
=> add pcdm-staging config

inventory/all_projects/_orphans
adding my sandbox into the correct group.
=> added sandbox to orphans

playbooks/incommon_certbot.yml, playbooks/incommon_certbot_multi.yml, roles/nginxplus/files/conf/http/theses_dissertations.conf
- point theses-dissertations to new hosted site 4science
- 
- change loadbalancer name in incommon_cert config files
related to #5781
=> [theses_dissertations] point theses-dissertations to new hosted site 

group_vars/bibdata/common.yml
Resolves pulibrary/bibdata#2625 with pulibrary/bibdata#2652
=> [Bibdata] Upgrade nodejs to 22.x

nomad/traefik-wall/deploy/sites/sites-staging.yml, roles/nginxplus/files/conf/http/dev/catalog_staging.conf
- **add catalog-staging to traefik-wall**
- **catalog has two staging servers**
related to #5918 
Not sure this is effective on staging given how it is restricted to on-prem
=> [catalog] add traefik-wall

nomad/traefik-wall/deploy/sites/sites-production.yml
the middleware is making our subject and other browses break
=> [catalog] remove middleware

group_vars/pulmap/production.yml
=> [Pulmap] Forward pulmap passenger logs.

roles/nginxplus/files/conf/http/dev/dpul-collections-staging.conf
=> [DPUL-C] Update load balancer to only get the frontend web servers

nomad/traefik-wall/deploy/sites/sites-production.yml, nomad/traefik-wall/deploy/sites/sites-staging.yml, roles/nginxplus/files/conf/http/maps-prod.conf, roles/nginxplus/files/conf/http/maps-staging.conf
=> [Traefik Wall / Pulmap] Add Pulmap to Traefik Bot Wall

group_vars/checkmk/local_check_templates/redis_health_check.j2, group_vars/checkmk/rule_redis.yml
fixes https://github.com/pulibrary/pdc_describe/issues/1930
=> [PDC_DESCRIBE_REDIS] Add local rule to monitor redis information

roles/nginxplus/templates/etc_nginx.conf.j2
=> Add host to nginx+ logging.

roles/ezproxy/templates/config.txt.j2, roles/ezproxy/templates/shibuser.txt.j2, roles/ezproxy/templates/user.txt.j2
Made EZproxy config.txt consistent with working production configuration.
=> Update ezproxy configuration templates. 

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml, nomad/traefik-wall/deploy/bot-plugin-staging.tpl.yml
See https://commoncrawl.org/ccbot. They're friendly, and we should trust 'em!
Closes #5976
=> [Traefik Wall] Add commoncrawl as a good bot.

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml, nomad/traefik-wall/deploy/bot-plugin-staging.tpl.yml, nomad/traefik-wall/deploy/sites/sites-production.yml, nomad/traefik-wall/deploy/sites/sites-staging.yml, roles/nginxplus/files/conf/http/dpul-prod.conf, roles/nginxplus/files/conf/http/dpul-staging.conf
Closes #5948
Blocked until the firewall's opened up.
=> Add DPUL to the Traefik Wall.

group_vars/ezproxy/production.yml, group_vars/ezproxy/testing.yml, roles/ezproxy/tasks/main.yml
- removed unused group_vars
- updated bin file in roles to pull latest version 
- update playbook to add user.txt template 
Related to #4788
=> [ezproxy] update ansible role, group vars, templates

inventory/all_projects/_orphans
=> add theprince to inventory

roles/nginxplus/files/conf/http/lib-solr8-prod.conf, roles/nginxplus/files/conf/http/lib-solr8-staging.conf, roles/nginxplus/files/conf/http/lib-solr8d-staging.conf, roles/nginxplus/files/conf/http/lib-solr9-prod.conf, roles/nginxplus/files/conf/http/lib-solr9-staging.conf
our solr-servers restrict who can access them. this configuration fixes access from the private network
=> add the private network for our solr boxes

group_vars/figgy/common.yml, group_vars/figgy/production.yml, group_vars/figgy/staging.yml, playbooks/figgy_production.yml, playbooks/figgy_staging.yml
Reformatted figgy production and staging group vars consolidating identical values into a single file.
Closes #4952
=> Add a common.yml for figgy group vars

group_vars/pdc_describe/main.yml
needed for https://github.com/pulibrary/pdc_describe/pull/2023
Tried to go to 3.4.2, [but too many gems needed to be updated for that](https://ansible-tower.princeton.edu/#/jobs/playbook/15885/output)
=> [PDCDescribe] upgrade ruby to 3.3.7

roles/nginxplus/files/conf/http/dev/kennyloggin_staging.conf
reconfiguring kennyloggin-staging1 to test loki/grafana
related to #5479
=> [nginxplus] deleted second kennyloggin config

nomad/traefik-wall/deploy/bot-plugin-testing.tpl.yml, nomad/traefik-wall/deploy/testing.hcl, roles/nginxplus/files/conf/http/catalog-prod.conf, roles/pul_nomad/tasks/traefik_wall.yml
Created with @christinach 
We wanted a wall that could be changed without affecting all the other sites.
=> [Catalog] Add a test traefik wall that can be quickly adjusted just for catalog testing

group_vars/orangelight/common.yml, roles/orangelight/handlers/main.yml, roles/orangelight/molecule/default/converge.yml, roles/orangelight/molecule/default/molecule.yml, roles/orangelight/molecule/default/verify.yml, roles/orangelight/tasks/main.yml, roles/orangelight/templates/sneakers.logrotate.j2, roles/orangelight/templates/sneakers.service.j2, roles/orangelight/vars/main.yml, roles/sneakers_worker/tasks/main.yml
catalog-qa{1,2} keep getting filled up. This addresses that.
closes #6042
=> [orangelight] reduce disk filling up

group_vars/allsearch_frontend/common.yml
closes https://github.com/pulibrary/allsearch_frontend/issues/460
also review https://github.com/pulibrary/allsearch_frontend/pull/477
=> [AllSearchFrontEnd] Use nodejs 23.11.0

group_vars/repec/common.yml
It is not needed for this application.  Helps with https://github.com/pulibrary/repecwp/issues/165
=> [Repec] Don't install nodejs

group_vars/approvals/common.yml
Friend Pr https://github.com/pulibrary/approvals/pull/1241
=> Use node 23.11.0

group_vars/bibdata/qa.yml, playbooks/bibdata.yml
Currently it does not work and fails the playbook to run against any environment.
=> Remove prometheus. It was added do test metrics. This work is complete.

group_vars/libstatic/staging.yml, roles/libstatic/defaults/main.yml, roles/nginxplus/files/conf/http/dev/daviesproject_staging.conf, roles/nginxplus/files/conf/http/dev/static_staging.conf
migrate daviesproject staging to use nomad orchestation
related to #6049
=> [daviesproject] move staging to nomad

nomad/observability/README.md, nomad/observability/deploy/grafana.hcl, nomad/observability/deploy/log-shipping.hcl, nomad/observability/deploy/loki.hcl, nomad/observability/deploy/prometheus.hcl
This is the observability infrastructure we built to monitor DPUL-Collections in staging. Now that it's also monitoring a mount and other folks are using Nomad, it seemed prudent to move it here.
=> [Observability] Add Nomad observability infrastructure.

group_vars/libstatic/production.yml, roles/libstatic/molecule/default/verify.yml, roles/nginxplus/files/conf/http/daviesproject_prod.conf, roles/nginxplus/files/conf/http/static_prod.conf
migrate the davies project from libstatic prod to our container environment
closes #6049
=> add daviesproject configuration files

nomad/traefik-wall/deploy/sites/sites-production.yml, nomad/traefik-wall/deploy/sites/sites-staging.yml
=> [Traefik Wall] Add health checks.

inventory/by_cloud/google_cloud
we caught the wrong VM requiring deletion
related to #5982
=> add simrisk back to inventory

group_vars/lockers_and_study_spaces/common.yml
Sibling PR: https://github.com/pulibrary/lockers_and_study_spaces/pull/411
=> [lockers] node 22

nomad/traefik-wall/README.md
Update Traefik README.md with steps for adding coverage to a website.
Related to #5992
=> Update Traefik README.md

roles/postfix/vars/main.yml
Removed maps-staging1 since the vm is decomissioned. Closes #6092
=> Decommission maps-staging1

group_vars/all/vars.yml, requirements.txt
OIT updated the version of Rapid7 we use.
This PR updates it on our end to fix the security playbook.
=> updates Rapid7 package version

inventory/by_cloud/aws
instead of having to remember IP addresses. Use DNS names of our Globus
servers
=> [globus] use dns

inventory/all_projects/tigerdata
Add tigerdata-ci1 to tigerdata inventory. Closes #6115
=> Add tigerdata-ci1 to tigerdata inventory

roles/bibdata/tasks/main.yml, roles/bibdata/vars/main.yml
Connected to https://github.com/pulibrary/bibdata/issues/2693
=> [bibdata] Make sure file for symlink exists

roles/rust/meta/main.yml, roles/rust/molecule/default/verify.yml, roles/rust/tasks/main.yml
@christinach and I did this work, but then I forgot to commit it as part of #6129 -- sorry!
=> [rust] Allow deploy user to run rust binaries

inventory/by_environment/staging
Add pulemetry-staging to inventory. Add kennyloggin-staging to inventory.
Related to #6119
=> Add pulemetry-staging to inventory

group_vars/figgy/production.yml, roles/figgy/molecule/default/converge.yml, roles/figgy/molecule/default/molecule.yml, roles/figgy/molecule/default/verify.yml, roles/figgy/tasks/main.yml, roles/redis/tasks/main.yml
Removed references to /mnt/illiad as the path is now /mnt/hosted_illiad
Closes #6118
=> Remove /mnt/illiad paths

nomad/traefik-wall/deploy/sites/sites-production.yml, roles/nginxplus/files/conf/http/datacommons.conf
datacommons is experiencing a robot based spike traffic
=> add datacommons to the traefik-wall

inventory/all_projects/nomad
Add nomad-host-staging VMs to nomad project inventory
Closes #6147
=> Add nomad-host-staging to inventory

group_vars/nginxplus/main.yml
this excludes WARN messages from going to datadog
related #6143
=> [nginxplus] exclude warn messages

inventory/all_projects/reservoir, inventory/by_environment/staging
Add reservoir-staging{1,2}.lib.princeton.edu to princeton_ansible inventory
Closes #6173
=> Add reservoir staging machines to inventory

group_vars/solr9cloud/production.yml, group_vars/zookeeper/production.yml, roles/solr9cloud/tasks/install.yml, roles/solr9cloud/tasks/main.yml, roles/solr9cloud/templates/solr.in.sh.j2
related to #5740  we add the production solr9 cluster.
=> I5740 solr backup production

playbooks/oawaiver.yml
Advances https://github.com/pulibrary/oawaiver/issues/257
=> Removed datadog role from oawaiver

nomad/traefik-wall/deploy/bot-plugin-production.tpl.yml
The bots have found us. We need a better solution, but this'll slow 'em
down.
=> Block some browse pages for DPUL.

roles/nginxplus/files/conf/http/pulmonitor_production.conf
add new server block for staging and production with location additions on the TLS server blocks
related #6084
=> [checkmk] not have production and staging paths

roles/common/handlers/main.yml, roles/common/vars/main.yml, roles/nginxplus/meta/main.yml, roles/nginxplus/tasks/localhost.yml, roles/nginxplus/templates/vector.yaml.j2
this enables our loadbalancers to ship logs to our logging infra.
related to #5479 and #6126
can we ship logs locally
=> [nginxplus] ships logs

roles/postgresql/tasks/main.yml
as currently configured the postgresql role installs vector configuration to all clients
closes #6245
=> make sure log configuration only runs on server

group_vars/allsearch_frontend/common.yml
Helps with https://github.com/pulibrary/allsearch_frontend/issues/482
I ran this on staging
=> [allsearch-frontend] Node 24

group_vars/oawaiver/staging.yml
Advances https://github.com/pulibrary/oawaiver/issues/258
=> Ensuring that oawaiver-staging deployments exclusively use lib-solr8d-staging for Solr

roles/nginxplus/files/tigerdata-error.html
ref https://github.com/pulibrary/tigerdata-app/issues/1555
=> [tigerdata] remove maintenance window message from error page

group_vars/approvals/common.yml
partof https://github.com/pulibrary/approvals/issues/1246
=> [approvals] Node 24.3

group_vars/static_tables/common.yml
part of https://github.com/pulibrary/static-tables/issues/212
=> [static-tables] Use node 24

roles/figgy/tasks/main.yml
Work towards pulibrary/figgy#6700
=> [Figgy] Use new load balanced tigerdata path.

group_vars/lib_jobs/common.yml
as currently set up the file is owned by root. we make deploy user the owner
closes #6324
=> [lib_jobs] switch owner

roles/memcached/defaults/main.yml
=> [memcached] Increase memcached max item size

Pipfile, Pipfile.lock
allow autogeneration of documentation using [docsible](https://docsible.github.io/)
=> [prancible] add docsible

inventory/all_projects/_orphans, inventory/all_projects/recap, inventory/by_environment/production, inventory/by_environment/staging
Created a new group for recap and added prod and staging servers.
=> Updated inventory to include new recap servers

inventory/all_projects/sandboxes
A bit more tidying on our staging inventory.
This host has already been removed from CheckMK and from vSphere.
=> removes another unused sandbox

inventory/by_cloud/google_cloud
To test these changes in Tower, I think we need to merge this.
Related to #6376, partial fix (we hope) for #6357.
=> Trying something different for GCP Tower access

inventory/all_projects/checkmk
=> [CheckMK] remove canary1.lib.princeton.edu from inventory

group_vars/postgresql/production.yml, group_vars/postgresql/qa.yml, group_vars/postgresql/staging.yml, roles/postgresql/tasks/main.yml
when logrotation happens pg.json is owned by root. This stops the
postgresql server from restarting successfully. We make sure the
permission of the createmode are given to the `postgres` user.
related to this https://github.com/pulibrary/allsearch_api/issues/390
=> [postgresql] logrotate is stopping restart

playbooks/utils/remove_crowdstrike.yml
=> [prancible] remove rhel rocky

group_vars/lib_jobs/common.yml
Resolves pulibrary/lib_jobs#938
=> [Lib_Jobs] Using active updates directory

group_vars/tigerdata/production.yml
Related to TigerData issue https://github.com/pulibrary/tigerdata-app/issues/1717
=> [TigerData] Use the correct prefix for TigerData DataCite DOIs

nomad/circleci_deployer/Dockerfile, nomad/circleci_deployer/deploy/all.hcl
This allows Podman to be run inside the CircleCI container, done for pulibrary/tigerdata#1662
=> Try building a CI deployer with podman installed.

roles/nginxplus/files/conf/http/dpul-collections-prod.conf
We'll merge/deploy this when pulibrary/dpul-collections#696 and
pulibrary/dpul-collections#695 are merged and deployed.
=> [Digital Collections] Soft launch!

inventory/all_projects/fred
Adding lib-fred-mudd to ansible inventory.
=> Added second fred server to inventory

playbooks/utils/checkmk_agent.yml
Ref https://github.com/pulibrary/tigerdata-app/issues/1771
=> Fix ansible-galaxy installation instructions

roles/nginxplus/files/conf/http/dev/eal_staging.conf, roles/nginxplus/files/conf/http/eal_prod.conf
This has been run on adc dev and prod.
=> Ignore all params for EALJ redirect.

group_vars/pdc_describe/main.yml, group_vars/pdc_describe/staging.yml
Also move variables to make it more clear they need to be updated when ruby changes
=> [PDC-DESCRIBE] Update mailcatcher version to run with the new ruby

inventory/all_projects/recap
This PR is to update the inventory to reflect the new VM name.
=> rename recap dev vm

group_vars/solr9cloud/staging.yml, roles/solr9cloud/templates/solr.in.sh.j2, roles/solr9cloud/templates/solr.service.j2, roles/solr9cloud/templates/solr.xml.j2, roles/zookeeper/templates/zoo.cfg.j2
=> I6487 zookeeper timeouts

group_vars/orcid/main.yml
'refs https://github.com/pulibrary/orcid_princeton_hanami/pull/97
=> [ORCID] Upgrade Ruby

group_vars/bibdata/production.yml, group_vars/bibdata/qa.yml, group_vars/orangelight/production_solr.yml, group_vars/orangelight/qa_solr.yml
=> [catalog] use solr 9 in prod and qa

inventory/all_projects/mysql
related to this ticket https://gitlab.lib.princeton.edu/ops/team-handbook/-/issues/173
=> remove mysql-db-dev1

inventory/all_projects/_orphans, inventory/by_service/apache, inventory/by_team/dacs, roles/nginxplus/files/conf/http/dev/templates/libwww-proxy-pass-staging.conf, roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf
=> I6568 loadtest
